import { resolveUiWebMode } from '../process/uiWebEnv';

export type VoiceBrowserQaRouteProfile = 'direct' | 'relay';

export function resolveVoiceBrowserQaUiWebMode(env: NodeJS.ProcessEnv): 'metro' | 'export' {
  const explicitMode = String(env.HAPPIER_E2E_UI_WEB_MODE ?? '').trim();
  return explicitMode.length === 0 ? 'metro' : resolveUiWebMode(env);
}

const DIRECT_DISABLED_ENV = Object.freeze({
  HAPPIER_FEATURE_MACHINES_RPC_DIRECT_PEER__ENABLED: '0',
  HAPPIER_FEATURE_MACHINES_TUNNEL_DIRECT_PEER__ENABLED: '0',
  HAPPIER_FEATURE_MACHINES_LIVE_STREAM_DIRECT_PEER__ENABLED: '0',
});

const RELAY_DISABLED_ENV = Object.freeze({
  HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ENABLED: '0',
  HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__ENABLED: '0',
});

export function buildVoiceBrowserQaRouteFeatureEnv(
  profile: VoiceBrowserQaRouteProfile,
  daemonControlPort: number,
): Readonly<Record<string, string>> {
  if (!Number.isInteger(daemonControlPort) || daemonControlPort < 1 || daemonControlPort > 65_535) {
    throw new Error(`invalid Voice browser QA daemon control port: ${String(daemonControlPort)}`);
  }
  const allowedPortEnv = {
    HAPPIER_FEATURE_MACHINES_TUNNEL_ALLOWED_PORTS: String(daemonControlPort),
  };
  if (profile === 'direct') {
    return {
      HAPPIER_FEATURE_MACHINES_RPC_DIRECT_PEER__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_TUNNEL_DIRECT_PEER__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_DIRECT_PEER__ENABLED: '1',
      ...RELAY_DISABLED_ENV,
      ...allowedPortEnv,
    };
  }

  return {
    ...DIRECT_DISABLED_ENV,
    ...allowedPortEnv,
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ENABLED: '1',
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__SUPPORTED_ENCODINGS: 'binary_frame_v2',
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__PREFERRED_ENCODING: 'binary_frame_v2',
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ALLOW_V1_FALLBACK: '0',
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__MAX_BYTES: String(8 * 1024 * 1024),
    HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__MAX_FRAME_BYTES: String(64 * 1024),
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__ENABLED: '1',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_BITRATE_BPS: '512000',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_FRAMES_PER_SECOND: '60',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_FRAME_BYTES: String(64 * 1024),
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_DURATION_MS: '120000',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_TOTAL_BYTES: String(8 * 1024 * 1024),
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_ACCOUNT: '4',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_SOCKET: '2',
    HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_MACHINE: '2',
  };
}
