import { describe, expect, it } from 'vitest';

import {
  buildVoiceBrowserQaRouteFeatureEnv,
  resolveVoiceBrowserQaUiWebMode,
} from './voiceBrowserQaRouteProfile';

describe('Voice browser QA route profiles', () => {
  it('defaults to Metro but honors an explicit canonical export selection', () => {
    expect(resolveVoiceBrowserQaUiWebMode({})).toBe('metro');
    expect(resolveVoiceBrowserQaUiWebMode({ HAPPIER_E2E_UI_WEB_MODE: '  ' })).toBe('metro');
    expect(resolveVoiceBrowserQaUiWebMode({ HAPPIER_E2E_UI_WEB_MODE: 'export' })).toBe('export');
  });

  it('enables peer-direct transport exclusively for the direct profile', () => {
    expect(buildVoiceBrowserQaRouteFeatureEnv('direct', 43123)).toEqual({
      HAPPIER_FEATURE_MACHINES_RPC_DIRECT_PEER__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_TUNNEL_DIRECT_PEER__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_DIRECT_PEER__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ENABLED: '0',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__ENABLED: '0',
      HAPPIER_FEATURE_MACHINES_TUNNEL_ALLOWED_PORTS: '43123',
    });
  });

  it('disables peer-direct and enables bounded binary relay capabilities for the relay profile', () => {
    expect(buildVoiceBrowserQaRouteFeatureEnv('relay', 43124)).toEqual({
      HAPPIER_FEATURE_MACHINES_RPC_DIRECT_PEER__ENABLED: '0',
      HAPPIER_FEATURE_MACHINES_TUNNEL_DIRECT_PEER__ENABLED: '0',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_DIRECT_PEER__ENABLED: '0',
      HAPPIER_FEATURE_MACHINES_TUNNEL_ALLOWED_PORTS: '43124',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__SUPPORTED_ENCODINGS: 'binary_frame_v2',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__PREFERRED_ENCODING: 'binary_frame_v2',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__ALLOW_V1_FALLBACK: '0',
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__MAX_BYTES: String(8 * 1024 * 1024),
      HAPPIER_FEATURE_MACHINES_TUNNEL_SERVER_ROUTED__MAX_FRAME_BYTES: String(64 * 1024),
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__ENABLED: '1',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_BITRATE_BPS: '512000',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_FRAMES_PER_SECOND: '60',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_FRAME_BYTES: String(64 * 1024),
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_DURATION_MS: '120000',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_TOTAL_BYTES: String(8 * 1024 * 1024),
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_ACCOUNT: '4',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_SOCKET: '2',
      HAPPIER_FEATURE_MACHINES_LIVE_STREAM_SERVER_ROUTED__MAX_CONCURRENT_STREAMS_PER_MACHINE: '2',
    });
  });
});
