type Parts = Readonly<{ completed: number; total: number; admitted: number }>;

/** Owner-reported multipart and revision facts; never inferred from file counts or client history. */
export const walkthroughProgressTranslations = {
    'en': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} parts complete · ${admitted} admitted`, merge: 'Putting the walkthrough together…', titleEdited: 'Edited title', changed: 'Changed', moved: 'Moved', filesReadUnavailable: 'Files-read progress unavailable' },
    'ca': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} parts completades · ${admitted} admeses`, merge: 'S’està integrant el recorregut…', titleEdited: 'Títol editat', changed: 'Canviat', moved: 'Mogut', filesReadUnavailable: 'Progrés de lectura de fitxers no disponible' },
    'de': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} Teile abgeschlossen · ${admitted} angenommen`, merge: 'Der Durchgang wird zusammengefügt…', titleEdited: 'Titel bearbeitet', changed: 'Geändert', moved: 'Verschoben', filesReadUnavailable: 'Fortschritt gelesener Dateien nicht verfügbar' },
    'es': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} partes completas · ${admitted} admitidas`, merge: 'Integrando el recorrido…', titleEdited: 'Título editado', changed: 'Cambiado', moved: 'Movido', filesReadUnavailable: 'Progreso de lectura de archivos no disponible' },
    'fr': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} parties terminées · ${admitted} admises`, merge: 'Assemblage du parcours…', titleEdited: 'Titre modifié', changed: 'Modifié', moved: 'Déplacé', filesReadUnavailable: 'Progression de lecture des fichiers indisponible' },
    'it': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} parti completate · ${admitted} ammesse`, merge: 'Composizione del percorso…', titleEdited: 'Titolo modificato', changed: 'Modificato', moved: 'Spostato', filesReadUnavailable: 'Avanzamento della lettura dei file non disponibile' },
    'ja': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} パート完了 · ${admitted} 受付済み`, merge: 'ガイドをまとめています…', titleEdited: '編集済みのタイトル', changed: '変更済み', moved: '移動済み', filesReadUnavailable: 'ファイル読み取りの進捗は不明です' },
    'pl': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} części ukończone · ${admitted} przyjęte`, merge: 'Łączenie przewodnika…', titleEdited: 'Edytowany tytuł', changed: 'Zmieniono', moved: 'Przeniesiono', filesReadUnavailable: 'Postęp odczytu plików niedostępny' },
    'pt': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} partes concluídas · ${admitted} admitidas`, merge: 'Integrando o percurso…', titleEdited: 'Título editado', changed: 'Alterado', moved: 'Movido', filesReadUnavailable: 'Progresso de leitura de arquivos indisponível' },
    'ru': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} частей завершено · ${admitted} принято`, merge: 'Обзор объединяется…', titleEdited: 'Название изменено', changed: 'Изменено', moved: 'Перемещено', filesReadUnavailable: 'Прогресс чтения файлов недоступен' },
    'zh-Hans': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} 部分已完成 · ${admitted} 已接收`, merge: '正在整合导览…', titleEdited: '标题已编辑', changed: '已更改', moved: '已移动', filesReadUnavailable: '文件读取进度不可用' },
    'zh-Hant': { parts: ({ completed, total, admitted }: Parts) => `${completed}/${total} 部分已完成 · ${admitted} 已接收`, merge: '正在整合導覽…', titleEdited: '標題已編輯', changed: '已變更', moved: '已移動', filesReadUnavailable: '檔案讀取進度無法取得' },
};
