type VisibilityCopy = Readonly<{ title: string; chooseTeam: string; loadFailed: string; machines: string; transcripts: string; requiredSessionsEditable: string; visibleTo: (params: { team: string }) => string }>;
export const workflowRunVisibilityTranslations: Record<'en'|'de'|'es'|'fr'|'it'|'pt'|'ca'|'pl'|'ru'|'ja'|'zhHans'|'zhHant', VisibilityCopy> = {
    en: { title: "Visibility", chooseTeam: "Choose a Team", loadFailed: "Could not check who can see this run", machines: "Runs on your machines", transcripts: "Team members can view the step conversations.", requiredSessionsEditable: "This Team's sessions are editable by its members", visibleTo: ({ team }) => "Visible to " + team },
    de: { title: "Sichtbarkeit", chooseTeam: "Team wählen", loadFailed: "Sichtbarkeit des Laufs konnte nicht geprüft werden", machines: "Läuft auf deinen Maschinen", transcripts: "Teammitglieder können die Schrittgespräche ansehen.", requiredSessionsEditable: "Die Sitzungen dieses Teams können von seinen Mitgliedern bearbeitet werden", visibleTo: ({ team }) => "Sichtbar für " + team },
    es: { title: "Visibilidad", chooseTeam: "Elegir un equipo", loadFailed: "No se pudo comprobar quién puede ver esta ejecución", machines: "Se ejecuta en tus máquinas", transcripts: "Los miembros del equipo pueden ver las conversaciones de los pasos.", requiredSessionsEditable: "Los miembros de este equipo pueden editar sus sesiones", visibleTo: ({ team }) => "Visible para " + team },
    fr: { title: "Visibilité", chooseTeam: "Choisir une équipe", loadFailed: "Impossible de vérifier qui peut voir cette exécution", machines: "S’exécute sur vos machines", transcripts: "Les membres de l’équipe peuvent voir les conversations des étapes.", requiredSessionsEditable: "Les sessions de cette équipe sont modifiables par ses membres", visibleTo: ({ team }) => "Visible par " + team },
    it: { title: "Visibilità", chooseTeam: "Scegli un team", loadFailed: "Impossibile verificare chi può vedere questa esecuzione", machines: "Viene eseguito sulle tue macchine", transcripts: "I membri del team possono vedere le conversazioni dei passaggi.", requiredSessionsEditable: "Le sessioni di questo team possono essere modificate dai suoi membri", visibleTo: ({ team }) => "Visibile a " + team },
    pt: { title: "Visibilidade", chooseTeam: "Escolher uma equipe", loadFailed: "Não foi possível verificar quem pode ver esta execução", machines: "Executa nas suas máquinas", transcripts: "Os membros da equipe podem ver as conversas das etapas.", requiredSessionsEditable: "As sessões desta equipe podem ser editadas pelos seus membros", visibleTo: ({ team }) => "Visível para " + team },
    ca: { title: "Visibilitat", chooseTeam: "Tria un equip", loadFailed: "No s’ha pogut comprovar qui pot veure aquesta execució", machines: "S’executa a les teves màquines", transcripts: "Els membres de l’equip poden veure les converses dels passos.", requiredSessionsEditable: "Els membres d’aquest equip poden editar-ne les sessions", visibleTo: ({ team }) => "Visible per a " + team },
    pl: { title: "Widoczność", chooseTeam: "Wybierz zespół", loadFailed: "Nie udało się sprawdzić, kto może zobaczyć to uruchomienie", machines: "Działa na Twoich maszynach", transcripts: "Członkowie zespołu mogą przeglądać rozmowy kroków.", requiredSessionsEditable: "Członkowie tego zespołu mogą edytować jego sesje", visibleTo: ({ team }) => "Widoczne dla " + team },
    ru: { title: "Видимость", chooseTeam: "Выберите команду", loadFailed: "Не удалось проверить, кто может видеть этот запуск", machines: "Выполняется на ваших машинах", transcripts: "Участники команды могут просматривать разговоры шагов.", requiredSessionsEditable: "Участники этой команды могут редактировать её сессии", visibleTo: ({ team }) => "Видно команде " + team },
    ja: { title: "公開範囲", chooseTeam: "チームを選択", loadFailed: "この実行を閲覧できる人を確認できませんでした", machines: "あなたのマシンで実行します", transcripts: "チームメンバーは各ステップの会話を閲覧できます。", requiredSessionsEditable: "このチームのセッションはメンバーが編集できます", visibleTo: ({ team }) => "閲覧可能なチーム：" + team },
    zhHans: { title: "可见范围", chooseTeam: "选择团队", loadFailed: "无法检查谁能查看此运行", machines: "在你的机器上运行", transcripts: "团队成员可以查看步骤对话。", requiredSessionsEditable: "此团队的成员可以编辑团队会话", visibleTo: ({ team }) => "可见团队：" + team },
    zhHant: { title: "可見範圍", chooseTeam: "選擇團隊", loadFailed: "無法檢查誰能查看此執行", machines: "在你的機器上執行", transcripts: "團隊成員可以查看步驟對話。", requiredSessionsEditable: "此團隊的成員可以編輯團隊會話", visibleTo: ({ team }) => "可見團隊：" + team },
};
