type Edit = { name: string; definitionId: string; headerVersion: number; bodyVersion: number };
type RepeatableMessage = { text: string };
const repeatable = {
    en: { repeatable: 'Make this repeatable', repeatableDescription: 'Ask the agent to turn what worked here into a workflow you can run again.', repeatablePrompt: 'Turn what we did here into a workflow I can run again. Draft it, check it with workflow.validate and save it, but don\'t run it.', repeatableMessagePrompt: 'Turn what we did in this message into a workflow I can run again. Draft it, check it with workflow.validate and save it, but don\'t run it.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    de: { repeatable: 'Wiederholbar machen', repeatableDescription: 'Bitte den Agenten, daraus einen wiederverwendbaren Workflow zu machen.', repeatablePrompt: 'Mache aus unserer Arbeit hier einen Workflow, den ich wieder ausführen kann. Entwirf ihn, prüfe ihn mit workflow.validate und speichere ihn, aber starte ihn nicht.', repeatableMessagePrompt: 'Mache aus unserer Arbeit in dieser Nachricht einen Workflow, den ich wieder ausführen kann. Entwirf ihn, prüfe ihn mit workflow.validate und speichere ihn, aber starte ihn nicht.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    es: { repeatable: 'Hacerlo repetible', repeatableDescription: 'Pide al agente que convierta lo que funcionó aquí en un workflow reutilizable.', repeatablePrompt: 'Convierte lo que hicimos aquí en un workflow que pueda volver a ejecutar. Diséñalo, compruébalo con workflow.validate y guárdalo, pero no lo ejecutes.', repeatableMessagePrompt: 'Convierte lo que hicimos en este mensaje en un workflow que pueda volver a ejecutar. Diséñalo, compruébalo con workflow.validate y guárdalo, pero no lo ejecutes.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    fr: { repeatable: 'Rendre réutilisable', repeatableDescription: 'Demandez à l’agent de transformer ce qui a fonctionné ici en workflow réutilisable.', repeatablePrompt: 'Transforme ce que nous avons fait ici en workflow que je peux relancer. Conçois-le, vérifie-le avec workflow.validate et enregistre-le, mais ne l’exécute pas.', repeatableMessagePrompt: 'Transforme ce que nous avons fait dans ce message en workflow que je peux relancer. Conçois-le, vérifie-le avec workflow.validate et enregistre-le, mais ne l’exécute pas.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    it: { repeatable: 'Rendi ripetibile', repeatableDescription: 'Chiedi all’agente di trasformare ciò che ha funzionato in un workflow riutilizzabile.', repeatablePrompt: 'Trasforma ciò che abbiamo fatto qui in un workflow che posso rieseguire. Progettalo, verificalo con workflow.validate e salvalo, ma non eseguirlo.', repeatableMessagePrompt: 'Trasforma ciò che abbiamo fatto in questo messaggio in un workflow che posso rieseguire. Progettalo, verificalo con workflow.validate e salvalo, ma non eseguirlo.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    pt: { repeatable: 'Tornar repetível', repeatableDescription: 'Peça ao agente para transformar o que funcionou aqui em um workflow reutilizável.', repeatablePrompt: 'Transforme o que fizemos aqui em um workflow que eu possa executar de novo. Crie, verifique com workflow.validate e salve, mas não execute.', repeatableMessagePrompt: 'Transforme o que fizemos nesta mensagem em um workflow que eu possa executar de novo. Crie, verifique com workflow.validate e salve, mas não execute.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    ca: { repeatable: 'Fes-ho repetible', repeatableDescription: 'Demana a l’agent que converteixi el que ha funcionat en un workflow reutilitzable.', repeatablePrompt: 'Converteix el que hem fet aquí en un workflow que pugui tornar a executar. Dissenya’l, comprova’l amb workflow.validate i desa’l, però no l’executis.', repeatableMessagePrompt: 'Converteix el que hem fet en aquest missatge en un workflow que pugui tornar a executar. Dissenya’l, comprova’l amb workflow.validate i desa’l, però no l’executis.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    pl: { repeatable: 'Uczyń powtarzalnym', repeatableDescription: 'Poproś agenta o zamianę tego, co się sprawdziło, w workflow wielokrotnego użytku.', repeatablePrompt: 'Zamień to, co tu zrobiliśmy, w workflow, który mogę uruchomić ponownie. Zaprojektuj go, sprawdź przez workflow.validate i zapisz, ale nie uruchamiaj.', repeatableMessagePrompt: 'Zamień to, co zrobiliśmy w tej wiadomości, w workflow, który mogę uruchomić ponownie. Zaprojektuj go, sprawdź przez workflow.validate i zapisz, ale nie uruchamiaj.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    ru: { repeatable: 'Сделать повторяемым', repeatableDescription: 'Попросите агента превратить то, что сработало, в переиспользуемый workflow.', repeatablePrompt: 'Преврати то, что мы сделали здесь, в workflow, который я смогу запускать снова. Создай его, проверь через workflow.validate и сохрани, но не запускай.', repeatableMessagePrompt: 'Преврати то, что мы сделали в этом сообщении, в workflow, который я смогу запускать снова. Создай его, проверь через workflow.validate и сохрани, но не запускай.', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    ja: { repeatable: '繰り返し使えるようにする', repeatableDescription: 'ここでうまくいった作業を再利用できるワークフローにするよう依頼します。', repeatablePrompt: 'ここでの作業を、もう一度実行できるワークフローにしてください。作成し、workflow.validate で検証して保存してください。実行はしないでください。', repeatableMessagePrompt: 'このメッセージでの作業を、もう一度実行できるワークフローにしてください。作成し、workflow.validate で検証して保存してください。実行はしないでください。', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    zhHans: { repeatable: '转为可重复使用', repeatableDescription: '请智能体把这里成功的做法变成可再次运行的工作流。', repeatablePrompt: '把我们在这里做的事情变成我可以再次运行的工作流。起草它，用 workflow.validate 检查并保存，但不要运行。', repeatableMessagePrompt: '把我们在这条消息中做的事情变成我可以再次运行的工作流。起草它，用 workflow.validate 检查并保存，但不要运行。', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
    zhHant: { repeatable: '轉為可重複使用', repeatableDescription: '請代理把這裡成功的做法變成可再次執行的工作流程。', repeatablePrompt: '把我們在這裡做的事情變成我可以再次執行的工作流程。起草它，用 workflow.validate 檢查並儲存，但不要執行。', repeatableMessagePrompt: '把我們在這則訊息中做的事情變成我可以再次執行的工作流程。起草它，用 workflow.validate 檢查並儲存，但不要執行。', repeatableMessageSource: ({ text }: RepeatableMessage) => `“${text}”` },
};
const en = {
    ...repeatable.en,
    create: 'Create with an agent', edit: 'Edit with an agent', agent: 'Agent',
    description: 'A new session drafts the workflow with you, checks it and saves it. Nothing runs until you choose Run now.',
    changedByAgent: 'Changed by the agent', saved: 'Saved by the agent just now',
    savedAge: ({ age }: { age: string }) => `Saved by the agent ${age}`,
    savedWorkflow: ({ name }: { name: string }) => `Saved workflow · ${name}`,
    updated: 'Updated the workflow', changed: ({ count }: { count: number }) => `Updated the workflow · ${count} steps changed`,
    openEditor: 'Open in editor', openSession: 'Open in Sessions',
    createPrompt: 'Draft a workflow with me, check it with workflow.validate, then save it. Don\'t run it.',
    createLead: 'Help me create a workflow that ',
    editPrompt: ({ name, definitionId, headerVersion, bodyVersion }: Edit) => `The saved workflow “${name}” has id ${definitionId} and revision: header ${headerVersion}, body ${bodyVersion}. Change it with workflow.definition.edit, and use workflow.definition.update only to replace it whole. Check it with workflow.validate before saving. Don't run it.`,
    editLead: ({ name }: { name: string }) => `Help me change ${name}: `,
};
type Copy = typeof en;
export const workflowAgentAuthoringTranslations: Record<'en'|'de'|'es'|'fr'|'it'|'pt'|'ca'|'pl'|'ru'|'ja'|'zhHans'|'zhHant', Copy> = {
    en,
    de: { ...repeatable.de, create: 'Mit einem Agenten erstellen', edit: 'Mit einem Agenten bearbeiten', agent: 'Agent', description: 'Eine neue Sitzung entwirft den Workflow mit dir, prüft ihn und speichert ihn. Erst „Jetzt starten“ führt ihn aus.', changedByAgent: 'Vom Agenten geändert', saved: 'Gerade vom Agenten gespeichert', savedAge: ({ age }) => `Vom Agenten gespeichert ${age}`, savedWorkflow: ({ name }) => `Workflow gespeichert · ${name}`, updated: 'Workflow aktualisiert', changed: ({ count }) => `Workflow aktualisiert · ${count} Schritte geändert`, openEditor: 'Im Editor öffnen', openSession: 'In Sitzungen öffnen', createPrompt: 'Entwirf mit mir einen Workflow, prüfe ihn mit workflow.validate und speichere ihn dann. Starte ihn nicht.', createLead: 'Hilf mir, einen Workflow zu erstellen, der ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `Der gespeicherte Workflow „${name}“ hat die ID ${definitionId} und die Revision: Kopf ${headerVersion}, Inhalt ${bodyVersion}. Ändere ihn mit workflow.definition.edit und nutze workflow.definition.update nur, um ihn ganz zu ersetzen. Prüfe ihn vor dem Speichern mit workflow.validate. Starte ihn nicht.`, editLead: ({ name }) => `Hilf mir, ${name} zu ändern: ` },
    es: { ...repeatable.es, create: 'Crear con un agente', edit: 'Editar con un agente', agent: 'Agente', description: 'Una sesión nueva diseña el workflow contigo, lo comprueba y lo guarda. No se ejecuta nada hasta que elijas Ejecutar ahora.', changedByAgent: 'Cambiado por el agente', saved: 'Guardado por el agente ahora', savedAge: ({ age }) => `Guardado por el agente ${age}`, savedWorkflow: ({ name }) => `Workflow guardado · ${name}`, updated: 'Workflow actualizado', changed: ({ count }) => `Workflow actualizado · ${count} pasos cambiados`, openEditor: 'Abrir en el editor', openSession: 'Abrir en Sesiones', createPrompt: 'Diseña conmigo un workflow, compruébalo con workflow.validate y luego guárdalo. No lo ejecutes.', createLead: 'Ayúdame a crear un workflow que ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `El workflow guardado «${name}» tiene el id ${definitionId} y la revisión: cabecera ${headerVersion}, cuerpo ${bodyVersion}. Cámbialo con workflow.definition.edit y usa workflow.definition.update solo para reemplazarlo entero. Compruébalo con workflow.validate antes de guardar. No lo ejecutes.`, editLead: ({ name }) => `Ayúdame a cambiar ${name}: ` },
    fr: { ...repeatable.fr, create: 'Créer avec un agent', edit: 'Modifier avec un agent', agent: 'Agent', description: 'Une nouvelle session conçoit le workflow avec vous, le vérifie et l’enregistre. Rien ne s’exécute avant Exécuter maintenant.', changedByAgent: 'Modifié par l’agent', saved: 'Enregistré par l’agent à l’instant', savedAge: ({ age }) => `Enregistré par l’agent ${age}`, savedWorkflow: ({ name }) => `Workflow enregistré · ${name}`, updated: 'Workflow mis à jour', changed: ({ count }) => `Workflow mis à jour · ${count} étapes modifiées`, openEditor: 'Ouvrir dans l’éditeur', openSession: 'Ouvrir dans Sessions', createPrompt: 'Conçois un workflow avec moi, vérifie-le avec workflow.validate, puis enregistre-le. Ne l’exécute pas.', createLead: 'Aide-moi à créer un workflow qui ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `Le workflow enregistré « ${name} » a l’id ${definitionId} et la révision : en-tête ${headerVersion}, corps ${bodyVersion}. Modifie-le avec workflow.definition.edit et utilise workflow.definition.update seulement pour le remplacer entièrement. Vérifie-le avec workflow.validate avant d’enregistrer. Ne l’exécute pas.`, editLead: ({ name }) => `Aide-moi à modifier ${name} : ` },
    it: { ...repeatable.it, create: 'Crea con un agente', edit: 'Modifica con un agente', agent: 'Agente', description: 'Una nuova sessione progetta il workflow con te, lo verifica e lo salva. Nulla viene eseguito finché non scegli Esegui ora.', changedByAgent: 'Modificato dall’agente', saved: 'Salvato dall’agente ora', savedAge: ({ age }) => `Salvato dall’agente ${age}`, savedWorkflow: ({ name }) => `Workflow salvato · ${name}`, updated: 'Workflow aggiornato', changed: ({ count }) => `Workflow aggiornato · ${count} passi modificati`, openEditor: 'Apri nell’editor', openSession: 'Apri in Sessioni', createPrompt: 'Progetta con me un workflow, verificalo con workflow.validate e poi salvalo. Non eseguirlo.', createLead: 'Aiutami a creare un workflow che ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `Il workflow salvato “${name}” ha id ${definitionId} e revisione: intestazione ${headerVersion}, corpo ${bodyVersion}. Modificalo con workflow.definition.edit e usa workflow.definition.update solo per sostituirlo interamente. Verificalo con workflow.validate prima di salvare. Non eseguirlo.`, editLead: ({ name }) => `Aiutami a modificare ${name}: ` },
    pt: { ...repeatable.pt, create: 'Criar com um agente', edit: 'Editar com um agente', agent: 'Agente', description: 'Uma nova sessão cria o workflow com você, verifica e salva. Nada é executado até você escolher Executar agora.', changedByAgent: 'Alterado pelo agente', saved: 'Salvo pelo agente agora', savedAge: ({ age }) => `Salvo pelo agente ${age}`, savedWorkflow: ({ name }) => `Workflow salvo · ${name}`, updated: 'Workflow atualizado', changed: ({ count }) => `Workflow atualizado · ${count} etapas alteradas`, openEditor: 'Abrir no editor', openSession: 'Abrir em Sessões', createPrompt: 'Crie comigo um workflow, verifique com workflow.validate e depois salve. Não execute.', createLead: 'Ajude-me a criar um workflow que ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `O workflow salvo “${name}” tem id ${definitionId} e revisão: cabeçalho ${headerVersion}, corpo ${bodyVersion}. Altere-o com workflow.definition.edit e use workflow.definition.update apenas para substituí-lo por inteiro. Verifique com workflow.validate antes de salvar. Não execute.`, editLead: ({ name }) => `Ajude-me a mudar ${name}: ` },
    ca: { ...repeatable.ca, create: 'Crea amb un agent', edit: 'Edita amb un agent', agent: 'Agent', description: 'Una sessió nova dissenya el workflow amb tu, el comprova i el desa. No s’executa res fins que triïs Executa ara.', changedByAgent: 'Canviat per l’agent', saved: 'Desat per l’agent ara mateix', savedAge: ({ age }) => `Desat per l’agent ${age}`, savedWorkflow: ({ name }) => `Workflow desat · ${name}`, updated: 'Workflow actualitzat', changed: ({ count }) => `Workflow actualitzat · ${count} passos canviats`, openEditor: 'Obre a l’editor', openSession: 'Obre a Sessions', createPrompt: 'Dissenya amb mi un workflow, comprova’l amb workflow.validate i després desa’l. No l’executis.', createLead: 'Ajuda’m a crear un workflow que ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `El workflow desat «${name}» té l’id ${definitionId} i la revisió: capçalera ${headerVersion}, cos ${bodyVersion}. Canvia’l amb workflow.definition.edit i usa workflow.definition.update només per substituir-lo sencer. Comprova’l amb workflow.validate abans de desar. No l’executis.`, editLead: ({ name }) => `Ajuda’m a canviar ${name}: ` },
    pl: { ...repeatable.pl, create: 'Utwórz z agentem', edit: 'Edytuj z agentem', agent: 'Agent', description: 'Nowa sesja projektuje z tobą workflow, sprawdza go i zapisuje. Nic nie ruszy, dopóki nie wybierzesz Uruchom teraz.', changedByAgent: 'Zmienione przez agenta', saved: 'Właśnie zapisane przez agenta', savedAge: ({ age }) => `Zapisane przez agenta ${age}`, savedWorkflow: ({ name }) => `Zapisany workflow · ${name}`, updated: 'Workflow zaktualizowany', changed: ({ count }) => `Workflow zaktualizowany · zmienione kroki: ${count}`, openEditor: 'Otwórz w edytorze', openSession: 'Otwórz w Sesjach', createPrompt: 'Zaprojektuj ze mną workflow, sprawdź go przez workflow.validate, a potem zapisz. Nie uruchamiaj go.', createLead: 'Pomóż mi utworzyć workflow, który ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `Zapisany workflow „${name}” ma id ${definitionId} i rewizję: nagłówek ${headerVersion}, treść ${bodyVersion}. Zmień go przez workflow.definition.edit, a workflow.definition.update używaj tylko do zastąpienia całości. Sprawdź go przez workflow.validate przed zapisem. Nie uruchamiaj go.`, editLead: ({ name }) => `Pomóż mi zmienić ${name}: ` },
    ru: { ...repeatable.ru, create: 'Создать с агентом', edit: 'Изменить с агентом', agent: 'Агент', description: 'Новая сессия составит workflow вместе с вами, проверит и сохранит его. Ничего не запустится, пока вы не выберете «Запустить сейчас».', changedByAgent: 'Изменено агентом', saved: 'Только что сохранено агентом', savedAge: ({ age }) => `Сохранено агентом ${age}`, savedWorkflow: ({ name }) => `Workflow сохранён · ${name}`, updated: 'Workflow обновлён', changed: ({ count }) => `Workflow обновлён · изменено шагов: ${count}`, openEditor: 'Открыть в редакторе', openSession: 'Открыть в Сессиях', createPrompt: 'Составь со мной workflow, проверь его через workflow.validate, затем сохрани. Не запускай его.', createLead: 'Помоги мне создать workflow, который ', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `У сохранённого workflow «${name}» id ${definitionId} и ревизия: заголовок ${headerVersion}, тело ${bodyVersion}. Измени его через workflow.definition.edit, а workflow.definition.update используй только для полной замены. Перед сохранением проверь через workflow.validate. Не запускай его.`, editLead: ({ name }) => `Помоги мне изменить ${name}: ` },
    ja: { ...repeatable.ja, create: 'エージェントと作成', edit: 'エージェントと編集', agent: 'エージェント', description: '新しいセッションがあなたと一緒にワークフローを作成し、検証して保存します。「今すぐ実行」を選ぶまで何も実行されません。', changedByAgent: 'エージェントが変更', saved: 'エージェントが今保存しました', savedAge: ({ age }) => `エージェントが保存 · ${age}`, savedWorkflow: ({ name }) => `ワークフローを保存 · ${name}`, updated: 'ワークフローを更新', changed: ({ count }) => `ワークフローを更新 · ${count} ステップ変更`, openEditor: 'エディターで開く', openSession: 'セッションで開く', createPrompt: '一緒にワークフローを作成し、workflow.validate で検証してから保存してください。実行はしないでください。', createLead: '次のようなワークフローの作成を手伝ってください：', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `保存済みワークフロー「${name}」の id は ${definitionId}、リビジョンはヘッダー ${headerVersion}、本文 ${bodyVersion} です。workflow.definition.edit で変更し、全体を置き換えるときだけ workflow.definition.update を使ってください。保存前に workflow.validate で検証してください。実行はしないでください。`, editLead: ({ name }) => `${name} の変更を手伝ってください：` },
    zhHans: { ...repeatable.zhHans, create: '与智能体一起创建', edit: '与智能体一起编辑', agent: '智能体', description: '新会话会与你一起起草工作流，检查并保存。选择立即运行之前不会执行任何内容。', changedByAgent: '由智能体更改', saved: '智能体刚刚保存', savedAge: ({ age }) => `由智能体保存 · ${age}`, savedWorkflow: ({ name }) => `工作流已保存 · ${name}`, updated: '已更新工作流', changed: ({ count }) => `已更新工作流 · 更改了 ${count} 个步骤`, openEditor: '在编辑器中打开', openSession: '在会话中打开', createPrompt: '和我一起起草一个工作流，用 workflow.validate 检查，然后保存。不要运行它。', createLead: '帮我创建一个工作流，它会', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `已保存的工作流“${name}”的 id 为 ${definitionId}，版本：头部 ${headerVersion}，正文 ${bodyVersion}。用 workflow.definition.edit 修改它，只有整体替换时才使用 workflow.definition.update。保存前用 workflow.validate 检查。不要运行它。`, editLead: ({ name }) => `帮我修改 ${name}：` },
    zhHant: { ...repeatable.zhHant, create: '與代理一起建立', edit: '與代理一起編輯', agent: '代理', description: '新的工作階段會與你一起起草工作流程，檢查並儲存。選擇立即執行之前不會執行任何內容。', changedByAgent: '由代理更改', saved: '代理剛剛儲存', savedAge: ({ age }) => `由代理儲存 · ${age}`, savedWorkflow: ({ name }) => `工作流程已儲存 · ${name}`, updated: '已更新工作流程', changed: ({ count }) => `已更新工作流程 · 更改了 ${count} 個步驟`, openEditor: '在編輯器中開啟', openSession: '在工作階段中開啟', createPrompt: '和我一起起草一個工作流程，用 workflow.validate 檢查，然後儲存。不要執行它。', createLead: '幫我建立一個工作流程，它會', editPrompt: ({ name, definitionId, headerVersion, bodyVersion }) => `已儲存的工作流程「${name}」的 id 為 ${definitionId}，版本：標頭 ${headerVersion}，內容 ${bodyVersion}。用 workflow.definition.edit 修改它，只有整體替換時才使用 workflow.definition.update。儲存前用 workflow.validate 檢查。不要執行它。`, editLead: ({ name }) => `幫我修改 ${name}：` },
};
