import type { Prisma } from "@prisma/client";

/**
 * Canonical persistence reads for API, lifecycle, and change publication.
 * Keep these in one place so a new Run/trigger arm cannot be cast away by a
 * legacy partial select before versioned projections can enforce it.
 */
export const automationListItemSelect = {
    id: true,
    accountId: true,
    name: true,
    description: true,
    enabled: true,
    triggerKind: true,
    scheduleKind: true,
    scheduleExpr: true,
    everyMs: true,
    timezone: true,
    targetType: true,
    templateCiphertext: true,
    templateVersion: true,
    triggerEventPluginId: true,
    triggerEventLocalId: true,
    triggerSourceSelectorId: true,
    triggerSourceContractVersion: true,
    triggerObservationTransport: true,
    triggerWebhookEndpointId: true,
    triggerObservationStartsAt: true,
    watcherMachineId: true,
    watcherMachineInstallationId: true,
    watcherPluginId: true,
    watcherMaterializationId: true,
    triggerDefinitionEnvelope: true,
    nextRunAt: true,
    lastRunAt: true,
    createdAt: true,
    updatedAt: true,
    assignments: {
        select: {
            machineId: true,
            enabled: true,
            priority: true,
            updatedAt: true,
        },
        orderBy: [{ priority: "desc" }, { machineId: "asc" }],
    },
} satisfies Prisma.AutomationSelect;

export const automationRunItemSelect = {
    id: true,
    automationId: true,
    accountId: true,
    state: true,
    originKind: true,
    originOccurredAt: true,
    occurrenceKey: true,
    occurrenceEvidenceEqualityTag: true,
    originSourceSelectorId: true,
    triggerEvidenceEnvelope: true,
    executionInputEnvelope: true,
    executionDispatchState: true,
    executionAttempt: true,
    executionDispatchCommittedAt: true,
    executionDispatchDueAt: true,
    executionNativeRunId: true,
    executionNativeCallId: true,
    executionNativeSidechainId: true,
    resultEnvelope: true,
    replyContextEnvelope: true,
    replyHandoffActionPluginId: true,
    replyHandoffActionLocalId: true,
    replyHandoffTargetMachineId: true,
    replyHandoffTargetMachineInstallationId: true,
    replyHandoffTargetMaterializationId: true,
    replyHandoffId: true,
    replyHandoffState: true,
    replyHandoffAttempt: true,
    replyHandoffDueAt: true,
    replyHandoffReceiptEnvelope: true,
    scheduledAt: true,
    dueAt: true,
    claimedAt: true,
    startedAt: true,
    finishedAt: true,
    claimedByMachineId: true,
    leaseExpiresAt: true,
    attempt: true,
    revision: true,
    summaryCiphertext: true,
    errorCode: true,
    errorMessage: true,
    producedSessionId: true,
    createdAt: true,
    updatedAt: true,
} as const;

export const automationRunWithAutomationSelect = {
    ...automationRunItemSelect,
    automation: {
        select: {
            id: true,
            name: true,
            enabled: true,
            targetType: true,
            templateCiphertext: true,
            triggerKind: true,
        },
    },
} as const;
