import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

import {
    MERMAID_WEBVIEW_BUNDLE_BYTES,
    MERMAID_WEBVIEW_BUNDLE_JS,
} from './mermaidWebViewBundle.generated';
import {
    assertMermaidWebViewBundleFresh,
    createMermaidWebViewBundleSource,
} from '../../../tools/mermaid/buildMermaidWebViewBundle.mjs';

const expoAppDir = path.resolve(path.dirname(url.fileURLToPath(import.meta.url)), '..', '..', '..');

describe('native Mermaid WebView bundle', () => {
    it('contains the local runtime and no CDN fallback within its reviewed budget', () => {
        expect(MERMAID_WEBVIEW_BUNDLE_JS).toContain('HAPPIER_MERMAID');
        expect(MERMAID_WEBVIEW_BUNDLE_JS).not.toContain('cdn.jsdelivr.net');
        expect(MERMAID_WEBVIEW_BUNDLE_JS).not.toContain('unpkg.com');
        expect(MERMAID_WEBVIEW_BUNDLE_BYTES).toBeLessThanOrEqual(3_500_000);
        expect(new TextEncoder().encode(MERMAID_WEBVIEW_BUNDLE_JS).byteLength)
            .toBe(MERMAID_WEBVIEW_BUNDLE_BYTES);
    });

    it('is byte-for-byte fresh from the current entry and locked dependencies', async () => {
        const expected = await createMermaidWebViewBundleSource({ expoAppDir });
        const generatedFilePath = path.resolve(
            expoAppDir,
            'sources/components/markdown/mermaidWebViewBundle.generated.ts',
        );
        expect(() => assertMermaidWebViewBundleFresh({
            actualContents: fs.readFileSync(generatedFilePath, 'utf8'),
            expectedContents: expected.contents,
            generatedFilePath,
        })).not.toThrow();
    });

    it('fails freshness verification for missing or stale generated bytes', () => {
        expect(() => assertMermaidWebViewBundleFresh({
            actualContents: null,
            expectedContents: 'fresh',
            generatedFilePath: '/candidate/mermaidWebViewBundle.generated.ts',
        })).toThrow(/missing/i);
        expect(() => assertMermaidWebViewBundleFresh({
            actualContents: 'stale',
            expectedContents: 'fresh',
            generatedFilePath: '/candidate/mermaidWebViewBundle.generated.ts',
        })).toThrow(/stale/i);
    });

    it('fails candidate verification when the generator cannot produce expected bytes', async () => {
        await expect(createMermaidWebViewBundleSource({
            expoAppDir: path.resolve(expoAppDir, 'missing-generator-input'),
        })).rejects.toThrow(/entry not found/i);
    });

    it('declares esbuild at the UI build owner', () => {
        const packageJson = JSON.parse(fs.readFileSync(path.resolve(expoAppDir, 'package.json'), 'utf8'));
        expect(packageJson.devDependencies?.esbuild).toBe('^0.27.2');
    });
});
