export const SANDBOX_PRESERVE_KEYS = [
  'HAPPIER_STACK_VERBOSE',
  'HAPPIER_STACK_INVOKED_CWD',
  'HAPPIER_STACK_SANDBOX_DIR',
  'HAPPIER_STACK_SANDBOX_ALLOW_GLOBAL',
  'HAPPIER_STACK_SANDBOX_WORKSPACE_DIR',
  // Mobile review UX (safe to preserve; required so dev-client links target the correct app scheme).
  'HAPPIER_STACK_DEV_CLIENT_SCHEME',
  'HAPPIER_STACK_REVIEW_MOBILE_SCHEME',
  'HAPPIER_STACK_MOBILE_SCHEME',
  'HAPPIER_STACK_MOBILE_HOST',
  'HAPPIER_STACK_UPDATE_CHECK',
  'HAPPIER_STACK_UPDATE_CHECK_INTERVAL_MS',
  'HAPPIER_STACK_UPDATE_NOTIFY_INTERVAL_MS',
];

export const STACK_WRAPPER_PRESERVE_KEYS = [
  // Stack/env pointers:
  'HAPPIER_STACK_ENV_FILE',
  'HAPPIER_STACK_STACK',
  'HAPPIER_STACK_OWNER',
  'HAPPIER_STACK_REPO_DIR',
  'HAPPIER_STACK_RUNTIME_MODE',
  'HAPPIER_STACK_RUNTIME_STATE_PATH',
  'HAPPIER_STACK_DAEMON',

  // Sandbox detection + policy.
  'HAPPIER_STACK_SANDBOX_DIR',
  'HAPPIER_STACK_SANDBOX_ALLOW_GLOBAL',
  'HAPPIER_STACK_SANDBOX_WORKSPACE_DIR',

  // Sandbox-enforced dirs.
  'HAPPIER_STACK_CLI_ROOT_DISABLE',
  'HAPPIER_STACK_CANONICAL_HOME_DIR',
  'HAPPIER_STACK_HOME_DIR',
  'HAPPIER_STACK_WORKSPACE_DIR',
  'HAPPIER_STACK_RUNTIME_DIR',
  'HAPPIER_STACK_STORAGE_DIR',
  'HAPPIER_STACK_CLI_HOME_DIR',
  'HAPPIER_STACK_CLI_IDENTITY',

  // UX knobs.
  'HAPPIER_STACK_VERBOSE',
  // TUI marker (set by `hstack tui` and must survive stack env scrubbing).
  'HAPPIER_STACK_TUI',
  'HAPPIER_STACK_RESCUE',
  'HAPPIER_STACK_UPDATE_CHECK',
  'HAPPIER_STACK_UPDATE_CHECK_INTERVAL_MS',
  'HAPPIER_STACK_UPDATE_NOTIFY_INTERVAL_MS',

  // Guided auth flow coordination across wrappers.
  'HAPPIER_STACK_DAEMON_WAIT_FOR_AUTH',
  'HAPPIER_STACK_AUTH_FLOW',
  'HAPPIER_STACK_AUTH_INNER',
  'HAPPIER_STACK_AUTH_SKIP_BUNDLE_CHECK',
  'HAPPIER_STACK_AUTH_UI_READY_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_UI_START_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_SERVER_READY_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_EXPO_SOFT_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_EXPO_MAX_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_EXPO_BUNDLE_READY_TIMEOUT_MS',
  'HAPPIER_STACK_AUTH_EXPO_PROGRESS_INTERVAL_MS',
  'HAPPIER_STACK_AUTH_CREDENTIAL_VALIDATION_ATTEMPTS',
  'HAPPIER_STACK_AUTH_CREDENTIAL_VALIDATION_RETRY_DELAY_MS',

  // Safe global defaults.
  'HAPPIER_STACK_STACK_PORT_START',
  'HAPPIER_STACK_PM_CACHE_BASE_DIR',

  // Explicit local runtime/build overrides for source-mode stack launches.
  'HAPPIER_STACK_CLI_BUILD',
  'HAPPIER_STACK_CLI_BUILD_MODE',
  'HAPPIER_STACK_SYNC_BUNDLED_WORKSPACES',
  'HAPPIER_STACK_SKIP_REFRESH_DEPS',
  'HAPPIER_STACK_DISABLE_REFRESH_DEPS',
  'HAPPIER_STACK_ALLOW_REFRESH_DEPS',
  'HAPPIER_STACK_SERVICE_ALLOW_REFRESH_DEPS',

  'HAPPIER_STACK_BIND_MODE',
  'HAPPIER_STACK_EXPO_HOST',

  // Expo dev-server port strategy.
  'HAPPIER_STACK_EXPO_DEV_PORT',
  'HAPPIER_STACK_EXPO_DEV_PORT_STRATEGY',
  'HAPPIER_STACK_EXPO_DEV_PORT_BASE',
  'HAPPIER_STACK_EXPO_DEV_PORT_RANGE',

  // Mobile review UX.
  'HAPPIER_STACK_DEV_CLIENT_SCHEME',
  'HAPPIER_STACK_REVIEW_MOBILE_SCHEME',
  'HAPPIER_STACK_MOBILE_SCHEME',
  'HAPPIER_STACK_MOBILE_HOST',

  // Mobile native-build hygiene knobs.
  'HAPPIER_STACK_CLEAR_ANDROID_NATIVE_BUILD_STATE',
];

export const STACK_WRAPPER_CLEAR_UNPREFIXED_KEYS = [
  'HAPPIER_SERVER_URL',
  'HAPPIER_PUBLIC_SERVER_URL',
  'HAPPIER_LOCAL_SERVER_URL',
  'HAPPIER_WEBAPP_URL',
  'HAPPIER_PLUGIN_UI_ARTIFACT_BROWSER_ORIGIN',
  'HAPPIER_HOME_DIR',
  'HAPPIER_ACTIVE_SERVER_ID',
  'HAPPIER_CONNECTED_SERVICE_TARGET_MATERIALIZED_ROOT',
  'TSX_TSCONFIG_PATH',
  'APP_ENV',
  'EXPO_UPDATES_CHANNEL',
  'EXPO_PUBLIC_HAPPIER_FEATURE_POLICY_ENV',
  'EXPO_PUBLIC_HAPPIER_BUILD_FEATURES_ALLOW',
  'EXPO_PUBLIC_HAPPIER_BUILD_FEATURES_DENY',
  // Runtime feature policy knobs should be stack-local; stale values from a prior stack can
  // silently bleed into a newly selected stack and override expected defaults.
  'HAPPIER_FEATURE_POLICY_ENV',
  'HAPPIER_EMBEDDED_POLICY_ENV',
  'HAPPIER_BUILD_FEATURES_ALLOW',
  'HAPPIER_BUILD_FEATURES_DENY',
];

export function scrubHappierStackEnv(
  env,
  { keepHappierStackKeys = [], clearUnprefixedKeys = [] } = {},
) {
  const input = env && typeof env === 'object' ? env : {};
  const out = { ...input };
  const keep = new Set((keepHappierStackKeys ?? []).map((k) => String(k).trim()).filter(Boolean));
  for (const k of Object.keys(out)) {
    if (k.startsWith('HAPPIER_STACK_') && !keep.has(k)) {
      delete out[k];
    }
  }
  for (const k of (clearUnprefixedKeys ?? []).map((x) => String(x).trim()).filter(Boolean)) {
    delete out[k];
  }
  return out;
}
