import type { TranslationKeyNoParams } from '@/text';

/** Settings sections that own a nested layout; their screens resolve under `/settings/<navigator>`. */
export type SettingsNestedNavigator = 'account/api-tokens' | 'connected-services' | 'providers' | 'agents' | 'teams' | 'mcp' | 'prompts' | 'prompts/docs' | 'prompts/skills' | 'prompts/templates' | 'machines' | 'embeds' | 'profiles' | 'roles' | 'remote-hosts' | 'home/[serverId]' | 'server';

type SettingsRouteChromeDefinition = Readonly<{
    navigator?: SettingsNestedNavigator;
    headerBackTitleKey?: TranslationKeyNoParams;
    headerShown?: boolean;
    /**
     * An entity page names itself in its own `PageHeader alwaysShowTitle` (a Team, a member, a
     * Group), so the phone header keeps an empty title: one title on the page.
     */
    headsItself?: boolean;
    name: string;
    titleKey?: TranslationKeyNoParams;
}>;

export const SETTINGS_ROUTE_CHROME_DEFINITIONS: readonly SettingsRouteChromeDefinition[] = [
    { name: 'index', titleKey: 'settings.title', headerBackTitleKey: 'common.home' },
    { name: 'account', titleKey: 'settings.account' },
    { name: 'account/security', titleKey: 'settingsAccount.security', headerBackTitleKey: 'settings.account' },
    // API tokens are one collection (the rail + a token's detail) under its own nested stack.
    { name: 'account/api-tokens', titleKey: 'settingsApiTokens.title' },
    { name: 'index', navigator: 'account/api-tokens', titleKey: 'settingsApiTokens.title' },
    { name: '[tokenId]', navigator: 'account/api-tokens', titleKey: 'settingsApiTokens.title', headsItself: true },
    { name: 'acp-backend', titleKey: 'settings.acpCatalogBackendEditorTitle' },
    { name: 'acp', titleKey: 'settings.acpCatalog' },
    { name: 'actions', titleKey: 'common.actions' },
    { name: 'actions/[actionId]', titleKey: 'common.actions' },
    { name: 'add-phone', titleKey: 'settings.addYourPhone' },
    { name: 'appearance', titleKey: 'settings.appearance' },
    { name: 'appearance/themes', titleKey: 'settingsAppearance.themeProfiles.title' },
    { name: 'appearance/themes/[profileId]', titleKey: 'settingsAppearance.themeProfiles.editorTitle' },
    { name: 'appearance/themes/import', titleKey: 'settingsAppearance.themeProfiles.importProfile' },
    { name: 'appearance/themes/export', titleKey: 'settingsAppearance.themeProfiles.exportProfile' },
    { name: 'attachments', titleKey: 'settings.attachments' },
    { name: 'connect/claude', headerShown: false },
    // Connected services is one collection (its rail + the detail) under its own nested stack; the
    // index of every service is its unselected detail (lab `csvc` C1/C2).
    { name: 'connected-services', titleKey: 'settings.connectedServices' },
    { name: 'index', navigator: 'connected-services', titleKey: 'settings.connectedServices' },
    { name: 'connect', navigator: 'connected-services', titleKey: 'settings.connectedServices', headsItself: true },
    { name: '[serviceId]', navigator: 'connected-services', titleKey: 'connectedServices.fallbackName' },
    { name: 'account', navigator: 'connected-services', titleKey: 'settings.connectedServices', headsItself: true },
    { name: 'sign-in', navigator: 'connected-services', titleKey: 'connectedServicesCollection.agentSignInTitle' },
    { name: 'provider-state-sharing', navigator: 'connected-services', titleKey: 'connectedServicesSettings.perAgentTitle' },
    // Legacy deep-link redirects (`ConnectedAccountLegacyRouteRedirect`). They
    // render no screen of their own, so their chrome title is the section's, not
    // the name of the screen each one used to be.
    { name: 'group', navigator: 'connected-services', titleKey: 'connectedServices.title' },
    { name: 'oauth', navigator: 'connected-services', titleKey: 'connectedServices.title' },
    { name: 'profile', navigator: 'connected-services', titleKey: 'connectedServices.title' },
    { name: 'desktop', titleKey: 'settingsDesktop.title' },
    { name: 'diagnosis', titleKey: 'diagnosis.title' },
    { name: 'features', titleKey: 'settings.features' },
    { name: 'external-sessions', titleKey: 'externalSessions.settingsTitle' },
    { name: 'home/index', titleKey: 'homeGovernance.title' },
    // The Home console is one collection (its rail + the page) under its own nested stack (plan §3.10).
    { name: 'home/[serverId]', titleKey: 'homeGovernance.title' },
    { name: 'index', navigator: 'home/[serverId]', titleKey: 'homeGovernance.title' },
    { name: 'people/index', navigator: 'home/[serverId]', titleKey: 'homeGovernance.people' },
    { name: 'people/[accountId]', navigator: 'home/[serverId]', titleKey: 'homeGovernance.people', headsItself: true },
    { name: 'policies', navigator: 'home/[serverId]', titleKey: 'homeGovernance.policies' },
    { name: 'teams', navigator: 'home/[serverId]', titleKey: 'homeGovernance.teams' },
    { name: 'reach', navigator: 'home/[serverId]', titleKey: 'homeGovernance.reach.title' },
    { name: 'email', navigator: 'home/[serverId]', titleKey: 'homeGovernance.email.title' },
    { name: 'features', navigator: 'home/[serverId]', titleKey: 'homeGovernance.features.title' },
    { name: 'data', navigator: 'home/[serverId]', titleKey: 'homeGovernance.data.title' },
    { name: 'runtime', navigator: 'home/[serverId]', titleKey: 'homeGovernance.runtime.title' },
    { name: 'server-settings', navigator: 'home/[serverId]', titleKey: 'homeGovernance.console.serverSettings' },
    { name: 'activity', navigator: 'home/[serverId]', titleKey: 'homeGovernance.activity.title' },
    { name: 'policies/identity/new', navigator: 'home/[serverId]', titleKey: 'identityAdministration.createTitle' },
    { name: 'policies/identity/[providerId]/index', navigator: 'home/[serverId]', titleKey: 'identityAdministration.title' },
    { name: 'policies/identity/[providerId]/edit', navigator: 'home/[serverId]', titleKey: 'identityAdministration.editTitle' },
    { name: 'policies/github-apps/new', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubAppCreateTitle' },
    { name: 'policies/github-apps/[registrationId]/index', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubApps' },
    { name: 'policies/github-apps/[registrationId]/edit', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubAppEditTitle' },
    // Identity providers and GitHub Apps live under Sign-in providers; the Policies routes above
    // only redirect links saved before the move.
    { name: 'sign-in-providers', navigator: 'home/[serverId]', titleKey: 'homeGovernance.signInProviders.title' },
    { name: 'sign-in-providers/identity/new', navigator: 'home/[serverId]', titleKey: 'identityAdministration.createTitle' },
    { name: 'sign-in-providers/identity/[providerId]/index', navigator: 'home/[serverId]', titleKey: 'identityAdministration.title' },
    { name: 'sign-in-providers/identity/[providerId]/edit', navigator: 'home/[serverId]', titleKey: 'identityAdministration.editTitle' },
    { name: 'sign-in-providers/github-apps/new', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubAppCreateTitle' },
    { name: 'sign-in-providers/github-apps/[registrationId]/index', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubApps' },
    { name: 'sign-in-providers/github-apps/[registrationId]/edit', navigator: 'home/[serverId]', titleKey: 'identityAdministration.githubAppEditTitle' },
    { name: 'keyboard', titleKey: 'settingsKeyboard.title' },
    { name: 'language', titleKey: 'settingsLanguage.title' },
    // Embeds is one collection (its rail + the detail, create and edit) under its own nested stack (plan 04 §4.10).
    { name: 'embeds', titleKey: 'settingsEmbeds.title' },
    { name: 'index', navigator: 'embeds', titleKey: 'settingsEmbeds.title' },
    { name: 'new', navigator: 'embeds', titleKey: 'settingsEmbeds.newTitle' },
    { name: '[tokenId]', navigator: 'embeds', titleKey: 'settingsEmbeds.title', headsItself: true },
    { name: 'machines', titleKey: 'settings.machines' },
    { name: 'index', navigator: 'machines', titleKey: 'settings.machines' },
    { name: '[id]', navigator: 'machines', titleKey: 'settings.machines' },
    { name: 'managed/[id]', navigator: 'machines', titleKey: 'settings.machines' },
    { name: 'add', navigator: 'machines', titleKey: 'settings.addMachine' },
    { name: 'add/[provisioner]', navigator: 'machines', titleKey: 'settings.addMachine' },
    { name: 'presets/new', navigator: 'machines', titleKey: 'machinePresets.newPreset' },
    { name: 'presets/[presetId]', navigator: 'machines', titleKey: 'machinePresets.title', headsItself: true },
    { name: 'this-computer', navigator: 'machines', titleKey: 'settingsMachines.thisComputerTitle' },
    { name: 'defaults', navigator: 'machines', titleKey: 'settingsMachines.defaultsTitle', headsItself: true },
    { name: 'pools/[poolId]', navigator: 'machines', titleKey: 'machinePools.title' },
    { name: 'pools/new', navigator: 'machines', titleKey: 'machinePools.add' },
    { name: 'mcp-server', titleKey: 'settings.mcpServersEditorTitle' },
    { name: 'mcp', titleKey: 'settings.mcpServers' },
    { name: 'index', navigator: 'mcp', titleKey: 'settings.mcpServers' },
    { name: 'new', navigator: 'mcp', titleKey: 'mcpSettings.newServer' },
    { name: 'on-machine', navigator: 'mcp', titleKey: 'mcpSettings.onMachineTitle' },
    { name: 'preview', navigator: 'mcp', titleKey: 'mcpSettings.previewTitle' },
    { name: '[serverId]', navigator: 'mcp', titleKey: 'settings.mcpServersEditorTitle' },
    { name: 'memory', titleKey: 'settings.memorySearch' },
    { name: 'search', titleKey: 'conversationSearch.settingsTitle' },
    { name: 'notifications', titleKey: 'settings.notifications' },
    { name: 'notifications/push', titleKey: 'settingsNotifications.push.troubleshootTitle' },
    { name: 'pets', titleKey: 'settingsPets.title' },
    { name: 'plugins/index', titleKey: 'settingsPlugins.title' },
    { name: 'plugins/webhooks', titleKey: 'settingsPlugins.webhookAdministration.title' },
    { name: 'plugins/listing', titleKey: 'settingsPlugins.detailTitle' },
    { name: 'plugins/[pluginId]', titleKey: 'settingsPlugins.detailTitle' },
    { name: 'plugins/[pluginId]/[pageId]', titleKey: 'settingsPlugins.detailTitle' },
    { name: 'plugins/sources', titleKey: 'settingsPlugins.sourceAdministration.title' },
    { name: 'plugins/development', titleKey: 'settingsPlugins.views.development' },
    { name: 'plugins/diagnostics', titleKey: 'settingsPlugins.views.diagnostics' },
    { name: 'profiles', titleKey: 'settingsFeatures.profiles' },
    { name: 'index', navigator: 'profiles', titleKey: 'settingsFeatures.profiles' },
    { name: 'new', navigator: 'profiles', titleKey: 'profiles.addProfile' },
    { name: 'default-environment', navigator: 'profiles', titleKey: 'profiles.noProfile' },
    { name: '[profileId]', navigator: 'profiles', titleKey: 'profiles.editProfile' },
    { name: 'roles', titleKey: 'roles.rail.label' },
    { name: 'index', navigator: 'roles', titleKey: 'roles.rail.label' },
    { name: 'new', navigator: 'roles', titleKey: 'roles.settings.newRole' },
    { name: '[roleId]', navigator: 'roles', titleKey: 'roles.rail.label' },
    { name: 'delegation', titleKey: 'roles.delegation.title' },
    // `prompts` has its own layout (it waits for the library to load), so the stack sees one `prompts` screen.
    { name: 'prompts', titleKey: 'settings.prompts' },
    { name: 'index', navigator: 'prompts', titleKey: 'settings.prompts' },
    { name: 'assets', navigator: 'prompts', titleKey: 'promptLibrary.externalAssets' },
    { name: 'index', navigator: 'prompts/docs', titleKey: 'promptLibrary.prompts' },
    { name: '[id]', navigator: 'prompts/docs', titleKey: 'promptLibrary.editPrompt' },
    { name: '[id]/export', navigator: 'prompts/docs', titleKey: 'promptLibrary.externalAssetsExportTitle' },
    { name: 'new', navigator: 'prompts/docs', titleKey: 'promptLibrary.newPrompt' },
    { name: 'docs', navigator: 'prompts', titleKey: 'promptLibrary.prompts' },
    { name: 'skills', navigator: 'prompts', titleKey: 'promptLibrary.skills' },
    { name: 'templates', navigator: 'prompts', titleKey: 'promptLibrary.templates' },
    { name: 'folders', navigator: 'prompts', titleKey: 'promptLibrary.folders' },
    { name: 'library', navigator: 'prompts', headerShown: false },
    { name: 'registries', navigator: 'prompts', titleKey: 'promptLibrary.registries' },
    { name: 'registries/item', navigator: 'prompts', titleKey: 'promptLibrary.registries' },
    { name: 'index', navigator: 'prompts/skills', titleKey: 'promptLibrary.skills' },
    { name: '[id]', navigator: 'prompts/skills', titleKey: 'promptLibrary.editSkill' },
    { name: '[id]/export', navigator: 'prompts/skills', titleKey: 'promptLibrary.externalAssetsExportTitle' },
    { name: '[id]/files/edit', navigator: 'prompts/skills', titleKey: 'promptLibrary.editSupportingFile' },
    { name: '[id]/files/new', navigator: 'prompts/skills', titleKey: 'promptLibrary.newSupportingFile' },
    { name: 'new', navigator: 'prompts/skills', titleKey: 'promptLibrary.newSkill' },
    { name: 'stacks', navigator: 'prompts', titleKey: 'contextPages.account.title' },
    { name: 'stacks/coding', navigator: 'prompts', titleKey: 'contextPages.account.title' },
    { name: 'stacks/profiles/index', navigator: 'prompts', titleKey: 'promptLibrary.profileStacks' },
    { name: 'stacks/profiles/[id]', navigator: 'prompts', titleKey: 'promptLibrary.profileStacks' },
    { name: 'stacks/voice', navigator: 'prompts', titleKey: 'promptLibrary.voiceStack' },
    { name: 'memory/[id]', navigator: 'prompts', titleKey: 'memoryContext.memory.title' },
    { name: 'index', navigator: 'prompts/templates', titleKey: 'promptLibrary.templates' },
    { name: '[id]', navigator: 'prompts/templates', titleKey: 'promptLibrary.editTemplate' },
    { name: 'new', navigator: 'prompts/templates', titleKey: 'promptLibrary.newTemplate' },
    { name: 'agents', titleKey: 'settingsAgents.title' },
    { name: 'index', navigator: 'agents', titleKey: 'settingsAgents.title' },
    { name: '[agentId]', navigator: 'agents', titleKey: 'settingsAgents.title' },
    { name: '[agentId]/models', navigator: 'agents', titleKey: 'settingsAgents.models' },
    { name: 'custom/index', navigator: 'agents', titleKey: 'settingsAgents.customAcp.newTitle' },
    { name: 'custom/[backendId]', navigator: 'agents', titleKey: 'settingsAgents.collection.customAgents' },
    { name: 'providers', titleKey: 'settingsProviders.title' },
    { name: 'index', navigator: 'providers', titleKey: 'settingsProviders.title' },
    { name: '[connectionId]', navigator: 'providers', titleKey: 'settingsProviders.detailTitle' },
    { name: '[connectionId]/models', navigator: 'providers', titleKey: 'settingsProviders.models.manage' },
    { name: 'new', navigator: 'providers', titleKey: 'settingsProviders.addCustom' },
    { name: 'remote-hosts', titleKey: 'settings.remoteHostsTitle' },
    { name: 'index', navigator: 'remote-hosts', titleKey: 'settings.remoteHostsTitle' },
    { name: '[hostId]', navigator: 'remote-hosts', titleKey: 'settings.remoteHostsTitle' },
    { name: 'new', navigator: 'remote-hosts', titleKey: 'settingsRemoteHostsPage.newHostTitle' },
    { name: 'access', navigator: 'remote-hosts', titleKey: 'settingsRemoteHostsPage.accessTitle' },
    { name: 'report-issue', titleKey: 'settings.reportIssue' },
    { name: 'secrets', titleKey: 'settings.secrets' },
    { name: 'server', titleKey: 'settings.servers' },
    { name: 'index', navigator: 'server', titleKey: 'settings.servers' },
    { name: 'device', navigator: 'server', titleKey: 'addFlows.thisDeviceTitle' },
    { name: 'add', navigator: 'server', titleKey: 'addFlows.addHome' },
    { name: '[homeId]', navigator: 'server', titleKey: 'settings.servers', headsItself: true },
    { name: 'groups/new', navigator: 'server', titleKey: 'addFlows.newGroup' },
    { name: 'groups/[groupId]', navigator: 'server', titleKey: 'addFlows.groupsTitle', headsItself: true },
    { name: 'session', titleKey: 'settings.sessions' },
    { name: 'session/composer', titleKey: 'settingsSession.composer.title' },
    { name: 'session/handoff', titleKey: 'settingsSession.handoff.title' },
    { name: 'session/new-session-wizard', titleKey: 'settingsSession.sessionCreation.wizardDispositionTitle' },
    { name: 'session/permissions', titleKey: 'settingsSession.permissions.title' },
    { name: 'session/provider-limits', titleKey: 'settingsSession.providerLimits.title' },
    { name: 'session/resume', titleKey: 'settingsSession.resume.title' },
    { name: 'session/runtime', titleKey: 'settingsSession.runtime.title' },
    { name: 'session/tool-rendering', titleKey: 'settingsSession.toolRendering.title' },
    { name: 'session/transcript', titleKey: 'settingsSession.transcript.title' },
    { name: 'session/transcript/advanced', titleKey: 'settingsSessionPages.transcript.advancedTitle' },
    { name: 'source-control', titleKey: 'navigation.sourceControl' },
    { name: 'sub-agent', titleKey: 'subAgentGuidance.settings.groupTitle' },
    { name: 'system-status', titleKey: 'settings.systemStatus' },
    { name: 'updates', titleKey: 'updates.title' },
    { name: 'teams', titleKey: 'teams.title' },
    { name: 'index', navigator: 'teams', titleKey: 'teams.title' },
    { name: 'new', navigator: 'teams', titleKey: 'teams.create.title' },
    { name: '[serverId]/[teamId]/index', navigator: 'teams', titleKey: 'teams.title', headsItself: true },
    { name: '[serverId]/[teamId]/members/index', navigator: 'teams', titleKey: 'teams.tabs.members' },
    { name: '[serverId]/[teamId]/members/add', navigator: 'teams', titleKey: 'teams.tabs.members' },
    { name: '[serverId]/[teamId]/members/[membershipId]', navigator: 'teams', titleKey: 'teams.tabs.members', headsItself: true },
    { name: '[serverId]/[teamId]/groups/index', navigator: 'teams', titleKey: 'teams.tabs.groups' },
    { name: '[serverId]/[teamId]/groups/new', navigator: 'teams', titleKey: 'teams.tabs.groups' },
    { name: '[serverId]/[teamId]/groups/[groupId]', navigator: 'teams', titleKey: 'teams.tabs.groups', headsItself: true },
    { name: '[serverId]/[teamId]/invitations/index', navigator: 'teams', titleKey: 'teams.tabs.invitations' },
    { name: '[serverId]/[teamId]/settings', navigator: 'teams', titleKey: 'teams.tabs.settings' },
    { name: '[serverId]/[teamId]/authentication', navigator: 'teams', titleKey: 'teams.tabs.authentication' },
    { name: '[serverId]/[teamId]/authentication/new', navigator: 'teams', titleKey: 'identityAdministration.add' },
    { name: '[serverId]/[teamId]/authentication/github-apps/[registrationId]/index', navigator: 'teams', titleKey: 'identityAdministration.githubApps' },
    { name: '[serverId]/[teamId]/authentication/github-apps/[registrationId]/edit', navigator: 'teams', titleKey: 'identityAdministration.githubAppEditTitle' },
    { name: '[serverId]/[teamId]/authentication/directory', navigator: 'teams', titleKey: 'teams.authentication.directory.title' },
    { name: '[serverId]/[teamId]/authentication/directory/[sourceId]', navigator: 'teams', titleKey: 'teams.authentication.directory.title' },
    { name: '[serverId]/[teamId]/authentication/[connectionId]', navigator: 'teams', titleKey: 'teams.tabs.authentication' },
    { name: '[serverId]/[teamId]/authentication/[connectionId]/edit', navigator: 'teams', titleKey: 'identityAdministration.editTitle' },
    // Lane 10 shared credentials. Every destination the credential surfaces
    // navigate to is registered here, so a route reached by ordinary navigation
    // carries the same header, Back title and chrome as the rest of Settings
    // instead of falling back to the raw Expo Router segment.
    { name: '[serverId]/[teamId]/credentials/index', navigator: 'teams', titleKey: 'teams.credentials.title' },
    { name: '[serverId]/[teamId]/credentials/new', navigator: 'teams', titleKey: 'teams.credentials.create.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/index', navigator: 'teams', titleKey: 'teams.credentials.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/edit', navigator: 'teams', titleKey: 'teams.credentials.edit.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/access', navigator: 'teams', titleKey: 'teams.credentials.audience.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/request-policy', navigator: 'teams', titleKey: 'teams.credentials.requestPolicy.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/activity', navigator: 'teams', titleKey: 'teams.credentials.activity.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/limits', navigator: 'teams', titleKey: 'teams.credentials.limits.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/usage', navigator: 'teams', titleKey: 'teams.credentials.usage.title' },
    { name: '[serverId]/[teamId]/credentials/[resourceId]/external-api', navigator: 'teams', titleKey: 'teams.credentials.externalApi.title' },
    { name: 'usage', titleKey: 'settings.usage' },
    { name: 'voice', titleKey: 'settings.voiceAssistant' },
    { name: 'voice/dictation', titleKey: 'settingsVoice.intents.dictation.title' },
    { name: 'voice/conversations', titleKey: 'settingsVoice.intents.conversations.title' },
    { name: 'voice/service', titleKey: 'settingsVoice.pages.conversations.serviceTitle' },
    { name: 'voice/privacy', titleKey: 'settingsVoice.intents.privacy.title' },
    { name: 'voice/advanced', titleKey: 'settingsVoice.intents.advanced.title' },
    { name: 'voice-history', titleKey: 'settingsVoice.history.title' },
] as const;

/** Every registered settings route name, with its navigator prefix (`prompts/skills/[id]/files/edit`). */
export function listSettingsRouteNames(): string[] {
    return SETTINGS_ROUTE_CHROME_DEFINITIONS.map((definition) => (
        definition.navigator ? `${definition.navigator}/${definition.name}` : definition.name
    ));
}
