// GENERATED by scripts/icons/genHugeRegistry.mjs — do not edit.
//
// Only the icons the app actually uses are imported. The free package carries 5,437 of them, so
// importing the barrel would pull the whole set into the bundle.

import Album01Icon from '@hugeicons/core-free-icons/Album01Icon';
import Alert01Icon from '@hugeicons/core-free-icons/Alert01Icon';
import AlertCircleIcon from '@hugeicons/core-free-icons/AlertCircleIcon';
import Archive01Icon from '@hugeicons/core-free-icons/Archive01Icon';
import ArrowAllDirectionIcon from '@hugeicons/core-free-icons/ArrowAllDirectionIcon';
import ArrowDown01Icon from '@hugeicons/core-free-icons/ArrowDown01Icon';
import ArrowDown02Icon from '@hugeicons/core-free-icons/ArrowDown02Icon';
import ArrowExpand01Icon from '@hugeicons/core-free-icons/ArrowExpand01Icon';
import ArrowLeft01Icon from '@hugeicons/core-free-icons/ArrowLeft01Icon';
import ArrowLeft02Icon from '@hugeicons/core-free-icons/ArrowLeft02Icon';
import ArrowLeftRightIcon from '@hugeicons/core-free-icons/ArrowLeftRightIcon';
import ArrowRight01Icon from '@hugeicons/core-free-icons/ArrowRight01Icon';
import ArrowRight02Icon from '@hugeicons/core-free-icons/ArrowRight02Icon';
import ArrowShrink01Icon from '@hugeicons/core-free-icons/ArrowShrink01Icon';
import ArrowTurnBackwardIcon from '@hugeicons/core-free-icons/ArrowTurnBackwardIcon';
import ArrowTurnForwardIcon from '@hugeicons/core-free-icons/ArrowTurnForwardIcon';
import ArrowUp01Icon from '@hugeicons/core-free-icons/ArrowUp01Icon';
import ArrowUp02Icon from '@hugeicons/core-free-icons/ArrowUp02Icon';
import ArrowUpDownIcon from '@hugeicons/core-free-icons/ArrowUpDownIcon';
import AtIcon from '@hugeicons/core-free-icons/AtIcon';
import Atom01Icon from '@hugeicons/core-free-icons/Atom01Icon';
import Attachment02Icon from '@hugeicons/core-free-icons/Attachment02Icon';
import BarChartIcon from '@hugeicons/core-free-icons/BarChartIcon';
import Book01Icon from '@hugeicons/core-free-icons/Book01Icon';
import BookBookmark01Icon from '@hugeicons/core-free-icons/BookBookmark01Icon';
import BookOpen01Icon from '@hugeicons/core-free-icons/BookOpen01Icon';
import Bookmark01Icon from '@hugeicons/core-free-icons/Bookmark01Icon';
import BookmarkPlusIcon from '@hugeicons/core-free-icons/BookmarkPlusIcon';
import Books01Icon from '@hugeicons/core-free-icons/Books01Icon';
import BotIcon from '@hugeicons/core-free-icons/BotIcon';
import BrowserIcon from '@hugeicons/core-free-icons/BrowserIcon';
import BubbleChatIcon from '@hugeicons/core-free-icons/BubbleChatIcon';
import Bug01Icon from '@hugeicons/core-free-icons/Bug01Icon';
import BulbIcon from '@hugeicons/core-free-icons/BulbIcon';
import Calendar01Icon from '@hugeicons/core-free-icons/Calendar01Icon';
import CallIcon from '@hugeicons/core-free-icons/CallIcon';
import Camera01Icon from '@hugeicons/core-free-icons/Camera01Icon';
import Cancel01Icon from '@hugeicons/core-free-icons/Cancel01Icon';
import CancelCircleIcon from '@hugeicons/core-free-icons/CancelCircleIcon';
import ChartLineData01Icon from '@hugeicons/core-free-icons/ChartLineData01Icon';
import ChartRelationshipIcon from '@hugeicons/core-free-icons/ChartRelationshipIcon';
import Chatting01Icon from '@hugeicons/core-free-icons/Chatting01Icon';
import CheckListIcon from '@hugeicons/core-free-icons/CheckListIcon';
import CheckmarkCircle01Icon from '@hugeicons/core-free-icons/CheckmarkCircle01Icon';
import CheckmarkSquare01Icon from '@hugeicons/core-free-icons/CheckmarkSquare01Icon';
import CircleArrowDown01Icon from '@hugeicons/core-free-icons/CircleArrowDown01Icon';
import CircleArrowRight01Icon from '@hugeicons/core-free-icons/CircleArrowRight01Icon';
import CircleArrowUp01Icon from '@hugeicons/core-free-icons/CircleArrowUp01Icon';
import CircleIcon from '@hugeicons/core-free-icons/CircleIcon';
import ClipboardIcon from '@hugeicons/core-free-icons/ClipboardIcon';
import Clock01Icon from '@hugeicons/core-free-icons/Clock01Icon';
import CloudCheckIcon from '@hugeicons/core-free-icons/CloudCheckIcon';
import CloudDownloadIcon from '@hugeicons/core-free-icons/CloudDownloadIcon';
import CloudIcon from '@hugeicons/core-free-icons/CloudIcon';
import CloudOffIcon from '@hugeicons/core-free-icons/CloudOffIcon';
import CloudUploadIcon from '@hugeicons/core-free-icons/CloudUploadIcon';
import Comment01Icon from '@hugeicons/core-free-icons/Comment01Icon';
import ComputerPhoneSyncIcon from '@hugeicons/core-free-icons/ComputerPhoneSyncIcon';
import ContrastIcon from '@hugeicons/core-free-icons/ContrastIcon';
import Copy01Icon from '@hugeicons/core-free-icons/Copy01Icon';
import CornerDownLeftIcon from '@hugeicons/core-free-icons/CornerDownLeftIcon';
import CornerDownRightIcon from '@hugeicons/core-free-icons/CornerDownRightIcon';
import CornerUpLeftIcon from '@hugeicons/core-free-icons/CornerUpLeftIcon';
import CornerUpRightIcon from '@hugeicons/core-free-icons/CornerUpRightIcon';
import CpuIcon from '@hugeicons/core-free-icons/CpuIcon';
import CreditCardIcon from '@hugeicons/core-free-icons/CreditCardIcon';
import CrosshairIcon from '@hugeicons/core-free-icons/CrosshairIcon';
import CubeIcon from '@hugeicons/core-free-icons/CubeIcon';
import DashboardSpeed01Icon from '@hugeicons/core-free-icons/DashboardSpeed01Icon';
import DashboardSquare01Icon from '@hugeicons/core-free-icons/DashboardSquare01Icon';
import Delete01Icon from '@hugeicons/core-free-icons/Delete01Icon';
import DiscordIcon from '@hugeicons/core-free-icons/DiscordIcon';
import Dollar01Icon from '@hugeicons/core-free-icons/Dollar01Icon';
import Download01Icon from '@hugeicons/core-free-icons/Download01Icon';
import ExternalLinkIcon from '@hugeicons/core-free-icons/ExternalLinkIcon';
import EyeIcon from '@hugeicons/core-free-icons/EyeIcon';
import File01Icon from '@hugeicons/core-free-icons/File01Icon';
import FileCodeIcon from '@hugeicons/core-free-icons/FileCodeIcon';
import FileDiffIcon from '@hugeicons/core-free-icons/FileDiffIcon';
import FileDownloadIcon from '@hugeicons/core-free-icons/FileDownloadIcon';
import FileEmpty01Icon from '@hugeicons/core-free-icons/FileEmpty01Icon';
import FileMinusIcon from '@hugeicons/core-free-icons/FileMinusIcon';
import FilePlusIcon from '@hugeicons/core-free-icons/FilePlusIcon';
import FileUploadIcon from '@hugeicons/core-free-icons/FileUploadIcon';
import Files01Icon from '@hugeicons/core-free-icons/Files01Icon';
import FilterMailIcon from '@hugeicons/core-free-icons/FilterMailIcon';
import FingerPrintIcon from '@hugeicons/core-free-icons/FingerPrintIcon';
import FireIcon from '@hugeicons/core-free-icons/FireIcon';
import FirstAidKitIcon from '@hugeicons/core-free-icons/FirstAidKitIcon';
import Flag01Icon from '@hugeicons/core-free-icons/Flag01Icon';
import FlashIcon from '@hugeicons/core-free-icons/FlashIcon';
import FlaskConicalIcon from '@hugeicons/core-free-icons/FlaskConicalIcon';
import FloppyDiskIcon from '@hugeicons/core-free-icons/FloppyDiskIcon';
import Folder02Icon from '@hugeicons/core-free-icons/Folder02Icon';
import FolderAddIcon from '@hugeicons/core-free-icons/FolderAddIcon';
import FolderOpenIcon from '@hugeicons/core-free-icons/FolderOpenIcon';
import FootprintsIcon from '@hugeicons/core-free-icons/FootprintsIcon';
import FullSignalIcon from '@hugeicons/core-free-icons/FullSignalIcon';
import GameController01Icon from '@hugeicons/core-free-icons/GameController01Icon';
import Gif01Icon from '@hugeicons/core-free-icons/Gif01Icon';
import GiftIcon from '@hugeicons/core-free-icons/GiftIcon';
import GitCommitIcon from '@hugeicons/core-free-icons/GitCommitIcon';
import GitCompareIcon from '@hugeicons/core-free-icons/GitCompareIcon';
import GitMergeIcon from '@hugeicons/core-free-icons/GitMergeIcon';
import GitPullRequestIcon from '@hugeicons/core-free-icons/GitPullRequestIcon';
import GithubIcon from '@hugeicons/core-free-icons/GithubIcon';
import GlobeIcon from '@hugeicons/core-free-icons/GlobeIcon';
import GoogleIcon from '@hugeicons/core-free-icons/GoogleIcon';
import Grid2X2Icon from '@hugeicons/core-free-icons/Grid2X2Icon';
import GripVerticalIcon from '@hugeicons/core-free-icons/GripVerticalIcon';
import HammerIcon from '@hugeicons/core-free-icons/HammerIcon';
import HandIcon from '@hugeicons/core-free-icons/HandIcon';
import HardDriveDownloadIcon from '@hugeicons/core-free-icons/HardDriveDownloadIcon';
import HardDriveIcon from '@hugeicons/core-free-icons/HardDriveIcon';
import HeadingIcon from '@hugeicons/core-free-icons/HeadingIcon';
import HeartIcon from '@hugeicons/core-free-icons/HeartIcon';
import HelpCircleIcon from '@hugeicons/core-free-icons/HelpCircleIcon';
import HierarchySquare03Icon from '@hugeicons/core-free-icons/HierarchySquare03Icon';
import HistoryIcon from '@hugeicons/core-free-icons/HistoryIcon';
import Home01Icon from '@hugeicons/core-free-icons/Home01Icon';
import HourglassIcon from '@hugeicons/core-free-icons/HourglassIcon';
import Image01Icon from '@hugeicons/core-free-icons/Image01Icon';
import InboxIcon from '@hugeicons/core-free-icons/InboxIcon';
import Infinity01Icon from '@hugeicons/core-free-icons/Infinity01Icon';
import InformationCircleIcon from '@hugeicons/core-free-icons/InformationCircleIcon';
import Key01Icon from '@hugeicons/core-free-icons/Key01Icon';
import KeyboardIcon from '@hugeicons/core-free-icons/KeyboardIcon';
import LaptopIcon from '@hugeicons/core-free-icons/LaptopIcon';
import Layers01Icon from '@hugeicons/core-free-icons/Layers01Icon';
import LayoutTwoColumnIcon from '@hugeicons/core-free-icons/LayoutTwoColumnIcon';
import LayoutTwoRowIcon from '@hugeicons/core-free-icons/LayoutTwoRowIcon';
import Leaf01Icon from '@hugeicons/core-free-icons/Leaf01Icon';
import LeftToRightListBulletIcon from '@hugeicons/core-free-icons/LeftToRightListBulletIcon';
import LeftToRightListNumberIcon from '@hugeicons/core-free-icons/LeftToRightListNumberIcon';
import LifebuoyIcon from '@hugeicons/core-free-icons/LifebuoyIcon';
import Link01Icon from '@hugeicons/core-free-icons/Link01Icon';
import Login01Icon from '@hugeicons/core-free-icons/Login01Icon';
import Logout01Icon from '@hugeicons/core-free-icons/Logout01Icon';
import MagicWand01Icon from '@hugeicons/core-free-icons/MagicWand01Icon';
import Mail01Icon from '@hugeicons/core-free-icons/Mail01Icon';
import MailOpen01Icon from '@hugeicons/core-free-icons/MailOpen01Icon';
import MailOpenIcon from '@hugeicons/core-free-icons/MailOpenIcon';
import MapPinIcon from '@hugeicons/core-free-icons/MapPinIcon';
import Menu01Icon from '@hugeicons/core-free-icons/Menu01Icon';
import Message01Icon from '@hugeicons/core-free-icons/Message01Icon';
import Mic01Icon from '@hugeicons/core-free-icons/Mic01Icon';
import MicOff01Icon from '@hugeicons/core-free-icons/MicOff01Icon';
import MinusSignCircleIcon from '@hugeicons/core-free-icons/MinusSignCircleIcon';
import MinusSignIcon from '@hugeicons/core-free-icons/MinusSignIcon';
import MinusSignSquareIcon from '@hugeicons/core-free-icons/MinusSignSquareIcon';
import Moon01Icon from '@hugeicons/core-free-icons/Moon01Icon';
import MoreHorizontalIcon from '@hugeicons/core-free-icons/MoreHorizontalIcon';
import MoreVerticalIcon from '@hugeicons/core-free-icons/MoreVerticalIcon';
import MusicNote01Icon from '@hugeicons/core-free-icons/MusicNote01Icon';
import NavigationIcon from '@hugeicons/core-free-icons/NavigationIcon';
import News01Icon from '@hugeicons/core-free-icons/News01Icon';
import NewsIcon from '@hugeicons/core-free-icons/NewsIcon';
import NextIcon from '@hugeicons/core-free-icons/NextIcon';
import NoteIcon from '@hugeicons/core-free-icons/NoteIcon';
import Notification01Icon from '@hugeicons/core-free-icons/Notification01Icon';
import NotificationOff01Icon from '@hugeicons/core-free-icons/NotificationOff01Icon';
import OctagonXIcon from '@hugeicons/core-free-icons/OctagonXIcon';
import PaintBoardIcon from '@hugeicons/core-free-icons/PaintBoardIcon';
import PaintBrush01Icon from '@hugeicons/core-free-icons/PaintBrush01Icon';
import PanelRightCloseIcon from '@hugeicons/core-free-icons/PanelRightCloseIcon';
import PanelRightOpenIcon from '@hugeicons/core-free-icons/PanelRightOpenIcon';
import PauseCircleIcon from '@hugeicons/core-free-icons/PauseCircleIcon';
import PeerToPeer01Icon from '@hugeicons/core-free-icons/PeerToPeer01Icon';
import PencilEdit01Icon from '@hugeicons/core-free-icons/PencilEdit01Icon';
import PencilIcon from '@hugeicons/core-free-icons/PencilIcon';
import PieChart01Icon from '@hugeicons/core-free-icons/PieChart01Icon';
import PinIcon from '@hugeicons/core-free-icons/PinIcon';
import PinOffIcon from '@hugeicons/core-free-icons/PinOffIcon';
import PlayCircleIcon from '@hugeicons/core-free-icons/PlayCircleIcon';
import PlayIcon from '@hugeicons/core-free-icons/PlayIcon';
import PlusSignCircleIcon from '@hugeicons/core-free-icons/PlusSignCircleIcon';
import PlusSignIcon from '@hugeicons/core-free-icons/PlusSignIcon';
import PlusSignSquareIcon from '@hugeicons/core-free-icons/PlusSignSquareIcon';
import PreviousIcon from '@hugeicons/core-free-icons/PreviousIcon';
import Pulse01Icon from '@hugeicons/core-free-icons/Pulse01Icon';
import PuzzleIcon from '@hugeicons/core-free-icons/PuzzleIcon';
import QrCode01Icon from '@hugeicons/core-free-icons/QrCode01Icon';
import QuotesIcon from '@hugeicons/core-free-icons/QuotesIcon';
import RadioButtonIcon from '@hugeicons/core-free-icons/RadioButtonIcon';
import RadioIcon from '@hugeicons/core-free-icons/RadioIcon';
import Refresh01Icon from '@hugeicons/core-free-icons/Refresh01Icon';
import Refresh04Icon from '@hugeicons/core-free-icons/Refresh04Icon';
import RepeatIcon from '@hugeicons/core-free-icons/RepeatIcon';
import Resize01Icon from '@hugeicons/core-free-icons/Resize01Icon';
import Rocket01Icon from '@hugeicons/core-free-icons/Rocket01Icon';
import Route01Icon from '@hugeicons/core-free-icons/Route01Icon';
import Scissor01Icon from '@hugeicons/core-free-icons/Scissor01Icon';
import Search01Icon from '@hugeicons/core-free-icons/Search01Icon';
import SecurityCheckIcon from '@hugeicons/core-free-icons/SecurityCheckIcon';
import Sent02Icon from '@hugeicons/core-free-icons/Sent02Icon';
import SentIcon from '@hugeicons/core-free-icons/SentIcon';
import Settings01Icon from '@hugeicons/core-free-icons/Settings01Icon';
import Share01Icon from '@hugeicons/core-free-icons/Share01Icon';
import Shield01Icon from '@hugeicons/core-free-icons/Shield01Icon';
import ShuffleIcon from '@hugeicons/core-free-icons/ShuffleIcon';
import SidebarLeft01Icon from '@hugeicons/core-free-icons/SidebarLeft01Icon';
import SidebarRight01Icon from '@hugeicons/core-free-icons/SidebarRight01Icon';
import SlidersHorizontalIcon from '@hugeicons/core-free-icons/SlidersHorizontalIcon';
import SmartPhone01Icon from '@hugeicons/core-free-icons/SmartPhone01Icon';
import SmileIcon from '@hugeicons/core-free-icons/SmileIcon';
import SourceCodeIcon from '@hugeicons/core-free-icons/SourceCodeIcon';
import SparklesIcon from '@hugeicons/core-free-icons/SparklesIcon';
import SquareIcon from '@hugeicons/core-free-icons/SquareIcon';
import SquareLock01Icon from '@hugeicons/core-free-icons/SquareLock01Icon';
import SquareUnlock01Icon from '@hugeicons/core-free-icons/SquareUnlock01Icon';
import StarIcon from '@hugeicons/core-free-icons/StarIcon';
import StopCircleIcon from '@hugeicons/core-free-icons/StopCircleIcon';
import StopIcon from '@hugeicons/core-free-icons/StopIcon';
import Sun01Icon from '@hugeicons/core-free-icons/Sun01Icon';
import Tag02Icon from '@hugeicons/core-free-icons/Tag02Icon';
import Target01Icon from '@hugeicons/core-free-icons/Target01Icon';
import TerminalIcon from '@hugeicons/core-free-icons/TerminalIcon';
import TextBoldIcon from '@hugeicons/core-free-icons/TextBoldIcon';
import TextFontIcon from '@hugeicons/core-free-icons/TextFontIcon';
import TextItalicIcon from '@hugeicons/core-free-icons/TextItalicIcon';
import TextStrikethroughIcon from '@hugeicons/core-free-icons/TextStrikethroughIcon';
import TextUnderlineIcon from '@hugeicons/core-free-icons/TextUnderlineIcon';
import Tick01Icon from '@hugeicons/core-free-icons/Tick01Icon';
import TickDouble01Icon from '@hugeicons/core-free-icons/TickDouble01Icon';
import Timer01Icon from '@hugeicons/core-free-icons/Timer01Icon';
import ToggleOnIcon from '@hugeicons/core-free-icons/ToggleOnIcon';
import TranslateIcon from '@hugeicons/core-free-icons/TranslateIcon';
import Unlink01Icon from '@hugeicons/core-free-icons/Unlink01Icon';
import Upload01Icon from '@hugeicons/core-free-icons/Upload01Icon';
import UserAdd01Icon from '@hugeicons/core-free-icons/UserAdd01Icon';
import UserCircleIcon from '@hugeicons/core-free-icons/UserCircleIcon';
import UserIcon from '@hugeicons/core-free-icons/UserIcon';
import UserMinus01Icon from '@hugeicons/core-free-icons/UserMinus01Icon';
import UserMultipleIcon from '@hugeicons/core-free-icons/UserMultipleIcon';
import Video01Icon from '@hugeicons/core-free-icons/Video01Icon';
import ViewOffSlashIcon from '@hugeicons/core-free-icons/ViewOffSlashIcon';
import VolumeHighIcon from '@hugeicons/core-free-icons/VolumeHighIcon';
import VolumeLowIcon from '@hugeicons/core-free-icons/VolumeLowIcon';
import VolumeMute01Icon from '@hugeicons/core-free-icons/VolumeMute01Icon';
import WheelchairIcon from '@hugeicons/core-free-icons/WheelchairIcon';
import WifiFullSignalIcon from '@hugeicons/core-free-icons/WifiFullSignalIcon';
import WindowsNewIcon from '@hugeicons/core-free-icons/WindowsNewIcon';
import Wrench01Icon from '@hugeicons/core-free-icons/Wrench01Icon';

import type { IconName } from './iconRegistry.generated';

/** Concepts HugeIcons can draw. A concept absent here falls back to the Phosphor registry. */
export const HUGE_ICON_REGISTRY = {
    'archive': Archive01Icon,
    'arrow-arc-left': ArrowTurnBackwardIcon,
    'arrow-arc-right': ArrowTurnForwardIcon,
    'arrow-circle-down': CircleArrowDown01Icon,
    'arrow-circle-right': CircleArrowRight01Icon,
    'arrow-circle-up': CircleArrowUp01Icon,
    'arrow-clockwise': Refresh04Icon,
    'arrow-down': ArrowDown02Icon,
    'arrow-elbow-down-left': CornerDownLeftIcon,
    'arrow-elbow-down-right': CornerDownRightIcon,
    'arrow-elbow-up-left': CornerUpLeftIcon,
    'arrow-elbow-up-right': CornerUpRightIcon,
    'arrow-left': ArrowLeft02Icon,
    'arrow-right': ArrowRight02Icon,
    'arrow-square-out': ExternalLinkIcon,
    'arrow-up': ArrowUp02Icon,
    'arrows-clockwise': Refresh01Icon,
    'arrows-down-up': ArrowUpDownIcon,
    'arrows-in': ArrowShrink01Icon,
    'arrows-left-right': ArrowLeftRightIcon,
    'arrows-out': ArrowExpand01Icon,
    'arrows-out-cardinal': ArrowAllDirectionIcon,
    'article': News01Icon,
    'at': AtIcon,
    'atom': Atom01Icon,
    'bell': Notification01Icon,
    'bell-slash': NotificationOff01Icon,
    'book': Book01Icon,
    'book-bookmark': BookBookmark01Icon,
    'book-open': BookOpen01Icon,
    'bookmark': Bookmark01Icon,
    'bookmark-plus': BookmarkPlusIcon,
    'books': Books01Icon,
    'browsers': BrowserIcon,
    'bug': Bug01Icon,
    'calendar': Calendar01Icon,
    'camera': Camera01Icon,
    'caret-down': ArrowDown01Icon,
    'caret-left': ArrowLeft01Icon,
    'caret-right': ArrowRight01Icon,
    'caret-up': ArrowUp01Icon,
    'cell-signal-high': FullSignalIcon,
    'chart-bar': BarChartIcon,
    'chart-line': ChartLineData01Icon,
    'chart-pie': PieChart01Icon,
    'chat': BubbleChatIcon,
    'chat-circle': Message01Icon,
    'chat-circle-dots': Comment01Icon,
    'chat-dots': BubbleChatIcon,
    'chats-circle': Chatting01Icon,
    'check': Tick01Icon,
    'check-circle': CheckmarkCircle01Icon,
    'check-square': CheckmarkSquare01Icon,
    'checks': TickDouble01Icon,
    'circle': CircleIcon,
    'circle-half': ContrastIcon,
    'clipboard': ClipboardIcon,
    'clock': Clock01Icon,
    'clock-counter-clockwise': HistoryIcon,
    'cloud': CloudIcon,
    'cloud-arrow-down': CloudDownloadIcon,
    'cloud-arrow-up': CloudUploadIcon,
    'cloud-check': CloudCheckIcon,
    'cloud-slash': CloudOffIcon,
    'code': SourceCodeIcon,
    'copy': Copy01Icon,
    'cpu': CpuIcon,
    'credit-card': CreditCardIcon,
    'crosshair': CrosshairIcon,
    'cube': CubeIcon,
    'currency-dollar': Dollar01Icon,
    'desktop': ComputerPhoneSyncIcon,
    'device-mobile': SmartPhone01Icon,
    'discord-logo': DiscordIcon,
    'dots-six-vertical': GripVerticalIcon,
    'dots-three': MoreHorizontalIcon,
    'dots-three-vertical': MoreVerticalIcon,
    'download': Download01Icon,
    'envelope': Mail01Icon,
    'envelope-open': MailOpen01Icon,
    'envelope-simple-open': MailOpenIcon,
    'eye': EyeIcon,
    'eye-slash': ViewOffSlashIcon,
    'file': FileEmpty01Icon,
    'file-arrow-down': FileDownloadIcon,
    'file-arrow-up': FileUploadIcon,
    'file-code': FileCodeIcon,
    'file-dashed': FileEmpty01Icon,
    'file-diff': FileDiffIcon,
    'file-minus': FileMinusIcon,
    'file-plus': FilePlusIcon,
    'file-text': File01Icon,
    'files': Files01Icon,
    'fingerprint': FingerPrintIcon,
    'first-aid-kit': FirstAidKitIcon,
    'flag': Flag01Icon,
    'flame': FireIcon,
    'flask': FlaskConicalIcon,
    'floppy-disk': FloppyDiskIcon,
    'folder': Folder02Icon,
    'folder-open': FolderOpenIcon,
    'folder-plus': FolderAddIcon,
    'funnel-simple': FilterMailIcon,
    'game-controller': GameController01Icon,
    'gear': Settings01Icon,
    'gif': Gif01Icon,
    'gift': GiftIcon,
    'git-branch': GitMergeIcon,
    'git-commit': GitCommitIcon,
    'git-diff': GitCompareIcon,
    'git-merge': GitMergeIcon,
    'git-pull-request': GitPullRequestIcon,
    'github-logo': GithubIcon,
    'globe': GlobeIcon,
    'google-logo': GoogleIcon,
    'graph': ChartRelationshipIcon,
    'grid-four': Grid2X2Icon,
    'hammer': HammerIcon,
    'hand': HandIcon,
    'hard-drive-download': HardDriveDownloadIcon,
    'hard-drives': HardDriveIcon,
    'heart': HeartIcon,
    'hourglass': HourglassIcon,
    'house': Home01Icon,
    'image': Image01Icon,
    'images': Album01Icon,
    'infinity': Infinity01Icon,
    'info': InformationCircleIcon,
    'key': Key01Icon,
    'keyboard': KeyboardIcon,
    'laptop': LaptopIcon,
    'leaf': Leaf01Icon,
    'lifebuoy': LifebuoyIcon,
    'lightbulb': BulbIcon,
    'lightning': FlashIcon,
    'link': Link01Icon,
    'link-break': Unlink01Icon,
    'list': Menu01Icon,
    'list-bullets': LeftToRightListBulletIcon,
    'list-checks': CheckListIcon,
    'list-numbers': LeftToRightListNumberIcon,
    'lock': SquareLock01Icon,
    'lock-open': SquareUnlock01Icon,
    'magic-wand': MagicWand01Icon,
    'magnifying-glass': Search01Icon,
    'mailbox': InboxIcon,
    'map-pin': MapPinIcon,
    'microphone': Mic01Icon,
    'microphone-slash': MicOff01Icon,
    'minus': MinusSignIcon,
    'minus-circle': MinusSignCircleIcon,
    'minus-square': MinusSignSquareIcon,
    'moon': Moon01Icon,
    'music-notes': MusicNote01Icon,
    'navigation-arrow': NavigationIcon,
    'newspaper': NewsIcon,
    'note': NoteIcon,
    'note-pencil': PencilEdit01Icon,
    'octagon-x': OctagonXIcon,
    'paint-brush': PaintBrush01Icon,
    'palette': PaintBoardIcon,
    'paper-plane': Sent02Icon,
    'paper-plane-tilt': SentIcon,
    'paperclip': Attachment02Icon,
    'path': Route01Icon,
    'pause-circle': PauseCircleIcon,
    'paw-print': FootprintsIcon,
    'pencil': PencilIcon,
    'pencil-simple': PencilEdit01Icon,
    'person': UserIcon,
    'phone': CallIcon,
    'play': PlayIcon,
    'play-circle': PlayCircleIcon,
    'plus': PlusSignIcon,
    'plus-circle': PlusSignCircleIcon,
    'plus-square': PlusSignSquareIcon,
    'pulse': Pulse01Icon,
    'push-pin': PinIcon,
    'push-pin-slash': PinOffIcon,
    'puzzle-piece': PuzzleIcon,
    'qr-code': QrCode01Icon,
    'question': HelpCircleIcon,
    'quotes': QuotesIcon,
    'radio': RadioIcon,
    'radio-button': RadioButtonIcon,
    'repeat': RepeatIcon,
    'resize': Resize01Icon,
    'robot': BotIcon,
    'rocket': Rocket01Icon,
    'rocket-launch': Rocket01Icon,
    'scissors': Scissor01Icon,
    'share': Share01Icon,
    'share-network': PeerToPeer01Icon,
    'shield': Shield01Icon,
    'shield-check': SecurityCheckIcon,
    'shuffle': ShuffleIcon,
    'sidebar-left-close': SidebarLeft01Icon,
    'sidebar-left-open': SidebarRight01Icon,
    'sidebar-right-close': PanelRightCloseIcon,
    'sidebar-right-open': PanelRightOpenIcon,
    'sign-in': Login01Icon,
    'sign-out': Logout01Icon,
    'skip-back': PreviousIcon,
    'skip-forward': NextIcon,
    'sliders-horizontal': SlidersHorizontalIcon,
    'smiley': SmileIcon,
    'sparkle': SparklesIcon,
    'speaker-high': VolumeHighIcon,
    'speaker-low': VolumeLowIcon,
    'speaker-slash': VolumeMute01Icon,
    'speedometer': DashboardSpeed01Icon,
    'square': SquareIcon,
    'square-split-horizontal': LayoutTwoColumnIcon,
    'square-split-vertical': LayoutTwoRowIcon,
    'squares-four': DashboardSquare01Icon,
    'stack': Layers01Icon,
    'stack-simple': Layers01Icon,
    'star': StarIcon,
    'stop': StopIcon,
    'stop-circle': StopCircleIcon,
    'sun': Sun01Icon,
    'tag': Tag02Icon,
    'target': Target01Icon,
    'terminal': TerminalIcon,
    'text-aa': TextFontIcon,
    'text-b': TextBoldIcon,
    'text-h': HeadingIcon,
    'text-italic': TextItalicIcon,
    'text-strikethrough': TextStrikethroughIcon,
    'text-underline': TextUnderlineIcon,
    'timer': Timer01Icon,
    'toggle-right': ToggleOnIcon,
    'translate': TranslateIcon,
    'trash': Delete01Icon,
    'tray': InboxIcon,
    'tree-structure': HierarchySquare03Icon,
    'upload': Upload01Icon,
    'user-circle': UserCircleIcon,
    'user-minus': UserMinus01Icon,
    'user-plus': UserAdd01Icon,
    'users': UserMultipleIcon,
    'video-camera': Video01Icon,
    'warning': Alert01Icon,
    'warning-circle': AlertCircleIcon,
    'wheelchair': WheelchairIcon,
    'wifi-high': WifiFullSignalIcon,
    'windows-logo': WindowsNewIcon,
    'wrench': Wrench01Icon,
    'x': Cancel01Icon,
    'x-circle': CancelCircleIcon,
} as const satisfies Partial<Record<IconName, unknown>>;

export type HugeIconName = keyof typeof HUGE_ICON_REGISTRY;
