// GENERATED — do not edit by hand.
// Source: scripts/icons/mapping.json  ·  Regenerate: node scripts/icons/genRegistry.mjs
//
// Only the icons this app actually uses are imported. Phosphor ships 1,512 icons; importing the
// whole catalogue would bundle ~12MB of path data, so the registry is the allowlist. Adding a new
// icon is a one-line addition to the mapping, which keeps the icon set curated on purpose.
import {
    ArchiveIcon,
    ArrowArcLeftIcon,
    ArrowCircleDownIcon,
    ArrowCircleRightIcon,
    ArrowCircleUpIcon,
    ArrowClockwiseIcon,
    ArrowDownIcon,
    ArrowElbowDownLeftIcon,
    ArrowElbowDownRightIcon,
    ArrowElbowUpLeftIcon,
    ArrowElbowUpRightIcon,
    ArrowLeftIcon,
    ArrowRightIcon,
    ArrowSquareOutIcon,
    ArrowUpIcon,
    ArrowsClockwiseIcon,
    ArrowsDownUpIcon,
    ArrowsInIcon,
    ArrowsLeftRightIcon,
    ArrowsOutCardinalIcon,
    ArrowsOutIcon,
    ArticleIcon,
    AtIcon,
    AtomIcon,
    BackspaceIcon,
    BellIcon,
    BellSlashIcon,
    BookBookmarkIcon,
    BookIcon,
    BookmarkIcon,
    BooksIcon,
    BrowsersIcon,
    BugIcon,
    CalendarIcon,
    CameraIcon,
    CaretDownIcon,
    CaretLeftIcon,
    CaretRightIcon,
    CaretUpIcon,
    CellSignalHighIcon,
    ChartBarIcon,
    ChartLineIcon,
    ChartPieIcon,
    ChatCircleDotsIcon,
    ChatCircleIcon,
    ChatDotsIcon,
    ChatIcon,
    ChatsCircleIcon,
    CheckCircleIcon,
    CheckIcon,
    CheckSquareIcon,
    ChecksIcon,
    CircleHalfIcon,
    CircleIcon,
    ClipboardIcon,
    ClockCounterClockwiseIcon,
    ClockIcon,
    CloudArrowDownIcon,
    CloudArrowUpIcon,
    CloudCheckIcon,
    CloudIcon,
    CloudSlashIcon,
    CodeIcon,
    CopyIcon,
    CpuIcon,
    CreditCardIcon,
    CrosshairIcon,
    CubeIcon,
    CurrencyDollarIcon,
    DesktopIcon,
    DeviceMobileIcon,
    DiscordLogoIcon,
    DotsSixVerticalIcon,
    DotsThreeIcon,
    DotsThreeVerticalIcon,
    DownloadIcon,
    EnvelopeIcon,
    EnvelopeOpenIcon,
    EnvelopeSimpleOpenIcon,
    EyeIcon,
    EyeSlashIcon,
    FileArrowDownIcon,
    FileArrowUpIcon,
    FileCodeIcon,
    FileDashedIcon,
    FileIcon,
    FileMinusIcon,
    FilePlusIcon,
    FileTextIcon,
    FilesIcon,
    FingerprintIcon,
    FirstAidKitIcon,
    FlagIcon,
    FlameIcon,
    FlaskIcon,
    FloppyDiskIcon,
    FolderIcon,
    FolderOpenIcon,
    FunnelSimpleIcon,
    GameControllerIcon,
    GearIcon,
    GifIcon,
    GiftIcon,
    GitBranchIcon,
    GitCommitIcon,
    GitDiffIcon,
    GitMergeIcon,
    GitPullRequestIcon,
    GithubLogoIcon,
    GlobeIcon,
    GoogleLogoIcon,
    GraphIcon,
    GridFourIcon,
    HammerIcon,
    HandIcon,
    HardDrivesIcon,
    HeartIcon,
    HourglassIcon,
    HouseIcon,
    ImageIcon,
    ImagesIcon,
    InfinityIcon,
    InfoIcon,
    KeyIcon,
    LaptopIcon,
    LeafIcon,
    LifebuoyIcon,
    LightbulbIcon,
    LightningIcon,
    LinkBreakIcon,
    LinkIcon,
    ListBulletsIcon,
    ListChecksIcon,
    ListIcon,
    ListNumbersIcon,
    LockIcon,
    LockOpenIcon,
    MagicWandIcon,
    MagnifyingGlassIcon,
    MailboxIcon,
    MapPinIcon,
    MarkdownLogoIcon,
    MicrophoneIcon,
    MicrophoneSlashIcon,
    MinusCircleIcon,
    MinusIcon,
    MinusSquareIcon,
    MoonIcon,
    MusicNotesIcon,
    NavigationArrowIcon,
    NewspaperIcon,
    NoteIcon,
    NotePencilIcon,
    PaintBrushIcon,
    PaletteIcon,
    PaperPlaneIcon,
    PaperPlaneTiltIcon,
    PaperclipIcon,
    PauseCircleIcon,
    PawPrintIcon,
    PencilIcon,
    PencilSimpleIcon,
    PersonIcon,
    PhoneIcon,
    PlayCircleIcon,
    PlayIcon,
    PlusCircleIcon,
    PlusIcon,
    PlusSquareIcon,
    ProhibitIcon,
    PulseIcon,
    PushPinIcon,
    PushPinSlashIcon,
    PuzzlePieceIcon,
    QrCodeIcon,
    QuestionIcon,
    QuotesIcon,
    RadioButtonIcon,
    RadioIcon,
    RepeatIcon,
    ResizeIcon,
    RobotIcon,
    RocketIcon,
    RocketLaunchIcon,
    ScissorsIcon,
    ShareIcon,
    ShareNetworkIcon,
    ShieldCheckIcon,
    ShieldIcon,
    ShuffleIcon,
    SidebarIcon,
    SidebarSimpleIcon,
    SignInIcon,
    SignOutIcon,
    SkipBackIcon,
    SkipForwardIcon,
    SlidersHorizontalIcon,
    SmileyIcon,
    SparkleIcon,
    SpeakerHighIcon,
    SpeakerLowIcon,
    SpeakerSlashIcon,
    SpeedometerIcon,
    SquareIcon,
    SquaresFourIcon,
    StackIcon,
    StackSimpleIcon,
    StarIcon,
    StopCircleIcon,
    StopIcon,
    SunIcon,
    TagIcon,
    TargetIcon,
    TerminalIcon,
    TextAaIcon,
    TextBIcon,
    TextHIcon,
    TextItalicIcon,
    TextStrikethroughIcon,
    TextUnderlineIcon,
    TimerIcon,
    ToggleRightIcon,
    TranslateIcon,
    TrashIcon,
    TrayIcon,
    TreeStructureIcon,
    UploadIcon,
    UserCircleIcon,
    UserMinusIcon,
    UserPlusIcon,
    UsersIcon,
    VideoCameraIcon,
    WarningCircleIcon,
    WarningIcon,
    WheelchairIcon,
    WifiHighIcon,
    WindowsLogoIcon,
    WrenchIcon,
    XCircleIcon,
    XIcon,
} from 'phosphor-react-native';
import type { Icon as PhosphorIcon } from 'phosphor-react-native';

export const ICON_REGISTRY = {
    'archive': ArchiveIcon,
    'arrow-arc-left': ArrowArcLeftIcon,
    'arrow-circle-down': ArrowCircleDownIcon,
    'arrow-circle-right': ArrowCircleRightIcon,
    'arrow-circle-up': ArrowCircleUpIcon,
    'arrow-clockwise': ArrowClockwiseIcon,
    'arrow-down': ArrowDownIcon,
    'arrow-elbow-down-left': ArrowElbowDownLeftIcon,
    'arrow-elbow-down-right': ArrowElbowDownRightIcon,
    'arrow-elbow-up-left': ArrowElbowUpLeftIcon,
    'arrow-elbow-up-right': ArrowElbowUpRightIcon,
    'arrow-left': ArrowLeftIcon,
    'arrow-right': ArrowRightIcon,
    'arrow-square-out': ArrowSquareOutIcon,
    'arrow-up': ArrowUpIcon,
    'arrows-clockwise': ArrowsClockwiseIcon,
    'arrows-down-up': ArrowsDownUpIcon,
    'arrows-in': ArrowsInIcon,
    'arrows-left-right': ArrowsLeftRightIcon,
    'arrows-out': ArrowsOutIcon,
    'arrows-out-cardinal': ArrowsOutCardinalIcon,
    'article': ArticleIcon,
    'at': AtIcon,
    'atom': AtomIcon,
    'backspace': BackspaceIcon,
    'bell': BellIcon,
    'bell-slash': BellSlashIcon,
    'book': BookIcon,
    'book-bookmark': BookBookmarkIcon,
    'bookmark': BookmarkIcon,
    'books': BooksIcon,
    'browsers': BrowsersIcon,
    'bug': BugIcon,
    'calendar': CalendarIcon,
    'camera': CameraIcon,
    'caret-down': CaretDownIcon,
    'caret-left': CaretLeftIcon,
    'caret-right': CaretRightIcon,
    'caret-up': CaretUpIcon,
    'cell-signal-high': CellSignalHighIcon,
    'chart-bar': ChartBarIcon,
    'chart-line': ChartLineIcon,
    'chart-pie': ChartPieIcon,
    'chat': ChatIcon,
    'chat-circle': ChatCircleIcon,
    'chat-circle-dots': ChatCircleDotsIcon,
    'chat-dots': ChatDotsIcon,
    'chats-circle': ChatsCircleIcon,
    'check': CheckIcon,
    'check-circle': CheckCircleIcon,
    'check-square': CheckSquareIcon,
    'checks': ChecksIcon,
    'circle': CircleIcon,
    'circle-half': CircleHalfIcon,
    'clipboard': ClipboardIcon,
    'clock': ClockIcon,
    'clock-counter-clockwise': ClockCounterClockwiseIcon,
    'cloud': CloudIcon,
    'cloud-arrow-down': CloudArrowDownIcon,
    'cloud-arrow-up': CloudArrowUpIcon,
    'cloud-check': CloudCheckIcon,
    'cloud-slash': CloudSlashIcon,
    'code': CodeIcon,
    'copy': CopyIcon,
    'cpu': CpuIcon,
    'credit-card': CreditCardIcon,
    'crosshair': CrosshairIcon,
    'cube': CubeIcon,
    'currency-dollar': CurrencyDollarIcon,
    'desktop': DesktopIcon,
    'device-mobile': DeviceMobileIcon,
    'discord-logo': DiscordLogoIcon,
    'dots-six-vertical': DotsSixVerticalIcon,
    'dots-three': DotsThreeIcon,
    'dots-three-vertical': DotsThreeVerticalIcon,
    'download': DownloadIcon,
    'envelope': EnvelopeIcon,
    'envelope-open': EnvelopeOpenIcon,
    'envelope-simple-open': EnvelopeSimpleOpenIcon,
    'eye': EyeIcon,
    'eye-slash': EyeSlashIcon,
    'file': FileIcon,
    'file-arrow-down': FileArrowDownIcon,
    'file-arrow-up': FileArrowUpIcon,
    'file-code': FileCodeIcon,
    'file-dashed': FileDashedIcon,
    'file-minus': FileMinusIcon,
    'file-plus': FilePlusIcon,
    'file-text': FileTextIcon,
    'files': FilesIcon,
    'fingerprint': FingerprintIcon,
    'first-aid-kit': FirstAidKitIcon,
    'flag': FlagIcon,
    'flame': FlameIcon,
    'flask': FlaskIcon,
    'floppy-disk': FloppyDiskIcon,
    'folder': FolderIcon,
    'folder-open': FolderOpenIcon,
    'funnel-simple': FunnelSimpleIcon,
    'game-controller': GameControllerIcon,
    'gear': GearIcon,
    'gif': GifIcon,
    'gift': GiftIcon,
    'git-branch': GitBranchIcon,
    'git-commit': GitCommitIcon,
    'git-diff': GitDiffIcon,
    'git-merge': GitMergeIcon,
    'git-pull-request': GitPullRequestIcon,
    'github-logo': GithubLogoIcon,
    'globe': GlobeIcon,
    'google-logo': GoogleLogoIcon,
    'graph': GraphIcon,
    'grid-four': GridFourIcon,
    'hammer': HammerIcon,
    'hand': HandIcon,
    'hard-drives': HardDrivesIcon,
    'heart': HeartIcon,
    'hourglass': HourglassIcon,
    'house': HouseIcon,
    'image': ImageIcon,
    'images': ImagesIcon,
    'infinity': InfinityIcon,
    'info': InfoIcon,
    'key': KeyIcon,
    'laptop': LaptopIcon,
    'leaf': LeafIcon,
    'lifebuoy': LifebuoyIcon,
    'lightbulb': LightbulbIcon,
    'lightning': LightningIcon,
    'link': LinkIcon,
    'link-break': LinkBreakIcon,
    'list': ListIcon,
    'list-bullets': ListBulletsIcon,
    'list-checks': ListChecksIcon,
    'list-numbers': ListNumbersIcon,
    'lock': LockIcon,
    'lock-open': LockOpenIcon,
    'magic-wand': MagicWandIcon,
    'magnifying-glass': MagnifyingGlassIcon,
    'mailbox': MailboxIcon,
    'map-pin': MapPinIcon,
    'markdown-logo': MarkdownLogoIcon,
    'microphone': MicrophoneIcon,
    'microphone-slash': MicrophoneSlashIcon,
    'minus': MinusIcon,
    'minus-circle': MinusCircleIcon,
    'minus-square': MinusSquareIcon,
    'moon': MoonIcon,
    'music-notes': MusicNotesIcon,
    'navigation-arrow': NavigationArrowIcon,
    'newspaper': NewspaperIcon,
    'note': NoteIcon,
    'note-pencil': NotePencilIcon,
    'octagon-x': ProhibitIcon,
    'paint-brush': PaintBrushIcon,
    'palette': PaletteIcon,
    'paper-plane': PaperPlaneIcon,
    'paper-plane-tilt': PaperPlaneTiltIcon,
    'paperclip': PaperclipIcon,
    'pause-circle': PauseCircleIcon,
    'paw-print': PawPrintIcon,
    'pencil': PencilIcon,
    'pencil-simple': PencilSimpleIcon,
    'person': PersonIcon,
    'phone': PhoneIcon,
    'play': PlayIcon,
    'play-circle': PlayCircleIcon,
    'plus': PlusIcon,
    'plus-circle': PlusCircleIcon,
    'plus-square': PlusSquareIcon,
    'pulse': PulseIcon,
    'push-pin': PushPinIcon,
    'push-pin-slash': PushPinSlashIcon,
    'puzzle-piece': PuzzlePieceIcon,
    'qr-code': QrCodeIcon,
    'question': QuestionIcon,
    'quotes': QuotesIcon,
    'radio': RadioIcon,
    'radio-button': RadioButtonIcon,
    'repeat': RepeatIcon,
    'resize': ResizeIcon,
    'robot': RobotIcon,
    'rocket': RocketIcon,
    'rocket-launch': RocketLaunchIcon,
    'scissors': ScissorsIcon,
    'share': ShareIcon,
    'share-network': ShareNetworkIcon,
    'shield': ShieldIcon,
    'shield-check': ShieldCheckIcon,
    'shuffle': ShuffleIcon,
    'sidebar-left-close': SidebarIcon,
    'sidebar-left-open': SidebarSimpleIcon,
    'sidebar-right-close': SidebarIcon,
    'sidebar-right-open': SidebarSimpleIcon,
    'sign-in': SignInIcon,
    'sign-out': SignOutIcon,
    'skip-back': SkipBackIcon,
    'skip-forward': SkipForwardIcon,
    'sliders-horizontal': SlidersHorizontalIcon,
    'smiley': SmileyIcon,
    'sparkle': SparkleIcon,
    'speaker-high': SpeakerHighIcon,
    'speaker-low': SpeakerLowIcon,
    'speaker-slash': SpeakerSlashIcon,
    'speedometer': SpeedometerIcon,
    'square': SquareIcon,
    'squares-four': SquaresFourIcon,
    'stack': StackIcon,
    'stack-simple': StackSimpleIcon,
    'star': StarIcon,
    'stop': StopIcon,
    'stop-circle': StopCircleIcon,
    'sun': SunIcon,
    'tag': TagIcon,
    'target': TargetIcon,
    'terminal': TerminalIcon,
    'text-aa': TextAaIcon,
    'text-b': TextBIcon,
    'text-h': TextHIcon,
    'text-italic': TextItalicIcon,
    'text-strikethrough': TextStrikethroughIcon,
    'text-underline': TextUnderlineIcon,
    'timer': TimerIcon,
    'toggle-right': ToggleRightIcon,
    'translate': TranslateIcon,
    'trash': TrashIcon,
    'tray': TrayIcon,
    'tree-structure': TreeStructureIcon,
    'upload': UploadIcon,
    'user-circle': UserCircleIcon,
    'user-minus': UserMinusIcon,
    'user-plus': UserPlusIcon,
    'users': UsersIcon,
    'video-camera': VideoCameraIcon,
    'warning': WarningIcon,
    'warning-circle': WarningCircleIcon,
    'wheelchair': WheelchairIcon,
    'wifi-high': WifiHighIcon,
    'windows-logo': WindowsLogoIcon,
    'wrench': WrenchIcon,
    'x': XIcon,
    'x-circle': XCircleIcon,
} as const satisfies Record<string, PhosphorIcon>;

export type IconName = keyof typeof ICON_REGISTRY;
