// IMPORTANT: this must stay JSON-serializable (data-only).
export const AGENT_DEFINITION = Object.freeze({
  id: '__pluginId__',
  core: {
    id: '__pluginId__',
    cliSubcommand: '__pluginId__',
    detectKey: '__pluginId__',
    resume: { vendorResume: 'unsupported', vendorResumeIdField: null },
    sessionStorage: { direct: false, persisted: false },
    sessionCapabilities: {
      sessionListing: 'unsupported',
      sessionFork: { conversation: 'unsupported', fromMessage: 'unsupported' },
      sessionRollback: { conversation: 'unsupported' },
    },
    handoff: { vendorStateTransfer: 'unsupported' },
    tools: { delivery: 'unsupported', support: 'unsupported' },
  },
  sessionModeDescriptor: { source: 'none', semantics: 'none', runtimeSwitch: 'none' },
  sessionModesKind: 'none',
  modelConfig: {
    supportsSelection: false,
    nonAcpApplyScope: 'spawn_only',
    defaultMode: 'default',
    allowedModes: ['default'],
  },
  authProbeConfig: {
    agentId: '__pluginId__',
    binaryNames: ['__pluginId__'],
    statusCommand: null,
    parser: 'unknown',
    backgroundChecks: 'safe',
  },
  localCli: {
    agentId: '__pluginId__',
    detectKey: '__pluginId__',
    machineLoginKey: '__pluginId__',
    supportKind: 'unsupported',
    loginLaunch: null,
  },
  agentCliRuntime: {
    id: '__pluginId__',
    title: '__pluginId__ CLI',
    binaryName: '__pluginId__',
    sourcePreferenceDefault: 'system-first',
    managedInstall: null,
    manualInstallKind: 'none',
    manualInstallRecipes: null,
    acceptsJavaScriptFileOverride: false,
  },
  providerSettings: null,
});
