import { RPC_METHODS } from './index.js';

export const DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION = 'legacy_direct_session_rpc_alias';

export type DirectSessionLegacyRpcAlias = Readonly<{
  legacyMethod: string;
  canonicalMethod: string;
  classification: typeof DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION;
}>;

export const DIRECT_SESSION_LEGACY_RPC_ALIASES = Object.freeze([
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSIONS_CANDIDATES_LIST_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSIONS_CANDIDATES_LIST,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_LINK_ENSURE_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_LINK_ENSURE,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_ATTACH_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_ATTACH,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_DETACH_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_DETACH,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_FOLLOW_POLICY_SET_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_BACKGROUND_FOLLOW_SET,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_STATUS_GET_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_STATUS_GET,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_TRANSCRIPT_PAGE_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_TRANSCRIPT_PAGE,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_TRANSCRIPT_READ_AFTER_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_TRANSCRIPT_READ_AFTER,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_TAKEOVER_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_TAKEOVER,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
  {
    legacyMethod: RPC_METHODS.DAEMON_DIRECT_SESSION_TAKEOVER_PERSIST_LEGACY,
    canonicalMethod: RPC_METHODS.DAEMON_EXTERNAL_SESSION_TAKEOVER,
    classification: DIRECT_SESSION_LEGACY_RPC_ALIAS_CLASSIFICATION,
  },
] satisfies readonly DirectSessionLegacyRpcAlias[]);

export function resolveDirectSessionLegacyRpcAlias(method: string): DirectSessionLegacyRpcAlias | null {
  return DIRECT_SESSION_LEGACY_RPC_ALIASES.find((alias) => alias.legacyMethod === method) ?? null;
}
