import {
    EXTERNAL_ACTION_RELAY_REQUEST_SOCKET_MIN_BUFFER_BYTES_V2,
    EXTERNAL_ACTION_RELAY_RESPONSE_SOCKET_MIN_BUFFER_BYTES_V2,
} from '../../actions/externalActionApi.js';
import { defineServerConfigRegistry } from '../serverConfigEntry.js';

const PER_PROCESS_IDENTITY = 'Identifies one server process; a single stored value cannot describe several replicas.';
const BUILD_POLICY_CEILING = 'Build policy is the ceiling a Home feature switch must never lift.';
const SET_BY_RUNTIME = 'Set by the Happier runtime that launches the server, not by an operator.';

const DEFAULT_METRICS_PORT_VALUE = 9090;
/** Socket.IO must carry the largest external Action relay request and response. */
const SOCKET_MIN_BUFFER_BYTES = Math.max(
    EXTERNAL_ACTION_RELAY_REQUEST_SOCKET_MIN_BUFFER_BYTES_V2,
    EXTERNAL_ACTION_RELAY_RESPONSE_SOCKET_MIN_BUFFER_BYTES_V2,
);

/**
 * Process, networking, logging, monitoring, UI serving, sockets, presence and RPC. All are
 * Home-editable except the managed-runtime marker; `apply: 'restart'` keys are read at startup and
 * take effect at the next start (an explicitly set env value always wins, plan D-14).
 */
export const SERVER_RUNTIME_SERVER_CONFIG = defineServerConfigRegistry({
    PORT: {
        type: 'int',
        default: 3005,
        bounds: { min: 1, max: 65_535 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Port the HTTP server listens on.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SERVER_HOST: {
        type: 'string',
        default: '0.0.0.0',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        aliases: ['HAPPY_SERVER_HOST'],
        description: 'Address the HTTP server binds to.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SERVER_FLAVOR: {
        type: 'enum',
        bounds: { values: ['light', 'full'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        aliases: ['HAPPY_SERVER_FLAVOR'],
        description: 'Server flavour. The entry point sets it; operators do not.',
        docs: 'self-hosting/env#flavorinternal-markers',
    },
    NODE_ENV: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Node.js environment; `production` hides development diagnostics and enforces production defaults.',
    },
    SERVER_ROLE: {
        type: 'enum',
        default: 'all',
        bounds: { values: ['all', 'api', 'worker'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'process',
        description: 'Process role in a multi-replica deployment: `all`, `api` or `worker`.',
        docs: 'self-hosting/env#core-runtime',
        readOnlyReason: 'per_process_identity',
        reason: PER_PROCESS_IDENTITY,
    },
    UV_THREADPOOL_SIZE: {
        type: 'int',
        default: 4,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'libuv worker threads; also sizes password hashing concurrency.',
    },
    HAPPIER_INSTANCE_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'process',
        aliases: ['HAPPY_INSTANCE_ID'],
        description: 'Stable id of this replica in the socket cluster. A random id is used when unset.',
        docs: 'self-hosting/env#core-runtime',
        readOnlyReason: 'per_process_identity',
        reason: PER_PROCESS_IDENTITY,
    },
    HAPPIER_SERVER_SHUTDOWN_DEADLINE_MS: {
        type: 'int',
        default: 5000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Time a graceful shutdown may take before the process exits, in milliseconds.',
    },
    HAPPY_EXIT_ON_FATAL: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Exit the process after a fatal error. `0` or `false` keeps it running.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_API_CORS_MAX_AGE_SECONDS: {
        type: 'int',
        default: 600,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        aliases: ['HAPPY_API_CORS_MAX_AGE_SECONDS'],
        description: 'How long browsers may cache CORS preflight answers, in seconds.',
    },
    HAPPIER_SERVER_IDENTITY_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Pins the server identity id. When unset, one is generated once and persisted.',
    },
    HAPPIER_MANAGED_RELAY_PURPOSE: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'process',
        description: 'Set to `personal-home` by the managed runtime that hosts a Personal Home.',
        readOnlyReason: 'before_database',
        reason: SET_BY_RUNTIME,
    },
    HAPPIER_STACK_SHARED_DB_SOURCE_STACK: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'internal',
        section: 'server',
        group: 'process',
        description: 'Source stack of a shared QA database; set by Stack for schema mismatch diagnostics.',
    },
    HAPPIER_PERSONAL_HOME_RELOCATION_OPERATION_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Relocation operation a restarting Personal Home completes. Set by the relocation runtime.',
    },
    HAPPIER_SERVER_STARTUP_RECEIPT_PATH: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'File the server writes its startup receipt to. Set by the process supervisor.',
    },
    HAPPIER_SERVER_STARTUP_RECEIPT_NONCE: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Nonce echoed in the startup receipt. Set by the process supervisor.',
    },
    HAPPIER_UPDATER_FORWARD_RECOVERY_CAPABILITY: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Declares that the updater can recover forward from an irreversible migration. Set by the updater.',
    },
    HAPPIER_RELEASE_SOURCE_SHA: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'process',
        description: 'Source commit of this build, reported by the version route.',
    },
    HAPPIER_FEATURE_POLICY_ENV: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'bootstrap',
        section: 'server',
        group: 'buildPolicy',
        aliases: ['HAPPIER_EMBEDDED_POLICY_ENV'],
        description: 'Embedded feature policy (release ring) the server applies.',
        readOnlyReason: 'invariant',
        reason: BUILD_POLICY_CEILING,
    },
    HAPPIER_BUILD_FEATURES_ALLOW: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'bootstrap',
        section: 'server',
        group: 'buildPolicy',
        description: 'Feature ids this deployment allows; when set, every other feature is denied.',
        readOnlyReason: 'invariant',
        reason: BUILD_POLICY_CEILING,
    },
    HAPPIER_BUILD_FEATURES_DENY: {
        type: 'list',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'bootstrap',
        section: 'server',
        group: 'buildPolicy',
        description: 'Feature ids this deployment denies; a deny always wins.',
        readOnlyReason: 'invariant',
        reason: BUILD_POLICY_CEILING,
    },
    HAPPIER_SERVER_LOG_LEVEL: {
        type: 'enum',
        default: 'info',
        bounds: { values: ['fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'logging',
        aliases: ['HAPPIER_LOG_LEVEL', 'LOG_LEVEL'],
        description: 'Server log level.',
    },
    DANGEROUSLY_LOG_TO_SERVER_FOR_AI_AUTO_DEBUGGING: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'logging',
        description: 'Any value turns on the consolidated client and server debug log. Development only.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_SELF_HOST_LOG_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'logging',
        description: 'Directory holding `server.log`, attached to bug-report server diagnostics.',
    },
    HAPPIER_AUTH_DECORATOR_DIAGNOSTIC_LOGS: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'logging',
        aliases: ['HAPPY_AUTH_DECORATOR_DIAGNOSTIC_LOGS'],
        description: 'Logs authentication decorator diagnostics. Only the value `1` turns it on.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_SOCKET_MESSAGE_DIAGNOSTIC_LOGS: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_MESSAGE_DIAGNOSTIC_LOGS'],
        description: 'Logs socket message diagnostics. Only the value `1` turns it on.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    METRICS_ENABLED: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        description: 'Serves Prometheus metrics on the metrics port.',
        docs: 'self-hosting/env#metrics-and-observability',
    },
    METRICS_PORT: {
        type: 'int',
        default: DEFAULT_METRICS_PORT_VALUE,
        bounds: { min: 0, max: 65_535 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        description: 'Port of the metrics server.',
        docs: 'self-hosting/env#metrics-and-observability',
    },
    SENTRY_DSN: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_DSN'],
        description: 'Sentry DSN for server error reporting.',
    },
    HAPPIER_SENTRY_USE_CENTRAL_DSN: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['SENTRY_USE_CENTRAL_DSN'],
        description: 'Reports to the central Happier Sentry project when no DSN is set.',
    },
    HAPPIER_SENTRY_CENTRAL_DSN: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['SENTRY_CENTRAL_DSN'],
        description: 'Central Sentry DSN used when central reporting is on.',
    },
    SENTRY_ENVIRONMENT: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_ENVIRONMENT'],
        description: 'Sentry environment name. When unset, derived from NODE_ENV and the flavour.',
    },
    SENTRY_RELEASE: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_RELEASE', 'HAPPIER_RELEASE'],
        description: 'Sentry release name. When unset, the build release applies.',
    },
    SENTRY_PROFILE_LIFECYCLE: {
        type: 'enum',
        default: 'manual',
        bounds: { values: ['manual', 'trace'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_PROFILE_LIFECYCLE'],
        description: 'Sentry profiling lifecycle.',
    },
    SENTRY_SEND_DEFAULT_PII: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_SEND_DEFAULT_PII'],
        description: 'Lets Sentry attach default personal data (IP addresses, headers).',
    },
    SENTRY_TRACES_SAMPLE_RATE: {
        type: 'float',
        default: 0,
        bounds: { min: 0, max: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_TRACES_SAMPLE_RATE'],
        description: 'Share of requests traced by Sentry, from 0 to 1.',
    },
    SENTRY_PROFILE_SESSION_SAMPLE_RATE: {
        type: 'float',
        default: 0,
        bounds: { min: 0, max: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_PROFILE_SESSION_SAMPLE_RATE'],
        description: 'Share of sessions profiled by Sentry, from 0 to 1.',
    },
    SENTRY_ENABLE_LOGS: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_ENABLE_LOGS'],
        description: 'Sends server logs to Sentry.',
    },
    SENTRY_LOG_LEVELS: {
        type: 'list',
        default: ['error', 'fatal'],
        bounds: { values: ['trace', 'debug', 'info', 'warn', 'error', 'fatal'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_LOG_LEVELS'],
        description: 'Log levels sent to Sentry when logs are on.',
    },
    SENTRY_MONITORS_ENABLED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'monitoring',
        aliases: ['HAPPIER_SENTRY_MONITORS_ENABLED'],
        description: 'Reports background job check-ins to Sentry cron monitors.',
    },
    HAPPIER_SERVER_UI_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'ui',
        aliases: ['HAPPIER_SERVER_LIGHT_UI_DIR'],
        description: 'Directory of the web app bundle the server serves. The web app is not served when unset.',
        docs: 'self-hosting/env#uistatic-serving',
    },
    HAPPIER_SERVER_UI_PREFIX: {
        type: 'string',
        default: '/',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'ui',
        aliases: ['HAPPIER_SERVER_LIGHT_UI_PREFIX'],
        description: 'Path the web app is mounted under.',
        docs: 'self-hosting/env#uistatic-serving',
    },
    HAPPIER_SERVER_UI_REQUIRED: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'ui',
        aliases: ['HAPPIER_SERVER_LIGHT_UI_REQUIRED'],
        description: 'Stops startup when the web app bundle is missing or incomplete.',
        docs: 'self-hosting/env#uistatic-serving',
    },
    HAPPIER_SERVER_UI_DEPLOYMENT_ID: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'ui',
        description: 'Deployment id of the served web app bundle (16-128 letters, digits, `_` or `-`).',
        docs: 'self-hosting/env#uistatic-serving',
    },
    HAPPIER_SERVER_UI_DEBUG_PATH: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'ui',
        description: 'Shows the bundle path on the missing-bundle page in production. Only the value `1` turns it on.',
        docs: 'self-hosting/env#uistatic-serving',
    },
    HAPPIER_SOCKET_ADAPTER: {
        type: 'string',
        default: 'memory',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_ADAPTER'],
        description: 'Socket.IO adapter: `memory` (also `mem`) or `redis-streams` (also `redis`, `redis_streams`).',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SOCKET_REDIS_ADAPTER: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_REDIS_ADAPTER'],
        description: 'Legacy switch for the Redis Streams adapter; prefer the socket adapter setting.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SOCKET_ADAPTER_MAXLEN: {
        type: 'int',
        default: 200_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_ADAPTER_MAXLEN'],
        description: 'Longest Redis stream the socket adapter keeps.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SOCKET_ADAPTER_READ_COUNT: {
        type: 'int',
        default: 2000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_ADAPTER_READ_COUNT'],
        description: 'Entries the socket adapter reads per Redis stream read.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_SOCKET_MAX_HTTP_BUFFER_SIZE: {
        type: 'int',
        default: SOCKET_MIN_BUFFER_BYTES,
        bounds: { min: SOCKET_MIN_BUFFER_BYTES },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_MAX_HTTP_BUFFER_SIZE'],
        description: 'Largest Socket.IO message, in bytes. A lower value than external Action relay messages need stops startup.',
    },
    HAPPIER_SOCKET_FAST_DISCONNECT_LOG_THRESHOLD_MS: {
        type: 'int',
        default: 1000,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_FAST_DISCONNECT_LOG_THRESHOLD_MS'],
        description: 'Connections shorter than this are logged as fast disconnects, in milliseconds.',
    },
    HAPPIER_SOCKET_PLANNED_RESTART_RETRY_AFTER_MS: {
        type: 'int',
        default: 10_000,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_PLANNED_RESTART_RETRY_AFTER_MS'],
        description: 'Reconnect delay suggested to clients during a planned restart, in milliseconds.',
    },
    HAPPIER_SOCKET_RECONNECT_WINDOW_MS: {
        type: 'int',
        default: 30_000,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        aliases: ['HAPPY_SOCKET_RECONNECT_WINDOW_MS'],
        description: 'A connection within this time of a disconnect counts as a reconnect in metrics, in milliseconds.',
    },
    HAPPY_SOCKET_ROOMS_ONLY: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        description: 'Fails event fan-out loudly when Socket.IO is not initialized. Only the value `1` turns it on.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_MACHINE_SOCKET_OWNER_TTL_SECONDS: {
        type: 'int',
        default: 120,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        description: 'How long a replica holds ownership of a machine socket without renewal, in seconds.',
    },
    HAPPIER_PRESENCE_STREAM_MAXLEN: {
        type: 'int',
        default: 100_000,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_STREAM_MAXLEN'],
        description: 'Longest Redis presence stream; 0 removes the cap.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_PRESENCE_WORKER_DB_WRITE_CONCURRENCY: {
        type: 'int',
        default: 1,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_WORKER_DB_WRITE_CONCURRENCY'],
        description: 'Concurrent database writes of the presence worker.',
    },
    HAPPIER_PRESENCE_WORKER_FLUSH_INTERVAL_MS: {
        type: 'int',
        default: 5000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_WORKER_FLUSH_INTERVAL_MS'],
        description: 'Time between presence worker flushes, in milliseconds.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_PRESENCE_WORKER_READ_BLOCK_MS: {
        type: 'int',
        default: 5000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_WORKER_READ_BLOCK_MS'],
        description: 'How long a presence stream read blocks, in milliseconds.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_PRESENCE_WORKER_READ_COUNT: {
        type: 'int',
        default: 200,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_WORKER_READ_COUNT'],
        description: 'Entries read per presence stream read.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_PRESENCE_WORKER_RECLAIM_IDLE_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        aliases: ['HAPPY_PRESENCE_WORKER_RECLAIM_IDLE_MS'],
        description: 'Idle time after which unacknowledged presence entries are reclaimed, in milliseconds.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_PRESENCE_SESSION_TIMEOUT_MS: {
        type: 'int',
        default: 600_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        description: 'Silence after which a session is marked inactive, in milliseconds.',
    },
    HAPPIER_PRESENCE_MACHINE_TIMEOUT_MS: {
        type: 'int',
        default: 600_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        description: 'Silence after which a machine is marked offline, in milliseconds.',
    },
    HAPPIER_PRESENCE_TIMEOUT_TICK_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        description: 'Time between presence timeout checks, in milliseconds.',
    },
    HAPPIER_PRESENCE_SHUTDOWN_FLUSH_TIMEOUT_MS: {
        type: 'float',
        default: 5000,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'presence',
        description: 'How long shutdown waits for the presence cache to flush, in milliseconds.',
    },
    HAPPIER_RPC_FORWARD_TIMEOUT_MS: {
        type: 'int',
        default: 30_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'Timeout of an RPC forwarded to a machine or session, in milliseconds.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_RPC_FORWARD_CAPABILITIES_TIMEOUT_MS: {
        type: 'int',
        default: 120_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'Timeout of a forwarded capabilities RPC, in milliseconds.',
        docs: 'self-hosting/env#advanced--debug-controls',
    },
    HAPPIER_RPC_FORWARD_MAX_TIMEOUT_MS: {
        type: 'int',
        default: 300_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'Longest timeout a forwarded RPC may request, in milliseconds.',
    },
    HAPPIER_RPC_METHOD_AVAILABILITY_GRACE_MS: {
        type: 'int',
        default: 750,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'How long an RPC waits for its session method to register, in milliseconds.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_RPC_METHOD_AVAILABILITY_POLL_MS: {
        type: 'int',
        default: 25,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'Poll interval while waiting for an RPC method to register, in milliseconds.',
        docs: 'self-hosting/env#core-runtime',
    },
    HAPPIER_RPC_CLUSTER_FETCH_TIMEOUT_MS: {
        type: 'int',
        default: 1000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'Timeout of a cross-replica RPC method lookup, in milliseconds.',
    },
    HAPPIER_STOP_SESSION_RPC_METHOD_AVAILABILITY_GRACE_MS: {
        type: 'int',
        default: 10_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'How long a stop-session RPC waits for its method to register, in milliseconds.',
    },
    HAPPIER_DIRECT_SESSIONS_RPC_METHOD_AVAILABILITY_GRACE_MS: {
        type: 'int',
        default: 15_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'rpc',
        description: 'How long a direct or external session RPC waits for its method to register, in milliseconds.',
    },
    HAPPIER_V2_SESSION_LIST_INITIAL_ATTENTION_ROW_LIMIT: {
        type: 'int',
        default: 100,
        bounds: { min: 1, max: 500 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'limits',
        description: 'Sessions needing attention loaded with the first session list page.',
    },
    HAPPIER_SESSION_ROLLBACK_ELIGIBLE_TURN_RELATION_LIMIT: {
        type: 'int',
        default: 50,
        bounds: { min: 1, max: 500 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'limits',
        description: 'Turns examined when deciding which turns can be rolled back.',
    },
    HAPPIER_ACCOUNT_SETTINGS_HISTORY_LIMIT: {
        type: 'int',
        default: 25,
        bounds: { min: 0 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'limits',
        description: 'Account settings versions kept in history; larger values are capped at 250.',
    },
    HAPPIER_MACHINES_REQUIRE_CONTENT_PUBLIC_KEY_FOR_DEK: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'live',
        editable: 'home',
        section: 'server',
        group: 'limits',
        description: 'Refuses an end-to-end machine data key without a signed content public key.',
    },
});
