import { defineServerConfigRegistry } from '../serverConfigEntry.js';

const BEFORE_DATABASE = 'Read before the database opens.';
const STORAGE_TUNING = 'Database tuning is read by the database layer that Home settings are themselves read through.';

/**
 * Database, file storage, Redis and light-flavour data locations. The database, SQLite, master
 * secret and light data directories are `bootstrap`; the rest are Home-editable at the next start.
 */
export const STORAGE_SERVER_CONFIG = defineServerConfigRegistry({
    DATABASE_URL: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        description: 'Database connection URL. Required for the full flavour; the light flavour defaults to its SQLite file.',
        docs: 'self-hosting/env#core-runtime',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_DB_PROVIDER: {
        type: 'enum',
        bounds: { values: ['postgres', 'postgresql', 'pglite', 'sqlite', 'mysql'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_PROVIDER'],
        description: 'Database engine. When unset, the flavour chooses (SQLite for light, PostgreSQL for full).',
        docs: 'self-hosting/env#core-runtime',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_DB_CONNECTION_LIMIT: {
        type: 'int',
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_CONNECTION_LIMIT'],
        description: 'Connection pool size added to the database URL. When unset, the URL or driver default applies.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_DB_READINESS_TIMEOUT_MS: {
        type: 'int',
        default: 15_000,
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'live',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        description: 'How long the readiness probe waits for the database, in milliseconds.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_MAX_RETRIES: {
        type: 'int',
        bounds: { min: 0, max: 100 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_MAX_RETRIES'],
        description: 'Retries of a transaction that hit a retryable conflict. When unset: 8.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_RETRY_BASE_DELAY_MS: {
        type: 'int',
        bounds: { min: 0, max: 60_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_RETRY_BASE_DELAY_MS'],
        description: 'First transaction retry delay, in milliseconds. When unset: 100 on SQLite, otherwise 200.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_RETRY_MAX_DELAY_MS: {
        type: 'int',
        bounds: { min: 0, max: 600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_RETRY_MAX_DELAY_MS'],
        description: 'Longest transaction retry delay, in milliseconds (at least the base delay). When unset: 1600 on SQLite, otherwise 5000.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_RETRY_JITTER_FACTOR: {
        type: 'float',
        bounds: { min: 0, max: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_RETRY_JITTER_FACTOR'],
        description: 'Random spread applied to retry delays, from 0 to 1. When unset: 0 on SQLite, otherwise 0.25.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_TIMEOUT_MS: {
        type: 'int',
        bounds: { min: 1_000, max: 600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_TIMEOUT_MS'],
        description: 'Longest a transaction may run, in milliseconds. In 0.3 development, when unset: the SQLite busy timeout (minimum 1000), otherwise 15000.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_MAX_WAIT_MS: {
        type: 'int',
        bounds: { min: 1_000, max: 600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_MAX_WAIT_MS'],
        description: 'Longest a transaction waits for a connection, in milliseconds. In 0.3 development, when unset: the SQLite busy timeout (minimum 1000), otherwise 10000.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_DB_TX_TOTAL_RETRY_BUDGET_MS: {
        type: 'int',
        bounds: { min: 1, max: 600_000 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_DB_TX_TOTAL_RETRY_BUDGET_MS'],
        description: 'Total time one transaction may spend retrying, in milliseconds. In 0.3 development, when unset on SQLite: 2 × (maxWaitMs + timeoutMs) + retryBaseDelayMs (normally 120100); otherwise 600000.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_SERVER_DB_SIZE_WARN_BYTES: {
        type: 'int',
        bounds: { min: 1 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'database',
        description: 'Logs a warning at startup when the SQLite database is larger than this many bytes. Off when unset.',
    },
    HAPPIER_SQLITE_AUTO_MIGRATE: {
        type: 'boolean',
        default: false,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_AUTO_MIGRATE'],
        description: 'Applies pending SQLite migrations at startup. Packaged light servers turn it on.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SQLITE_MIGRATIONS_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_MIGRATIONS_DIR'],
        description: 'Directory of SQLite migrations to apply. Packaged light servers set their bundled directory.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SQLITE_JOURNAL_MODE: {
        type: 'enum',
        default: 'WAL',
        bounds: { values: ['WAL', 'DELETE'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_JOURNAL_MODE'],
        description: 'SQLite journal mode. Any other value stops the server at startup.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SQLITE_SYNCHRONOUS: {
        type: 'enum',
        default: 'NORMAL',
        bounds: { values: ['OFF', 'NORMAL', 'FULL', 'EXTRA'] },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_SYNCHRONOUS'],
        description: 'SQLite synchronous pragma. Any other value stops the server at startup.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SQLITE_JOURNAL_SIZE_LIMIT_BYTES: {
        type: 'int',
        default: 64 * 1024 * 1024,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_JOURNAL_SIZE_LIMIT_BYTES'],
        description: 'Size the SQLite write-ahead log is truncated to after a checkpoint, in bytes; a negative value means no limit.',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SQLITE_WAL_CHECKPOINT_INTERVAL_MS: {
        type: 'int',
        default: 60_000,
        bounds: { min: 0, max: 2_147_483_647 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_WAL_CHECKPOINT_INTERVAL_MS'],
        description: 'Time between SQLite write-ahead-log checkpoints, in milliseconds; 0 turns them off.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_SQLITE_WAL_CHECKPOINT_BUSY_TIMEOUT_MS: {
        type: 'int',
        default: 5_000,
        bounds: { min: 0, max: 2_147_483_647 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_WAL_CHECKPOINT_BUSY_TIMEOUT_MS'],
        description: 'How long a checkpoint waits for readers and writers, in milliseconds; 0 checkpoints only when idle.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_SQLITE_INCREMENTAL_VACUUM_INTERVAL_MS: {
        type: 'int',
        default: 6 * 60 * 60 * 1000,
        bounds: { min: 0, max: 2_147_483_647 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_INCREMENTAL_VACUUM_INTERVAL_MS'],
        description: 'Time between SQLite incremental vacuums, in milliseconds; 0 turns them off.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_SQLITE_INCREMENTAL_VACUUM_PAGES: {
        type: 'int',
        default: 1_000,
        bounds: { min: 1, max: 2_147_483_647 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'database',
        aliases: ['HAPPY_SQLITE_INCREMENTAL_VACUUM_PAGES'],
        description: 'Free pages reclaimed by one SQLite incremental vacuum.',
        readOnlyReason: 'before_database',
        reason: STORAGE_TUNING,
    },
    HAPPIER_FILES_BACKEND: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        aliases: ['HAPPY_FILES_BACKEND'],
        description: 'Where uploaded files are stored: `local` (also `disk`, `fs`, `file`) or `s3` (also `minio`). When unset: local for light, S3 for full.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_HOST: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3-compatible storage host. Required with the S3 files backend.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_PORT: {
        type: 'int',
        bounds: { min: 1, max: 65_535 },
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3-compatible storage port. When unset, the client default for the scheme applies.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_USE_SSL: {
        type: 'boolean',
        default: true,
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'Connect to S3 over TLS. Only the exact value `true` turns it on once set.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_REGION: {
        type: 'string',
        default: 'us-east-1',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3 region.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_BUCKET: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3 bucket for uploaded files. Required with the S3 files backend.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_PRIVATE_BUCKET: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'Private S3 bucket for Artifact bytes in development 0.3. Must have no anonymous-access policy; never falls back to the public uploaded-files bucket.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_PUBLIC_URL: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'Public base URL of the S3 bucket. Required with the S3 files backend.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_ACCESS_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3 access key. Required with the S3 files backend.',
        docs: 'self-hosting/env#storage-backends',
    },
    S3_SECRET_KEY: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'storage',
        description: 'S3 secret key. Required with the S3 files backend.',
        docs: 'self-hosting/env#storage-backends',
    },
    REDIS_URL: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'home',
        section: 'server',
        group: 'sockets',
        description: 'Redis connection URL. Required when the Redis socket adapter or multiple replicas are used.',
        docs: 'self-hosting/env#core-runtime',
    },
    HANDY_MASTER_SECRET: {
        type: 'string',
        sensitivity: 'secret',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'security',
        description: 'Root secret for server-side sealing and signing. The light flavour generates and keeps one when unset.',
        docs: 'self-hosting/env#core-runtime',
        readOnlyReason: 'before_database',
        reason: 'Everything the server seals depends on it; it cannot change while the Home runs.',
    },
    HAPPIER_SERVER_LIGHT_DATA_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'storage',
        aliases: ['HAPPY_SERVER_LIGHT_DATA_DIR'],
        description: 'Light-flavour data directory. When unset: `~/.happy/server-light`.',
        docs: 'self-hosting/env#light-flavor-paths',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SERVER_LIGHT_DB_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'storage',
        aliases: ['HAPPY_SERVER_LIGHT_DB_DIR'],
        description: 'Light-flavour embedded database directory. When unset: `<data dir>/pglite`.',
        docs: 'self-hosting/env#light-flavor-paths',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
    HAPPIER_SERVER_LIGHT_FILES_DIR: {
        type: 'string',
        sensitivity: 'plain',
        apply: 'restart',
        editable: 'bootstrap',
        section: 'server',
        group: 'storage',
        aliases: ['HAPPY_SERVER_LIGHT_FILES_DIR'],
        description: 'Light-flavour uploaded files directory. When unset: `<data dir>/files`.',
        docs: 'self-hosting/env#light-flavor-paths',
        readOnlyReason: 'before_database',
        reason: BEFORE_DATABASE,
    },
});
