import type { AcpPermissionModeArgvSpecV1 } from '@happier-dev/plugin-sdk/acp';

export const GEMINI_PERMISSION_MODE_ARGV = Object.freeze({
  flag: '--approval-mode',
  map: {
    default: null,
    ask: null,
    prompt: null,
    normal: null,
    'read-only': null,
    read_only: null,
    readonly: null,
    read: null,
    ro: null,
    plan: 'plan',
    acceptEdits: 'auto_edit',
    'accept-edits': 'auto_edit',
    'safe-yolo': 'auto_edit',
    safeyolo: 'auto_edit',
    safe: 'auto_edit',
    'workspace-write': 'auto_edit',
    workspace: 'auto_edit',
    auto_edit: 'auto_edit',
    'auto-edit': 'auto_edit',
    yolo: 'yolo',
    bypassPermissions: 'yolo',
    'bypass-permissions': 'yolo',
    bypass: 'yolo',
    full: 'yolo',
    'full-access': 'yolo',
    dontask: 'yolo',
    'dont-ask': 'yolo',
    danger: 'yolo',
    'danger-full-access': 'yolo',
  },
} satisfies AcpPermissionModeArgvSpecV1);
