import {
  OPEN_CODE_ANTHROPIC_REQUEST_AUTH_PURPOSE_ID,
  OPEN_CODE_OPENAI_CODEX_REQUEST_AUTH_PURPOSE_ID,
} from './requestAuth/purposes.js';

export {
  OPEN_CODE_ANTHROPIC_REQUEST_AUTH_PURPOSE_ID,
  OPEN_CODE_OPENAI_CODEX_REQUEST_AUTH_PURPOSE_ID,
};

export const OPEN_CODE_OPENAI_API_KEY_PURPOSE_ID = 'openai-api-key' as const;
export const OPEN_CODE_ANTHROPIC_API_KEY_PURPOSE_ID = 'anthropic-api-key' as const;

export const OPEN_CODE_CONNECTED_ACCOUNT_PURPOSE_IDS = Object.freeze([
  OPEN_CODE_ANTHROPIC_REQUEST_AUTH_PURPOSE_ID,
  OPEN_CODE_OPENAI_CODEX_REQUEST_AUTH_PURPOSE_ID,
  OPEN_CODE_OPENAI_API_KEY_PURPOSE_ID,
  OPEN_CODE_ANTHROPIC_API_KEY_PURPOSE_ID,
] as const);

export type OpenCodeConnectedAccountPurposeId =
  typeof OPEN_CODE_CONNECTED_ACCOUNT_PURPOSE_IDS[number];
