import { SIDEBAR_DOCK_MIN_WIDTH_PX } from '../sidebarSizing';

export const DESKTOP_SIDEBAR_CHROME_ACTIONS_COMPACT_THRESHOLD_PX = SIDEBAR_DOCK_MIN_WIDTH_PX + 120;
export const DESKTOP_SIDEBAR_CHROME_HORIZONTAL_PADDING_PX = 16;
export const DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX = 8;
export const DESKTOP_SIDEBAR_CHROME_COLLAPSED_HORIZONTAL_PADDING_PX = 8;
export const DESKTOP_SIDEBAR_CHROME_COLLAPSED_VERTICAL_GAP_PX = 8;
export const DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX = 68;
export const DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX = 28;
