import { Typography } from '@/constants/Typography';
import { StyleSheet } from 'react-native-unistyles';
import {
    DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    DESKTOP_SIDEBAR_CHROME_HORIZONTAL_PADDING_PX,
    DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
    DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
} from './desktopChromeMetrics';

export const desktopSidebarChromeStyles = StyleSheet.create((theme) => ({
    header: {
        flexDirection: 'column',
        alignItems: 'stretch',
        paddingHorizontal: DESKTOP_SIDEBAR_CHROME_HORIZONTAL_PADDING_PX,
        paddingTop: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
        paddingBottom: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
        backgroundColor: theme.colors.groupped.background,
        position: 'relative',
        zIndex: 100,
        overflow: 'visible',
        gap: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    },
    windowControlsRow: {
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    windowControlsHost: {
        flexShrink: 0,
        minWidth: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
        alignItems: 'flex-start',
        justifyContent: 'center',
    },
    contentRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    },
    brandGroup: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0,
        minWidth: 0,
        flexDirection: 'row',
        alignItems: 'center',
        gap: DESKTOP_SIDEBAR_CHROME_CONTROL_GAP_PX,
    },
    updateIndicatorHost: {
        flexShrink: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    windowControlsSlot: {
        minWidth: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_WIDTH_PX,
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        position: 'relative',
        justifyContent: 'center',
    },
    windowControlsContent: {
        minHeight: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    windowDragRegion: {
        ...StyleSheet.absoluteFillObject,
        borderRadius: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX / 2,
    },
    logoContainer: {
        width: 32,
    },
    logo: {
        height: 24,
        width: 24,
    },
    titleContainerLeft: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: 0,
        minWidth: 0,
        flexDirection: 'column',
        alignItems: 'flex-start',
        justifyContent: 'center',
        overflow: 'visible',
    },
    titleText: {
        fontSize: 16,
        color: theme.colors.header.tint,
        ...Typography.default('semiBold'),
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexShrink: 1,
        minWidth: 0,
        maxWidth: '100%',
    },
    statusControlWrapper: {
        alignSelf: 'stretch',
        flexShrink: 1,
        minWidth: 0,
        maxWidth: '100%',
    },
    envBadge: {
        marginTop: -4,
        marginLeft: -4,
        paddingHorizontal: 4,
        paddingVertical: 1,
        borderRadius: 999,
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
    },
    envBadgeText: {
        fontSize: 6,
        lineHeight: 8,
        color: theme.colors.textSecondary,
        ...Typography.default('semiBold'),
    },
    rightContainer: {
        flexShrink: 0,
        alignItems: 'center',
        flexDirection: 'row',
        gap: 4,
    },
    iconButton: {
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    notificationButton: {
        position: 'relative',
    },
    badge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: theme.colors.status.error,
        borderRadius: 8,
        minWidth: 16,
        height: 16,
        paddingHorizontal: 4,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: theme.colors.button.primary.tint,
        fontSize: 10,
        ...Typography.default('semiBold'),
    },
    indicatorDot: {
        position: 'absolute',
        top: 4,
        right: 2,
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: theme.colors.text,
    },
    windowControlsButtons: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    windowControlsButtonsColumn: {
        flexDirection: 'column',
        alignItems: 'center',
        gap: 6,
    },
    windowControlsButton: {
        width: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        height: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX,
        borderRadius: DESKTOP_WINDOW_CONTROLS_SLOT_MIN_HEIGHT_PX / 2,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: theme.colors.divider,
        backgroundColor: theme.colors.surface,
    },
}));
