import { Typography } from '@/constants/Typography';
import { layout } from '@/components/ui/layout/layout';
import { StyleSheet } from 'react-native-unistyles';

export const sessionListStyles = StyleSheet.create((theme) => ({
    container: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'stretch',
        backgroundColor: theme.colors.background.canvas,
    },
    contentContainer: {
        flex: 1,
        maxWidth: layout.maxWidth,
    },
    headerSection: {
        backgroundColor: theme.colors.background.canvas,
        paddingHorizontal: 24,
        paddingTop: 14,
    },
    listHeaderSection: {
        backgroundColor: theme.colors.background.canvas,
    },
    headerText: {
        fontSize: 13,
        color: theme.colors.text.secondary,
    },
    groupHeaderSection: {
        backgroundColor: theme.colors.background.canvas,
        paddingHorizontal: 24,
        paddingTop: 10,
        paddingBottom: 5,
    },
    groupHeaderTitle: {
        fontSize: 12,
        fontWeight: '600',
        color: theme.colors.text.secondary,
        flexShrink: 1,
        ...Typography.default('semiBold'),
    },
    groupHeaderSubtitle: {
        fontSize: 11,
        color: theme.colors.text.secondary,
        marginTop: 2,
        ...Typography.default(),
    },
    groupHeaderRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
    },
    groupHeaderTitleRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 6,
        flex: 1,
        minWidth: 0,
    },
    groupHeaderFavicon: {
        width: 16,
        height: 16,
        borderRadius: 4,
    },
    groupHeaderFaviconFrame: {
        width: 16,
        minWidth: 16,
        maxWidth: 16,
        height: 16,
        minHeight: 16,
        maxHeight: 16,
        flexShrink: 0,
        borderRadius: 4,
        backgroundColor: theme.colors.background.canvas,
        overflow: 'hidden' as const,
    },
    folderHeaderSection: {
        backgroundColor: theme.colors.background.canvas,
        paddingHorizontal: 10,
        paddingTop: 0,
        paddingBottom: 0,
    },
    folderHeaderRow: {
        minHeight: 22,
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
        borderRadius: 8,
    },
    groupHeaderContent: {
        flex: 1,
        minWidth: 0,
    },
    groupHeaderInlineActions: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 2,
        flexShrink: 0,
    },
    groupHeaderTrailingActions: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        flexShrink: 0,
        marginLeft: 8,
    },
    groupHeaderActionButton: {
        width: 18,
        height: 14,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        borderRadius: 999,
        marginLeft: 4,
    },
    folderHeaderDragHandleIcon: {
        opacity: 0,
    },
    folderHeaderDragHandleIconActive: {
        opacity: 1,
    },
    groupHeaderActionIcon: {
        color: theme.colors.text.secondary,
    },
    headerRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'space-between' as const,
    },
    headerLabelRow: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 4,
        flex: 1,
        minWidth: 0,
    },
    headerChevron: {
        width: 16,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        color: theme.colors.text.secondary,
    },
    headerActionButton: {
        width: 18,
        height: 14,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        borderRadius: 999,
        marginLeft: 4,
    },
    headerActiveFilterBadge: {
        top: -2,
        right: -3,
    },
    headerControls: {
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        gap: 8,
        marginLeft: 4,
    },
    headerSearchShell: {
        position: 'relative' as const,
        height: 28,
        flexDirection: 'row' as const,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        overflow: 'visible' as const,
    },
    headerSearchShellCollapsed: {
        width: 16,
    },
    headerSearchShellExpanded: {
        borderRadius: 7,
        justifyContent: 'flex-start' as const,
        paddingLeft: 6,
        paddingRight: 8,
        gap: 5,
        zIndex: 2,
    },
    headerSearchShellBackdrop: {
        position: 'absolute' as const,
        top: -3,
        right: -3,
        bottom: -3,
        left: -3,
        borderRadius: 10,
        backgroundColor: theme.colors.background.canvas,
        shadowColor: theme.colors.background.canvas,
        shadowOpacity: 1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        boxShadow: `0 0 0 3px ${theme.colors.background.canvas}, 0 4px 12px ${theme.colors.background.canvas}`,
        zIndex: 0,
    },
    headerSearchShellBorder: {
        position: 'absolute' as const,
        top: 0,
        right: 0,
        bottom: 0,
        left: 0,
        borderRadius: 7,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        zIndex: 1,
    },
    headerSearchIcon: {
        position: 'relative' as const,
        zIndex: 2,
    },
    headerSearchInputContainer: {
        position: 'relative' as const,
        zIndex: 2,
        flex: 1,
        minWidth: 0,
    },
    headerSearchTrailingAccessory: {
        position: 'relative' as const,
        zIndex: 2,
        width: 18,
        minWidth: 18,
        height: 20,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
    },
    headerSearchInput: {
        flex: 1,
        minWidth: 0,
        height: 20,
        lineHeight: 20,
        padding: 0,
        margin: 0,
        borderWidth: 0,
        borderColor: 'transparent',
        backgroundColor: 'transparent',
        color: theme.colors.text.primary,
    },
    groupHeaderChevron: {
        width: 16,
        alignItems: 'center' as const,
        justifyContent: 'center' as const,
        color: theme.colors.text.secondary,
    },
    webHoverHiddenChevron: {
        opacity: 0,
    },
    webHoverVisibleChevron: {
        opacity: 1,
    },
    footerContainer: {
        marginTop: -4,
    },
    filteredNoResultsContainer: {
        paddingHorizontal: 24,
        paddingTop: 12,
        paddingBottom: 8,
    },
    filteredNoResultsText: {
        color: theme.colors.text.secondary,
        ...Typography.default(),
    },
    dropIndicator: {
        position: 'absolute' as const,
        left: 16,
        right: 16,
        height: 2,
        borderRadius: 1,
        backgroundColor: theme.colors.accent.blue,
        zIndex: 10,
    },
}));
