export type { ParsedScmRemoteUrl } from './projections.js';
export type { PluginScmRegistrationApi } from './projections.js';
export { SCM_COMMIT_MESSAGE_MAX_LENGTH } from './projections.js';
export { SCM_COMMIT_PATCH_MAX_COUNT } from './projections.js';
export { SCM_COMMIT_PATCH_MAX_LENGTH } from './projections.js';
export { SCM_OPERATION_ERROR_CODES } from './projections.js';
export { SCM_WORKTREE_REMOVE_AUTHORIZATION_TOKEN } from './projections.js';
export type { ScmBranchCheckoutRequest } from './projections.js';
export type { ScmBranchCheckoutResponse } from './projections.js';
export type { ScmBranchCreateRequest } from './projections.js';
export type { ScmBranchCreateResponse } from './projections.js';
export type { ScmBranchIntegrationOperation } from './projections.js';
export type { ScmBranchIntegrationRequest } from './projections.js';
export type { ScmBranchIntegrationResponse } from './projections.js';
export type { ScmBranchListEntry } from './projections.js';
export type { ScmBranchListRequest } from './projections.js';
export type { ScmBranchListResponse } from './projections.js';
export type { ScmBranchOperationControlRequest } from './projections.js';
export type { ScmBranchSourceRefNormalizationResult } from './projections.js';
export type { ScmCapabilities } from './projections.js';
export { ScmCapabilitiesSchema } from './projections.js';
export type { ScmChangeApplyRequest } from './projections.js';
export type { ScmChangeApplyResponse } from './projections.js';
export type { ScmChangeDiscardRequest } from './projections.js';
export type { ScmChangeDiscardResponse } from './projections.js';
export type { ScmCloneProtocol } from './projections.js';
export { ScmCloneProtocolSchema } from './projections.js';
export type { ScmCommitBackoutRequest } from './projections.js';
export type { ScmCommitBackoutResponse } from './projections.js';
export type { ScmCommitCreateRequest } from './projections.js';
export type { ScmCommitCreateResponse } from './projections.js';
export type { ScmDefaultBranchPushPolicy } from './projections.js';
export type { ScmDiffCommitRequest } from './projections.js';
export type { ScmDiffCommitResponse } from './projections.js';
export type { ScmDiffFileRequest } from './projections.js';
export type { ScmDiffFileResponse } from './projections.js';
export type { ScmFollowupAction } from './projections.js';
export type { ScmHostingRepositoryAuthSummary } from './projections.js';
export type { ScmHostingRepositoryDescribePublishTargetsRequest } from './projections.js';
export type { ScmHostingRepositoryDescribePublishTargetsResponse } from './projections.js';
export type { ScmHostingRepositoryPublishRequest } from './projections.js';
export type { ScmHostingRepositoryPublishResponse } from './projections.js';
export type { ScmHostingRepositoryPublishTarget } from './projections.js';
export type { ScmHostingRepositoryRemoteUrlKind } from './projections.js';
export type { ScmHostingRepositorySummary } from './projections.js';
export type { ScmHostingRepositoryVisibility } from './projections.js';
export type { ScmLogEntry } from './projections.js';
export type { ScmLogListRequest } from './projections.js';
export type { ScmLogListResponse } from './projections.js';
export type { ScmOperationErrorCode } from './projections.js';
export type { ScmOperationState } from './projections.js';
export type { ScmPullRequestAuthState } from './projections.js';
export type { ScmPullRequestCheckoutRequest } from './projections.js';
export type { ScmPullRequestCheckoutResponse } from './projections.js';
export type { ScmPullRequestChecksState } from './projections.js';
export type { ScmPullRequestGetRequest } from './projections.js';
export type { ScmPullRequestGetResponse } from './projections.js';
export type { ScmPullRequestListRequest } from './projections.js';
export type { ScmPullRequestListResponse } from './projections.js';
export type { ScmPullRequestOpenComposeRequest } from './projections.js';
export type { ScmPullRequestOpenComposeResponse } from './projections.js';
export type { ScmPullRequestOpenOrReuseRequest } from './projections.js';
export type { ScmPullRequestOpenOrReuseResponse } from './projections.js';
export type { ScmPullRequestPrepareWorktreeRequest } from './projections.js';
export type { ScmPullRequestPrepareWorktreeResponse } from './projections.js';
export type { ScmPullRequestReference } from './projections.js';
export type { ScmPullRequestRunStackedPhase } from './projections.js';
export type { ScmPullRequestRunStackedProgressEvent } from './projections.js';
export type { ScmPullRequestRunStackedRequest } from './projections.js';
export type { ScmPullRequestRunStackedResponse } from './projections.js';
export type { ScmPullRequestState } from './projections.js';
export type { ScmPullRequestStatusProjection } from './projections.js';
export type { ScmPullRequestSummary } from './projections.js';
export type { ScmRefreshPolicy } from './projections.js';
export { ScmRefreshPolicySchema } from './projections.js';
export type { ScmRemoteAddRequest } from './projections.js';
export type { ScmRemoteInfo } from './projections.js';
export type { ScmRemoteManagementResponse } from './projections.js';
export type { ScmRemoteMutationGuardResult } from './projections.js';
export type { ScmRemoteMutationKind } from './projections.js';
export type { ScmRemoteMutationPolicy } from './projections.js';
export type { ScmRemoteMutationReason } from './projections.js';
export type { ScmRemoteMutationReasonMapper } from './projections.js';
export type { ScmRemoteMutationResult } from './projections.js';
export type { ScmRemoteMutationSnapshot } from './projections.js';
export type { ScmRemoteNameNormalizationResult } from './projections.js';
export type { ScmRemotePublishRequest } from './projections.js';
export type { ScmRemotePublishResponse } from './projections.js';
export type { ScmRemoteRemoveRequest } from './projections.js';
export type { ScmRemoteRequest } from './projections.js';
export type { ScmRemoteRequestNormalizationResult } from './projections.js';
export type { ScmRemoteResponse } from './projections.js';
export type { ScmRemoteSetUrlRequest } from './projections.js';
export type { ScmRemoteUrlNormalizationResult } from './projections.js';
export type { ScmRemoteUrlScheme } from './projections.js';
export type { ScmRepoMode } from './projections.js';
export type { ScmRepositoryCloneInput } from './projections.js';
export type { ScmRepositoryCloneOutput } from './projections.js';
export type { ScmRepositoryCloneTarget } from './projections.js';
export type { ScmRepositoryCloneTargetDescription } from './projections.js';
export type { ScmRepositoryInitRequest } from './projections.js';
export type { ScmRepositoryInitResponse } from './projections.js';
export type { ScmRepositoryRemoveIndexLockRequest } from './projections.js';
export type { ScmRepositoryRemoveIndexLockResponse } from './projections.js';
export type { ScmSelectedMutationPath } from './projections.js';
export { ScmSelectedMutationPathSchema } from './projections.js';
export type { ScmStashApplyRequest } from './projections.js';
export type { ScmStashApplyResponse } from './projections.js';
export type { ScmStashDropRequest } from './projections.js';
export type { ScmStashDropResponse } from './projections.js';
export type { ScmStashEntry } from './projections.js';
export type { ScmStashListRequest } from './projections.js';
export type { ScmStashListResponse } from './projections.js';
export type { ScmStashPopRequest } from './projections.js';
export type { ScmStashPopResponse } from './projections.js';
export type { ScmStashShowRequest } from './projections.js';
export type { ScmStashShowResponse } from './projections.js';
export type { ScmStatusSnapshotRequest } from './projections.js';
export type { ScmStatusSnapshotResponse } from './projections.js';
export type { ScmWorkingEntry } from './projections.js';
export type { ScmWorkingSnapshot } from './projections.js';
export { ScmWorkingSnapshotSchema } from './projections.js';
export type { ScmWorktree } from './projections.js';
export type { ScmWorktreeCreateRequest } from './projections.js';
export type { ScmWorktreeCreateResponse } from './projections.js';
export type { ScmWorktreeEnrichmentEntry } from './projections.js';
export type { ScmWorktreePruneRequest } from './projections.js';
export type { ScmWorktreePruneResponse } from './projections.js';
export type { ScmWorktreeRemoveRequest } from './projections.js';
export type { ScmWorktreeRemoveResponse } from './projections.js';
export type { ScmWorktreesEnrichmentRequest } from './projections.js';
export type { ScmWorktreesEnrichmentResponse } from './projections.js';
export { createScmCapabilities } from './projections.js';
export { encodeCompareRef } from './projections.js';
export { evaluateScmRemoteMutationPolicy } from './projections.js';
export { evaluateScmRemoteMutationPreconditions } from './projections.js';
export { isScmPatchBoundToPath } from './projections.js';
export { normalizeScmBranchSourceRef } from './projections.js';
export { normalizeScmRemoteName } from './projections.js';
export { normalizeScmRemoteRequest } from './projections.js';
export { normalizeScmRemoteUrl } from './projections.js';
export { parseScmRemoteUrl } from './projections.js';
export { resolveScmScopedChangedPaths } from './projections.js';
export { stripTrailingSlash } from './projections.js';
