export type { ManagedDependenciesService } from './contract.js';
export type { ManagedDependencyContribution } from './contract.js';
export type { ManagedDependencyDescriptor } from './contract.js';
export { ManagedDependencyDescriptorSchema } from './contract.js';
export type { ManagedDependencyReady } from './contract.js';
export type { ManagedDependencyStatus } from './contract.js';
export type { ManagedExecutableRef } from './contract.js';
export type { ManagedServiceAttachClientAccess } from './contract.js';
export type { ManagedServiceClientAccess } from './contract.js';
export type { ManagedServiceCredentialBinding } from './contract.js';
export type { ManagedServiceEndpointHostPolicy } from './contract.js';
export type { ManagedServiceEndpointUrlFacts } from './contract.js';
export type { ManagedServiceEndpointUrlRejection } from './contract.js';
export type { ManagedServiceEndpointUrlResult } from './contract.js';
export type { ManagedServiceErrorCode } from './contract.js';
export type { ManagedServiceHandle } from './contract.js';
export type { ManagedServiceHealthCheck } from './contract.js';
export type { ManagedServiceLocalId } from './contract.js';
export { ManagedServiceLocalIdSchema } from './contract.js';
export type { ManagedServiceMaterializationInjection } from './contract.js';
export type { ManagedServiceRequest } from './contract.js';
export type { ManagedServiceResponse } from './contract.js';
export type { ManagedServiceSnapshot } from './contract.js';
export type { ManagedServiceSpec } from './contract.js';
export type { ManagedServices } from './contract.js';
export { readManagedServiceEndpointUrl } from './contract.js';
