import { StyleSheet } from 'react-native-unistyles';

import { Typography } from '@/constants/Typography';

export const simulatorStreamStyles = StyleSheet.create((theme) => ({
    root: {
        flex: 1,
        minHeight: 0,
        backgroundColor: theme.colors.surface.base,
    },
    paneRoot: {
        flex: 1,
        minHeight: 0,
        backgroundColor: theme.colors.surface.base,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
    },
    paneContent: {
        flex: 1,
        minHeight: 0,
        flexDirection: 'row',
    },
    paneMain: {
        flex: 1,
        minWidth: 0,
        minHeight: 0,
    },
    streamShell: {
        flex: 1,
        minHeight: 0,
    },
    inputOverlay: {
        ...StyleSheet.absoluteFillObject,
    },
    picker: {
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
        paddingHorizontal: 10,
        paddingVertical: 8,
        gap: 8,
    },
    pickerList: {
        flexDirection: 'row',
        alignItems: 'stretch',
        gap: 8,
    },
    pickerEmpty: {
        minHeight: 44,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    deviceOption: {
        minWidth: 128,
        maxWidth: 220,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 10,
        paddingVertical: 8,
        gap: 4,
    },
    deviceOptionSelected: {
        borderColor: theme.colors.border.strong,
        backgroundColor: theme.colors.surface.elevated,
    },
    statusRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        flexWrap: 'wrap',
    },
    statusBadge: {
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    header: {
        gap: 4,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
    },
    headerTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    titleText: {
        color: theme.colors.text.primary,
        ...Typography.default('semiBold'),
    },
    metaText: {
        color: theme.colors.text.secondary,
        ...Typography.default(),
    },
    body: {
        flex: 1,
        minHeight: 0,
    },
    bodyOverlayHost: {
        flex: 1,
        minHeight: 0,
        position: 'relative',
    },
    unavailable: {
        flex: 1,
        minHeight: 180,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 20,
        backgroundColor: theme.colors.surface.inset,
    },
    connecting: {
        flex: 1,
        minHeight: 180,
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        padding: 20,
        backgroundColor: theme.colors.surface.inset,
    },
    connectingHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    connectingSkeleton: {
        width: '60%',
        maxWidth: 240,
        height: 12,
        borderRadius: 6,
        backgroundColor: theme.colors.surface.pressedOverlay,
    },
    toolbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-start',
        flexWrap: 'wrap',
        gap: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
    },
    toolbarGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
    },
    toolbarQualityGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    toolbarOverflowPanel: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.elevated,
        paddingHorizontal: 10,
        paddingVertical: 8,
    },
    readonlyBadge: {
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    controlState: {
        minHeight: 32,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
    controlStateDisabled: {
        backgroundColor: theme.colors.surface.base,
    },
    badgeText: {
        color: theme.colors.text.secondary,
        ...Typography.default('semiBold'),
    },
    badgeTextDisabled: {
        color: theme.colors.text.disabled,
    },
    inputLayer: {
        flex: 1,
        minHeight: 0,
        backgroundColor: theme.colors.effect.surfaceHighlight,
    },
    sidebandPanel: {
        width: 260,
        maxWidth: 320,
        minHeight: 0,
        borderLeftWidth: 1,
        borderLeftColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.base,
        padding: 10,
        gap: 8,
    },
    sidebandDrawer: {
        gap: 8,
        minHeight: 0,
    },
    sidebandSection: {
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.inset,
        paddingHorizontal: 10,
        paddingVertical: 8,
        gap: 6,
    },
    sidebandHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 8,
    },
    sidebandText: {
        color: theme.colors.text.secondary,
        ...Typography.default(),
    },
    sidebandStructuredRows: {
        gap: 4,
    },
    sidebandStructuredRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
    },
    sidebandStructuredKey: {
        minWidth: 72,
        color: theme.colors.text.secondary,
        ...Typography.mono(),
    },
    sidebandStructuredValue: {
        flex: 1,
        minWidth: 0,
        color: theme.colors.text.primary,
        ...Typography.mono(),
    },
    diagnosticRow: {
        borderWidth: 1,
        borderColor: theme.colors.border.default,
        backgroundColor: theme.colors.surface.elevated,
        paddingHorizontal: 10,
        paddingVertical: 6,
    },
}));
