import { SPAWN_SESSION_ERROR_CODES } from '@happier-dev/protocol/spawnSession';

const DEFINITE_SPAWN_PRE_ADMISSION_ERROR_CODES = new Set<string>([
  SPAWN_SESSION_ERROR_CODES.INVALID_REQUEST,
  SPAWN_SESSION_ERROR_CODES.INVALID_ENVIRONMENT_VARIABLES,
  SPAWN_SESSION_ERROR_CODES.AUTH_ENV_UNEXPANDED,
  SPAWN_SESSION_ERROR_CODES.RESUME_NOT_SUPPORTED,
  SPAWN_SESSION_ERROR_CODES.RESUME_MISSING_ENCRYPTION_KEY,
  SPAWN_SESSION_ERROR_CODES.DIRECTORY_CREATE_FAILED,
  SPAWN_SESSION_ERROR_CODES.SESSION_DIRECTORY_MISSING,
  SPAWN_SESSION_ERROR_CODES.SPAWN_VALIDATION_FAILED,
  SPAWN_SESSION_ERROR_CODES.AGENT_CLI_MISSING,
  SPAWN_SESSION_ERROR_CODES.AGENT_SIGNED_OUT,
]);

/** Only a definitive rejection proves launch never admitted the runner. */
export function isDefiniteSpawnPreAdmissionRejection(code: unknown): boolean {
  return typeof code === 'string'
    && DEFINITE_SPAWN_PRE_ADMISSION_ERROR_CODES.has(code);
}
