// Generates the HugeIcons registry from the verified concept mapping.
// Re-run after editing mapping.hugeicons.json; never hand-edit the generated file.
//
//   node scripts/icons/genHugeRegistry.mjs scripts/icons/mapping.hugeicons.json <out.ts>
//
// HugeIcons ships icon DATA (an array of svg element tuples), not components: one `HugeiconsIcon`
// renders any of them. So this registry maps a concept to a data object, where the Phosphor one maps
// a concept to a component. `Icon` owns that difference.
import { readFileSync, writeFileSync } from 'node:fs';

const [, , mappingPath, outPath] = process.argv;
if (!mappingPath || !outPath) {
    console.error('usage: genHugeRegistry.mjs <mapping.json> <out.ts>');
    process.exit(1);
}

const mapping = JSON.parse(readFileSync(mappingPath, 'utf8'));
const entries = Object.entries(mapping).sort(([a], [b]) => (a < b ? -1 : 1));
const identifiers = [...new Set(entries.map(([, v]) => v))].sort();

const lines = [
    '// GENERATED by scripts/icons/genHugeRegistry.mjs — do not edit.',
    '//',
    '// Only the icons the app actually uses are imported. The free package carries 5,437 of them, so',
    '// importing the barrel would pull the whole set into the bundle.',
    '',
    ...identifiers.map((id) => `import { ${id} } from '@hugeicons/core-free-icons';`),
    '',
    "import type { IconName } from './iconRegistry.generated';",
    '',
    '/** Concepts HugeIcons can draw. A concept absent here falls back to the Phosphor registry. */',
    'export const HUGE_ICON_REGISTRY = {',
    ...entries.map(([concept, id]) => `    '${concept}': ${id},`),
    '} as const satisfies Partial<Record<IconName, unknown>>;',
    '',
    'export type HugeIconName = keyof typeof HUGE_ICON_REGISTRY;',
    '',
];

writeFileSync(outPath, lines.join('\n'));
console.log(`${entries.length} concepts -> ${identifiers.length} distinct HugeIcons`);
