import { readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { assertCoherentPublicToolchainCompatibilityV1 } from '../../protocol/dist/plugins/publicToolchainCompatibilityV1.js';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const DEFAULT_REPO_ROOT = resolve(dirname(SCRIPT_PATH), '../../..');
const DEFAULT_OUTPUT_PATH = 'packages/plugin-sdk/src/ui/build/publicToolchainCompatibility.generated.ts';
const GENERATED_CONSUMER_PACKAGE_ROOTS = Object.freeze([
  'packages/plugin-sdk/examples',
  'packages/plugin-ui/fixtures/external-authoring',
  'packages/tests/fixtures/plugin-platform/composer-external-dogfood',
  'packages/tests/fixtures/plugin-platform/packed-targeted-contribution-projection',
]);
const GENERATED_CONSUMER_SOURCE_ROOTS = Object.freeze([
  'packages/plugin-sdk/examples',
  'packages/plugin-ui/fixtures/external-authoring/src',
  'packages/tests/fixtures/plugin-platform/composer-external-dogfood',
]);
const GENERATED_CONSUMER_SOURCE_PATHS = Object.freeze([
  'apps/cli/src/plugins/scaffold/scaffold.ts',
  'packages/tests/scripts/plugin-platform/run-packed-composer-external-dogfood.mjs',
  'packages/tests/pluginSdkConsumers/run-probes.mjs',
]);
const GENERATED_DOCUMENTATION_OUTPUTS = Object.freeze([
  Object.freeze({
    endMarker: '{/* public-toolchain-compatibility:versioning-facts:end */}',
    path: 'apps/docs/content/docs/plugins/packaging/versioning-compat.mdx',
    startMarker: '{/* public-toolchain-compatibility:versioning-facts:start */}',
  }),
  Object.freeze({
    endMarker: '{/* public-toolchain-compatibility:manifest-example:end */}',
    path: 'apps/docs/content/docs/plugins/manifest/index.mdx',
    startMarker: '{/* public-toolchain-compatibility:manifest-example:start */}',
  }),
]);
const AUTHORING_SOURCE_FILE_PATTERN = /\.(?:[cm]?[jt]sx?)$/u;
const MANAGED_AUTHORING_IMPORTS = Object.freeze([
  Object.freeze({ group: 'dependencies', packageName: '@happier-dev/plugin-sdk' }),
  Object.freeze({ group: 'dependencies', packageName: '@happier-dev/plugin-ui' }),
  Object.freeze({ group: 'dependencies', packageName: 'react' }),
  Object.freeze({ group: 'dependencies', packageName: 'react-dom' }),
  Object.freeze({ group: 'dependencies', packageName: 'react-native' }),
  Object.freeze({ group: 'dependencies', packageName: 'react-native-web' }),
  Object.freeze({ group: 'devDependencies', packageName: '@callstack/repack' }),
  Object.freeze({ group: 'devDependencies', packageName: '@react-native-community/cli' }),
  Object.freeze({ group: 'devDependencies', packageName: '@rspack/core' }),
  Object.freeze({ group: 'devDependencies', packageName: '@vitejs/plugin-react' }),
  Object.freeze({ group: 'devDependencies', packageName: 'vite' }),
]);
const GENERATED_MODULE_PREFIX = [
  '// This file is generated by scripts/generatePublicToolchainCompatibility.mjs. Do not edit by hand.',
  "import type { PublicToolchainCompatibilityV1 } from './toolchainCompatibility.js';",
  '',
  'export const PUBLIC_TOOLCHAIN_COMPATIBILITY_V1: PublicToolchainCompatibilityV1 = Object.freeze(',
  '',
].join('\n');
const GENERATED_MODULE_SUFFIX = ',\n);\n';

function asRecord(value, label) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }
  return value;
}

function requiredString(value, label) {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`${label} is required.`);
  }
  return value.trim();
}

async function readJson(path, label) {
  let source;
  try {
    source = await readFile(path, 'utf8');
  } catch (cause) {
    throw new Error(`${label} is unavailable at ${path}: ${cause instanceof Error ? cause.message : String(cause)}`);
  }
  try {
    return asRecord(JSON.parse(source), label);
  } catch (cause) {
    throw new Error(`${label} is not valid JSON: ${cause instanceof Error ? cause.message : String(cause)}`);
  }
}

async function readSource(path, label) {
  try {
    return await readFile(path, 'utf8');
  } catch (cause) {
    throw new Error(`${label} is unavailable at ${path}: ${cause instanceof Error ? cause.message : String(cause)}`);
  }
}

function readDependency(manifest, packageName, label) {
  const dependencyGroups = ['dependencies', 'devDependencies', 'peerDependencies'];
  for (const group of dependencyGroups) {
    const dependencies = manifest[group];
    if (!dependencies || typeof dependencies !== 'object' || Array.isArray(dependencies)) continue;
    const value = dependencies[packageName];
    if (typeof value === 'string' && value.trim() !== '') return value.trim();
  }
  throw new Error(`${label} must declare ${packageName}.`);
}

function readLockEntries(lockSource) {
  const entries = [];
  const lines = lockSource.split(/\r?\n/u);
  for (let index = 0; index < lines.length; index += 1) {
    const header = lines[index];
    if (!header || /^\s/u.test(header) || !header.endsWith(':')) continue;
    let version = null;
    for (let nested = index + 1; nested < lines.length; nested += 1) {
      const line = lines[nested];
      if (line && !/^\s/u.test(line)) break;
      const match = line?.match(/^  version "([^"]+)"$/u);
      if (match) {
        version = match[1];
        break;
      }
    }
    if (version) entries.push(Object.freeze({ header: header.slice(0, -1), version }));
  }
  return entries;
}

function readResolvedVersion(lockEntries, packageName, dependencySpec, label) {
  const needle = `${packageName}@${dependencySpec}`;
  const entry = lockEntries.find((candidate) => candidate.header.includes(needle));
  if (!entry) {
    throw new Error(`${label} has no Yarn lock resolution for ${needle}.`);
  }
  return entry.version;
}

function expectSame(left, right, label) {
  if (left !== right) {
    throw new Error(`${label} disagree (${left} versus ${right}).`);
  }
}

async function readProtocolPublicToolchainFacts(repoRoot) {
  const modulePath = resolve(repoRoot, 'packages/protocol/dist/plugins/publicToolchainFactsV1.js');
  let imported;
  try {
    imported = await import(pathToFileURL(modulePath).href);
  } catch (cause) {
    throw new Error(
      `Built Protocol public toolchain facts are unavailable at ${modulePath}: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  }
  const facts = asRecord(imported.PUBLIC_TOOLCHAIN_PROTOCOL_FACTS_V1, 'Protocol public toolchain facts');
  const ui = asRecord(facts.ui, 'Protocol public toolchain UI facts');
  const bundlers = asRecord(facts.bundlers, 'Protocol public toolchain bundler facts');
  const vite = asRecord(bundlers.vite, 'Protocol Vite bundler facts');
  const repack = asRecord(bundlers.repack, 'Protocol Re.Pack bundler facts');
  const runtimeApiVersion = Number(facts.runtimeApiVersion);
  const artifactGrammarVersion = Number(ui.artifactGrammarVersion);
  if (!Number.isInteger(runtimeApiVersion) || runtimeApiVersion < 1) {
    throw new Error('Protocol runtimeApiVersion must be a positive integer.');
  }
  if (!Number.isInteger(artifactGrammarVersion) || artifactGrammarVersion < 1) {
    throw new Error('Protocol artifactGrammarVersion must be a positive integer.');
  }
  return Object.freeze({
    runtimeApiVersion,
    ui: Object.freeze({
      artifactGrammarVersion,
      hostApiVersion: requiredString(ui.hostApiVersion, 'Protocol hostApiVersion'),
    }),
    bundlers: Object.freeze({
      vite: Object.freeze({
        packageName: requiredString(vite.packageName, 'Protocol Vite packageName'),
        executable: requiredString(vite.executable, 'Protocol Vite executable'),
      }),
      repack: Object.freeze({
        packageName: requiredString(repack.packageName, 'Protocol Re.Pack packageName'),
        executable: requiredString(repack.executable, 'Protocol Re.Pack executable'),
      }),
    }),
  });
}

function authoringDependency(packageName, dependencySpec, resolvedVersion) {
  return Object.freeze({ packageName, dependencySpec, resolvedVersion });
}

function publicAuthoringDependencyVersions(packet) {
  return Object.freeze({
    '@callstack/repack': packet.framework.repack,
    '@happier-dev/plugin-sdk': packet.pluginSdk.version,
    '@happier-dev/plugin-ui': packet.pluginUi.version,
    '@react-native-community/cli': packet.authoringDependencies.reactNativeCommunityCli.dependencySpec,
    '@rspack/core': packet.authoringDependencies.rspack.dependencySpec,
    '@swc/helpers': packet.authoringDependencies.swcHelpers.dependencySpec,
    '@types/node': packet.authoringDependencies.nodeTypes.dependencySpec,
    '@types/react': packet.authoringDependencies.reactTypes.dependencySpec,
    typescript: packet.authoringDependencies.typescript.dependencySpec,
    '@typescript/native': packet.authoringDependencies.typescriptNative.dependencySpec,
    '@vitejs/plugin-react': packet.authoringDependencies.viteReactPlugin.dependencySpec,
    react: packet.framework.react,
    'react-dom': packet.authoringDependencies.reactDom.dependencySpec,
    'react-native': packet.framework.reactNative,
    'react-native-web': packet.framework.reactNativeWeb,
    vite: packet.framework.vite,
  });
}

function publicAuthoringDependencyVersion(packet, packageName) {
  const version = publicAuthoringDependencyVersions(packet)[packageName];
  if (!version) throw new Error(`No public toolchain dependency version exists for ${packageName}.`);
  return version;
}

function sourceImportSpecifiers(source) {
  return [...source.matchAll(/(?:from\s*|import\s*(?:\(\s*)?|require\s*\(\s*)["']([^"']+)["']/gu)]
    .map((match) => match[1]);
}

function managedAuthoringDependenciesForSources(sourcePaths) {
  const source = sourcePaths.map(({ source: current }) => current).join('\n');
  const imports = sourceImportSpecifiers(source);
  const managedImports = MANAGED_AUTHORING_IMPORTS.filter(({ packageName }) => imports.some((specifier) => (
    specifier === packageName || specifier.startsWith(`${packageName}/`)
  )));
  return sourcePaths.some(({ path }) => basename(path) === 'pluginUiBuild.ts')
    ? [...managedImports, Object.freeze({ group: 'devDependencies', packageName: 'typescript' })]
    : managedImports;
}

function dependencyGroupFor(manifest, packageName, fallbackGroup) {
  for (const dependencyGroup of ['dependencies', 'devDependencies', 'peerDependencies']) {
    const dependencies = manifest[dependencyGroup];
    if (dependencies && typeof dependencies === 'object' && !Array.isArray(dependencies)
      && Object.hasOwn(dependencies, packageName)) {
      return dependencyGroup;
    }
  }
  return fallbackGroup;
}

function renderGeneratedConsumerPackageJson(manifest, packet, packagePath, sourcePaths) {
  const versions = publicAuthoringDependencyVersions(packet);
  const generated = { ...manifest };
  for (const dependencyGroup of ['dependencies', 'devDependencies', 'peerDependencies']) {
    const dependencies = manifest[dependencyGroup];
    if (dependencies === undefined) continue;
    const dependencyRecord = asRecord(dependencies, `${packagePath} ${dependencyGroup}`);
    const nextDependencies = { ...dependencyRecord };
    for (const [packageName, version] of Object.entries(versions)) {
      if (!Object.hasOwn(dependencyRecord, packageName)) continue;
      requiredString(
        dependencyRecord[packageName],
        `${packagePath} ${dependencyGroup}.${packageName}`,
      );
      nextDependencies[packageName] = version;
    }
    generated[dependencyGroup] = nextDependencies;
  }
  for (const { group, packageName } of managedAuthoringDependenciesForSources(sourcePaths)) {
    const dependencyGroup = dependencyGroupFor(manifest, packageName, group);
    const dependencies = generated[dependencyGroup] ?? {};
    const dependencyRecord = asRecord(dependencies, `${packagePath} ${dependencyGroup}`);
    generated[dependencyGroup] = {
      ...dependencyRecord,
      [packageName]: publicAuthoringDependencyVersion(packet, packageName),
    };
  }
  return `${JSON.stringify(generated, null, 2)}\n`;
}

async function collectConsumerPackagePaths(root) {
  let entries;
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (cause) {
    if (cause?.code === 'ENOENT') return [];
    throw cause;
  }
  const nested = await Promise.all(entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => collectConsumerPackagePaths(resolve(root, entry.name))));
  return [
    ...entries
      .filter((entry) => entry.isFile() && entry.name === 'package.json')
      .map((entry) => resolve(root, entry.name)),
    ...nested.flat(),
  ];
}

async function collectConsumerSourcePaths(root) {
  let entries;
  try {
    entries = await readdir(root, { withFileTypes: true });
  } catch (cause) {
    if (cause?.code === 'ENOENT') return [];
    throw cause;
  }
  const nested = await Promise.all(entries
    .filter((entry) => entry.isDirectory() && entry.name !== 'dist' && entry.name !== 'node_modules')
    .map((entry) => collectConsumerSourcePaths(resolve(root, entry.name))));
  const sources = await Promise.all(entries
    .filter((entry) => entry.isFile() && AUTHORING_SOURCE_FILE_PATTERN.test(entry.name))
    .map(async (entry) => {
      const path = resolve(root, entry.name);
      return Object.freeze({ path, source: await readSource(path, 'public toolchain consumer source') });
    }));
  return [...sources, ...nested.flat()].sort((left, right) => left.path.localeCompare(right.path));
}

async function consumerPackageSourcePaths(packagePath) {
  return collectConsumerSourcePaths(dirname(packagePath));
}

async function deriveGeneratedConsumerPackageOutputs(repoRoot, packet) {
  const packagePaths = (await Promise.all(GENERATED_CONSUMER_PACKAGE_ROOTS.map((relativeRoot) => (
    collectConsumerPackagePaths(resolve(repoRoot, relativeRoot))
  )))).flat().sort();
  return Promise.all(packagePaths.map(async (packagePath) => {
    const [manifest, sourcePaths] = await Promise.all([
      readJson(packagePath, 'generated consumer package manifest'),
      consumerPackageSourcePaths(packagePath),
    ]);
    return Object.freeze({
      output: renderGeneratedConsumerPackageJson(manifest, packet, packagePath, sourcePaths),
      packagePath,
    });
  }));
}

async function checkGeneratedConsumerPackageOutputs(repoRoot, packet) {
  const outputs = await deriveGeneratedConsumerPackageOutputs(repoRoot, packet);
  await Promise.all(outputs.map(async ({ output, packagePath }) => {
    const current = await readSource(packagePath, 'generated consumer package manifest');
    if (current !== output) {
      throw new Error(`Public toolchain consumer package output is stale: ${packagePath}`);
    }
  }));
}

async function writeGeneratedConsumerPackageOutputs(repoRoot, packet) {
  const outputs = await deriveGeneratedConsumerPackageOutputs(repoRoot, packet);
  await Promise.all(outputs.map(({ output, packagePath }) => writeFile(packagePath, output, 'utf8')));
}

function copiedPublicToolchainSourceFact(source) {
  const fields = [
    'apiVersion',
    'artifactGrammarVersion',
    'happier',
    'hostUiApiVersion',
    'reactNativeVersion',
    'reactNativeWebVersion',
    'reactVersion',
    'repackVersion',
    'viteVersion',
  ];
  return fields.find((field) => (
    new RegExp(`(?:\\b${field}\\b|[\"']${field}[\"'])\\s*(?::|=)\\s*(?:[\"'][^\"']*[\"']|\\d+)`, 'u').test(source)
  )) ?? null;
}

async function publicToolchainConsumerSources(repoRoot) {
  const rootedSources = await Promise.all(GENERATED_CONSUMER_SOURCE_ROOTS.map((relativeRoot) => (
    collectConsumerSourcePaths(resolve(repoRoot, relativeRoot))
  )));
  const explicitSources = await Promise.all(GENERATED_CONSUMER_SOURCE_PATHS.map(async (relativePath) => {
    const path = resolve(repoRoot, relativePath);
    return Object.freeze({ path, source: await readSource(path, 'public toolchain consumer source') });
  }));
  return [...rootedSources.flat(), ...explicitSources].sort((left, right) => left.path.localeCompare(right.path));
}

/**
 * Lists the source directories that must reach a pack sandbox before this
 * generator can check external public-toolchain consumers. It deliberately
 * derives from the generator's own source and documentation inputs so the
 * stack pack adapter cannot drift into a second inventory.
 */
export function resolvePublicToolchainRequiredInputStagingRelDirs() {
  const parentDirectory = (relativePath) => relativePath.slice(0, relativePath.lastIndexOf('/'));
  return Object.freeze([...new Set([
    ...GENERATED_CONSUMER_SOURCE_PATHS.map(parentDirectory),
    ...GENERATED_DOCUMENTATION_OUTPUTS.map(({ path }) => parentDirectory(path)),
  ])].sort((left, right) => left.localeCompare(right)));
}

async function checkGeneratedSourceBindings(repoRoot) {
  const sourcePaths = await publicToolchainConsumerSources(repoRoot);
  for (const { path, source } of sourcePaths) {
    const copiedFact = copiedPublicToolchainSourceFact(source);
    if (copiedFact) {
      throw new Error(`Public toolchain source consumer copies public toolchain fact ${copiedFact}: ${path}`);
    }
  }
}

function replaceGeneratedDocumentationBlock(source, { endMarker, path, startMarker }, content) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  if (start < 0 || end < 0 || end < start || source.indexOf(startMarker, start + startMarker.length) >= 0
    || source.indexOf(endMarker, end + endMarker.length) >= 0) {
    throw new Error(`Generated documentation markers are invalid: ${path}`);
  }
  return `${source.slice(0, start + startMarker.length)}\n${content}\n${source.slice(end)}`;
}

function documentationOutsideGeneratedBlock(source, { endMarker, startMarker }) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker);
  return `${source.slice(0, start)}${source.slice(end + endMarker.length)}`;
}

function copiedPublicToolchainDocumentationFact(source, documentation) {
  const outsideGeneratedBlock = documentationOutsideGeneratedBlock(source, documentation);
  if (documentation.path.endsWith('/versioning-compat.mdx')) {
    if (/engines\.happier[^\n]*\d/u.test(outsideGeneratedBlock)) return 'engines.happier';
    if (/runtime\.apiVersion[^\n]*\d/u.test(outsideGeneratedBlock)) return 'runtime.apiVersion';
    return null;
  }
  if (documentation.path.endsWith('/manifest/index.mdx')) {
    if (/"happier"\s*:\s*"[^"]+"/u.test(outsideGeneratedBlock)) return 'engines.happier';
    if (/"apiVersion"\s*:\s*\d+/u.test(outsideGeneratedBlock)) return 'runtime.apiVersion';
  }
  return null;
}

function renderGeneratedDocumentationBlock(documentation, packet) {
  if (documentation.path.endsWith('/versioning-compat.mdx')) {
    const hostRangeFact = packet.host.enginesHappier === undefined
      ? '- `engines.happier` is optional. Declare a non-wildcard compatible range only when your plugin owns one.'
      : `- Current supported host range: \`${packet.host.enginesHappier}\`.`;
    return [
      '',
      `- Current host build provenance: \`${packet.host.buildIdentity}\`.`,
      hostRangeFact,
      `- Current runtime API: \`${packet.framework.runtime}\`.`,
      '',
    ].join('\n');
  }
  if (documentation.path.endsWith('/manifest/index.mdx')) {
    return [
      '```json',
      '{',
      '  "schemaVersion": 2,',
      '  "id": "com.example.plugin",',
      '  "version": "0.1.0",',
      '  "displayName": "Example plugin",',
      '  "description": "Local Happier plugin scaffold for Example plugin.",',
      ...(packet.host.enginesHappier === undefined
        ? []
        : [`  "engines": { "happier": "${packet.host.enginesHappier}" },`]),
      `  "runtime": { "apiVersion": ${packet.framework.runtime} },`,
      '  "entrypoints": {',
      '    "daemon": "./dist/index.js",',
      '    "development": "./src/index.ts"',
      '  },',
      '  "contributes": {',
      '    "actions": [',
      '      {',
      '        "id": "save-note",',
      '        "title": "Save note",',
      '        "description": "Returns the supplied note from one minimal plugin action.",',
      '        "scopes": ["global"],',
      '        "surfaces": ["agent", "cli", "mcp"],',
      '        "execution": { "target": "daemon" },',
      '        "placementBindings": ["commandPalette"],',
      '        "dangerLevel": "safe",',
      '        "inputSchema": {',
      '          "type": "object",',
      '          "additionalProperties": false,',
      '          "properties": { "note": { "type": "string" } },',
      '          "required": ["note"]',
      '        },',
      '        "resultSchema": {',
      '          "type": "object",',
      '          "additionalProperties": false,',
      '          "properties": { "note": { "type": "string" } },',
      '          "required": ["note"]',
      '        }',
      '      }',
      '    ]',
      '  }',
      '}',
      '```',
    ].join('\n');
  }
  throw new Error(`No public toolchain documentation renderer exists for ${documentation.path}.`);
}

async function deriveGeneratedDocumentationOutputs(repoRoot, packet) {
  return Promise.all(GENERATED_DOCUMENTATION_OUTPUTS.map(async (documentation) => {
    const path = resolve(repoRoot, documentation.path);
    const source = await readSource(path, 'public toolchain documentation source');
    return Object.freeze({
      output: replaceGeneratedDocumentationBlock(
        source,
        documentation,
        renderGeneratedDocumentationBlock(documentation, packet),
      ),
      path,
    });
  }));
}

async function checkGeneratedDocumentationOutputs(repoRoot, packet) {
  const outputs = await deriveGeneratedDocumentationOutputs(repoRoot, packet);
  await Promise.all(outputs.map(async ({ output, path }) => {
    const current = await readSource(path, 'public toolchain documentation source');
    const documentation = GENERATED_DOCUMENTATION_OUTPUTS.find((candidate) => (
      resolve(repoRoot, candidate.path) === path
    ));
    if (!documentation) throw new Error(`No generated documentation owner exists for ${path}.`);
    const copiedFact = copiedPublicToolchainDocumentationFact(current, documentation);
    if (copiedFact) {
      throw new Error(`Documentation copies public toolchain fact ${copiedFact}: ${path}`);
    }
    if (current !== output) throw new Error(`Generated documentation output is stale: ${path}`);
  }));
}

async function writeGeneratedDocumentationOutputs(repoRoot, packet) {
  const outputs = await deriveGeneratedDocumentationOutputs(repoRoot, packet);
  await Promise.all(outputs.map(({ output, path }) => writeFile(path, output, 'utf8')));
}

/**
 * Reads only owning package/lock/Protocol/build-tool facts and produces the
 * strict public authoring packet. This source-boundary generator intentionally
 * knows no registry, release state, or candidate custody.
 */
export async function derivePublicToolchainCompatibilityV1({ repoRoot = DEFAULT_REPO_ROOT } = {}) {
  const root = resolve(repoRoot);
  const [rootPackage, cliPackage, appPackage, sdkPackage, uiPackage, lockSource, protocolFacts] = await Promise.all([
    readJson(resolve(root, 'package.json'), 'root package manifest'),
    readJson(resolve(root, 'apps/cli/package.json'), 'CLI package manifest'),
    readJson(resolve(root, 'apps/ui/package.json'), 'host UI package manifest'),
    readJson(resolve(root, 'packages/plugin-sdk/package.json'), 'Plugin SDK package manifest'),
    readJson(resolve(root, 'packages/plugin-ui/package.json'), 'Plugin UI package manifest'),
    readSource(resolve(root, 'yarn.lock'), 'Yarn lock'),
    readProtocolPublicToolchainFacts(root),
  ]);
  const lockEntries = readLockEntries(lockSource);

  const cliName = requiredString(cliPackage.name, 'CLI package name');
  const cliVersion = requiredString(cliPackage.version, 'CLI package version');
  const sdkName = requiredString(sdkPackage.name, 'Plugin SDK package name');
  const sdkVersion = requiredString(sdkPackage.version, 'Plugin SDK package version');
  const uiName = requiredString(uiPackage.name, 'Plugin UI package name');
  const uiVersion = requiredString(uiPackage.version, 'Plugin UI package version');
  expectSame(readDependency(uiPackage, sdkName, 'Plugin UI package manifest'), sdkVersion, 'Plugin UI and SDK package relationship');

  const reactSpec = readDependency(appPackage, 'react', 'host UI package manifest');
  const reactVersion = readResolvedVersion(lockEntries, 'react', reactSpec, 'host UI package manifest');
  const sdkReactVersion = readResolvedVersion(
    lockEntries,
    'react',
    readDependency(sdkPackage, 'react', 'Plugin SDK package manifest'),
    'Plugin SDK package manifest',
  );
  expectSame(reactVersion, sdkReactVersion, 'Host and Plugin SDK React facts');

  const reactNativeSpec = readDependency(appPackage, 'react-native', 'host UI package manifest');
  const reactNativeVersion = readResolvedVersion(lockEntries, 'react-native', reactNativeSpec, 'host UI package manifest');
  const sdkReactNativeVersion = readResolvedVersion(
    lockEntries,
    'react-native',
    readDependency(sdkPackage, 'react-native', 'Plugin SDK package manifest'),
    'Plugin SDK package manifest',
  );
  expectSame(reactNativeVersion, sdkReactNativeVersion, 'Host and Plugin SDK React Native facts');
  const pluginUiReactNativeSpec = readDependency(
    uiPackage,
    'react-native',
    'Plugin UI package manifest',
  );
  expectSame(reactNativeSpec, pluginUiReactNativeSpec, 'Host and Plugin UI React Native declarations');
  const pluginUiReactNativeVersion = readResolvedVersion(
    lockEntries,
    'react-native',
    pluginUiReactNativeSpec,
    'Plugin UI package manifest',
  );
  expectSame(reactNativeVersion, pluginUiReactNativeVersion, 'Host and Plugin UI React Native facts');

  const reactNativeWebSpec = readDependency(appPackage, 'react-native-web', 'host UI package manifest');
  const reactNativeWebVersion = readResolvedVersion(lockEntries, 'react-native-web', reactNativeWebSpec, 'host UI package manifest');
  const sdkReactNativeWebVersion = readResolvedVersion(
    lockEntries,
    'react-native-web',
    readDependency(sdkPackage, 'react-native-web', 'Plugin SDK package manifest'),
    'Plugin SDK package manifest',
  );
  expectSame(reactNativeWebVersion, sdkReactNativeWebVersion, 'Host and Plugin SDK React Native Web facts');

  const viteSpec = readDependency(sdkPackage, 'vite', 'Plugin SDK package manifest');
  const viteVersion = readResolvedVersion(lockEntries, 'vite', viteSpec, 'Plugin SDK package manifest');
  const repackSpec = readDependency(sdkPackage, '@callstack/repack', 'Plugin SDK package manifest');
  const repackVersion = readResolvedVersion(lockEntries, '@callstack/repack', repackSpec, 'Plugin SDK package manifest');
  const expoSpec = readDependency(appPackage, 'expo', 'host UI package manifest');
  const expoVersion = readResolvedVersion(lockEntries, 'expo', expoSpec, 'host UI package manifest');

  const viteDescriptor = protocolFacts.bundlers.vite;
  const repackDescriptor = protocolFacts.bundlers.repack;
  expectSame(viteDescriptor.packageName, 'vite', 'Vite managed bundler package');
  expectSame(repackDescriptor.packageName, '@callstack/repack', 'Re.Pack managed bundler package');

  const reactDomSpec = readDependency(appPackage, 'react-dom', 'host UI package manifest');
  const reactDomVersion = readResolvedVersion(lockEntries, 'react-dom', reactDomSpec, 'host UI package manifest');
  const nodeTypesSpec = readDependency(sdkPackage, '@types/node', 'Plugin SDK package manifest');
  const nodeTypesVersion = readResolvedVersion(lockEntries, '@types/node', nodeTypesSpec, 'Plugin SDK package manifest');
  const reactTypesSpec = readDependency(sdkPackage, '@types/react', 'Plugin SDK package manifest');
  const reactTypesVersion = readResolvedVersion(lockEntries, '@types/react', reactTypesSpec, 'Plugin SDK package manifest');
  const cliSpec = readDependency(sdkPackage, '@react-native-community/cli', 'Plugin SDK package manifest');
  const cliResolvedVersion = readResolvedVersion(lockEntries, '@react-native-community/cli', cliSpec, 'Plugin SDK package manifest');
  const rspackSpec = readDependency(sdkPackage, '@rspack/core', 'Plugin SDK package manifest');
  const rspackVersion = readResolvedVersion(lockEntries, '@rspack/core', rspackSpec, 'Plugin SDK package manifest');
  const swcHelpersSpec = readDependency(sdkPackage, '@swc/helpers', 'Plugin SDK package manifest');
  const swcHelpersVersion = readResolvedVersion(lockEntries, '@swc/helpers', swcHelpersSpec, 'Plugin SDK package manifest');
  const typescriptSpec = readDependency(rootPackage, 'typescript', 'root package manifest');
  const typescriptVersion = readResolvedVersion(lockEntries, 'typescript', typescriptSpec, 'root package manifest');
  const typescriptNativeSpec = readDependency(rootPackage, '@typescript/native', 'root package manifest');
  const typescriptNativeVersion = readResolvedVersion(lockEntries, '@typescript/native', typescriptNativeSpec, 'root package manifest');
  const viteReactPluginSpec = readDependency(sdkPackage, '@vitejs/plugin-react', 'Plugin SDK package manifest');
  const viteReactPluginVersion = readResolvedVersion(lockEntries, '@vitejs/plugin-react', viteReactPluginSpec, 'Plugin SDK package manifest');

  const runtimeVersion = String(protocolFacts.runtimeApiVersion);
  const hostApiVersion = protocolFacts.ui.hostApiVersion;
  const artifactGrammarVersion = protocolFacts.ui.artifactGrammarVersion;

  return Object.freeze({
    schemaVersion: 1,
    host: Object.freeze({ buildIdentity: `${cliName}@${cliVersion}` }),
    pluginSdk: Object.freeze({ version: sdkVersion }),
    pluginUi: Object.freeze({ version: uiVersion, pluginSdkVersion: sdkVersion }),
    framework: Object.freeze({
      react: reactVersion,
      reactNative: reactNativeVersion,
      reactNativeWeb: reactNativeWebVersion,
      vite: viteVersion,
      repack: repackVersion,
      expo: expoVersion,
      runtime: runtimeVersion,
    }),
    ui: Object.freeze({ artifactGrammarVersion, hostApiVersion }),
    authoringDependencies: Object.freeze({
      nodeTypes: authoringDependency('@types/node', nodeTypesVersion, nodeTypesVersion),
      reactDom: authoringDependency('react-dom', reactDomVersion, reactDomVersion),
      reactTypes: authoringDependency('@types/react', reactTypesVersion, reactTypesVersion),
      reactNativeCommunityCli: authoringDependency('@react-native-community/cli', cliResolvedVersion, cliResolvedVersion),
      rspack: authoringDependency('@rspack/core', rspackVersion, rspackVersion),
      swcHelpers: authoringDependency('@swc/helpers', swcHelpersSpec, swcHelpersVersion),
      typescript: authoringDependency('typescript', typescriptSpec, typescriptVersion),
      typescriptNative: authoringDependency('@typescript/native', typescriptNativeSpec, typescriptNativeVersion),
      viteReactPlugin: authoringDependency('@vitejs/plugin-react', viteReactPluginVersion, viteReactPluginVersion),
    }),
    buildTools: Object.freeze([
      Object.freeze({
        packageName: repackDescriptor.packageName,
        packageVersion: repackVersion,
        executable: repackDescriptor.executable,
        executableVersion: cliResolvedVersion,
      }),
      Object.freeze({
        packageName: viteDescriptor.packageName,
        packageVersion: viteVersion,
        executable: viteDescriptor.executable,
        executableVersion: viteVersion,
      }),
    ]),
  });
}

export function renderPublicToolchainCompatibilityModule(packet) {
  return `${GENERATED_MODULE_PREFIX}${JSON.stringify(packet, null, 2)}${GENERATED_MODULE_SUFFIX}`;
}

function parseGeneratedPacketModule(source, outputPath) {
  if (!source.startsWith(GENERATED_MODULE_PREFIX) || !source.endsWith(GENERATED_MODULE_SUFFIX)) {
    throw new Error(`Generated public toolchain packet is not the canonical generated module: ${outputPath}`);
  }
  const serializedPacket = source.slice(
    GENERATED_MODULE_PREFIX.length,
    source.length - GENERATED_MODULE_SUFFIX.length,
  );
  let packet;
  try {
    packet = JSON.parse(serializedPacket);
  } catch (cause) {
    throw new Error(
      `Generated public toolchain packet is not valid JSON: ${outputPath}: ${cause instanceof Error ? cause.message : String(cause)}`,
    );
  }
  if (renderPublicToolchainCompatibilityModule(packet) !== source) {
    throw new Error(`Generated public toolchain packet is not canonical: ${outputPath}`);
  }
  return asRecord(packet, 'generated public toolchain packet');
}

function validateGeneratedPacketForPack(packet, sdkPackage) {
  // This is the same strict Protocol owner that the installed public SDK uses
  // at runtime. Checking it before packaging keeps malformed generated bytes
  // from becoming an artifact that fails only when an author imports it.
  const coherentPacket = assertCoherentPublicToolchainCompatibilityV1(packet);
  const pluginSdk = asRecord(coherentPacket.pluginSdk, 'generated public toolchain packet Plugin SDK facts');
  const pluginUi = asRecord(coherentPacket.pluginUi, 'generated public toolchain packet Plugin UI facts');
  const generatedSdkVersion = requiredString(
    pluginSdk.version,
    'generated public toolchain packet Plugin SDK version',
  );
  const generatedPluginUiSdkVersion = requiredString(
    pluginUi.pluginSdkVersion,
    'generated public toolchain packet Plugin UI SDK version',
  );
  const localSdkVersion = requiredString(sdkPackage.version, 'Plugin SDK package version');
  expectSame(
    generatedSdkVersion,
    localSdkVersion,
    'Generated public toolchain packet and Plugin SDK package version',
  );
  expectSame(
    generatedPluginUiSdkVersion,
    generatedSdkVersion,
    'Generated public toolchain packet Plugin UI and SDK relationship',
  );
}

async function checkGeneratedPublicToolchainCompatibility({ repoRoot, outputPath }) {
  const [source, sdkPackage] = await Promise.all([
    readSource(outputPath, 'generated public toolchain packet'),
    readJson(resolve(repoRoot, 'packages/plugin-sdk/package.json'), 'Plugin SDK package manifest'),
  ]);
  const packet = parseGeneratedPacketModule(source, outputPath);
  validateGeneratedPacketForPack(packet, sdkPackage);
}

function parseArgs(args) {
  let repoRoot = DEFAULT_REPO_ROOT;
  let outputPath = null;
  let check = false;
  let checkGenerated = false;
  let write = false;
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === '--check') {
      check = true;
      continue;
    }
    if (arg === '--write') {
      write = true;
      continue;
    }
    if (arg === '--check-generated') {
      checkGenerated = true;
      continue;
    }
    if (arg === '--repo-root' || arg === '--output') {
      const value = args[index + 1];
      if (!value || value.startsWith('--')) throw new Error(`${arg} requires a value.`);
      if (arg === '--repo-root') repoRoot = resolve(value);
      else outputPath = value;
      index += 1;
      continue;
    }
    throw new Error(`Unknown public toolchain generator argument: ${arg}`);
  }
  if ([check, checkGenerated, write].filter(Boolean).length > 1) {
    throw new Error('--check, --check-generated, and --write are mutually exclusive.');
  }
  return Object.freeze({ repoRoot, outputPath, check, checkGenerated, write });
}

async function main() {
  const options = parseArgs(process.argv.slice(2));
  const outputPath = resolve(options.repoRoot, options.outputPath ?? DEFAULT_OUTPUT_PATH);
  if (options.checkGenerated) {
    await checkGeneratedPublicToolchainCompatibility({
      repoRoot: options.repoRoot,
      outputPath,
    });
    return;
  }
  const packet = await derivePublicToolchainCompatibilityV1({ repoRoot: options.repoRoot });
  const expected = renderPublicToolchainCompatibilityModule(packet);
  let current = null;
  try {
    current = await readFile(outputPath, 'utf8');
  } catch (cause) {
    if (cause?.code !== 'ENOENT') throw cause;
  }
  if (options.check) {
    if (current !== expected) throw new Error(`Public toolchain compatibility output is stale: ${outputPath}`);
    await checkGeneratedConsumerPackageOutputs(options.repoRoot, packet);
    await checkGeneratedSourceBindings(options.repoRoot);
    await checkGeneratedDocumentationOutputs(options.repoRoot, packet);
    return;
  }
  if (options.write) {
    await writeFile(outputPath, expected, 'utf8');
    await writeGeneratedConsumerPackageOutputs(options.repoRoot, packet);
    await writeGeneratedDocumentationOutputs(options.repoRoot, packet);
    return;
  }
  process.stdout.write(expected);
}

if (process.argv[1] && resolve(process.argv[1]) === SCRIPT_PATH) {
  main().catch((error) => {
    process.stderr.write(`${error instanceof Error ? error.stack ?? error.message : String(error)}\n`);
    process.exitCode = 1;
  });
}
