import type { AcpPermissionModeArgvSpecV1 } from '@happier-dev/plugin-sdk/acp';

export const QWEN_PERMISSION_MODE_ARGV = Object.freeze({
  flag: '--approval-mode',
  map: Object.freeze({
    default: null,
    ask: null,
    prompt: null,
    normal: null,
    plan: 'plan',
    'read-only': 'plan',
    read_only: 'plan',
    readonly: 'plan',
    read: 'plan',
    ro: 'plan',
    acceptEdits: 'auto-edit',
    'accept-edits': 'auto-edit',
    'safe-yolo': 'auto-edit',
    safeyolo: 'auto-edit',
    safe: 'auto-edit',
    'workspace-write': 'auto-edit',
    workspace: 'auto-edit',
    'auto-edit': 'auto-edit',
    auto: 'auto-edit',
    yolo: 'yolo',
    bypassPermissions: 'yolo',
    'bypass-permissions': 'yolo',
    bypass: 'yolo',
    full: 'yolo',
    'full-access': 'yolo',
    dontask: 'yolo',
    'dont-ask': 'yolo',
    danger: 'yolo',
    'danger-full-access': 'yolo',
  }),
} satisfies AcpPermissionModeArgvSpecV1);
