import { definePlugin } from '@happier-dev/plugin-sdk';
import type { TargetedContributionPointRef } from '@happier-dev/plugin-sdk';
import type { PluginManifest } from '@happier-dev/plugin-sdk/manifest';
import {
  CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1,
  CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1,
  CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1,
  CONVERSATION_MANAGEMENT_ACTION_IDS_V1,
  ConversationProvidersContributionPointV1,
} from '@happier-dev/channels-protocol/v1';

import { CHANNEL_ACCOUNT_COLLECTION_DECLARATIONS } from './collections.js';

export const CHANNELS_PLUGIN_ID = 'happier.channels';
export const CHANNELS_NATIVE_BUNDLE_ID = 'channels-app-native';
export const CHANNELS_RENDERER_ID = 'channels-renderer';
export const CHANNELS_SETTINGS_GROUP_ID = 'channels';
export const CHANNELS_SETTINGS_PAGE_ID = 'connections';

/**
 * The sole provider discovery authority for Channels runtime work. The host
 * supplies its immutable admitted snapshot; Channels selects only within it.
 */
export const CHANNELS_PROVIDER_POINT_ID = 'providers' as const;
const CHANNELS_PROVIDER_POINT_DEFINITION = definePlugin({
  id: CHANNELS_PLUGIN_ID,
  version: '0.0.0',
  contributionPoints: {
    [CHANNELS_PROVIDER_POINT_ID]: ConversationProvidersContributionPointV1,
  },
});

/** The one admitted V1 provider contribution at Channels' target-owned point. */
export type ChannelsProviderContributionV1 = (
  typeof CHANNELS_PROVIDER_POINT_DEFINITION.contributionPoints.providers
) extends TargetedContributionPointRef<infer TContribution>
  ? TContribution
  : never;

/**
 * `definePlugin` is the sole projector of both the cold declaration and the
 * live target reference, preventing a hand-maintained point/ref split.
 */
export const CHANNELS_PROVIDER_POINT_REF =
  CHANNELS_PROVIDER_POINT_DEFINITION.contributionPoints[CHANNELS_PROVIDER_POINT_ID];

/**
 * The generic Settings catalog owns the route and availability decision. This
 * contribution supplies one native renderer and one page, rather than a
 * Channels-specific route, Resource store, or connection cache.
 */
export const CHANNELS_UI = {
  views: [],
  renderers: [{
    id: CHANNELS_RENDERER_ID,
    kind: 'reactNative' as const,
    artifact: CHANNELS_NATIVE_BUNDLE_ID,
    // Resources and Actions are opportunistic daemon capabilities. This
    // Account-Collection renderer remains useful cold offline through the
    // admitted direct Data client, so declaring either as a mount requirement
    // would make the manifest contradict its real supported lifecycle.
    requiredHostMethods: [],
  }],
  settingsGroups: [{
    id: CHANNELS_SETTINGS_GROUP_ID,
    title: { key: 'plugins.channels.title', fallback: 'Conversation Channels' },
    icon: 'settings' as const,
    defaultRank: 20,
  }],
  settingsPages: [{
    id: CHANNELS_SETTINGS_PAGE_ID,
    group: { kind: 'plugin' as const, localId: CHANNELS_SETTINGS_GROUP_ID },
    title: { key: 'plugins.channels.settings.connections', fallback: 'Connections' },
    subtitle: {
      key: 'plugins.channels.settings.connections.subtitle',
      fallback: 'Account policy for external conversation integrations.',
    },
    keywords: ['conversation', 'channels', 'connections'],
    icon: 'settings' as const,
    defaultRank: 20,
    renderer: CHANNELS_RENDERER_ID,
  }],
  translations: [{
    locale: 'en',
    messages: {
      'plugins.channels.title': 'Conversation Channels',
      'plugins.channels.settings.connections': 'Connections',
      'plugins.channels.settings.connections.subtitle': 'Account policy for external conversation integrations.',
      'plugins.channels.surface.connections': 'Conversation connections',
      'plugins.channels.surface.title': 'Conversation Channels',
      'plugins.channels.surface.description': 'Manage the Account policy for each external conversation integration.',
      'plugins.channels.surface.bindings': 'Conversation bindings',
      'plugins.channels.surface.bindingsDescription': 'Manage where each external conversation sends eligible messages.',
      'plugins.channels.surface.bindingsRefreshing': 'Refreshing binding details',
      'plugins.channels.surface.bindingsStaleTitle': 'Showing last known binding details',
      'plugins.channels.surface.bindingsStaleDescription': 'Live binding updates are temporarily unavailable.',
      'plugins.channels.surface.bindingsLiveUpdatesEndedTitle': 'Live binding updates are unavailable',
      'plugins.channels.surface.bindingsLiveUpdatesEndedDescription': 'Refresh to read the current Account binding policy again.',
      'plugins.channels.surface.bindingsEmptyTitle': 'No conversation bindings yet',
      'plugins.channels.surface.bindingsEmptyDescription': 'Bindings created for this Account will appear here.',
      'plugins.channels.surface.bindingsLoadingTitle': 'Loading conversation bindings',
      'plugins.channels.surface.bindingsLoadingDescription': 'Reading the current binding policy from your Account.',
      'plugins.channels.surface.bindingsErrorTitle': 'Binding details are unavailable',
      'plugins.channels.surface.bindingsErrorDescription': 'Refresh to try reading the current Account binding policy again.',
      'plugins.channels.surface.bindingsResourceContentTypeInvalid': 'The binding Resource did not return JSON.',
      'plugins.channels.surface.bindingsResourceInvalidJson': 'The binding Resource could not be read.',
      'plugins.channels.surface.bindingsResourceShapeInvalid': 'The binding Resource has an unexpected shape.',
      'plugins.channels.surface.bindingsResourceBindingInvalid': 'The binding Resource contains an invalid binding.',
      'plugins.channels.surface.bindingEndpointFallback': 'External conversation',
      'plugins.channels.surface.bindingAudienceDirect': 'Direct conversation',
      'plugins.channels.surface.bindingAudienceShared': 'Shared conversation',
      'plugins.channels.surface.bindingTargetSession': 'Session',
      'plugins.channels.surface.bindingTargetAutomation': 'Automation',
      'plugins.channels.surface.bindingInputDirectMentionsOnly': 'Direct mentions only',
      'plugins.channels.surface.bindingInputAddressedMessages': 'Addressed messages',
      'plugins.channels.surface.bindingInputAllAllowedMessages': 'All allowed messages',
      'plugins.channels.surface.bindingDeliveryRepliesOnly': 'Replies only',
      'plugins.channels.surface.bindingDeliveryMirrorSession': 'Mirror Session',
      'plugins.channels.surface.bindingDeliveryFinalResult': 'Final result',
      'plugins.channels.surface.bindingDeliveryNone': 'No external result',
      'plugins.channels.surface.bindingConnectionUnavailable': 'Connection details are unavailable',
      'plugins.channels.surface.bindingCreateAction': 'Create binding',
      'plugins.channels.surface.bindingCreateTitle': 'Create conversation binding',
      'plugins.channels.surface.bindingCreateDescription': 'Choose the current external conversation, allowed principals, and destination.',
      'plugins.channels.surface.bindingCreateEndpointQuery': 'Conversation search',
      'plugins.channels.surface.bindingCreateEndpointSearch': 'Search conversations',
      'plugins.channels.surface.bindingCreatePrincipalQuery': 'Principal search',
      'plugins.channels.surface.bindingCreatePrincipalSearch': 'Search allowed principals',
      'plugins.channels.surface.bindingCreateTarget': 'Destination',
      'plugins.channels.surface.bindingCreateSession': 'Session',
      'plugins.channels.surface.bindingCreateAutomation': 'Automation',
      'plugins.channels.surface.bindingCreateAutomationLoadMore': 'Show more Automations',
      'plugins.channels.surface.bindingCreatePolicies': 'Binding policy',
      'plugins.channels.surface.bindingCreatePolicySummary': 'Binding policy',
      'plugins.channels.surface.bindingCreateContinue': 'Continue',
      'plugins.channels.surface.bindingCreateReview': 'Review binding',
      'plugins.channels.surface.bindingCreateConfirm': 'Create binding',
      'plugins.channels.surface.bindingCreateBack': 'Back',
      'plugins.channels.surface.bindingCreateCancel': 'Cancel',
      'plugins.channels.surface.bindingCreateCurrentStep': 'Current step',
      'plugins.channels.surface.bindingCreatePrivacyPlain': 'Storage and privacy: Channel configuration, binding policy, provider-derived identities, and externally bridged Session content use the documented server, database, and backup visibility of their canonical plain Account/Session owners.',
      'plugins.channels.surface.bindingCreatePrivacyE2ee': 'Storage and privacy: private fields remain inside canonical encrypted envelopes; only the bounded routing/index projection is server-readable.',
      'plugins.channels.surface.bindingCreateConversation': 'Conversation',
      'plugins.channels.surface.bindingCreateAllowedSender': 'Allowed sender',
      'plugins.channels.surface.bindingCreatePairingRequiredSummary': 'Pairing challenge required',
      'plugins.channels.surface.bindingCreateConnectionUnavailable': 'Connection unavailable',
      'plugins.channels.surface.bindingCreateInputMode': 'Incoming messages',
      'plugins.channels.surface.bindingCreateDeliveryMode': 'Session delivery',
      'plugins.channels.surface.bindingCreatePermissionCeiling': 'Permission ceiling',
      'plugins.channels.surface.bindingCreateApprovals': 'Approvals',
      'plugins.channels.surface.bindingCreateApprovalsOff': 'Off',
      'plugins.channels.surface.bindingCreateAllowBots': 'Allow bot senders',
      'plugins.channels.surface.bindingCreateAllowBotsAllowed': 'Allowed',
      'plugins.channels.surface.bindingCreateAllowBotsBlocked': 'Blocked',
      'plugins.channels.surface.bindingCreateLinkPreview': 'Link previews',
      'plugins.channels.surface.bindingCreateSenderFeedback': 'Sender feedback',
      'plugins.channels.surface.bindingCreateWebhookBoundary': 'Webhook trust boundary',
      'plugins.channels.surface.bindingCreateWebhookBoundaryDurablePush': 'Uses this connection’s host-verified webhook endpoint.',
      'plugins.channels.surface.bindingCreateCreated': 'Conversation binding created.',
      'plugins.channels.surface.bindingCreateUnavailableTitle': 'Binding setup is unavailable',
      'plugins.channels.surface.bindingCreateUnavailableDescription': 'Refresh connection details and try again.',
      'plugins.channels.surface.bindingCreateStaleTitle': 'Binding setup changed',
      'plugins.channels.surface.bindingCreateStaleDescription': 'Refresh connection details and choose the current conversation again.',
      'plugins.channels.surface.bindingCreateUnknownTitle': 'Could not confirm binding creation',
      'plugins.channels.surface.bindingCreateUnknownDescription': 'A binding may already be saved. Refresh binding details before trying again.',
      'plugins.channels.surface.bindingCreatePairingTitle': 'Pairing is required',
      'plugins.channels.surface.bindingCreatePairingDescription': 'This provider requires a separate pairing flow before it can resolve principals.',
      'plugins.channels.surface.bindingCreateSessionUnavailableTitle': 'Session destination is unavailable',
      'plugins.channels.surface.bindingCreateAutomationUnavailableTitle': 'Automation destination is unavailable',
      'plugins.channels.surface.bindingCreateConfigureNewSession': 'Configure new Session',
      'plugins.channels.surface.bindingCreateNewSessionDisabled': 'Do not create a new Session',
      'plugins.channels.surface.bindingCreateNewSessionEnabled': 'Create a new Session',
      'plugins.channels.surface.bindingCreateNewSessionUnavailable': 'New Session creation is unavailable for this destination.',
      'plugins.channels.surface.bindingEnabled': 'Binding enabled',
      'plugins.channels.surface.bindingSaveUnknownDescription': 'The change may already be saved. Refresh binding details before changing it again.',
      'plugins.channels.surface.savedPendingMachineReconciliation': 'Saved to your Account. The selected machine will reconcile this policy when it is available.',
      'plugins.channels.surface.providerActionsUnavailableTitle': 'Provider actions need your selected machine',
      'plugins.channels.surface.providerActionsUnavailableDescription': 'This Account policy can be saved now. Connection deletion, transport stop, and delivery resolution remain unavailable until the selected machine can run the provider.',
      'plugins.channels.surface.bindingProviderFilters': 'Filter conversation bindings by integration',
      'plugins.channels.surface.bindingProviderFilterAll': 'All',
      'plugins.channels.surface.bindingProviderFilterFallback': 'Integration',
      'plugins.channels.surface.providerSetupTitle': 'Add a conversation provider',
      'plugins.channels.surface.providerSetupDescription': 'Choose an installed provider to begin setup.',
      'plugins.channels.surface.providerSetupAction': 'Set up',
      'plugins.channels.surface.providerSetupUnavailableTitle': 'Provider setup is unavailable',
      'plugins.channels.surface.providerSetupUnavailableDescription': 'The available provider selection is no longer current. Refresh this page and try again.',
      'plugins.channels.surface.providerPreparationUnavailableTitle': 'Could not prepare the provider',
      'plugins.channels.surface.providerPreparationUnavailableDescription': 'The provider did not return a usable setup result. Try again after refreshing this page.',
      'plugins.channels.surface.providerSetupRemediationTitle': 'Finish provider setup',
      'plugins.channels.surface.providerSetupRemediationDescription': 'Finish the provider setup before creating a connection.',
      'plugins.channels.surface.providerSetupRemediationAction': 'Resolve provider setup',
      'plugins.channels.surface.providerSetupRemediationUnavailableTitle': 'Provider setup needs attention',
      'plugins.channels.surface.providerSetupRemediationUnavailableDescription': 'This provider has no current setup action for the required change. Refresh and choose the provider again.',
      'plugins.channels.surface.providerSetupRemediationFailedTitle': 'Could not finish provider setup',
      'plugins.channels.surface.providerSetupRemediationFailedDescription': 'The provider did not confirm the setup change. You can try again after checking its configuration.',
      'plugins.channels.surface.providerSetupRemediationUnknownTitle': 'Could not confirm provider setup remediation',
      'plugins.channels.surface.providerSetupRemediationUnknownDescription': 'The provider change may already have completed. Check provider setup again before trying another change.',
      'plugins.channels.surface.providerSetupReady': 'Provider setup is ready. Choose a supported transport and create the connection.',
      'plugins.channels.surface.providerSetupUnknownTitle': 'Could not confirm provider setup',
      'plugins.channels.surface.providerSetupUnknownDescription': 'Refresh this page before trying provider setup again.',
      'plugins.channels.surface.providerSetupTransportDescription': 'Choose how Happier will receive conversation updates from this provider.',
      'plugins.channels.surface.providerCreate': 'Create connection',
      'plugins.channels.surface.providerCreating': 'Creating connection…',
      'plugins.channels.surface.providerCreationUnavailableTitle': 'No supported connection transport is available',
      'plugins.channels.surface.providerCreationUnavailableDescription': 'This provider setup cannot create a connection on this server. Refresh the page before trying again.',
      'plugins.channels.surface.providerCreationFailedTitle': 'Could not create the connection',
      'plugins.channels.surface.providerCreationFailedDescription': 'The connection was not saved. Review the setup and try again.',
      'plugins.channels.surface.providerCreationUnknownTitle': 'Could not confirm connection creation',
      'plugins.channels.surface.providerCreationUnknownDescription': 'A connection may already be saved. Refresh connection details before trying again.',
      'plugins.channels.surface.bindingApprovalUnavailableRequest': 'Approval requests are unavailable for request scope. This saved policy does not authorize messages.',
      'plugins.channels.surface.bindingApprovalUnavailableSession': 'Approval requests are unavailable for session scope. This saved policy does not authorize messages.',
      'plugins.channels.surface.refresh': 'Refresh',
      'plugins.channels.surface.refreshing': 'Refreshing connection details',
      'plugins.channels.surface.staleTitle': 'Showing last known connection details',
      'plugins.channels.surface.staleDescription': 'Live connection updates are temporarily unavailable.',
      'plugins.channels.surface.tryAgain': 'Try again',
      'plugins.channels.surface.liveUpdatesEndedTitle': 'Live updates are unavailable',
      'plugins.channels.surface.liveUpdatesEndedDescription': 'Refresh to read the current Account connection policy again.',
      'plugins.channels.surface.provider': 'Provider',
      'plugins.channels.surface.providerFallback': 'Integration provider',
      'plugins.channels.surface.transport': 'Transport',
      'plugins.channels.surface.transportCheckpointedPull': 'Checkpointed pull',
      'plugins.channels.surface.transportSocket': 'Live socket',
      'plugins.channels.surface.transportDurablePush': 'Durable push',
      'plugins.channels.surface.pollBlocked': 'Polling needs attention',
      'plugins.channels.surface.pollRetryDue': 'Polling will retry',
      'plugins.channels.surface.pollRetryDueTitle': 'Conversation polling will retry',
      'plugins.channels.surface.pollRetryDueDescription': 'Happier will retry this connection automatically.',
      'plugins.channels.surface.pollBlockedTitle': 'Conversation polling needs attention',
      'plugins.channels.surface.pollBlockedDescription': 'Happier stopped retrying this connection poll. Retry polling after reviewing the current connection policy.',
      'plugins.channels.surface.pollRetry': 'Retry polling',
      'plugins.channels.surface.pollRetrying': 'Retrying polling…',
      'plugins.channels.surface.pollRetryFailedTitle': 'Could not retry polling',
      'plugins.channels.surface.pollRetryFailedDescription': 'The blocked poll state may have changed. Refresh connection details before trying again.',
      'plugins.channels.surface.pollRetryUnknownTitle': 'Could not confirm the polling retry',
      'plugins.channels.surface.pollRetryUnknownDescription': 'The retry may already be scheduled. Refresh connection details before trying again.',
      'plugins.channels.surface.ingressAttentionTitle': 'Incoming messages need attention',
      'plugins.channels.surface.ingressAttentionDescription': 'Review saved incoming-message outcomes. Retry is available only for inputs that stopped before Happier could finish admitting them.',
      'plugins.channels.surface.ingressAttentionEmptyTitle': 'No incoming messages need attention',
      'plugins.channels.surface.ingressAttentionEmptyDescription': 'Incoming messages that need your action will appear here.',
      'plugins.channels.surface.ingressAttentionLoading': 'Loading blocked inputs',
      'plugins.channels.surface.ingressAttentionReadFailedTitle': 'Could not read blocked inputs',
      'plugins.channels.surface.ingressAttentionReadFailedDescription': 'Refresh to see the current saved input recovery state.',
      'plugins.channels.surface.ingressAttentionActionsUnavailable': 'Connect the selected machine to retry these saved inputs.',
      'plugins.channels.surface.ingressAttentionAttemptCountPrefix': 'Retry stopped after',
      'plugins.channels.surface.ingressAttentionAttemptCountSingular': 'attempt',
      'plugins.channels.surface.ingressAttentionAttemptCountPlural': 'attempts',
      'plugins.channels.surface.ingressAttentionTerminal': 'An incoming message was not accepted.',
      'plugins.channels.surface.ingressAttentionOccurrenceConflict': 'An incoming occurrence has contradictory evidence.',
      'plugins.channels.surface.ingressAttentionRetry': 'Retry saved input',
      'plugins.channels.surface.ingressAttentionRetrying': 'Retrying saved input…',
      'plugins.channels.surface.ingressAttentionLoadMore': 'Show more blocked inputs',
      'plugins.channels.surface.ingressAttentionRetryFailedTitle': 'Could not retry the saved input',
      'plugins.channels.surface.ingressAttentionRetryFailedDescription': 'The blocked input may have changed. Refresh before trying again.',
      'plugins.channels.surface.ingressAttentionRetryUnknownTitle': 'Could not confirm the saved input retry',
      'plugins.channels.surface.ingressAttentionRetryUnknownDescription': 'The retry may already be scheduled. Refresh blocked input details before trying again.',
      'plugins.channels.surface.selectedMachineSummary': 'Runs on your selected machine',
      'plugins.channels.surface.stopPending': 'Stop reconciliation pending',
      'plugins.channels.surface.deleteFinalizing': 'Deletion cleanup in progress',
      'plugins.channels.surface.oldTransportStopUnconfirmed': 'Old transport stop is unconfirmed',
      'plugins.channels.surface.oldTransportStopUnconfirmedTitle': 'Previous transport may still be running',
      'plugins.channels.surface.oldTransportStopUnconfirmedDescription': 'Happier has not confirmed that the previous transport stopped. New connection authority is protected while reconciliation continues.',
      'plugins.channels.surface.acceptedPossibleLossTitle': 'Possible message loss was accepted',
      'plugins.channels.surface.acceptedPossibleLossDescription': 'Deletion cleanup can continue because you accepted possible message loss; Happier has not claimed the old transport stopped.',
      'plugins.channels.surface.historyGap': 'History gap needs attention',
      'plugins.channels.surface.ingressOccurrenceConflict': 'Incoming occurrence conflict needs attention',
      'plugins.channels.surface.ingressOccurrenceConflictTitle': 'Incoming occurrence conflict needs attention',
      'plugins.channels.surface.ingressOccurrenceConflictDescription': 'Happier received contradictory evidence for one incoming occurrence. It will not retry or advance this connection; delete the connection to remove the retained conflict.',
      'plugins.channels.surface.deliveryOutcomeUnknown': 'Delivery outcome needs attention',
      'plugins.channels.surface.deliveryPartial': 'Delivery was only partly sent',
      'plugins.channels.surface.deliveryNotDelivered': 'Delivery was not sent',
      'plugins.channels.surface.deliveryRetryDue': 'Delivery is waiting to retry',
      'plugins.channels.surface.deliveryRetryDueTitle': 'A message delivery is waiting to retry',
      'plugins.channels.surface.deliveryRetryDueDescription': 'Happier has not sent one message yet and will retry it when the saved connection policy remains current.',
      'plugins.channels.surface.deliveryNotDeliveredTitle': 'A message delivery was not sent',
      'plugins.channels.surface.deliveryNotDeliveredDescription': 'Happier confirmed that one message was not delivered.',
      'plugins.channels.surface.deliveryPartialTitle': 'A message delivery was only partly sent',
      'plugins.channels.surface.deliveryPartialDescription': 'Happier could not complete one message delivery, so its final effect needs attention.',
      'plugins.channels.surface.deliveryOutcomeUnknownTitle': 'A message delivery needs confirmation',
      'plugins.channels.surface.deliveryOutcomeUnknownDescription': 'Happier cannot confirm whether one message delivery completed. It will not resend it automatically.',
      'plugins.channels.surface.deliveryResolutionTitle': 'Resolve delivery outcome',
      'plugins.channels.surface.deliveryResolutionDescription': 'Review each delivery that may already have had an external effect. Happier will not send it again automatically.',
      'plugins.channels.surface.deliveryResolutionPartial': 'Partly sent',
      'plugins.channels.surface.deliveryResolutionOutcomeUnknown': 'Outcome unknown',
      'plugins.channels.surface.deliveryResolutionAccept': 'Accept as sent',
      'plugins.channels.surface.deliveryResolutionDiscard': 'Discard delivery',
      'plugins.channels.surface.deliveryResolutionAccepting': 'Accepting…',
      'plugins.channels.surface.deliveryResolutionDiscarding': 'Discarding…',
      'plugins.channels.surface.deliveryResolutionReadFailedTitle': 'Could not read delivery details',
      'plugins.channels.surface.deliveryResolutionReadFailedDescription': 'Refresh to see the current delivery decisions.',
      'plugins.channels.surface.deliveryResolutionFailedTitle': 'Could not record the delivery decision',
      'plugins.channels.surface.deliveryResolutionFailedDescription': 'Refresh delivery details before trying again.',
      'plugins.channels.surface.deliveryResolutionUnknownTitle': 'Could not confirm the delivery decision',
      'plugins.channels.surface.deliveryResolutionUnknownDescription': 'The decision may already be saved. Refresh delivery details before making another choice.',
      'plugins.channels.surface.deliveryResolutionLoadMore': 'Show more delivery decisions',
      'plugins.channels.surface.deliveryResolutionLoading': 'Loading delivery details',
      'plugins.channels.surface.deliveryResolutionEmpty': 'No unresolved delivery decisions are currently available.',
      'plugins.channels.surface.disabled': 'Disabled',
      'plugins.channels.surface.bestEffort': 'Best effort before durable admission',
      'plugins.channels.surface.enabled': 'Enabled',
      'plugins.channels.surface.integrationIdentity': 'Integration identity and Account policy',
      'plugins.channels.surface.currentPolicy': 'Current connection policy',
      'plugins.channels.surface.technicalDetails': 'Technical details',
      'plugins.channels.surface.providerPluginId': 'Provider plugin ID',
      'plugins.channels.surface.selectedMachineId': 'Selected machine ID',
      'plugins.channels.surface.updateUnavailableTitle': 'Editing is unavailable during deletion',
      'plugins.channels.surface.updateUnavailableDescription': 'This connection is reconciling its stop or deletion state. Refresh for its current status.',
      'plugins.channels.surface.enabledPolicy': 'Enabled',
      'plugins.channels.surface.enabledPolicyDescription': 'Allow this integration to accept and deliver under its saved policy.',
      'plugins.channels.surface.maximumObservationAge': 'Maximum observation age',
      'plugins.channels.surface.maximumObservationAgeDescription': 'Accept incoming observations no older than this limit.',
      'plugins.channels.surface.maximumObservationAgeInput': 'Maximum observation age in milliseconds',
      'plugins.channels.surface.observationAgeRange': 'Choose a value from',
      'plugins.channels.surface.observationAgeInvalid': 'Enter a whole number from',
      'plugins.channels.surface.through': 'through',
      'plugins.channels.surface.day': 'day',
      'plugins.channels.surface.days': 'days',
      'plugins.channels.surface.hour': 'hour',
      'plugins.channels.surface.hours': 'hours',
      'plugins.channels.surface.minute': 'minute',
      'plugins.channels.surface.minutes': 'minutes',
      'plugins.channels.surface.second': 'second',
      'plugins.channels.surface.seconds': 'seconds',
      'plugins.channels.surface.saved': 'Saved to your Account. The selected machine will reconcile this policy when it is available.',
      'plugins.channels.surface.saveFailedTitle': 'Could not save connection policy',
      'plugins.channels.surface.saveFailedDescription': 'The Account policy was not saved. Refresh connection details before trying again.',
      'plugins.channels.surface.saveUnknownTitle': 'Could not confirm the save',
      'plugins.channels.surface.saveUnknownDescription': 'The update may already be saved. Refresh connection details before making another change.',
      'plugins.channels.surface.saving': 'Saving…',
      'plugins.channels.surface.save': 'Save changes',
      'plugins.channels.surface.deleteTitle': 'Delete connection',
      'plugins.channels.surface.deleteDescription': 'Disable this connection and wait for exact transport-stop proof before cleanup.',
      'plugins.channels.surface.delete': 'Delete connection',
      'plugins.channels.surface.deleting': 'Deleting…',
      'plugins.channels.surface.connectionDeleted': 'Connection deleted.',
      'plugins.channels.surface.deleteStopPendingTitle': 'Waiting for transport stop',
      'plugins.channels.surface.deleteStopPendingDescription': 'Deletion is waiting for exact proof that the transport stopped. You can keep waiting, or accept possible message loss to continue cleanup.',
      'plugins.channels.surface.acceptPossibleLoss': 'Accept possible loss',
      'plugins.channels.surface.acceptingPossibleLoss': 'Accepting…',
      'plugins.channels.surface.deleteFinalizingDescription': 'Deletion cleanup is in progress. This connection will disappear after cleanup finishes.',
      'plugins.channels.surface.deleteFailedTitle': 'Could not start connection deletion',
      'plugins.channels.surface.acceptLossFailedTitle': 'Could not accept possible loss',
      'plugins.channels.surface.deleteFailedDescription': 'Happier reread the current connection details. Review its status before trying again.',
      'plugins.channels.surface.deleteUnknownTitle': 'Could not confirm the deletion request',
      'plugins.channels.surface.deleteUnknownDescription': 'The request may already be saved. Refresh connection details before making another change.',
      'plugins.channels.surface.loadingTitle': 'Loading conversation connections',
      'plugins.channels.surface.loadingDescription': 'Reading the current connection policy from your Account.',
      'plugins.channels.surface.errorTitle': 'Connection details are unavailable',
      'plugins.channels.surface.errorDescription': 'Refresh to try reading the current Account connection policy again.',
      'plugins.channels.surface.emptyTitle': 'No conversation connections yet',
      'plugins.channels.surface.emptyDescription': 'Connections created for this Account will appear here.',
      'plugins.channels.surface.resourceContentTypeInvalid': 'The connection Resource did not return JSON.',
      'plugins.channels.surface.resourceInvalidJson': 'The connection Resource could not be read.',
      'plugins.channels.surface.resourceShapeInvalid': 'The connection Resource has an unexpected shape.',
      'plugins.channels.surface.resourceConnectionInvalid': 'The connection Resource contains an invalid connection.',
    },
  }],
};

/**
 * The Channels core owns durable Account state and the strict caller-filtered
 * provider reconciliation Actions. Its management Resource projects only
 * safe local Account facts; provider list/read remain the reconciliation
 * authority and do not consume this Resource.
 */
export const PLUGIN_MANIFEST: PluginManifest = {
  schemaVersion: 2,
  id: CHANNELS_PLUGIN_ID,
  version: '0.0.0',
  displayName: 'Conversation Channels',
  description: 'Connects external conversations to Happier sessions and automations.',
  engines: { happier: '^0.0.0' },
  runtime: { apiVersion: 1 },
  entrypoints: { daemon: './dist/index.js' },
  hostAccess: {
    required: [{
      id: 'account-storage',
      capability: 'storage.account',
      reason: 'Read current Channel connection and binding state.',
      scope: { enabled: true },
    }],
    optional: [],
  },
  contributes: {
    accountCollections: [...CHANNEL_ACCOUNT_COLLECTION_DECLARATIONS],
    pluginContributionPoints:
      CHANNELS_PROVIDER_POINT_DEFINITION.manifest.contributes.pluginContributionPoints,
    resources: [
      {
        id: 'connections-v1',
        source: 'dynamic',
        kind: 'config',
        contentType: 'application/json',
        maxBytes: 196_608,
        hostAccess: ['account-storage'],
      },
      {
        id: 'bindings-v1',
        source: 'dynamic',
        kind: 'config',
        contentType: 'application/json',
        maxBytes: 212_992,
        hostAccess: ['account-storage'],
      },
      {
        id: 'pairing-v1',
        source: 'dynamic',
        kind: 'config',
        contentType: 'application/json',
        maxBytes: 524_288,
        hostAccess: ['account-storage'],
      },
      {
        id: 'outward-delivery-activities-v1',
        source: 'dynamic',
        kind: 'config',
        scope: 'session',
        contentType: 'application/vnd.happier.transcript-activity+json;v=1',
        maxBytes: 64 * 1024,
        hostAccess: ['account-storage'],
      },
    ],
    transcriptActivities: [{
      id: 'outward-delivery',
      resourceId: 'outward-delivery-activities-v1',
      actions: [],
    }],
    ui: CHANNELS_UI,
    actions: [
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionPairingCreate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionPairingCreate,
        title: 'Create conversation pairing challenge',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Create conversation pairing challenge?',
          body: 'This creates a short-lived pairing challenge for the selected connection.',
          confirmLabel: 'Create challenge',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionPairingFinalize,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionPairingFinalize,
        title: 'Finalize conversation pairing',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Finalize conversation pairing?',
          body: 'This saves the authenticated pairing proposal as a paused conversation binding.',
          confirmLabel: 'Finalize pairing',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionPairingCancel,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionPairingCancel,
        title: 'Cancel conversation pairing',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['secondary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Cancel conversation pairing?',
          body: 'This cancels the selected unfinished pairing challenge or proposal.',
          confirmLabel: 'Cancel pairing',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionCreate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionCreate,
        title: 'Create conversation connection',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Create conversation connection?',
          body: 'This saves the connection and its current transport configuration to this Happier Account.',
          confirmLabel: 'Create connection',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionTransfer,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionTransfer,
        title: 'Transfer conversation connection',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Transfer conversation connection?',
          body: 'This replaces the saved provider setup and transport while retaining exact old-stop custody.',
          confirmLabel: 'Transfer connection',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionPrepare,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionPrepare,
        title: 'Prepare conversation connection',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'safe',
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionUpdate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionUpdate,
        title: 'Update conversation connection',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Update conversation connection?',
          body: 'This saves the edited connection policy to this Happier Account.',
          confirmLabel: 'Update connection',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionSetEnabled,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionSetEnabled,
        title: 'Set conversation connection enabled state',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Change conversation connection enabled state?',
          body: 'This changes whether the connection may accept or deliver under its saved Account policy.',
          confirmLabel: 'Save connection state',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionDelete,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionDelete,
        title: 'Delete conversation connection',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Delete conversation connection?',
          body: 'This disables the connection and waits for exact transport-stop proof before cleanup.',
          confirmLabel: 'Delete connection',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionAbandon,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionAbandon,
        title: 'Abandon pending conversation connection stop',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['secondary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Accept possible message loss?',
          body: 'This permits the connection lifecycle to continue without claiming the old physical transport stopped.',
          confirmLabel: 'Accept possible loss',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.streamBaselineAccept,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.streamBaselineAccept,
        title: 'Accept conversation history baseline',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Accept a new conversation history baseline?',
          body: 'This accepts the provider’s current replay baseline and resumes the saved connection without replaying unavailable history.',
          confirmLabel: 'Accept baseline',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.connectionPollRetry,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.connectionPollRetry,
        title: 'Retry blocked conversation poll',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Retry this blocked conversation poll?',
          body: 'This clears the saved blocked poll state so the current connection can retry it.',
          confirmLabel: 'Retry poll',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingRead,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingRead,
        title: 'Read conversation binding',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['secondary'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingResolve,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingResolve,
        title: 'Resolve conversation binding candidates',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['secondary'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingCreate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingCreate,
        title: 'Create conversation binding',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Create conversation binding?',
          body: 'This saves the external conversation binding and its target policy to this Happier Account.',
          confirmLabel: 'Create binding',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingUpdate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingUpdate,
        title: 'Update conversation binding',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Update conversation binding?',
          body: 'This saves the edited external conversation binding policy to this Happier Account.',
          confirmLabel: 'Update binding',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingSetEnabled,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingSetEnabled,
        title: 'Set conversation binding enabled state',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Change conversation binding enabled state?',
          body: 'This changes whether the binding may route eligible external messages to its saved target.',
          confirmLabel: 'Save binding state',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingDelete,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingDelete,
        title: 'Delete conversation binding',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Delete conversation binding?',
          body: 'This immediately disables new binding effects while retained ingress and delivery custody finish safely.',
          confirmLabel: 'Delete binding',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.bindingTargetRotate,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.bindingTargetRotate,
        title: 'Rotate conversation binding target',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Rotate conversation binding target?',
          body: 'This changes the external conversation target and verifies the current Automation template when applicable.',
          confirmLabel: 'Rotate target',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.ingressRetry,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.ingressRetry,
        title: 'Retry blocked conversation ingress',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Retry this blocked conversation input?',
          body: 'This re-enables the same frozen admission request for bounded retry.',
          confirmLabel: 'Retry input',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_MANAGEMENT_ACTION_IDS_V1.deliveryResolve,
        ...CONVERSATION_MANAGEMENT_ACTION_DECLARATIONS_V1.deliveryResolve,
        title: 'Resolve ambiguous conversation delivery',
        scopes: ['global'],
        surfaces: ['cli', 'ui'],
        placementBindings: ['primary'],
        dangerLevel: 'writesLocal',
        confirmation: {
          title: 'Record this delivery decision?',
          body: 'This records whether you accept or discard the current delivery outcome. It does not resend the message.',
          confirmLabel: 'Record decision',
        },
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1.observationIngest,
        ...CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1.observationIngest,
        title: 'Ingest authenticated provider observation',
        scopes: ['global'],
        surfaces: ['plugin'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1.connectionsList,
        ...CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1.connectionsList,
        title: 'List current provider connections',
        scopes: ['global'],
        surfaces: ['plugin'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1.connectionRead,
        ...CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1.connectionRead,
        title: 'Read current provider connection',
        scopes: ['global'],
        surfaces: ['plugin'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1.transportFactReport,
        ...CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1.transportFactReport,
        title: 'Report current transport fact',
        scopes: ['global'],
        surfaces: ['plugin'],
        dangerLevel: 'safe',
        hostAccess: ['account-storage'],
      },
      {
        id: CONVERSATION_CORE_PROVIDER_ACTION_IDS_V1.automationResultDeliver,
        ...CONVERSATION_CORE_PROVIDER_ACTION_DECLARATIONS_V1.automationResultDeliver,
        title: 'Accept Automation result delivery custody',
        scopes: ['global'],
        surfaces: ['plugin'],
        dangerLevel: 'writesLocal',
        hostAccess: ['account-storage'],
      },
    ],
    // Socket services remain provider-owned. The core owns the two persisted
    // work families: checkpointed ingress and retained outward delivery.
    backgroundServices: [
      {
        id: 'ingress-supervisor',
        title: 'Conversation ingress supervisor',
      },
      {
        id: 'outward-delivery-supervisor',
        title: 'Conversation outward delivery supervisor',
      },
    ],
  },
} satisfies PluginManifest;
