// `/v1/features` returns:
// - `features`: catalog feature gates (enablement only; derived-path `...enabled` bits)
// - `capabilities`: configuration/status details used by clients (not themselves catalog feature gates)

export { OAuthProviderStatusSchema, type OAuthProviderStatus } from './features/payload/oauthProviderStatus.js';
export { FeatureGateSchema, type FeatureGate } from './features/payload/featureGate.js';

export {
  BugReportsCapabilitiesSchema,
  BUG_REPORT_DEFAULT_ACCEPTED_ARTIFACT_KINDS,
  BUG_REPORT_DEFAULT_CONTEXT_WINDOW_MS,
  DEFAULT_BUG_REPORTS_CAPABILITIES,
  coerceBugReportsCapabilitiesFromFeaturesPayload,
  type BugReportsCapabilities,
} from './features/payload/capabilities/bugReportsCapabilities.js';

export {
  VoiceCapabilitiesSchema,
  DEFAULT_VOICE_CAPABILITIES,
  type VoiceCapabilities,
} from './features/payload/capabilities/voiceCapabilities.js';

export {
  DEFAULT_PETS_CAPABILITIES,
  DEFAULT_PETS_PACKAGE_LIMITS_CAPABILITIES,
  PetsCapabilitiesSchema,
  PetsPackageLimitsCapabilitiesSchema,
  type PetsCapabilities,
  type PetsPackageLimitsCapabilities,
} from './features/payload/capabilities/petsCapabilities.js';

export {
  SocialFriendsCapabilitiesSchema,
  DEFAULT_SOCIAL_FRIENDS_CAPABILITIES,
  type SocialFriendsCapabilities,
} from './features/payload/capabilities/socialFriendsCapabilities.js';

export {
  AuthCapabilitiesSchema,
  DEFAULT_AUTH_CAPABILITIES,
  type AuthCapabilities,
} from './features/payload/capabilities/authCapabilities.js';
export {
  DEFAULT_MACHINE_TRANSFER_CAPABILITIES,
  DEFAULT_MACHINE_TRANSFER_SERVER_ROUTED_CAPABILITIES,
  DEFAULT_MACHINE_TRANSFER_SERVER_ROUTED_MAX_BYTES,
  MACHINE_TRANSFER_SERVER_ROUTED_MAX_BYTES_ENV_KEY,
  MACHINE_TRANSFER_SERVER_ROUTED_MAX_BYTES_HARD_MAX,
  MachineTransferCapabilitiesSchema,
  MachineTransferServerRoutedCapabilitiesSchema,
  normalizeMachineTransferServerRoutedMaxBytes,
  readMachineTransferServerRoutedMaxBytes,
  type MachineTransferCapabilities,
  type MachineTransferServerRoutedCapabilities,
} from './features/payload/capabilities/machineTransferCapabilities.js';
export {
  DEFAULT_MACHINE_TUNNEL_CAPABILITIES,
  DEFAULT_MACHINE_TUNNEL_DIRECT_ALLOWED_PORTS,
  DEFAULT_MACHINE_TUNNEL_DIRECT_PEER_CAPABILITIES,
  DEFAULT_MACHINE_TUNNEL_MAX_DURATION_MS,
  DEFAULT_MACHINE_TUNNEL_MAX_IDLE_MS,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_CAPABILITIES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_ALLOW_V1_FALLBACK,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_ACTIVE_TUNNELS_PER_SOCKET,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_AGGREGATE_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_BINARY_HEADER_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_BYTES_PER_SUBSTREAM,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_CONCURRENT_SUBSTREAMS,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_FRAME_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_FRAMED_MESSAGE_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_RAW_PAYLOAD_BYTES,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_SESSION_IDLE_MS,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_SUBSTREAM_IDLE_MS,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_MAX_TOTAL_SUBSTREAMS,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_PREFERRED_ENCODING,
  DEFAULT_MACHINE_TUNNEL_SERVER_ROUTED_SUPPORTED_ENCODINGS,
  DEFAULT_MACHINE_TUNNEL_SUBSTREAM_CAPABILITIES,
  MACHINE_TUNNEL_SERVER_ROUTED_MAX_ACTIVE_TUNNELS_PER_SOCKET_HARD_MAX,
  MACHINE_TUNNEL_SERVER_ROUTED_MAX_BYTES_HARD_MAX,
  MACHINE_TUNNEL_SERVER_ROUTED_MAX_FRAME_BYTES_HARD_MAX,
  MACHINE_TUNNEL_SERVER_ROUTED_MAX_SUBSTREAMS_HARD_MAX,
  MachineTunnelCapabilitiesSchema,
  MachineTunnelDirectPeerCapabilitiesSchema,
  MachineTunnelServerRoutedCapabilitiesSchema,
  MachineTunnelSubstreamCapabilitiesSchema,
  normalizeMachineTunnelAllowedPorts,
  normalizeMachineTunnelPositiveInt,
  normalizeMachineTunnelPreferredEncoding,
  normalizeMachineTunnelSupportedEncodings,
  type MachineTunnelCapabilities,
  type MachineTunnelDirectPeerCapabilities,
  type MachineTunnelServerRoutedCapabilities,
  type MachineTunnelSubstreamCapabilities,
} from './features/payload/capabilities/machineTunnelCapabilities.js';
export {
  DEFAULT_MACHINE_LIVE_STREAM_CAPABILITIES,
  DEFAULT_MACHINE_LIVE_STREAM_SERVER_ROUTED_CAPABILITIES,
  MachineLiveStreamCapabilitiesSchema,
  MachineLiveStreamRelayDisabledReasonSchema,
  MachineLiveStreamServerRoutedCapabilitiesSchema,
  readMachineLiveStreamRelayCaps,
  type MachineLiveStreamCapabilities,
  type MachineLiveStreamRelayDisabledReason,
  type MachineLiveStreamServerRoutedCapabilities,
} from './features/payload/capabilities/machineLiveStreamCapabilities.js';
export {
  DEFAULT_PEER_MEDIATION_CAPABILITIES,
  DEFAULT_PEER_MEDIATION_OBSERVABILITY_CAPABILITIES,
  DEFAULT_PEER_MEDIATION_OBSERVABILITY_RETENTION_CAPABILITIES,
  DEFAULT_PEER_MEDIATION_OBSERVABILITY_SAMPLING_CAPABILITIES,
  PeerMediationCapabilitiesSchema,
  PeerMediationGrantSigningKeyCapabilitySchema,
  PeerMediationObservabilityCapabilitiesSchema,
  PeerMediationObservabilityRetentionCapabilitiesSchema,
  PeerMediationObservabilitySamplingCapabilitiesSchema,
  type PeerMediationCapabilities,
  type PeerMediationGrantSigningKeyCapability,
  type PeerMediationObservabilityCapabilities,
  type PeerMediationObservabilityRetentionCapabilities,
  type PeerMediationObservabilitySamplingCapabilities,
} from './features/payload/capabilities/peerMediationCapabilities.js';
export {
  BrowserAutomationActionKindCapabilitiesSchema,
  BrowserAutomationCapabilitiesSchema,
  BrowserAutomationEvalCapabilitiesSchema,
  BrowserAutomationFidelityCapabilitiesSchema,
  BrowserAutomationInjectedPageCapabilitiesSchema,
  BrowserAutomationTimelineCapabilitiesSchema,
  BrowserCapabilitiesSchema,
  BrowserContextCapabilitiesSchema,
  BrowserContextScreenshotCapabilitiesSchema,
  BrowserContextTextCapabilitiesSchema,
  BrowserDiagnosticsCapabilitiesSchema,
  BrowserDiagnosticsRetentionCapabilitiesSchema,
  BrowserInternalCapabilitiesSchema,
  BrowserRecordingCapabilitiesSchema,
  BrowserSidecarCapabilitiesSchema,
  BrowserViewTargetCapabilitiesSchema,
  DEFAULT_BROWSER_AUTOMATION_CAPABILITIES,
  DEFAULT_BROWSER_AUTOMATION_EVAL_CAPABILITIES,
  DEFAULT_BROWSER_AUTOMATION_INJECTED_PAGE_CAPABILITIES,
  DEFAULT_BROWSER_AUTOMATION_TIMELINE_CAPABILITIES,
  DEFAULT_BROWSER_CAPABILITIES,
  DEFAULT_BROWSER_CONTEXT_CAPABILITIES,
  DEFAULT_BROWSER_CONTEXT_SCREENSHOT_CAPABILITIES,
  DEFAULT_BROWSER_CONTEXT_TEXT_CAPABILITIES,
  DEFAULT_BROWSER_DIAGNOSTICS_CAPABILITIES,
  DEFAULT_BROWSER_DIAGNOSTICS_RETENTION_CAPABILITIES,
  DEFAULT_BROWSER_INTERNAL_CAPABILITIES,
  DEFAULT_BROWSER_RECORDING_CAPABILITIES,
  DEFAULT_BROWSER_SIDECAR_CAPABILITIES,
  DEFAULT_BROWSER_VIEW_TARGET_CAPABILITIES,
  type BrowserAutomationActionKindCapabilities,
  type BrowserAutomationCapabilities,
  type BrowserAutomationEvalCapabilities,
  type BrowserAutomationFidelityCapabilities,
  type BrowserAutomationInjectedPageCapabilities,
  type BrowserAutomationTimelineCapabilities,
  type BrowserCapabilities,
  type BrowserContextCapabilities,
  type BrowserContextScreenshotCapabilities,
  type BrowserContextTextCapabilities,
  type BrowserDiagnosticsCapabilities,
  type BrowserDiagnosticsRetentionCapabilities,
  type BrowserInternalCapabilities,
  type BrowserRecordingCapabilities,
  type BrowserSidecarCapabilities,
  type BrowserViewTargetCapabilities,
} from './features/payload/capabilities/browserCapabilities.js';
export {
  DEFAULT_DEVICE_CAPABILITIES,
  DEFAULT_DEVICE_SIMULATOR_PREVIEW_CAPABILITIES,
  DeviceCapabilitiesSchema,
  DeviceSimulatorPreviewCapabilitiesSchema,
  type DeviceCapabilities,
  type DeviceSimulatorPreviewCapabilities,
} from './features/payload/capabilities/deviceCapabilities.js';
export {
  DEFAULT_LOCAL_SERVICE_ACTION_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_ACTION_GRACEFUL_TIMEOUT_MS,
  DEFAULT_LOCAL_SERVICE_ACTION_VERIFICATION_TIMEOUT_MS,
  DEFAULT_LOCAL_SERVICE_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_INVENTORY_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_INVENTORY_REFRESH_INTERVAL_MS,
  DEFAULT_LOCAL_SERVICE_INVENTORY_STALE_AFTER_MS,
  DEFAULT_LOCAL_SERVICE_LAUNCHER_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_LAUNCHER_RECENT_HISTORY_MAX_ENTRIES,
  DEFAULT_LOCAL_SERVICE_LAUNCHER_SCRIPT_DISCOVERY_MAX_DEPTH,
  DEFAULT_LOCAL_SERVICE_LAUNCHER_SCRIPT_DISCOVERY_MAX_SCRIPTS,
  DEFAULT_LOCAL_SERVICE_MANAGED_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_MANAGED_MAX_SERVICES_PER_OWNER,
  DEFAULT_LOCAL_SERVICE_MANAGED_PORT_RANGE_END,
  DEFAULT_LOCAL_SERVICE_MANAGED_PORT_RANGE_START,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_CONCURRENCY,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_FAILURE_TTL_MS,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_MAX_BODY_BYTES,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_SUCCESS_TTL_MS,
  DEFAULT_LOCAL_SERVICE_PAGE_TITLE_TIMEOUT_MS,
  DEFAULT_LOCAL_SERVICE_PREVIEW_CAPABILITIES,
  DEFAULT_LOCAL_SERVICE_PREVIEW_MAX_REQUEST_BODY_BYTES,
  DEFAULT_LOCAL_SERVICE_PREVIEW_MAX_RESPONSE_BODY_BYTES,
  DEFAULT_LOCAL_SERVICE_PREVIEW_TOKEN_TTL_MS,
  DEFAULT_LOCAL_SERVICE_PUBLIC_CAPABILITIES,
  LocalServiceActionCapabilitiesSchema,
  LocalServiceCapabilitiesSchema,
  LocalServiceInventoryCapabilitiesSchema,
  LocalServiceLauncherCapabilitiesSchema,
  LocalServiceManagedCapabilitiesSchema,
  LocalServicePageTitleCapabilitiesSchema,
  LocalServicePreviewCapabilitiesSchema,
  LocalServicePublicCapabilitiesSchema,
  type LocalServiceActionCapabilities,
  type LocalServiceCapabilities,
  type LocalServiceInventoryCapabilities,
  type LocalServiceLauncherCapabilities,
  type LocalServiceManagedCapabilities,
  type LocalServicePageTitleCapabilities,
  type LocalServicePreviewCapabilities,
  type LocalServicePublicCapabilities,
} from './features/payload/capabilities/localServiceCapabilities.js';

export {
  DEFAULT_SERVER_IDENTITY_CAPABILITIES,
  SERVER_IDENTITY_ID_PATTERN,
  ServerIdentityCapabilitiesSchema,
  normalizeServerIdentityIdCapability,
  type ServerIdentityCapabilities,
} from './features/payload/capabilities/serverIdentityCapabilities.js';

export {
  DEFAULT_SHARING_CAPABILITIES,
  DEFAULT_SHARING_PENDING_QUEUE_V2_CAPABILITIES,
  SharingCapabilitiesSchema,
  SharingPendingQueueV2CapabilitiesSchema,
  type SharingCapabilities,
  type SharingPendingQueueV2Capabilities,
} from './features/payload/capabilities/sharingCapabilities.js';

export {
  DEFAULT_SESSION_CAPABILITIES,
  DEFAULT_SESSION_MESSAGES_CAPABILITIES,
  SessionCapabilitiesSchema,
  SessionMessagesCapabilitiesSchema,
  type SessionCapabilities,
  type SessionMessagesCapabilities,
} from './features/payload/capabilities/sessionCapabilities.js';

export { CapabilitiesSchema, type Capabilities } from './features/payload/capabilities/capabilitiesSchema.js';
export {
  ConnectedServicesCapabilitiesSchema,
  ConnectedServicesCredentialDeleteCapabilitiesSchema,
  ConnectedServicesQualifiedAccountsCapabilitiesSchema,
  DEFAULT_CONNECTED_SERVICES_CAPABILITIES,
  DEFAULT_CONNECTED_SERVICES_CREDENTIAL_DELETE_CAPABILITIES,
  type ConnectedServicesCapabilities,
} from './features/payload/capabilities/connectedServicesCapabilities.js';
export { FeatureGatesSchema, type FeatureGates } from './features/payload/featureGatesSchema.js';
export { FeaturesResponseSchema, type FeaturesResponse } from './features/payload/featuresResponseSchema.js';
