export const HAPPY_PROTOCOL_PACKAGE = '@happier-dev/protocol';

export { SPAWN_SESSION_ERROR_CODES, type SpawnSessionErrorCode, type SpawnSessionResult } from './spawnSession.js';
export {
  RPC_ERROR_CODES,
  RPC_ERROR_MESSAGES,
  RPC_METHODS,
  isRpcMethodNotFoundResult,
  type RpcErrorCode,
  type RpcMethod,
} from './rpc.js';
export {
  createRpcCallError,
  isRpcMethodNotAvailableError,
  isRpcMethodNotFoundError,
  readRpcErrorCode,
  type RpcErrorCarrier,
} from './rpcErrors.js';
export { CHECKLIST_IDS, resumeChecklistId, type ChecklistId } from './checklists.js';
export { SOCKET_RPC_EVENTS, type SocketRpcEvent } from './socketRpc.js';
export {
  ChangeEntrySchema,
  ChangeKindSchema,
  ChangesResponseSchema,
  CursorGoneErrorSchema,
  type ChangeEntry,
  type ChangeKind,
  type ChangesResponse,
  type CursorGoneError,
} from './changes.js';
export {
  type CapabilitiesDescribeResponse,
  type CapabilitiesDetectRequest,
  type CapabilitiesDetectResponse,
  type CapabilitiesInvokeRequest,
  type CapabilitiesInvokeResponse,
  type CapabilityDescriptor,
  type CapabilityDetectRequest,
  type CapabilityDetectResult,
  type CapabilityId,
  type CapabilityKind,
} from './capabilities.js';

export {
  EphemeralUpdateSchema,
  MessageAckResponseSchema,
  SessionBroadcastBodySchema,
  SessionBroadcastContainerSchema,
  UpdateBodySchema,
  UpdateContainerSchema,
  UpdateMetadataAckResponseSchema,
  UpdateStateAckResponseSchema,
  type EphemeralUpdate,
  type MessageAckResponse,
  type SessionBroadcastBody,
  type SessionBroadcastContainer,
  type UpdateBody,
  type UpdateContainer,
  type UpdateMetadataAckResponse,
  type UpdateStateAckResponse,
} from './updates.js';

export { SENT_FROM_VALUES, SentFromSchema, type SentFrom } from './sentFrom.js';
export {
  SCM_COMMIT_MESSAGE_MAX_LENGTH,
  SCM_COMMIT_PATCH_MAX_COUNT,
  SCM_COMMIT_PATCH_MAX_LENGTH,
  SCM_OPERATION_ERROR_CODES,
  ScmBackendDescribeRequestSchema,
  ScmBackendDescribeResponseSchema,
  ScmBackendIdSchema,
  ScmBackendPreferenceSchema,
  ScmCapabilitiesSchema,
  ScmChangeApplyRequestSchema,
  ScmChangeApplyResponseSchema,
  ScmCommitBackoutRequestSchema,
  ScmCommitBackoutResponseSchema,
  ScmCommitPatchSchema,
  ScmCommitCreateRequestSchema,
  ScmCommitCreateResponseSchema,
  ScmDiffAreaSchema,
  ScmDiffCommitRequestSchema,
  ScmDiffCommitResponseSchema,
  ScmDiffFileRequestSchema,
  ScmDiffFileResponseSchema,
  ScmEntryKindSchema,
  ScmLogEntrySchema,
  ScmLogListRequestSchema,
  ScmLogListResponseSchema,
  ScmOperationErrorCodeSchema,
  ScmPathStatsSchema,
  ScmRemoteRequestSchema,
  ScmRemoteResponseSchema,
  classifyScmOperationErrorCode,
  evaluateScmRemoteMutationPolicy,
  hasAnyPendingScmChanges,
  inferScmRemoteTarget,
  isScmPatchBoundToPath,
  mapGitScmErrorCode,
  mapSaplingScmErrorCode,
  normalizeScmRemoteRequest,
  parseScmPatchPaths,
  parseScmUpstreamRef,
  ScmRepoModeSchema,
  ScmRequestBaseSchema,
  ScmStatusSnapshotRequestSchema,
  ScmStatusSnapshotResponseSchema,
  ScmWorkingEntrySchema,
  ScmWorkingSnapshotSchema,
  type ScmBackendDescribeRequest,
  type ScmBackendDescribeResponse,
  type ScmBackendId,
  type ScmBackendPreference,
  type ScmCapabilities,
  type ScmChangeApplyRequest,
  type ScmChangeApplyResponse,
  type ScmCommitBackoutRequest,
  type ScmCommitBackoutResponse,
  type ScmCommitPatch,
  type ScmCommitCreateRequest,
  type ScmCommitCreateResponse,
  type ScmDiffArea,
  type ScmDiffCommitRequest,
  type ScmDiffCommitResponse,
  type ScmDiffFileRequest,
  type ScmDiffFileResponse,
  type ScmEntryKind,
  type ScmLogEntry,
  type ScmLogListRequest,
  type ScmLogListResponse,
  type ScmOperationErrorCode,
  type ScmOperationErrorCategory,
  type ScmPathStats,
  type ScmRemoteMutationKind,
  type ScmRemoteMutationPolicy,
  type ScmRemoteMutationReason,
  type ScmRemoteMutationResult,
  type ScmRemoteMutationSnapshot,
  type ScmRemoteRequest,
  type ScmRemoteResponse,
  type ScmRemoteTarget,
  type ScmRepoMode,
  type ScmRequestBase,
  type ScmStatusSnapshotRequest,
  type ScmStatusSnapshotResponse,
  type ScmWorkingEntry,
  type ScmWorkingSnapshot,
} from './scm.js';
export {
  resolveScmScopedChangedPaths,
  scmPathMatchesScopePath,
} from './scmPathScope.js';
export {
  createGitScmCapabilities,
  createSaplingScmCapabilities,
  createScmCapabilities,
} from './scmCapabilities.js';

export {
  VOICE_MEDIATOR_ERROR_CODES,
  VoiceMediatorAgentSourceSchema,
  VoiceMediatorPermissionPolicySchema,
  VoiceMediatorStartRequestSchema,
  VoiceMediatorStartResponseSchema,
  VoiceMediatorSendTurnRequestSchema,
  VoiceMediatorSendTurnResponseSchema,
  VoiceMediatorTurnStreamStartRequestSchema,
  VoiceMediatorTurnStreamStartResponseSchema,
  VoiceMediatorTurnStreamReadRequestSchema,
  VoiceMediatorTurnStreamReadResponseSchema,
  VoiceMediatorTurnStreamCancelRequestSchema,
  VoiceMediatorTurnStreamCancelResponseSchema,
  VoiceMediatorTurnStreamEventSchema,
  VoiceMediatorTurnStreamEventDeltaSchema,
  VoiceMediatorTurnStreamEventDoneSchema,
  VoiceMediatorTurnStreamEventErrorSchema,
  VoiceMediatorCommitRequestSchema,
  VoiceMediatorCommitResponseSchema,
  VoiceMediatorStopRequestSchema,
  VoiceMediatorStopResponseSchema,
  VoiceMediatorGetModelsRequestSchema,
  VoiceMediatorGetModelsResponseSchema,
  VoiceMediatorVerbositySchema,
  type VoiceMediatorErrorCode,
  type VoiceMediatorAgentSource,
  type VoiceMediatorPermissionPolicy,
  type VoiceMediatorVerbosity,
  type VoiceMediatorStartRequest,
  type VoiceMediatorStartResponse,
  type VoiceMediatorSendTurnRequest,
  type VoiceMediatorSendTurnResponse,
  type VoiceMediatorTurnStreamStartRequest,
  type VoiceMediatorTurnStreamStartResponse,
  type VoiceMediatorTurnStreamReadRequest,
  type VoiceMediatorTurnStreamReadResponse,
  type VoiceMediatorTurnStreamCancelRequest,
  type VoiceMediatorTurnStreamCancelResponse,
  type VoiceMediatorTurnStreamEvent,
  type VoiceMediatorTurnStreamEventDelta,
  type VoiceMediatorTurnStreamEventDone,
  type VoiceMediatorTurnStreamEventError,
  type VoiceMediatorCommitRequest,
  type VoiceMediatorCommitResponse,
  type VoiceMediatorStopRequest,
  type VoiceMediatorStopResponse,
  type VoiceMediatorGetModelsRequest,
  type VoiceMediatorGetModelsResponse,
  type VoiceMediatorModel,
} from './voiceMediator.js';

export {
  VOICE_ACTIONS_BLOCK,
  VoiceAssistantActionSchema,
  extractVoiceActionsFromAssistantText,
  type VoiceAssistantAction,
} from './voiceActions.js';

// Tool normalization (V2)
export * from './tools/v2/index.js';

// Provider E2E specs (used by `@happier-dev/tests` to run real provider contract matrix)
export { E2eCliProviderSpecV1Schema, type E2eCliProviderSpecV1 } from './e2e/providerSpec.js';
export {
  E2eCliProviderScenarioRegistryV1Schema,
  type E2eCliProviderScenarioRegistryV1,
} from './e2e/providerScenarios.js';

// Diff helpers
export { splitUnifiedDiffByFile } from './diff/splitUnifiedDiffByFile.js';

// Happier server feature discovery + social contracts
export {
  BUG_REPORT_DEFAULT_ACCEPTED_ARTIFACT_KINDS,
  BugReportsFeatureSchema,
  DEFAULT_BUG_REPORTS_FEATURE,
  FeaturesResponseSchema,
  OAuthProviderStatusSchema,
  coerceBugReportsFeatureFromFeaturesPayload,
  type BugReportsFeature,
  type FeaturesResponse,
  type OAuthProviderStatus,
} from './features.js';
export {
  FEATURE_CATALOG,
  FEATURE_IDS,
  isFeatureId,
  type FeatureCatalogEntry,
  type FeatureFailMode,
  type FeatureId,
} from './features/catalog.js';
export {
  FeatureAxisSchema,
  FeatureBlockerCodeSchema,
  FeatureDecisionSchema,
  FeatureDecisionScopeSchema,
  FeatureStateSchema,
  createFeatureDecision,
  type FeatureAxis,
  type FeatureBlockerCode,
  type FeatureDecision,
  type FeatureDecisionScope,
  type FeatureState,
} from './features/decision.js';
export {
  evaluateFeatureBuildPolicy,
  parseFeatureBuildPolicy,
  type FeatureBuildPolicy,
  type FeatureBuildPolicyEvaluation,
} from './features/buildPolicy.js';
export {
  RelationshipStatusSchema,
  type RelationshipStatus,
  UserProfileSchema,
  type UserProfile,
  UserResponseSchema,
  type UserResponse,
  FriendsResponseSchema,
  type FriendsResponse,
  UsersSearchResponseSchema,
  type UsersSearchResponse,
  RelationshipUpdatedEventSchema,
  type RelationshipUpdatedEvent,
} from './social/friends.js';

export {
  AccountProfileSchema,
  AccountProfileResponseSchema,
  LinkedProviderSchema,
  type AccountProfile,
  type AccountProfileResponse,
  type LinkedProvider,
} from './account/profile.js';

export { ProfileBadgeSchema, type ProfileBadge } from './common/profileBadge.js';

// Auth provider registry + shared auth error codes
export { AuthProviderIdSchema, type AuthProviderId } from './auth/providers.js';
export { AUTH_ERROR_CODES, AuthErrorCodeSchema, type AuthErrorCode } from './auth/errors.js';
export {
  ExternalOAuthErrorResponseSchema,
  ExternalOAuthFinalizeAuthRequestSchema,
  ExternalOAuthFinalizeAuthSuccessResponseSchema,
  ExternalOAuthFinalizeConnectRequestSchema,
  ExternalOAuthFinalizeConnectSuccessResponseSchema,
  ExternalOAuthParamsResponseSchema,
  type ExternalOAuthErrorResponse,
  type ExternalOAuthFinalizeAuthRequest,
  type ExternalOAuthFinalizeAuthSuccessResponse,
  type ExternalOAuthFinalizeConnectRequest,
  type ExternalOAuthFinalizeConnectSuccessResponse,
  type ExternalOAuthParamsResponse,
} from './auth/externalOAuth.js';

export {
  BUG_REPORT_DEFAULT_ISSUE_OWNER,
  BUG_REPORT_DEFAULT_ISSUE_REPO,
  BUG_REPORT_DEFAULT_ISSUE_LABELS,
  BUG_REPORT_FALLBACK_BODY_TRUNCATION_SUFFIX,
  BUG_REPORT_FALLBACK_ISSUE_URL_MAX_LENGTH,
  BUG_REPORT_FALLBACK_MAX_LABELS,
  BUG_REPORT_FALLBACK_MAX_LABEL_LENGTH,
  buildBugReportFallbackIssueUrl,
  formatBugReportFallbackIssueBody,
  appendBugReportReporterToSummary,
  hasAcceptedBugReportArtifactKind,
  inferBugReportDeploymentTypeFromServerUrl,
  normalizeBugReportGithubUsername,
  normalizeBugReportIssueSlug,
  normalizeBugReportIssueTarget,
  normalizeBugReportProviderUrl,
  normalizeBugReportReproductionSteps,
  pushBugReportArtifact,
  redactBugReportSensitiveText,
  resolveBugReportIssueTargetWithDefaults,
  resolveBugReportServerDiagnosticsLines,
  sanitizeBugReportArtifactFileSegment,
  sanitizeBugReportArtifactPath,
  sanitizeBugReportDaemonDiagnosticsPayload,
  sanitizeBugReportStackContextPayload,
  sanitizeBugReportUrl,
  searchBugReportSimilarIssues,
  submitBugReportToService,
  trimBugReportTextToMaxBytes,
  type BugReportArtifactPayload,
  type BugReportDeploymentType,
  type BugReportEnvironmentPayload,
  type BugReportFormPayload,
  type BugReportFrequency,
  type BugReportSimilarIssue,
  type BugReportMachineDaemonLogLike,
  type BugReportMachineDaemonStateLike,
  type BugReportMachineDiagnosticsLike,
  type BugReportMachineRuntimeLike,
  type BugReportMachineStackContextLike,
  type BugReportServiceSubmitInput,
  type BugReportSeverity,
} from './bugReports.js';
