// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type AccountSecurityActionInputById = {
    readonly "account.security.terminalPresentUser.set": {
        policy: 'allowed' | 'disallowed';
    };
    readonly "account.security.get": Record<string, never>;
    readonly "account.password.enroll": {
        v: 1;
        kind: 'plain';
        email: string;
        targetCredential: {
            v: 1;
            kind: 'plain_password_hash';
            hash: {
                v: 1;
                algorithm: 'scrypt';
                parameters: {
                    n: number;
                    r: 8;
                    p: number;
                    keyLength: 32;
                };
                salt: string;
                digest: string;
            };
        };
        reauthentication: {
            provider: string;
            pending: string;
            proof: string;
        };
        verificationToken?: string | undefined;
    } | {
        v: 1;
        kind: 'e2ee';
        email: string;
        targetCredential: {
            v: 1;
            kind: 'e2ee_password_envelope';
            envelope: {
                v: 1;
                accountSigningPublicKey: string;
                kdf: {
                    algorithm: 'argon2id13';
                    salt: string;
                    opsLimit: number;
                    memLimitBytes: number;
                    outputBytes: 32;
                };
                cipher: {
                    algorithm: 'aes256gcm';
                    nonce: string;
                    ciphertext: string;
                };
            };
            authVerifier: {
                v: 1;
                hash: {
                    v: 1;
                    algorithm: 'scrypt';
                    parameters: {
                        n: number;
                        r: 8;
                        p: number;
                        keyLength: 32;
                    };
                    salt: string;
                    digest: string;
                };
            };
        };
        proof: {
            challengeId: string;
            publicKey: string;
            signature: string;
        };
        verificationToken?: string | undefined;
    };
    readonly "account.password.change": {
        v: 1;
        kind: 'plain';
        expectedCredentialRevision: number;
        currentPassword: string;
        newPassword: string;
    } | {
        v: 1;
        kind: 'e2ee';
        action: 'change' | 'recover';
        expectedCredentialRevision: number;
        targetCredential: {
            v: 1;
            kind: 'e2ee_password_envelope';
            envelope: {
                v: 1;
                accountSigningPublicKey: string;
                kdf: {
                    algorithm: 'argon2id13';
                    salt: string;
                    opsLimit: number;
                    memLimitBytes: number;
                    outputBytes: 32;
                };
                cipher: {
                    algorithm: 'aes256gcm';
                    nonce: string;
                    ciphertext: string;
                };
            };
            authVerifier: {
                v: 1;
                hash: {
                    v: 1;
                    algorithm: 'scrypt';
                    parameters: {
                        n: number;
                        r: 8;
                        p: number;
                        keyLength: 32;
                    };
                    salt: string;
                    digest: string;
                };
            };
        };
        proof: {
            challengeId: string;
            publicKey: string;
            signature: string;
        };
    };
    readonly "account.password.remove": {
        v: 1;
        kind: 'plain';
        expectedCredentialRevision: number;
        currentPassword: string;
    } | {
        v: 1;
        kind: 'e2ee';
        expectedCredentialRevision: number;
        proof: {
            challengeId: string;
            publicKey: string;
            signature: string;
        };
    };
    readonly "account.email.change.request": {
        v: 1;
        email: string;
    };
    readonly "account.encryption.automationTemplates.recover": Record<string, never>;
    readonly "account.encryption.historicalKey.forget": Record<string, never>;
};
export type AccountSecurityActionResultById = {
    readonly "account.security.terminalPresentUser.set": {
        policy: 'allowed' | 'disallowed';
    };
    readonly "account.security.get": {
        v: 1;
        encryptionMode: 'plain' | 'e2ee';
        terminalPresentUserPolicy: 'allowed' | 'disallowed';
        nativeEmail: string | null;
        password: {
            status: 'enrolled';
            revision: number;
        } | {
            status: 'not_enrolled';
            revision: null;
        };
    };
    readonly "account.password.enroll": {
        v: 1;
        status: 'enrolled' | 'updated' | 'removed';
    };
    readonly "account.password.change": {
        v: 1;
        status: 'enrolled' | 'updated' | 'removed';
    };
    readonly "account.password.remove": {
        v: 1;
        status: 'enrolled' | 'updated' | 'removed';
    };
    readonly "account.email.change.request": {
        v: 1;
        status: 'verification_sent';
    };
    readonly "account.encryption.automationTemplates.recover": {
        templates: {
            automationId: string;
            status: 'recovered' | 'already_plain' | 'retained_e2ee' | 'locked' | 'conflict';
        }[];
    };
    readonly "account.encryption.historicalKey.forget": {
        status: 'forgotten' | 'nothing_retained' | 'cancelled';
    };
};
