// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';
import type { InputPredicate, PluginDeclarativeNodeV2, PluginJsonSchemaV2, QualifiedAudienceSelection } from './pluginActionDtoSupport.generated.js';

export type BoardsActionInputById = {
    readonly "boards.list": Record<string, never>;
    readonly "boards.apply": {
        intent: {
            kind: 'widget_move';
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
            toIndex?: number | undefined;
            nativeIndex?: number | undefined;
        } | {
            kind: 'widget_add';
            instance: {
                v: 1;
                id: string;
                definition: {
                    kind: 'installed';
                    surface: {
                        pluginId: string;
                        localId: string;
                    };
                } | {
                    kind: 'builtin';
                    id: string;
                } | {
                    kind: 'artifact';
                    artifactId: string;
                } | {
                    kind: 'inline';
                    definition: {
                        provenance: {
                            source: {
                                kind: 'authored';
                            } | {
                                kind: 'session';
                                serverId: string;
                                sessionId: string;
                                itemId: string;
                            };
                            authorAccountId?: string | undefined;
                            author?: {
                                kind: 'person' | 'agent' | 'plugin';
                            } | undefined;
                            createdAt?: number | undefined;
                        };
                        sizeDeclaration: {
                            sizes: ('small' | 'medium' | 'wide' | 'full' | 'tall' | 'large')[];
                            defaultSize: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                        };
                        name: string;
                        body: {
                            kind: 'declarative';
                            document: unknown;
                        } | {
                            kind: 'installed';
                            surface: {
                                pluginId: string;
                                localId: string;
                            };
                        };
                        inputs: {
                            title?: string | undefined;
                            description?: string | undefined;
                            submitLabel?: string | undefined;
                            fields?: readonly {
                                path: string;
                                widget: 'number' | 'boolean' | 'text' | 'url' | 'secret' | 'textarea' | 'integer' | 'text_list' | 'select' | 'multiselect' | 'json';
                                title: string;
                                inputType?: {
                                    pluginId: string;
                                    localId: string;
                                } | undefined;
                                required?: boolean | undefined;
                                requireExplicitSelection?: boolean | undefined;
                                listSeparator?: 'comma' | 'newline' | undefined;
                                maxSelections?: number | undefined;
                                visibleWhen?: unknown;
                                requiredWhen?: unknown;
                                disabledWhen?: unknown;
                                optionsSourceId?: string | undefined;
                                connectedAccountOptions?: true | undefined;
                                resolvedEmptyConnectedAccountOptions?: true | undefined;
                                description?: string | undefined;
                                placeholder?: string | undefined;
                                options?: readonly {
                                    value: unknown;
                                    label: string;
                                    description?: string | undefined;
                                    disabled?: boolean | undefined;
                                }[] | undefined;
                            }[] | undefined;
                        };
                        inputSchema: unknown;
                        v: 1;
                        id: string;
                        description?: string | undefined;
                        sessionInputPath?: string | undefined;
                        connectedAccountPurposeBindings?: {
                            path: string;
                            purpose: string;
                            consumer: {
                                pluginId: string;
                                localId: string;
                            };
                            nativeServicePath?: string | undefined;
                        }[] | undefined;
                    };
                };
                bindings: Record<string, {
                    kind: 'value';
                    value: unknown;
                } | {
                    kind: 'context';
                    slot: string;
                } | {
                    kind: 'viewer';
                    purpose: string;
                }>;
                displayName?: string | undefined;
            };
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
            size?: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large' | undefined;
            frameStyle?: 'card' | 'plain' | undefined;
            toIndex?: number | undefined;
            nativeIndex?: number | undefined;
            position?: {
                x: number;
                y: number;
            } | undefined;
        } | {
            kind: 'widget_remove';
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
            expectedInstance?: {
                v: 1;
                id: string;
                definition: {
                    kind: 'installed';
                    surface: {
                        pluginId: string;
                        localId: string;
                    };
                } | {
                    kind: 'builtin';
                    id: string;
                } | {
                    kind: 'artifact';
                    artifactId: string;
                } | {
                    kind: 'inline';
                    definition: {
                        provenance: {
                            source: {
                                kind: 'authored';
                            } | {
                                kind: 'session';
                                serverId: string;
                                sessionId: string;
                                itemId: string;
                            };
                            authorAccountId?: string | undefined;
                            author?: {
                                kind: 'person' | 'agent' | 'plugin';
                            } | undefined;
                            createdAt?: number | undefined;
                        };
                        sizeDeclaration: {
                            sizes: ('small' | 'medium' | 'wide' | 'full' | 'tall' | 'large')[];
                            defaultSize: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                        };
                        name: string;
                        body: {
                            kind: 'declarative';
                            document: unknown;
                        } | {
                            kind: 'installed';
                            surface: {
                                pluginId: string;
                                localId: string;
                            };
                        };
                        inputs: {
                            title?: string | undefined;
                            description?: string | undefined;
                            submitLabel?: string | undefined;
                            fields?: readonly {
                                path: string;
                                widget: 'number' | 'boolean' | 'text' | 'url' | 'secret' | 'textarea' | 'integer' | 'text_list' | 'select' | 'multiselect' | 'json';
                                title: string;
                                inputType?: {
                                    pluginId: string;
                                    localId: string;
                                } | undefined;
                                required?: boolean | undefined;
                                requireExplicitSelection?: boolean | undefined;
                                listSeparator?: 'comma' | 'newline' | undefined;
                                maxSelections?: number | undefined;
                                visibleWhen?: unknown;
                                requiredWhen?: unknown;
                                disabledWhen?: unknown;
                                optionsSourceId?: string | undefined;
                                connectedAccountOptions?: true | undefined;
                                resolvedEmptyConnectedAccountOptions?: true | undefined;
                                description?: string | undefined;
                                placeholder?: string | undefined;
                                options?: readonly {
                                    value: unknown;
                                    label: string;
                                    description?: string | undefined;
                                    disabled?: boolean | undefined;
                                }[] | undefined;
                            }[] | undefined;
                        };
                        inputSchema: unknown;
                        v: 1;
                        id: string;
                        description?: string | undefined;
                        sessionInputPath?: string | undefined;
                        connectedAccountPurposeBindings?: {
                            path: string;
                            purpose: string;
                            consumer: {
                                pluginId: string;
                                localId: string;
                            };
                            nativeServicePath?: string | undefined;
                        }[] | undefined;
                    };
                };
                bindings: Record<string, {
                    kind: 'value';
                    value: unknown;
                } | {
                    kind: 'context';
                    slot: string;
                } | {
                    kind: 'viewer';
                    purpose: string;
                }>;
                displayName?: string | undefined;
            } | undefined;
            expectedPresentation?: {
                frameStyle: 'card' | 'plain' | null;
                nativeIndex: number;
                area?: 'main' | 'aside' | undefined;
                size?: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large' | undefined;
                tabId?: string | undefined;
                hidden?: boolean | undefined;
                canvasPosition?: [
                    number,
                    number
                ] | null | undefined;
            } | undefined;
        } | {
            kind: 'widget_size';
            size: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
        } | {
            kind: 'widget_frame';
            frameStyle: 'card' | 'plain' | null;
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
        } | {
            kind: 'widget_rename';
            displayName: string | null;
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
        } | {
            kind: 'widget_inputs';
            bindings: Record<string, {
                kind: 'value';
                value: unknown;
            } | {
                kind: 'context';
                slot: string;
            } | {
                kind: 'viewer';
                purpose: string;
            }>;
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
            paths?: string[] | undefined;
        } | {
            kind: 'widget_inputs_reset';
            boardId: string;
            ref: {
                surface: {
                    serverId: string;
                    accountId: string;
                    owner: {
                        kind: 'home';
                    } | {
                        kind: 'sessionBoard';
                        sessionId: string;
                    } | {
                        kind: 'companion';
                        sessionId: string;
                    } | {
                        kind: 'workBoard';
                        boardId: string;
                    } | {
                        kind: 'project';
                        projectId: string;
                        dashboardId?: string | undefined;
                    } | {
                        kind: 'pluginArea';
                        pluginId: string;
                        pageId: string;
                        area: string;
                    };
                    artifactId?: string | undefined;
                };
                instanceId: string;
            };
            paths?: string[] | undefined;
        } | {
            kind: 'create';
            board: {
                id: string;
                name: string;
            };
        } | {
            kind: 'delete';
            boardId: string;
        } | {
            kind: 'update';
            boardId: string;
            patch: {
                name?: string | undefined;
                mode?: 'canvas' | 'by_status' | undefined;
                snap?: boolean | undefined;
                pinnedInSessions?: boolean | undefined;
                source?: {
                    sections?: ('needs_you' | 'running' | 'my_machines')[] | null | undefined;
                    filter?: {
                        show: 'sessions' | 'runs' | 'both';
                        startedBy: ('you' | 'triggers' | 'agents')[];
                        scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                        attention: 'any' | 'needs_my_attention';
                        homeServerIds: string[];
                        audiences: ({
                            kind: 'outside_teams';
                            serverId: string;
                        } | {
                            kind: 'team';
                            teamId: string;
                            serverId: string;
                        } | {
                            kind: 'group';
                            teamId: string;
                            groupId: string;
                            serverId: string;
                        })[];
                        tagIds: {
                            serverId: string;
                            tagId: string;
                        }[];
                        source: 'all' | 'persisted' | 'direct';
                        bot?: 'bot' | 'ordinary' | undefined;
                    } | null | undefined;
                    picked?: {
                        kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                        qualifiedId: {
                            serverId: string;
                            id: string;
                        };
                    }[] | undefined;
                } | undefined;
            };
        } | {
            kind: 'add_items';
            boardId: string;
            refs: {
                kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                qualifiedId: {
                    serverId: string;
                    id: string;
                };
            }[];
            positionsByItemRef?: Record<string, {
                x: number;
                y: number;
            }> | undefined;
        } | {
            kind: 'remove_item';
            boardId: string;
            ref: {
                kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                qualifiedId: {
                    serverId: string;
                    id: string;
                };
            };
            membership?: {
                liveItemKeys: string[];
                unavailableServerIds: string[];
            } | undefined;
        } | {
            kind: 'set_positions';
            boardId: string;
            positionsByItemRef: Record<string, {
                x: number;
                y: number;
            }>;
            membership?: {
                liveItemKeys: string[];
                unavailableServerIds: string[];
            } | undefined;
        };
        boardId?: string | undefined;
    };
};
export type BoardsActionResultById = {
    readonly "boards.list": {
        boards: Readonly<{
            id: string;
            name: string;
            source: Readonly<{
                sections?: readonly ('needs_you' | 'running' | 'my_machines')[] | undefined;
                filter?: Readonly<{
                    show: 'sessions' | 'runs' | 'both';
                    startedBy: readonly ('you' | 'triggers' | 'agents')[];
                    scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                    attention: 'any' | 'needs_my_attention';
                    bot?: 'bot' | 'ordinary' | undefined;
                    homeServerIds: readonly string[];
                    audiences: readonly QualifiedAudienceSelection[];
                    tagIds: readonly Readonly<{
                        serverId: string;
                        tagId: string;
                    }>[];
                    source: 'all' | 'persisted' | 'direct';
                }> | undefined;
                picked: readonly Readonly<{
                    kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                    qualifiedId: Readonly<{
                        serverId: string;
                        id: string;
                    }>;
                }>[];
                unknown?: Readonly<{
                    sections?: readonly string[] | undefined;
                    picked?: readonly unknown[] | undefined;
                }> | undefined;
            }>;
            mode: 'canvas' | 'by_status';
            snap: boolean;
            positionsByItemRef: Readonly<Record<string, Readonly<{
                x: number;
                y: number;
            }>>>;
            pinnedInSessions: boolean;
            widgets?: readonly {
                kind: 'widget';
                ref: {
                    surface: {
                        serverId: string;
                        accountId: string;
                        owner: {
                            kind: 'home';
                        } | {
                            kind: 'sessionBoard';
                            sessionId: string;
                        } | {
                            kind: 'companion';
                            sessionId: string;
                        } | {
                            kind: 'workBoard';
                            boardId: string;
                        } | {
                            kind: 'project';
                            projectId: string;
                            dashboardId?: string | undefined;
                        } | {
                            kind: 'pluginArea';
                            pluginId: string;
                            pageId: string;
                            area: string;
                        };
                        artifactId?: string | undefined;
                    };
                    instanceId: string;
                };
                instance: {
                    v: 1;
                    id: string;
                    definition: {
                        kind: 'installed';
                        surface: {
                            pluginId: string;
                            localId: string;
                        };
                    } | {
                        kind: 'builtin';
                        id: string;
                    } | {
                        kind: 'artifact';
                        artifactId: string;
                    } | {
                        kind: 'inline';
                        definition: {
                            provenance: {
                                source: {
                                    kind: 'authored';
                                } | {
                                    kind: 'session';
                                    serverId: string;
                                    sessionId: string;
                                    itemId: string;
                                };
                                authorAccountId?: string | undefined;
                                author?: {
                                    kind: 'person' | 'agent' | 'plugin';
                                } | undefined;
                                createdAt?: number | undefined;
                            };
                            sizeDeclaration: {
                                sizes: ('small' | 'medium' | 'wide' | 'full' | 'tall' | 'large')[];
                                defaultSize: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                            };
                            name: string;
                            body: {
                                kind: 'declarative';
                                document: Readonly<{
                                    version: 1;
                                    root: PluginDeclarativeNodeV2;
                                }>;
                            } | {
                                kind: 'installed';
                                surface: {
                                    pluginId: string;
                                    localId: string;
                                };
                            };
                            inputs: {
                                fields: readonly {
                                    path: string;
                                    widget: 'number' | 'boolean' | 'text' | 'url' | 'secret' | 'textarea' | 'integer' | 'text_list' | 'select' | 'multiselect' | 'json';
                                    title: string;
                                    inputType?: {
                                        pluginId: string;
                                        localId: string;
                                    } | undefined;
                                    required?: boolean | undefined;
                                    requireExplicitSelection?: boolean | undefined;
                                    listSeparator?: 'comma' | 'newline' | undefined;
                                    maxSelections?: number | undefined;
                                    visibleWhen?: InputPredicate | undefined;
                                    requiredWhen?: InputPredicate | undefined;
                                    disabledWhen?: InputPredicate | undefined;
                                    optionsSourceId?: string | undefined;
                                    connectedAccountOptions?: true | undefined;
                                    resolvedEmptyConnectedAccountOptions?: true | undefined;
                                    description?: string | undefined;
                                    placeholder?: string | undefined;
                                    options?: readonly {
                                        value: JsonValue;
                                        label: string;
                                        description?: string | undefined;
                                        disabled?: boolean | undefined;
                                    }[] | undefined;
                                }[];
                                title?: string | undefined;
                                description?: string | undefined;
                                submitLabel?: string | undefined;
                            };
                            inputSchema: PluginJsonSchemaV2;
                            v: 1;
                            id: string;
                            description?: string | undefined;
                            sessionInputPath?: string | undefined;
                            connectedAccountPurposeBindings?: {
                                path: string;
                                purpose: string;
                                consumer: {
                                    pluginId: string;
                                    localId: string;
                                };
                                nativeServicePath?: string | undefined;
                            }[] | undefined;
                        };
                    };
                    bindings: Record<string, {
                        kind: 'value';
                        value: string | number | boolean | readonly JsonValue[] | {
                            readonly [key: string]: JsonValue;
                        } | null;
                    } | {
                        kind: 'context';
                        slot: string;
                    } | {
                        kind: 'viewer';
                        purpose: string;
                    }>;
                    displayName?: string | undefined;
                };
                size: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                frameStyle?: 'card' | 'plain' | undefined;
            }[] | undefined;
            itemOrder?: readonly string[] | undefined;
        }>[];
    };
    readonly "boards.apply": {
        boardId: string;
        board: Readonly<{
            id: string;
            name: string;
            source: Readonly<{
                sections?: readonly ('needs_you' | 'running' | 'my_machines')[] | undefined;
                filter?: Readonly<{
                    show: 'sessions' | 'runs' | 'both';
                    startedBy: readonly ('you' | 'triggers' | 'agents')[];
                    scope: 'my_work' | 'assigned_to_me' | 'following' | 'involving_me' | 'all_accessible';
                    attention: 'any' | 'needs_my_attention';
                    bot?: 'bot' | 'ordinary' | undefined;
                    homeServerIds: readonly string[];
                    audiences: readonly QualifiedAudienceSelection[];
                    tagIds: readonly Readonly<{
                        serverId: string;
                        tagId: string;
                    }>[];
                    source: 'all' | 'persisted' | 'direct';
                }> | undefined;
                picked: readonly Readonly<{
                    kind: 'session' | 'workflow_run' | 'workflow' | 'machine';
                    qualifiedId: Readonly<{
                        serverId: string;
                        id: string;
                    }>;
                }>[];
                unknown?: Readonly<{
                    sections?: readonly string[] | undefined;
                    picked?: readonly unknown[] | undefined;
                }> | undefined;
            }>;
            mode: 'canvas' | 'by_status';
            snap: boolean;
            positionsByItemRef: Readonly<Record<string, Readonly<{
                x: number;
                y: number;
            }>>>;
            pinnedInSessions: boolean;
            widgets?: readonly {
                kind: 'widget';
                ref: {
                    surface: {
                        serverId: string;
                        accountId: string;
                        owner: {
                            kind: 'home';
                        } | {
                            kind: 'sessionBoard';
                            sessionId: string;
                        } | {
                            kind: 'companion';
                            sessionId: string;
                        } | {
                            kind: 'workBoard';
                            boardId: string;
                        } | {
                            kind: 'project';
                            projectId: string;
                            dashboardId?: string | undefined;
                        } | {
                            kind: 'pluginArea';
                            pluginId: string;
                            pageId: string;
                            area: string;
                        };
                        artifactId?: string | undefined;
                    };
                    instanceId: string;
                };
                instance: {
                    v: 1;
                    id: string;
                    definition: {
                        kind: 'installed';
                        surface: {
                            pluginId: string;
                            localId: string;
                        };
                    } | {
                        kind: 'builtin';
                        id: string;
                    } | {
                        kind: 'artifact';
                        artifactId: string;
                    } | {
                        kind: 'inline';
                        definition: {
                            provenance: {
                                source: {
                                    kind: 'authored';
                                } | {
                                    kind: 'session';
                                    serverId: string;
                                    sessionId: string;
                                    itemId: string;
                                };
                                authorAccountId?: string | undefined;
                                author?: {
                                    kind: 'person' | 'agent' | 'plugin';
                                } | undefined;
                                createdAt?: number | undefined;
                            };
                            sizeDeclaration: {
                                sizes: ('small' | 'medium' | 'wide' | 'full' | 'tall' | 'large')[];
                                defaultSize: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                            };
                            name: string;
                            body: {
                                kind: 'declarative';
                                document: Readonly<{
                                    version: 1;
                                    root: PluginDeclarativeNodeV2;
                                }>;
                            } | {
                                kind: 'installed';
                                surface: {
                                    pluginId: string;
                                    localId: string;
                                };
                            };
                            inputs: {
                                fields: readonly {
                                    path: string;
                                    widget: 'number' | 'boolean' | 'text' | 'url' | 'secret' | 'textarea' | 'integer' | 'text_list' | 'select' | 'multiselect' | 'json';
                                    title: string;
                                    inputType?: {
                                        pluginId: string;
                                        localId: string;
                                    } | undefined;
                                    required?: boolean | undefined;
                                    requireExplicitSelection?: boolean | undefined;
                                    listSeparator?: 'comma' | 'newline' | undefined;
                                    maxSelections?: number | undefined;
                                    visibleWhen?: InputPredicate | undefined;
                                    requiredWhen?: InputPredicate | undefined;
                                    disabledWhen?: InputPredicate | undefined;
                                    optionsSourceId?: string | undefined;
                                    connectedAccountOptions?: true | undefined;
                                    resolvedEmptyConnectedAccountOptions?: true | undefined;
                                    description?: string | undefined;
                                    placeholder?: string | undefined;
                                    options?: readonly {
                                        value: JsonValue;
                                        label: string;
                                        description?: string | undefined;
                                        disabled?: boolean | undefined;
                                    }[] | undefined;
                                }[];
                                title?: string | undefined;
                                description?: string | undefined;
                                submitLabel?: string | undefined;
                            };
                            inputSchema: PluginJsonSchemaV2;
                            v: 1;
                            id: string;
                            description?: string | undefined;
                            sessionInputPath?: string | undefined;
                            connectedAccountPurposeBindings?: {
                                path: string;
                                purpose: string;
                                consumer: {
                                    pluginId: string;
                                    localId: string;
                                };
                                nativeServicePath?: string | undefined;
                            }[] | undefined;
                        };
                    };
                    bindings: Record<string, {
                        kind: 'value';
                        value: string | number | boolean | readonly JsonValue[] | {
                            readonly [key: string]: JsonValue;
                        } | null;
                    } | {
                        kind: 'context';
                        slot: string;
                    } | {
                        kind: 'viewer';
                        purpose: string;
                    }>;
                    displayName?: string | undefined;
                };
                size: 'small' | 'medium' | 'wide' | 'full' | 'tall' | 'large';
                frameStyle?: 'card' | 'plain' | undefined;
            }[] | undefined;
            itemOrder?: readonly string[] | undefined;
        }> | null;
    };
};
