// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type ConnectedServicesConfigurationActionInputById = {
    readonly "connectedServices.accounts.default.set": {
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
        agentId: string;
        makeDefault: boolean;
        machineId?: string | undefined;
    };
    readonly "connectedServices.pools.create": {
        service: {
            pluginId: string;
            localId: string;
        };
        group: {
            groupId: string;
            displayName?: string | null | undefined;
            policy?: {
                v?: 1 | undefined;
                strategy?: 'expiry_first' | 'priority' | 'least_limited' | 'manual' | undefined;
                autoSwitch?: boolean | undefined;
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
                switchOn?: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                } | undefined;
                cooldownMs?: number | undefined;
                honorProviderResetsAt?: boolean | undefined;
                autoRestorePrimaryWhenReset?: boolean | undefined;
                maxSwitchesPerTurn?: number | undefined;
                maxSwitchesPerSessionHour?: number | undefined;
                softSwitchRemainingPercent?: number | undefined;
                probeIfSnapshotOlderThanMs?: number | undefined;
                preTurnProbeMode?: 'never' | 'when_stale' | 'always_for_group' | undefined;
                preTurnProbeOrder?: 'current_first_then_candidates' | 'candidates_first_then_current' | undefined;
                recoveryMode?: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait' | undefined;
                resumePromptMode?: 'custom' | 'off' | 'standard' | undefined;
            } | undefined;
        };
    };
    readonly "connectedServices.pools.patch": {
        service: {
            pluginId: string;
            localId: string;
        };
        groupId: string;
        expectedGeneration: number;
        displayName?: string | null | undefined;
        policy?: {
            v?: 1 | undefined;
            strategy?: 'expiry_first' | 'priority' | 'least_limited' | 'manual' | undefined;
            autoSwitch?: boolean | undefined;
            autoUseQuotaResetsWhenExhausted?: boolean | undefined;
            autoDisablePlanInvalidAccounts?: boolean | undefined;
            quotaLimitSelection?: {
                mode: 'all';
                providerLimitIds: string[];
            } | {
                mode: 'selected';
                providerLimitIds: string[];
            } | undefined;
            switchOn?: {
                usageLimit: boolean;
                authExpired: boolean;
                accountChanged: boolean;
                refreshFailure: boolean;
            } | undefined;
            cooldownMs?: number | undefined;
            honorProviderResetsAt?: boolean | undefined;
            autoRestorePrimaryWhenReset?: boolean | undefined;
            maxSwitchesPerTurn?: number | undefined;
            maxSwitchesPerSessionHour?: number | undefined;
            softSwitchRemainingPercent?: number | undefined;
            probeIfSnapshotOlderThanMs?: number | undefined;
            preTurnProbeMode?: 'never' | 'when_stale' | 'always_for_group' | undefined;
            preTurnProbeOrder?: 'current_first_then_candidates' | 'candidates_first_then_current' | undefined;
            recoveryMode?: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait' | undefined;
            resumePromptMode?: 'custom' | 'off' | 'standard' | undefined;
        } | undefined;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
    };
    readonly "connectedServices.pools.delete": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        expectedGeneration: number;
        expectedIncarnation: string;
        expectedRuntimeStateRevision?: number | undefined;
    };
    readonly "connectedServices.pools.members.add": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        expectedGeneration: number;
        connectedAccountId: string;
        priority?: number | undefined;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
        enabled?: boolean | undefined;
    };
    readonly "connectedServices.pools.members.patch": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        expectedGeneration: number;
        connectedAccountId: string;
        priority?: number | undefined;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
        enabled?: boolean | undefined;
    };
    readonly "connectedServices.pools.members.remove": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        expectedGeneration: number;
        connectedAccountId: string;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
    };
    readonly "connectedServices.accounts.rename": {
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
        label: string | null;
    };
    readonly "connectedServices.pools.switchNow": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        connectedAccountId: string;
        expectedGeneration: number;
        expectedIncarnation?: string | undefined;
        expectedRuntimeStateRevision?: number | undefined;
        expectedSource?: {
            connectedAccountId: string;
            credentialRevision: string;
            configurationRevision: string | null;
        } | undefined;
        overrideRuntimeCooldown?: boolean | undefined;
    };
    readonly "connectedServices.pools.reorder": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        accountIds: string[];
    } | {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        move: {
            accountId: string;
            position: {
                anchorId: string | null;
                placement: 'before' | 'after';
            };
        };
    };
    readonly "connectedServices.pools.default.set": {
        group: {
            service: {
                pluginId: string;
                localId: string;
            };
            groupId: string;
        };
        agentId: string;
        makeDefault: boolean;
        machineId?: string | undefined;
    };
    readonly "connectedServices.quota.reset": {
        machineId: string;
        serviceId: 'openai-codex' | 'openai' | 'anthropic' | 'claude-subscription' | 'gemini' | 'github' | 'bitbucket';
        profileId: string;
        providerCreditId?: string | undefined;
        sourceSnapshotFetchedAtMs?: number | null | undefined;
    };
    readonly "connectedServices.quota.refresh": {
        account: {
            service: {
                pluginId: string;
                localId: string;
            };
            accountId: string;
        };
        machineId: string;
    };
    readonly "connectedServices.identityPrivacy.set": {
        hidden: boolean;
    };
};
export type ConnectedServicesConfigurationActionResultById = {
    readonly "connectedServices.accounts.default.set": {
        applied: true;
    };
    readonly "connectedServices.pools.create": {
        group: {
            v: 1;
            ref: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                groupId: string;
            };
            incarnation: string;
            displayName: string | null;
            policy: {
                v: 1;
                strategy: 'expiry_first' | 'priority' | 'least_limited' | 'manual';
                autoSwitch: boolean;
                switchOn: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                };
                cooldownMs: number;
                honorProviderResetsAt: boolean;
                autoRestorePrimaryWhenReset: boolean;
                maxSwitchesPerTurn: number;
                maxSwitchesPerSessionHour: number;
                softSwitchRemainingPercent: number;
                probeIfSnapshotOlderThanMs: number;
                preTurnProbeMode: 'never' | 'when_stale' | 'always_for_group';
                preTurnProbeOrder: 'current_first_then_candidates' | 'candidates_first_then_current';
                recoveryMode: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait';
                resumePromptMode: 'custom' | 'off' | 'standard';
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
            };
            activeConnectedAccountId: string | null;
            generation: number;
            runtimeStateRevision: number;
            state: {
                [x: string]: unknown;
                status?: 'error' | 'ready' | 'switching' | 'exhausted' | 'unknown' | undefined;
                lastSwitchAt?: number | null | undefined;
                lastSwitchReason?: string | null | undefined;
                activeSince?: {
                    accountId: string;
                    atMs: number;
                } | null | undefined;
            };
            createdAt: number;
            updatedAt: number;
            members: {
                v: 1;
                connectedAccountId: string;
                priority: number;
                enabled: boolean;
                state: {
                    [x: string]: unknown;
                    cooldownUntilMs?: number | null | undefined;
                    exhaustedUntilMs?: number | null | undefined;
                    quotaExhaustedUntilMs?: number | null | undefined;
                    rateLimitedUntilMs?: number | null | undefined;
                    capacityLimitedUntilMs?: number | null | undefined;
                    authInvalidUntilMs?: number | null | undefined;
                    planUnavailableUntilMs?: number | null | undefined;
                    modelUnavailableUntilMsByModelId?: Record<string, number> | undefined;
                    autoDisabledReason?: 'model_not_entitled' | null | undefined;
                    validationBlockedUntilMs?: number | null | undefined;
                    lastFailureKind?: string | null | undefined;
                    lastFailureCode?: string | null | undefined;
                    lastObservedPlanType?: string | null | undefined;
                    lastObservedAtMs?: number | null | undefined;
                    providerResetsAtMs?: number | null | undefined;
                    credentialHealthStatus?: 'connected' | 'refreshing' | 'needs_reauth' | 'refresh_failed_retryable' | null | undefined;
                };
                createdAt: number;
                updatedAt: number;
            }[];
        };
    };
    readonly "connectedServices.pools.patch": {
        group: {
            v: 1;
            ref: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                groupId: string;
            };
            incarnation: string;
            displayName: string | null;
            policy: {
                v: 1;
                strategy: 'expiry_first' | 'priority' | 'least_limited' | 'manual';
                autoSwitch: boolean;
                switchOn: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                };
                cooldownMs: number;
                honorProviderResetsAt: boolean;
                autoRestorePrimaryWhenReset: boolean;
                maxSwitchesPerTurn: number;
                maxSwitchesPerSessionHour: number;
                softSwitchRemainingPercent: number;
                probeIfSnapshotOlderThanMs: number;
                preTurnProbeMode: 'never' | 'when_stale' | 'always_for_group';
                preTurnProbeOrder: 'current_first_then_candidates' | 'candidates_first_then_current';
                recoveryMode: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait';
                resumePromptMode: 'custom' | 'off' | 'standard';
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
            };
            activeConnectedAccountId: string | null;
            generation: number;
            runtimeStateRevision: number;
            state: {
                [x: string]: unknown;
                status?: 'error' | 'ready' | 'switching' | 'exhausted' | 'unknown' | undefined;
                lastSwitchAt?: number | null | undefined;
                lastSwitchReason?: string | null | undefined;
                activeSince?: {
                    accountId: string;
                    atMs: number;
                } | null | undefined;
            };
            createdAt: number;
            updatedAt: number;
            members: {
                v: 1;
                connectedAccountId: string;
                priority: number;
                enabled: boolean;
                state: {
                    [x: string]: unknown;
                    cooldownUntilMs?: number | null | undefined;
                    exhaustedUntilMs?: number | null | undefined;
                    quotaExhaustedUntilMs?: number | null | undefined;
                    rateLimitedUntilMs?: number | null | undefined;
                    capacityLimitedUntilMs?: number | null | undefined;
                    authInvalidUntilMs?: number | null | undefined;
                    planUnavailableUntilMs?: number | null | undefined;
                    modelUnavailableUntilMsByModelId?: Record<string, number> | undefined;
                    autoDisabledReason?: 'model_not_entitled' | null | undefined;
                    validationBlockedUntilMs?: number | null | undefined;
                    lastFailureKind?: string | null | undefined;
                    lastFailureCode?: string | null | undefined;
                    lastObservedPlanType?: string | null | undefined;
                    lastObservedAtMs?: number | null | undefined;
                    providerResetsAtMs?: number | null | undefined;
                    credentialHealthStatus?: 'connected' | 'refreshing' | 'needs_reauth' | 'refresh_failed_retryable' | null | undefined;
                };
                createdAt: number;
                updatedAt: number;
            }[];
        };
    };
    readonly "connectedServices.pools.delete": {
        applied: true;
    };
    readonly "connectedServices.pools.members.add": {
        group: {
            v: 1;
            ref: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                groupId: string;
            };
            incarnation: string;
            displayName: string | null;
            policy: {
                v: 1;
                strategy: 'expiry_first' | 'priority' | 'least_limited' | 'manual';
                autoSwitch: boolean;
                switchOn: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                };
                cooldownMs: number;
                honorProviderResetsAt: boolean;
                autoRestorePrimaryWhenReset: boolean;
                maxSwitchesPerTurn: number;
                maxSwitchesPerSessionHour: number;
                softSwitchRemainingPercent: number;
                probeIfSnapshotOlderThanMs: number;
                preTurnProbeMode: 'never' | 'when_stale' | 'always_for_group';
                preTurnProbeOrder: 'current_first_then_candidates' | 'candidates_first_then_current';
                recoveryMode: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait';
                resumePromptMode: 'custom' | 'off' | 'standard';
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
            };
            activeConnectedAccountId: string | null;
            generation: number;
            runtimeStateRevision: number;
            state: {
                [x: string]: unknown;
                status?: 'error' | 'ready' | 'switching' | 'exhausted' | 'unknown' | undefined;
                lastSwitchAt?: number | null | undefined;
                lastSwitchReason?: string | null | undefined;
                activeSince?: {
                    accountId: string;
                    atMs: number;
                } | null | undefined;
            };
            createdAt: number;
            updatedAt: number;
            members: {
                v: 1;
                connectedAccountId: string;
                priority: number;
                enabled: boolean;
                state: {
                    [x: string]: unknown;
                    cooldownUntilMs?: number | null | undefined;
                    exhaustedUntilMs?: number | null | undefined;
                    quotaExhaustedUntilMs?: number | null | undefined;
                    rateLimitedUntilMs?: number | null | undefined;
                    capacityLimitedUntilMs?: number | null | undefined;
                    authInvalidUntilMs?: number | null | undefined;
                    planUnavailableUntilMs?: number | null | undefined;
                    modelUnavailableUntilMsByModelId?: Record<string, number> | undefined;
                    autoDisabledReason?: 'model_not_entitled' | null | undefined;
                    validationBlockedUntilMs?: number | null | undefined;
                    lastFailureKind?: string | null | undefined;
                    lastFailureCode?: string | null | undefined;
                    lastObservedPlanType?: string | null | undefined;
                    lastObservedAtMs?: number | null | undefined;
                    providerResetsAtMs?: number | null | undefined;
                    credentialHealthStatus?: 'connected' | 'refreshing' | 'needs_reauth' | 'refresh_failed_retryable' | null | undefined;
                };
                createdAt: number;
                updatedAt: number;
            }[];
        };
    };
    readonly "connectedServices.pools.members.patch": {
        group: {
            v: 1;
            ref: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                groupId: string;
            };
            incarnation: string;
            displayName: string | null;
            policy: {
                v: 1;
                strategy: 'expiry_first' | 'priority' | 'least_limited' | 'manual';
                autoSwitch: boolean;
                switchOn: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                };
                cooldownMs: number;
                honorProviderResetsAt: boolean;
                autoRestorePrimaryWhenReset: boolean;
                maxSwitchesPerTurn: number;
                maxSwitchesPerSessionHour: number;
                softSwitchRemainingPercent: number;
                probeIfSnapshotOlderThanMs: number;
                preTurnProbeMode: 'never' | 'when_stale' | 'always_for_group';
                preTurnProbeOrder: 'current_first_then_candidates' | 'candidates_first_then_current';
                recoveryMode: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait';
                resumePromptMode: 'custom' | 'off' | 'standard';
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
            };
            activeConnectedAccountId: string | null;
            generation: number;
            runtimeStateRevision: number;
            state: {
                [x: string]: unknown;
                status?: 'error' | 'ready' | 'switching' | 'exhausted' | 'unknown' | undefined;
                lastSwitchAt?: number | null | undefined;
                lastSwitchReason?: string | null | undefined;
                activeSince?: {
                    accountId: string;
                    atMs: number;
                } | null | undefined;
            };
            createdAt: number;
            updatedAt: number;
            members: {
                v: 1;
                connectedAccountId: string;
                priority: number;
                enabled: boolean;
                state: {
                    [x: string]: unknown;
                    cooldownUntilMs?: number | null | undefined;
                    exhaustedUntilMs?: number | null | undefined;
                    quotaExhaustedUntilMs?: number | null | undefined;
                    rateLimitedUntilMs?: number | null | undefined;
                    capacityLimitedUntilMs?: number | null | undefined;
                    authInvalidUntilMs?: number | null | undefined;
                    planUnavailableUntilMs?: number | null | undefined;
                    modelUnavailableUntilMsByModelId?: Record<string, number> | undefined;
                    autoDisabledReason?: 'model_not_entitled' | null | undefined;
                    validationBlockedUntilMs?: number | null | undefined;
                    lastFailureKind?: string | null | undefined;
                    lastFailureCode?: string | null | undefined;
                    lastObservedPlanType?: string | null | undefined;
                    lastObservedAtMs?: number | null | undefined;
                    providerResetsAtMs?: number | null | undefined;
                    credentialHealthStatus?: 'connected' | 'refreshing' | 'needs_reauth' | 'refresh_failed_retryable' | null | undefined;
                };
                createdAt: number;
                updatedAt: number;
            }[];
        };
    };
    readonly "connectedServices.pools.members.remove": {
        group: {
            v: 1;
            ref: {
                service: {
                    pluginId: string;
                    localId: string;
                };
                groupId: string;
            };
            incarnation: string;
            displayName: string | null;
            policy: {
                v: 1;
                strategy: 'expiry_first' | 'priority' | 'least_limited' | 'manual';
                autoSwitch: boolean;
                switchOn: {
                    usageLimit: boolean;
                    authExpired: boolean;
                    accountChanged: boolean;
                    refreshFailure: boolean;
                };
                cooldownMs: number;
                honorProviderResetsAt: boolean;
                autoRestorePrimaryWhenReset: boolean;
                maxSwitchesPerTurn: number;
                maxSwitchesPerSessionHour: number;
                softSwitchRemainingPercent: number;
                probeIfSnapshotOlderThanMs: number;
                preTurnProbeMode: 'never' | 'when_stale' | 'always_for_group';
                preTurnProbeOrder: 'current_first_then_candidates' | 'candidates_first_then_current';
                recoveryMode: 'off' | 'wait_until_reset' | 'switch_then_resume' | 'switch_or_wait';
                resumePromptMode: 'custom' | 'off' | 'standard';
                autoUseQuotaResetsWhenExhausted?: boolean | undefined;
                autoDisablePlanInvalidAccounts?: boolean | undefined;
                quotaLimitSelection?: {
                    mode: 'all';
                    providerLimitIds: string[];
                } | {
                    mode: 'selected';
                    providerLimitIds: string[];
                } | undefined;
            };
            activeConnectedAccountId: string | null;
            generation: number;
            runtimeStateRevision: number;
            state: {
                [x: string]: unknown;
                status?: 'error' | 'ready' | 'switching' | 'exhausted' | 'unknown' | undefined;
                lastSwitchAt?: number | null | undefined;
                lastSwitchReason?: string | null | undefined;
                activeSince?: {
                    accountId: string;
                    atMs: number;
                } | null | undefined;
            };
            createdAt: number;
            updatedAt: number;
            members: {
                v: 1;
                connectedAccountId: string;
                priority: number;
                enabled: boolean;
                state: {
                    [x: string]: unknown;
                    cooldownUntilMs?: number | null | undefined;
                    exhaustedUntilMs?: number | null | undefined;
                    quotaExhaustedUntilMs?: number | null | undefined;
                    rateLimitedUntilMs?: number | null | undefined;
                    capacityLimitedUntilMs?: number | null | undefined;
                    authInvalidUntilMs?: number | null | undefined;
                    planUnavailableUntilMs?: number | null | undefined;
                    modelUnavailableUntilMsByModelId?: Record<string, number> | undefined;
                    autoDisabledReason?: 'model_not_entitled' | null | undefined;
                    validationBlockedUntilMs?: number | null | undefined;
                    lastFailureKind?: string | null | undefined;
                    lastFailureCode?: string | null | undefined;
                    lastObservedPlanType?: string | null | undefined;
                    lastObservedAtMs?: number | null | undefined;
                    providerResetsAtMs?: number | null | undefined;
                    credentialHealthStatus?: 'connected' | 'refreshing' | 'needs_reauth' | 'refresh_failed_retryable' | null | undefined;
                };
                createdAt: number;
                updatedAt: number;
            }[];
        };
    };
    readonly "connectedServices.accounts.rename": {
        applied: true;
    };
    readonly "connectedServices.pools.switchNow": {
        applied: true;
    };
    readonly "connectedServices.pools.reorder": {
        applied: true;
    };
    readonly "connectedServices.pools.default.set": {
        applied: true;
    };
    readonly "connectedServices.quota.reset": {
        [x: string]: unknown;
        ok: true;
        snapshot: {
            v: 1;
            serviceId: 'openai-codex' | 'openai' | 'anthropic' | 'claude-subscription' | 'gemini' | 'github' | 'bitbucket';
            profileId: string;
            fetchedAt: number;
            staleAfterMs: number;
            planLabel: string | null;
            accountLabel: string | null;
            meters: {
                meterId: string;
                label: string;
                used: number | null;
                limit: number | null;
                unit: 'unknown' | 'credits' | 'count' | 'tokens' | 'usd' | 'requests';
                utilizationPct: number | null;
                resetsAt: number | null;
                status: 'ok' | 'estimated' | 'unavailable';
                details: {
                    note?: string | null | undefined;
                    code?: string | undefined;
                    rawScope?: string | undefined;
                    remainingPct?: number | null | undefined;
                    scope?: 'unknown' | 'tokens' | 'requests' | 'primary' | 'secondary' | 'daily' | 'weekly' | 'monthly' | 'five_hour' | 'seven_day' | 'session' | 'rolling' | 'model' | undefined;
                    providerLimitId?: string | undefined;
                    limitCategory?: 'unknown' | 'usage_limit' | 'rate_limit' | 'capacity' | 'temporary_throttle' | 'auth_invalid' | 'plan_invalid' | 'validation_failed' | 'disabled' | undefined;
                };
                remaining?: number | null | undefined;
                remainingPct?: number | null | undefined;
                usedPct?: number | null | undefined;
                resetAtMs?: number | null | undefined;
                resetSource?: 'unknown' | 'manual' | 'in_band_snapshot' | 'header' | 'body' | 'provider_event' | 'provider_probe' | 'computed' | 'provider' | 'retry_after' | undefined;
                providerLimitId?: string | undefined;
                windowDurationMs?: number | undefined;
                modelId?: string | null | undefined;
                isExhausted?: boolean | undefined;
                isSoftLimited?: boolean | undefined;
                isCapacityLimited?: boolean | undefined;
                source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
                scope?: 'unknown' | 'tokens' | 'requests' | 'primary' | 'secondary' | 'daily' | 'weekly' | 'monthly' | 'five_hour' | 'seven_day' | 'session' | 'rolling' | 'model' | undefined;
                limitScope?: 'account' | 'unknown' | 'provider' | 'session' | 'model' | 'workspace' | 'organization' | undefined;
                confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            }[];
            providerId?: string | undefined;
            activeAccountId?: string | undefined;
            fetchedAtMs?: number | undefined;
            staleAtMs?: number | undefined;
            source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
            confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            evidence?: {
                kind?: string | undefined;
                status?: number | undefined;
                headers?: Record<string, string> | undefined;
                code?: string | undefined;
                message?: string | undefined;
                providerLimitId?: string | undefined;
                observedAtMs?: number | undefined;
            } | undefined;
            recoveryCredits?: {
                availableCount: number;
                credits: {
                    kind: 'unknown' | 'usage_limit_reset' | 'rate_limit_reset' | 'quota_reset';
                    status: 'unknown' | 'available' | 'redeeming' | 'redeemed' | 'expired' | 'unavailable';
                    id?: string | undefined;
                    providerResetType?: string | undefined;
                    appliesToProviderLimitId?: string | null | undefined;
                    grantedAtMs?: number | null | undefined;
                    expiresAtMs?: number | null | undefined;
                    redeemStartedAtMs?: number | null | undefined;
                    redeemedAtMs?: number | null | undefined;
                    title?: string | null | undefined;
                    description?: string | null | undefined;
                }[];
                totalCount?: number | undefined;
                nextExpiresAtMs?: number | null | undefined;
                source?: 'unknown' | 'provider_api' | 'background_fetch' | 'runtime_event' | 'runtime_probe' | 'in_band_snapshot' | 'in_band_provider_snapshot' | 'manual_refresh' | 'user_probe' | 'cached' | undefined;
                confidence?: 'unknown' | 'exact' | 'derived' | 'estimated' | 'stale' | undefined;
            } | undefined;
            subscription?: {
                status: 'unavailable' | 'subscribed' | 'none';
                renewal: 'unknown' | 'off' | 'on';
                observedAtMs: number;
                staleAfterMs: number;
                currentPeriodStartAtMs?: number | undefined;
                currentPeriodEndAtMs?: number | undefined;
                lastRefreshError?: {
                    observedAtMs: number;
                    code: 'network' | 'malformed' | 'provider_backoff' | 'auth_failure' | 'missing_auth';
                    status?: number | undefined;
                } | undefined;
            } | undefined;
        } | null;
        receipt: {
            [x: string]: unknown;
            idempotencyKey: string;
            status: 'consumed' | 'already_consumed' | 'not_available' | 'nothing_to_reset' | 'unknown_after_timeout';
            providerCreditId?: string | undefined;
        };
    } | {
        [x: string]: unknown;
        ok: false;
        error: string;
        errorCode: string;
        receipt?: {
            [x: string]: unknown;
            idempotencyKey: string;
            status: 'consumed' | 'already_consumed' | 'not_available' | 'nothing_to_reset' | 'unknown_after_timeout';
            providerCreditId?: string | undefined;
        } | undefined;
    };
    readonly "connectedServices.quota.refresh": {
        applied: true;
    };
    readonly "connectedServices.identityPrivacy.set": {
        applied: true;
    };
};
