// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { SystemTaskJsonValue } from './pluginActionDtoSupport.generated.js';

export type HomeRuntimeActionInputById = {
    readonly "relay.access.status": Record<string, never>;
    readonly "relay.access.configure": {
        providerId: 'localOnly' | 'lan' | 'tailscaleServe' | 'tailscaleFunnel' | 'cloudflareNamed';
        config: {
            providerId: 'localOnly';
        } | {
            providerId: 'lan';
            url: string;
        } | {
            providerId: 'tailscaleServe';
        } | {
            providerId: 'tailscaleFunnel';
        } | {
            providerId: 'cloudflareNamed';
            hostname: string;
            token: string;
        };
        upstreamUrl?: string | null | undefined;
    };
    readonly "relay.access.disable": Record<string, never>;
    readonly "relay.runtime.status": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.install_or_update": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.start": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.stop": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.restart": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.uninstall": {
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        purpose?: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        } | undefined;
        anonymousSignupEnabled?: boolean | undefined;
        expectedPersonalHomeState?: {
            installed: boolean;
            canonicalServerUrl: string | null;
            dataPresent: boolean;
        } | undefined;
    };
    readonly "relay.runtime.personal_home.inspect": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.backup": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
        personalHomeOperation?: {
            outputPath?: string | undefined;
        } | undefined;
    };
    readonly "relay.runtime.personal_home.verify_backup": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        personalHomeOperation: {
            archivePath: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.restore": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        personalHomeOperation: {
            archivePath: string;
            confirmOverwrite?: true | undefined;
            expectedHomeServerIdentityId?: string | undefined;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.recover_restore": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.erase": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.claim": {
        purpose: {
            kind: 'personal-home';
            canonicalServerUrl: string;
        };
        personalHomeOperation: {
            accountId: string;
        };
        runtimeTarget?: {
            channel: 'stable' | 'preview' | 'dev';
            mode: 'user' | 'system';
        } | undefined;
    };
    readonly "relay.runtime.personal_home.relocate": {
        hostId: string;
        expectedRevision: number | 'absent';
        sourceServerId: string;
        operationId: string;
        sourceDescriptorRevision: number;
        recoveryAction?: 'finish_move' | 'return_to_source' | undefined;
    };
    readonly "relay.runtime.personal_home.choose_archive": Record<string, never>;
    readonly "relay.runtime.personal_home.choose_backup_destination": Record<string, never>;
    readonly "relay.runtime.open_path": {
        path: string;
    };
    readonly "relay.runtime.reveal_output": {
        path: string;
    };
    readonly "home.runtime.get": {
        force?: boolean | undefined;
    };
    readonly "home.runtime.restart": {
        machineId: string;
        channel?: 'stable' | 'preview' | 'dev' | undefined;
        mode?: 'user' | 'system' | undefined;
    };
};
export type HomeRuntimeActionResultById = {
    readonly "relay.access.status": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.access.configure": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.access.disable": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.status": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.install_or_update": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.start": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.stop": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.restart": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.uninstall": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.inspect": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.backup": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.verify_backup": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.restore": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.recover_restore": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.erase": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.claim": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.relocate": {
        status: 'task_started';
        taskId: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    } | {
        status: 'unavailable';
        reason: string;
    };
    readonly "relay.runtime.personal_home.choose_archive": {
        status: 'unavailable';
        reason: string;
    } | {
        path: string | null;
    };
    readonly "relay.runtime.personal_home.choose_backup_destination": {
        status: 'unavailable';
        reason: string;
    } | {
        path: string | null;
    };
    readonly "relay.runtime.open_path": {
        status: 'unavailable';
        reason: string;
    } | {
        status: 'completed';
    };
    readonly "relay.runtime.reveal_output": {
        status: 'unavailable';
        reason: string;
    } | {
        status: 'completed';
    };
    readonly "home.runtime.get": {
        status: 'unavailable';
        reason: string;
    } | {
        status: 'ready';
        serverRelease: {
            version?: string | undefined;
            flavor?: 'full' | 'light' | undefined;
        } | null;
    };
    readonly "home.runtime.restart": {
        status: 'unavailable';
        reason: string;
    } | {
        status: 'completed';
        taskId: string;
        result: {
            protocolVersion: 1;
            taskId: string;
            ok: true;
            data?: SystemTaskJsonValue | undefined;
        } | {
            protocolVersion: 1;
            taskId: string;
            ok: false;
            error: {
                code: string;
                message: string;
            };
        };
    } | {
        status: 'outcome_unknown';
        taskId?: string | undefined;
    };
};
