// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type InventoryActionInputById = {
    readonly "paths.list_recent": {
        [x: string]: unknown;
        machineId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "projects.context.update": {
        target: {
            serverId: string;
            projectKey: string;
        };
        expectedRevision: number | 'absent';
        intent: {
            kind: 'attach';
            entry: {
                id: string;
                ref: {
                    kind: 'doc' | 'bundle';
                    artifactId: string;
                    serverId?: string | undefined;
                };
                enabled?: boolean | undefined;
                maxChars?: number | undefined;
                required?: boolean | undefined;
                placement?: 'system_append' | undefined;
            };
        } | {
            kind: 'detach';
            entryId: string;
        } | {
            kind: 'reorder';
            entryId: string;
            siblingId: string;
            position: 'before' | 'after';
        } | {
            kind: 'set_budget';
            entryId: string;
            maxChars: number | null;
        } | {
            kind: 'set_enabled';
            entryId: string;
            enabled: boolean;
        };
    };
    readonly "projects.visibility.set": {
        target: {
            serverId: string;
            projectKey: string;
        };
        expectedRevision: number | 'absent';
        hidden: boolean;
    };
    readonly "projects.workspace.update": {
        serverId: string;
        workspaceId: string;
        label?: string | null | undefined;
        pinned?: boolean | undefined;
    };
    readonly "projects.workspace.forget": {
        serverId: string;
        workspaceId: string;
    };
    readonly "projects.list": {
        serverId?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        includeHidden?: boolean | undefined;
    };
    readonly "projects.open": {
        serverId: string;
        machineId: string;
        source: {
            kind: 'workspace';
            workspaceId: string;
            checkout?: {
                serverId: string;
                workspaceId: string;
                machineId: string;
                rootPath: string;
            } | undefined;
        } | {
            kind: 'folder';
            path: string;
        } | {
            kind: 'source';
            id: string;
            revision: number;
            selector: {
                provider: {
                    id: string;
                    kind: 'unknown' | 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'azure-devops';
                    displayName: string;
                    baseUrl: string;
                };
                repository: {
                    nameWithOwner: string;
                    defaultBranch?: string | null | undefined;
                    visibility?: 'private' | 'public' | 'internal' | undefined;
                    webUrl?: string | undefined;
                    cloneUrl?: string | undefined;
                    sshUrl?: string | undefined;
                };
                protocol: 'auto' | 'ssh' | 'https';
            };
            defaultRef?: string | undefined;
            subdir?: string | undefined;
            checkout?: {
                serverId: string;
                workspaceId: string;
                machineId: string;
                rootPath: string;
            } | undefined;
        } | {
            kind: 'repository';
            selector: {
                provider: {
                    id: string;
                    kind: 'unknown' | 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'azure-devops';
                    displayName: string;
                    baseUrl: string;
                };
                repository: {
                    nameWithOwner: string;
                    defaultBranch?: string | null | undefined;
                    visibility?: 'private' | 'public' | 'internal' | undefined;
                    webUrl?: string | undefined;
                    cloneUrl?: string | undefined;
                    sshUrl?: string | undefined;
                };
                protocol: 'auto' | 'ssh' | 'https';
            };
        };
        materialization: {
            kind: 'attach';
        } | {
            kind: 'worktree';
            checkout: {
                kind: 'git_worktree';
                displayName: string;
                baseRef: string | null;
                branchMode?: 'new' | 'existing' | undefined;
            };
            targetPath?: string | undefined;
        } | {
            destinationParentPath: string;
            destinationDirectoryName: string;
            kind: 'clone';
        } | {
            kind: 'sync';
            targetPath: string;
            workspaceAction: {
                kind: 'none';
            } | {
                kind: 'copy_once';
                contentPolicy: {
                    v: 1;
                    selection: 'git_worktree' | 'all_files';
                    extraIgnorePatterns: readonly string[];
                    extraIncludePatterns: readonly string[];
                    policyDigest: string;
                };
            } | {
                kind: 'create_relationship';
                mode: 'keep_synced' | 'mirror_exactly' | 'keep_both_in_sync';
                contentPolicy: {
                    v: 1;
                    selection: 'git_worktree' | 'all_files';
                    extraIgnorePatterns: readonly string[];
                    extraIncludePatterns: readonly string[];
                    policyDigest: string;
                };
                flushBeforeCommit: true;
            } | {
                kind: 'relationship';
                relationshipId: string;
                flushBeforeCommit: boolean;
            } | {
                kind: 'linked_workspace';
            };
        };
        ref?: string | undefined;
        subdir?: string | undefined;
    };
    readonly "prompts.invocations.list": {
        [x: string]: unknown;
        limit?: number | undefined;
    };
    readonly "prompts.invocation.resolve": {
        [x: string]: unknown;
        invocationId: string;
        argsText?: string | undefined;
    };
    readonly "machines.list": {
        serverId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "servers.list": {
        [x: string]: unknown;
        limit?: number | undefined;
    };
    readonly "review.engines.list": {
        [x: string]: unknown;
        sessionId?: string | null | undefined;
        machineId?: string | undefined;
        includeDisabled?: boolean | undefined;
        scope?: 'paths' | undefined;
    };
    readonly "agents.backends.list": {
        [x: string]: unknown;
        includeDisabled?: boolean | undefined;
        limit?: number | undefined;
        machineId?: string | undefined;
    };
    readonly "machines.agents.list": {
        machineId: string;
        serverId?: string | undefined;
        agentId?: string | undefined;
        refresh?: boolean | undefined;
    };
    readonly "agents.models.list": {
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        serverId?: string | undefined;
        limit?: number | undefined;
        probe?: {
            cwd?: string | undefined;
            timeoutMs?: number | undefined;
            transportTimeoutMs?: number | undefined;
            bypassCache?: boolean | undefined;
            profileId?: string | undefined;
            runtimeDescriptorV1?: unknown;
            connectedServices?: {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 2;
                bindingsByServiceId?: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'direct';
                    disclosedMember: {
                        service: {
                            pluginId: string;
                            localId: string;
                        };
                        accountId: string;
                    };
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'brokered';
                    disclosedMember?: undefined;
                }> | undefined;
            } | undefined;
        } | undefined;
    };
    readonly "agents.config_options.list": {
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        modelId?: string | undefined;
        serverId?: string | undefined;
        probe?: {
            cwd?: string | undefined;
            timeoutMs?: number | undefined;
            transportTimeoutMs?: number | undefined;
            bypassCache?: boolean | undefined;
            profileId?: string | undefined;
            runtimeDescriptorV1?: unknown;
            connectedServices?: {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 2;
                bindingsByServiceId?: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'direct';
                    disclosedMember: {
                        service: {
                            pluginId: string;
                            localId: string;
                        };
                        accountId: string;
                    };
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'brokered';
                    disclosedMember?: undefined;
                }> | undefined;
            } | undefined;
        } | undefined;
    };
    readonly "agents.session_modes.list": {
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        serverId?: string | undefined;
        probe?: {
            cwd?: string | undefined;
            timeoutMs?: number | undefined;
            transportTimeoutMs?: number | undefined;
            bypassCache?: boolean | undefined;
            profileId?: string | undefined;
            runtimeDescriptorV1?: unknown;
            connectedServices?: {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 1;
                bindingsByServiceId: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                }>;
            } | {
                v: 2;
                bindingsByServiceId?: Record<string, {
                    source: 'native';
                } | {
                    source: 'connected';
                    selection: 'group';
                    groupId: string;
                    profileId?: string | undefined;
                } | {
                    source: 'connected';
                    profileId: string;
                    selection?: 'profile' | undefined;
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'direct';
                    disclosedMember: {
                        service: {
                            pluginId: string;
                            localId: string;
                        };
                        accountId: string;
                    };
                } | {
                    source: 'team_resource';
                    resourceId: string;
                    deliveryMode: 'brokered';
                    disclosedMember?: undefined;
                }> | undefined;
            } | undefined;
        } | undefined;
    };
    readonly "sessions.spawn.profiles.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
    };
    readonly "sessions.spawn.connected_services.list": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        limit?: number | undefined;
        includeUnavailable?: boolean | undefined;
        serverId?: string | undefined;
    };
    readonly "sessions.spawn.mcp_servers.preview": {
        [x: string]: unknown;
        agentId?: string | undefined;
        backendTargetKey?: string | undefined;
        machineId?: string | undefined;
        directory?: string | undefined;
        path?: string | undefined;
        selection?: unknown;
        limit?: number | undefined;
    };
};
export type InventoryActionResultById = {
    readonly "paths.list_recent": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "projects.context.update": {
        ok: true;
        row: {
            hidden?: boolean | undefined;
            pinned?: boolean | undefined;
            label?: string | undefined;
            promptStack?: {
                ref: {
                    kind: 'doc' | 'bundle';
                    artifactId: string;
                    serverId?: string | undefined;
                };
                id: string;
                enabled: boolean;
                placement: 'system_append' | 'composer_insert' | 'skill_instructions' | 'provider_asset';
                maxChars?: number | undefined;
                required?: boolean | undefined;
            }[] | undefined;
        };
        revision: number;
    } | {
        ok: false;
        errorCode: 'invalid_parameters' | 'entry_conflict' | 'entry_not_found' | 'project_context_conflict' | 'project_context_unavailable' | 'project_context_access_denied' | 'artifact_unavailable' | 'artifact_wrong_kind';
        currentRevision?: number | 'absent' | undefined;
    };
    readonly "projects.visibility.set": {
        ok: true;
        row: {
            hidden?: boolean | undefined;
            pinned?: boolean | undefined;
            label?: string | undefined;
            promptStack?: {
                ref: {
                    kind: 'doc' | 'bundle';
                    artifactId: string;
                    serverId?: string | undefined;
                };
                id: string;
                enabled: boolean;
                placement: 'system_append' | 'composer_insert' | 'skill_instructions' | 'provider_asset';
                maxChars?: number | undefined;
                required?: boolean | undefined;
            }[] | undefined;
        };
        revision: number;
    } | {
        ok: false;
        errorCode: 'invalid_parameters' | 'project_visibility_conflict' | 'project_visibility_access_denied' | 'project_visibility_unavailable';
        currentRevision?: number | 'absent' | undefined;
    };
    readonly "projects.workspace.update": {
        ok: true;
        workspaceRef: {
            id: string;
            serverId: string;
            machineId: string;
            rootPath: string;
            createdAtMs: number;
            label?: string | null | undefined;
            lastOpenedAtMs?: number | null | undefined;
            projectKey?: string | undefined;
            repositoryIdentity?: {
                kind: 'unknown' | 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'azure-devops';
                deployment: string;
                repository: string;
            } | undefined;
            source?: {
                sourceId: string;
                revision: number;
            } | undefined;
        };
        organization?: {
            hidden?: boolean | undefined;
            pinned?: boolean | undefined;
            label?: string | undefined;
            promptStack?: {
                ref: {
                    kind: 'doc' | 'bundle';
                    artifactId: string;
                    serverId?: string | undefined;
                };
                id: string;
                enabled: boolean;
                placement: 'system_append' | 'composer_insert' | 'skill_instructions' | 'provider_asset';
                maxChars?: number | undefined;
                required?: boolean | undefined;
            }[] | undefined;
        } | undefined;
    } | {
        ok: false;
        errorCode: string;
        error: string;
        details?: unknown;
    };
    readonly "projects.workspace.forget": {
        ok: false;
        errorCode: string;
        error: string;
        details?: unknown;
    } | {
        ok: true;
        workspaceId: string;
    };
    readonly "projects.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "projects.open": {
        kind: 'opened';
        workspace: {
            serverId: string;
            workspaceId: string;
            machineId: string;
            rootPath: string;
        };
        directory: string;
        setup: 'notRequired' | 'approvalRequired' | 'prepared' | 'failed';
        facts?: {
            projectKey?: string | undefined;
            repositoryIdentity?: {
                kind: 'unknown' | 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'azure-devops';
                deployment: string;
                repository: string;
            } | undefined;
            source?: {
                sourceId: string;
                revision: number;
            } | undefined;
        } | undefined;
    } | {
        kind: 'ambiguous';
        candidates: {
            id: string;
            serverId: string;
            machineId: string;
            rootPath: string;
            createdAtMs: number;
            projectKey?: string | undefined;
            repositoryIdentity?: {
                kind: 'unknown' | 'custom' | 'github' | 'gitlab' | 'bitbucket' | 'azure-devops';
                deployment: string;
                repository: string;
            } | undefined;
            source?: {
                sourceId: string;
                revision: number;
            } | undefined;
            label?: string | null | undefined;
            lastOpenedAtMs?: number | null | undefined;
        }[];
    } | {
        kind: 'refused';
        code: string;
        retryNotBeforeMs?: number | undefined;
        remediation?: {
            kind: 'retry' | 'commit_required' | 'set_url_required' | 'auth_required' | 'install_required' | 'unsupported_provider' | 'confirmation_required';
            label?: string | undefined;
            action?: string | undefined;
            url?: string | undefined;
        } | undefined;
    } | {
        kind: 'outcomeUnknown';
        operationId?: string | undefined;
    };
    readonly "prompts.invocations.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompts.invocation.resolve": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "machines.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "servers.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "review.engines.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.backends.list": {
        items: {
            targetKey: string;
            label: string;
            enabled: boolean;
            agentId?: string | undefined;
            identity?: {
                pluginId: string;
                localId: string;
            } | undefined;
            backendId?: string | undefined;
            description?: string | undefined;
        }[];
    };
    readonly "machines.agents.list": {
        items: {
            installed: boolean;
            version: string | null;
            latestVersion: string | null;
            update: {
                supported: boolean;
                command: string | null;
            };
            signIn: {
                status: 'unknown' | 'signedIn' | 'signedOut';
                loginSupport: 'login_terminal' | 'status_only' | 'manual_only' | 'unsupported';
                accountLabel?: string | undefined;
            };
            platform: {
                supported: true;
            } | {
                supported: false;
                reason: 'os' | 'arch';
            };
            install: {
                available: boolean;
                mode: 'none' | 'managed' | 'vendor_recipe' | 'manual';
                sizeBytes: number | null;
                guideUrl: string | null;
            };
            dependencies: {
                key: string;
                installed: boolean;
                version: string | null;
            }[];
            agentId: string;
            title: string;
        }[];
        unavailable?: {
            agentId: string;
            reason: 'missing_result' | 'probe_failed' | 'invalid_facts';
            errorCode?: string | undefined;
        }[] | undefined;
    };
    readonly "agents.models.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.config_options.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "agents.session_modes.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.profiles.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.connected_services.list": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "sessions.spawn.mcp_servers.preview": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
};
