// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type ListReorderActionInputById = {
    readonly "session.pending.reorder": {
        scope: {
            serverId: string;
            accountId: string;
        };
        sourceId: string;
        position: {
            anchorId: string | null;
            placement: 'before' | 'after';
        };
        sessionId: string;
        recipient: {
            kind: 'execution_run';
            runId: string;
        } | null;
    };
    readonly "todos.reorder": {
        scope: {
            serverId: string;
            accountId: string;
        };
        sourceId: string;
        position: {
            anchorId: string | null;
            placement: 'before' | 'after';
        };
    };
};
export type ListReorderActionResultById = {
    readonly "session.pending.reorder": {
        status: 'applied';
    } | {
        status: 'unavailable';
    } | {
        status: 'refused';
        reason: string;
    } | {
        status: 'unknown';
        reason: string;
    };
    readonly "todos.reorder": {
        status: 'applied';
    } | {
        status: 'unavailable';
    } | {
        status: 'refused';
        reason: string;
    } | {
        status: 'unknown';
        reason: string;
    };
};
