// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type LocalServicesLauncherActionInputById = {
    readonly "localServices.launcher.snapshot": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
    };
    readonly "localServices.launcher.start": {
        machineId: string;
        targetId: string;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        choice?: {
            kind: 'primary';
        } | {
            kind: 'workers';
            destination: {
                kind: 'machine';
                machineId: string;
            } | {
                kind: 'pool';
                poolId: string;
                selection: 'automatic' | 'ask';
            };
        } | undefined;
        workspace?: {
            serverId: string;
            workspaceId: string;
            machineId: string;
            rootPath: string;
        } | undefined;
        declaration?: {
            workspaceRefId: string;
            selection: {
                kind: 'manifest';
                name: string;
            } | {
                kind: 'native';
                source: {
                    kind: 'native';
                    tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                    file: string;
                    target: string;
                } | {
                    kind: 'pluginNative';
                    adapter: {
                        pluginId: string;
                        localId: string;
                    };
                    file: string;
                    target: string;
                };
            };
        } | undefined;
        expectedEffectDigest?: string | undefined;
    };
    readonly "localServices.launcher.openPreview": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
        scope?: 'machine' | 'workspace' | undefined;
        workspaceRoot?: string | undefined;
    };
    readonly "localServices.launcher.registerPreview": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
        scope?: 'machine' | 'workspace' | undefined;
        workspaceRoot?: string | undefined;
    };
    readonly "localServices.launcher.history.clear": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        targetId?: string | undefined;
        scope?: 'machine' | 'workspace' | undefined;
        workspaceRoot?: string | undefined;
    };
};
export type LocalServicesLauncherActionResultById = {
    readonly "localServices.launcher.snapshot": {
        v: 1;
        machineId: string;
        updatedAt: number;
        targets: {
            id: string;
            source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
            machineId: string;
            title: string;
            confidence: 'high' | 'medium' | 'low';
            state: 'starting' | 'available' | 'stale' | 'unavailable';
            actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
            sourceClass?: {
                kind: 'package_script';
                runTargetId: string;
                packageName: string;
                scriptName: string;
                cwd?: string | undefined;
            } | {
                kind: 'managed_service';
                managedServiceId: string;
                inventoryEntryId?: string | undefined;
            } | {
                kind: 'inventory_entry';
                inventoryEntryId: string;
            } | {
                kind: 'registered_preview';
                previewId: string;
            } | {
                kind: 'terminal_url';
                sourceId: string;
                addressLabel: string;
                host?: string | undefined;
                port?: number | undefined;
            } | {
                kind: 'workspace_file_asset';
                sourceId: string;
                assetRef: string;
                mediaType?: string | undefined;
            } | {
                kind: 'recent';
                targetId: string;
            } | undefined;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
            workspace?: {
                serverId: string;
                workspaceId: string;
                machineId: string;
                rootPath: string;
            } | undefined;
            cwd?: string | undefined;
            declaration?: {
                workspaceRefId: string;
                selection: {
                    kind: 'manifest';
                    name: string;
                } | {
                    kind: 'native';
                    source: {
                        kind: 'native';
                        tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                        file: string;
                        target: string;
                    } | {
                        kind: 'pluginNative';
                        adapter: {
                            pluginId: string;
                            localId: string;
                        };
                        file: string;
                        target: string;
                    };
                };
            } | undefined;
            serviceState?: 'starting' | 'running' | 'detecting' | 'healthy' | 'unhealthy' | 'stopping' | 'stopped' | 'failed' | undefined;
            readiness?: 'ready' | 'not_ready' | 'not_reported' | undefined;
            endpointUrl?: string | undefined;
            startedAtMs?: number | undefined;
            startedByAccountId?: string | undefined;
            endpointKind?: 'native' | 'none' | 'http' | undefined;
            subtitle?: string | undefined;
            kind?: string | undefined;
            commandPreview?: string | undefined;
            unavailableReason?: string | undefined;
            browserTarget?: {
                targetId: string;
                kind: 'localServicePreview';
                machineId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
                sessionId?: string | undefined;
            } | {
                targetId: string;
                kind: 'hostedPluginWeb';
                pluginId: string;
                contributionId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'externalUrl';
                url: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'streamedBrowser';
                streamId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
            } | {
                targetId: string;
                kind: 'simulatorPreview';
                deviceId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
                sourceId?: string | undefined;
            } | undefined;
        }[];
        sessionId?: string | undefined;
    };
    readonly "localServices.launcher.start": {
        protocolVersion: 1;
        machineId: string;
        targetId: string;
        status: 'failed' | 'succeeded' | 'denied';
        snapshot: {
            v: 1;
            machineId: string;
            updatedAt: number;
            targets: {
                id: string;
                source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
                machineId: string;
                title: string;
                confidence: 'high' | 'medium' | 'low';
                state: 'starting' | 'available' | 'stale' | 'unavailable';
                actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
                sourceClass?: {
                    kind: 'package_script';
                    runTargetId: string;
                    packageName: string;
                    scriptName: string;
                    cwd?: string | undefined;
                } | {
                    kind: 'managed_service';
                    managedServiceId: string;
                    inventoryEntryId?: string | undefined;
                } | {
                    kind: 'inventory_entry';
                    inventoryEntryId: string;
                } | {
                    kind: 'registered_preview';
                    previewId: string;
                } | {
                    kind: 'terminal_url';
                    sourceId: string;
                    addressLabel: string;
                    host?: string | undefined;
                    port?: number | undefined;
                } | {
                    kind: 'workspace_file_asset';
                    sourceId: string;
                    assetRef: string;
                    mediaType?: string | undefined;
                } | {
                    kind: 'recent';
                    targetId: string;
                } | undefined;
                sessionId?: string | undefined;
                workspaceId?: string | undefined;
                workspace?: {
                    serverId: string;
                    workspaceId: string;
                    machineId: string;
                    rootPath: string;
                } | undefined;
                cwd?: string | undefined;
                declaration?: {
                    workspaceRefId: string;
                    selection: {
                        kind: 'manifest';
                        name: string;
                    } | {
                        kind: 'native';
                        source: {
                            kind: 'native';
                            tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                            file: string;
                            target: string;
                        } | {
                            kind: 'pluginNative';
                            adapter: {
                                pluginId: string;
                                localId: string;
                            };
                            file: string;
                            target: string;
                        };
                    };
                } | undefined;
                serviceState?: 'starting' | 'running' | 'detecting' | 'healthy' | 'unhealthy' | 'stopping' | 'stopped' | 'failed' | undefined;
                readiness?: 'ready' | 'not_ready' | 'not_reported' | undefined;
                endpointUrl?: string | undefined;
                startedAtMs?: number | undefined;
                startedByAccountId?: string | undefined;
                endpointKind?: 'native' | 'none' | 'http' | undefined;
                subtitle?: string | undefined;
                kind?: string | undefined;
                commandPreview?: string | undefined;
                unavailableReason?: string | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | {
                    targetId: string;
                    kind: 'hostedPluginWeb';
                    pluginId: string;
                    contributionId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'externalUrl';
                    url: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'streamedBrowser';
                    streamId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'simulatorPreview';
                    deviceId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sourceId?: string | undefined;
                } | undefined;
            }[];
            sessionId?: string | undefined;
        };
        reasonCode?: string | undefined;
        reviewedEffect?: string | number | boolean | readonly JsonValue[] | {
            readonly [key: string]: JsonValue;
        } | null | undefined;
        reviewedEffectDigest?: string | undefined;
        currentTarget?: {
            kind: 'managed_service';
            managedServiceId: string;
            machineId: string;
            sessionId?: string | undefined;
            workspaceId?: string | undefined;
            cwd?: string | undefined;
            declaration?: {
                workspaceRefId: string;
                selection: {
                    kind: 'manifest';
                    name: string;
                } | {
                    kind: 'native';
                    source: {
                        kind: 'native';
                        tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                        file: string;
                        target: string;
                    } | {
                        kind: 'pluginNative';
                        adapter: {
                            pluginId: string;
                            localId: string;
                        };
                        file: string;
                        target: string;
                    };
                };
            } | undefined;
        } | undefined;
    };
    readonly "localServices.launcher.openPreview": {
        protocolVersion: 1;
        status: 'unavailable' | 'opened';
        targetId: string;
        browserTarget?: {
            targetId: string;
            kind: 'localServicePreview';
            machineId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sessionId?: string | undefined;
        } | {
            targetId: string;
            kind: 'hostedPluginWeb';
            pluginId: string;
            contributionId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'externalUrl';
            url: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'streamedBrowser';
            streamId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'simulatorPreview';
            deviceId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sourceId?: string | undefined;
        } | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.launcher.registerPreview": {
        protocolVersion: 1;
        status: 'unavailable' | 'registered' | 'existing';
        targetId: string;
        previewId?: string | undefined;
        browserTarget?: {
            targetId: string;
            kind: 'localServicePreview';
            machineId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sessionId?: string | undefined;
        } | {
            targetId: string;
            kind: 'hostedPluginWeb';
            pluginId: string;
            contributionId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'externalUrl';
            url: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'streamedBrowser';
            streamId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
        } | {
            targetId: string;
            kind: 'simulatorPreview';
            deviceId: string;
            display?: {
                title: string;
                addressLabel?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
            } | undefined;
            sourceId?: string | undefined;
        } | undefined;
        reasonCode?: string | undefined;
    };
    readonly "localServices.launcher.history.clear": {
        protocolVersion: 1;
        cleared: number;
        snapshot: {
            v: 1;
            machineId: string;
            updatedAt: number;
            targets: {
                id: string;
                source: 'package_script' | 'managed_service' | 'inventory_entry' | 'registered_preview' | 'terminal_url' | 'workspace_file_asset' | 'recent';
                machineId: string;
                title: string;
                confidence: 'high' | 'medium' | 'low';
                state: 'starting' | 'available' | 'stale' | 'unavailable';
                actions: ('start' | 'open' | 'open_preview' | 'register_preview' | 'manage' | 'terminate_detected')[];
                sourceClass?: {
                    kind: 'package_script';
                    runTargetId: string;
                    packageName: string;
                    scriptName: string;
                    cwd?: string | undefined;
                } | {
                    kind: 'managed_service';
                    managedServiceId: string;
                    inventoryEntryId?: string | undefined;
                } | {
                    kind: 'inventory_entry';
                    inventoryEntryId: string;
                } | {
                    kind: 'registered_preview';
                    previewId: string;
                } | {
                    kind: 'terminal_url';
                    sourceId: string;
                    addressLabel: string;
                    host?: string | undefined;
                    port?: number | undefined;
                } | {
                    kind: 'workspace_file_asset';
                    sourceId: string;
                    assetRef: string;
                    mediaType?: string | undefined;
                } | {
                    kind: 'recent';
                    targetId: string;
                } | undefined;
                sessionId?: string | undefined;
                workspaceId?: string | undefined;
                workspace?: {
                    serverId: string;
                    workspaceId: string;
                    machineId: string;
                    rootPath: string;
                } | undefined;
                cwd?: string | undefined;
                declaration?: {
                    workspaceRefId: string;
                    selection: {
                        kind: 'manifest';
                        name: string;
                    } | {
                        kind: 'native';
                        source: {
                            kind: 'native';
                            tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                            file: string;
                            target: string;
                        } | {
                            kind: 'pluginNative';
                            adapter: {
                                pluginId: string;
                                localId: string;
                            };
                            file: string;
                            target: string;
                        };
                    };
                } | undefined;
                serviceState?: 'starting' | 'running' | 'detecting' | 'healthy' | 'unhealthy' | 'stopping' | 'stopped' | 'failed' | undefined;
                readiness?: 'ready' | 'not_ready' | 'not_reported' | undefined;
                endpointUrl?: string | undefined;
                startedAtMs?: number | undefined;
                startedByAccountId?: string | undefined;
                endpointKind?: 'native' | 'none' | 'http' | undefined;
                subtitle?: string | undefined;
                kind?: string | undefined;
                commandPreview?: string | undefined;
                unavailableReason?: string | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | {
                    targetId: string;
                    kind: 'hostedPluginWeb';
                    pluginId: string;
                    contributionId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'externalUrl';
                    url: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'streamedBrowser';
                    streamId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                } | {
                    targetId: string;
                    kind: 'simulatorPreview';
                    deviceId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sourceId?: string | undefined;
                } | undefined;
            }[];
            sessionId?: string | undefined;
        };
    };
};
