// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type LocalServicesPreviewActionInputById = {
    readonly "localServices.preview.openOrCreate": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
    };
    readonly "localServices.preview.status": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
    };
    readonly "localServices.preview.revoke": {
        [x: string]: unknown;
        machineId?: string | undefined;
        sessionId?: string | undefined;
        workspaceId?: string | undefined;
        previewId?: string | undefined;
        targetId?: string | undefined;
    };
};
export type LocalServicesPreviewActionResultById = {
    readonly "localServices.preview.openOrCreate": {
        protocolVersion: 1;
        status: 'created' | 'existing';
        preview: {
            previewId: string;
            resource: {
                previewId: string;
                machineId: string;
                owner: {
                    kind: 'user';
                    id: string;
                } | {
                    kind: 'session';
                    id: string;
                } | {
                    kind: 'plugin';
                    id: string;
                } | {
                    kind: 'agent';
                    id: string;
                };
                target: {
                    scheme: 'http' | 'https';
                    host: string;
                    port: number;
                };
                initialPath: {
                    pathname: string;
                    search: string;
                };
                display: {
                    title: string;
                    addressLabel: string;
                    label?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    diagnostics?: Record<string, unknown> | undefined;
                };
                originMode: 'host';
                sessionId?: string | undefined;
                serviceTarget?: {
                    machineId: string;
                    kind: 'managed_service';
                    managedServiceId: string;
                    cwd: string;
                    declaration: {
                        workspaceRefId: string;
                        selection: {
                            kind: 'manifest';
                            name: string;
                        } | {
                            kind: 'native';
                            source: {
                                kind: 'native';
                                tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                file: string;
                                target: string;
                            } | {
                                kind: 'pluginNative';
                                adapter: {
                                    pluginId: string;
                                    localId: string;
                                };
                                file: string;
                                target: string;
                            };
                        };
                    };
                    workspaceId?: string | undefined;
                } | undefined;
                policy?: {
                    allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                    cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                    compressionPolicy: 'identity' | 'decode_reencode';
                    redirectPolicy: 'preserve_host_origin';
                    maxRequestBodyBytes: number;
                    maxResponseBodyBytes: number;
                } | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | undefined;
            };
            accessUrl: string | null;
            expiresAt: number | null;
            diagnostics: {
                v: 1;
                code: 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'expired' | 'not_yet_valid' | 'revoked' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                severity: 'error' | 'info' | 'warning';
                scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                details: Record<string, unknown>;
                previewId?: string | undefined;
                publicExposureId?: string | undefined;
                emittedAtMs?: number | undefined;
            }[];
            accessUnavailableReasonCode?: 'preview_private_route_unavailable' | undefined;
            nativeDirect?: {
                v: 1;
                kind: 'iroh_preview';
                previewId: string;
                machineId: string;
            } | undefined;
        };
        snapshot: {
            v: 1;
            machineId: string;
            generatedAt: number;
            refreshState: 'error' | 'idle' | 'refreshing';
            resources: {
                previewId: string;
                machineId: string;
                owner: {
                    kind: 'user';
                    id: string;
                } | {
                    kind: 'session';
                    id: string;
                } | {
                    kind: 'plugin';
                    id: string;
                } | {
                    kind: 'agent';
                    id: string;
                };
                target: {
                    scheme: 'http' | 'https';
                    host: string;
                    port: number;
                };
                initialPath: {
                    pathname: string;
                    search: string;
                };
                display: {
                    title: string;
                    addressLabel: string;
                    label?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    diagnostics?: Record<string, unknown> | undefined;
                };
                originMode: 'host';
                sessionId?: string | undefined;
                serviceTarget?: {
                    machineId: string;
                    kind: 'managed_service';
                    managedServiceId: string;
                    cwd: string;
                    declaration: {
                        workspaceRefId: string;
                        selection: {
                            kind: 'manifest';
                            name: string;
                        } | {
                            kind: 'native';
                            source: {
                                kind: 'native';
                                tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                file: string;
                                target: string;
                            } | {
                                kind: 'pluginNative';
                                adapter: {
                                    pluginId: string;
                                    localId: string;
                                };
                                file: string;
                                target: string;
                            };
                        };
                    };
                    workspaceId?: string | undefined;
                } | undefined;
                policy?: {
                    allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                    cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                    compressionPolicy: 'identity' | 'decode_reencode';
                    redirectPolicy: 'preserve_host_origin';
                    maxRequestBodyBytes: number;
                    maxResponseBodyBytes: number;
                } | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | undefined;
            }[];
            diagnostics: Record<string, unknown>[];
            previews?: {
                previewId: string;
                resource: {
                    previewId: string;
                    machineId: string;
                    owner: {
                        kind: 'user';
                        id: string;
                    } | {
                        kind: 'session';
                        id: string;
                    } | {
                        kind: 'plugin';
                        id: string;
                    } | {
                        kind: 'agent';
                        id: string;
                    };
                    target: {
                        scheme: 'http' | 'https';
                        host: string;
                        port: number;
                    };
                    initialPath: {
                        pathname: string;
                        search: string;
                    };
                    display: {
                        title: string;
                        addressLabel: string;
                        label?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                        diagnostics?: Record<string, unknown> | undefined;
                    };
                    originMode: 'host';
                    sessionId?: string | undefined;
                    serviceTarget?: {
                        machineId: string;
                        kind: 'managed_service';
                        managedServiceId: string;
                        cwd: string;
                        declaration: {
                            workspaceRefId: string;
                            selection: {
                                kind: 'manifest';
                                name: string;
                            } | {
                                kind: 'native';
                                source: {
                                    kind: 'native';
                                    tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                    file: string;
                                    target: string;
                                } | {
                                    kind: 'pluginNative';
                                    adapter: {
                                        pluginId: string;
                                        localId: string;
                                    };
                                    file: string;
                                    target: string;
                                };
                            };
                        };
                        workspaceId?: string | undefined;
                    } | undefined;
                    policy?: {
                        allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                        cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                        compressionPolicy: 'identity' | 'decode_reencode';
                        redirectPolicy: 'preserve_host_origin';
                        maxRequestBodyBytes: number;
                        maxResponseBodyBytes: number;
                    } | undefined;
                    browserTarget?: {
                        targetId: string;
                        kind: 'localServicePreview';
                        machineId: string;
                        display?: {
                            title: string;
                            addressLabel?: string | undefined;
                            folderLabel?: string | undefined;
                            iconToken?: string | undefined;
                            tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                        } | undefined;
                        sessionId?: string | undefined;
                    } | undefined;
                };
                accessUrl: string | null;
                expiresAt: number | null;
                diagnostics: {
                    v: 1;
                    code: 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'expired' | 'not_yet_valid' | 'revoked' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                    severity: 'error' | 'info' | 'warning';
                    scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                    details: Record<string, unknown>;
                    previewId?: string | undefined;
                    publicExposureId?: string | undefined;
                    emittedAtMs?: number | undefined;
                }[];
                accessUnavailableReasonCode?: 'preview_private_route_unavailable' | undefined;
                nativeDirect?: {
                    v: 1;
                    kind: 'iroh_preview';
                    previewId: string;
                    machineId: string;
                } | undefined;
            }[] | undefined;
        };
    };
    readonly "localServices.preview.status": {
        v: 1;
        machineId: string;
        generatedAt: number;
        refreshState: 'error' | 'idle' | 'refreshing';
        resources: {
            previewId: string;
            machineId: string;
            owner: {
                kind: 'user';
                id: string;
            } | {
                kind: 'session';
                id: string;
            } | {
                kind: 'plugin';
                id: string;
            } | {
                kind: 'agent';
                id: string;
            };
            target: {
                scheme: 'http' | 'https';
                host: string;
                port: number;
            };
            initialPath: {
                pathname: string;
                search: string;
            };
            display: {
                title: string;
                addressLabel: string;
                label?: string | undefined;
                folderLabel?: string | undefined;
                iconToken?: string | undefined;
                tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                diagnostics?: Record<string, unknown> | undefined;
            };
            originMode: 'host';
            sessionId?: string | undefined;
            serviceTarget?: {
                machineId: string;
                kind: 'managed_service';
                managedServiceId: string;
                cwd: string;
                declaration: {
                    workspaceRefId: string;
                    selection: {
                        kind: 'manifest';
                        name: string;
                    } | {
                        kind: 'native';
                        source: {
                            kind: 'native';
                            tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                            file: string;
                            target: string;
                        } | {
                            kind: 'pluginNative';
                            adapter: {
                                pluginId: string;
                                localId: string;
                            };
                            file: string;
                            target: string;
                        };
                    };
                };
                workspaceId?: string | undefined;
            } | undefined;
            policy?: {
                allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                compressionPolicy: 'identity' | 'decode_reencode';
                redirectPolicy: 'preserve_host_origin';
                maxRequestBodyBytes: number;
                maxResponseBodyBytes: number;
            } | undefined;
            browserTarget?: {
                targetId: string;
                kind: 'localServicePreview';
                machineId: string;
                display?: {
                    title: string;
                    addressLabel?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                } | undefined;
                sessionId?: string | undefined;
            } | undefined;
        }[];
        diagnostics: Record<string, unknown>[];
        previews?: {
            previewId: string;
            resource: {
                previewId: string;
                machineId: string;
                owner: {
                    kind: 'user';
                    id: string;
                } | {
                    kind: 'session';
                    id: string;
                } | {
                    kind: 'plugin';
                    id: string;
                } | {
                    kind: 'agent';
                    id: string;
                };
                target: {
                    scheme: 'http' | 'https';
                    host: string;
                    port: number;
                };
                initialPath: {
                    pathname: string;
                    search: string;
                };
                display: {
                    title: string;
                    addressLabel: string;
                    label?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    diagnostics?: Record<string, unknown> | undefined;
                };
                originMode: 'host';
                sessionId?: string | undefined;
                serviceTarget?: {
                    machineId: string;
                    kind: 'managed_service';
                    managedServiceId: string;
                    cwd: string;
                    declaration: {
                        workspaceRefId: string;
                        selection: {
                            kind: 'manifest';
                            name: string;
                        } | {
                            kind: 'native';
                            source: {
                                kind: 'native';
                                tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                file: string;
                                target: string;
                            } | {
                                kind: 'pluginNative';
                                adapter: {
                                    pluginId: string;
                                    localId: string;
                                };
                                file: string;
                                target: string;
                            };
                        };
                    };
                    workspaceId?: string | undefined;
                } | undefined;
                policy?: {
                    allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                    cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                    compressionPolicy: 'identity' | 'decode_reencode';
                    redirectPolicy: 'preserve_host_origin';
                    maxRequestBodyBytes: number;
                    maxResponseBodyBytes: number;
                } | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | undefined;
            };
            accessUrl: string | null;
            expiresAt: number | null;
            diagnostics: {
                v: 1;
                code: 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'expired' | 'not_yet_valid' | 'revoked' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                severity: 'error' | 'info' | 'warning';
                scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                details: Record<string, unknown>;
                previewId?: string | undefined;
                publicExposureId?: string | undefined;
                emittedAtMs?: number | undefined;
            }[];
            accessUnavailableReasonCode?: 'preview_private_route_unavailable' | undefined;
            nativeDirect?: {
                v: 1;
                kind: 'iroh_preview';
                previewId: string;
                machineId: string;
            } | undefined;
        }[] | undefined;
    };
    readonly "localServices.preview.revoke": {
        protocolVersion: 1;
        previewId: string;
        revoked: boolean;
        snapshot: {
            v: 1;
            machineId: string;
            generatedAt: number;
            refreshState: 'error' | 'idle' | 'refreshing';
            resources: {
                previewId: string;
                machineId: string;
                owner: {
                    kind: 'user';
                    id: string;
                } | {
                    kind: 'session';
                    id: string;
                } | {
                    kind: 'plugin';
                    id: string;
                } | {
                    kind: 'agent';
                    id: string;
                };
                target: {
                    scheme: 'http' | 'https';
                    host: string;
                    port: number;
                };
                initialPath: {
                    pathname: string;
                    search: string;
                };
                display: {
                    title: string;
                    addressLabel: string;
                    label?: string | undefined;
                    folderLabel?: string | undefined;
                    iconToken?: string | undefined;
                    tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    diagnostics?: Record<string, unknown> | undefined;
                };
                originMode: 'host';
                sessionId?: string | undefined;
                serviceTarget?: {
                    machineId: string;
                    kind: 'managed_service';
                    managedServiceId: string;
                    cwd: string;
                    declaration: {
                        workspaceRefId: string;
                        selection: {
                            kind: 'manifest';
                            name: string;
                        } | {
                            kind: 'native';
                            source: {
                                kind: 'native';
                                tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                file: string;
                                target: string;
                            } | {
                                kind: 'pluginNative';
                                adapter: {
                                    pluginId: string;
                                    localId: string;
                                };
                                file: string;
                                target: string;
                            };
                        };
                    };
                    workspaceId?: string | undefined;
                } | undefined;
                policy?: {
                    allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                    cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                    compressionPolicy: 'identity' | 'decode_reencode';
                    redirectPolicy: 'preserve_host_origin';
                    maxRequestBodyBytes: number;
                    maxResponseBodyBytes: number;
                } | undefined;
                browserTarget?: {
                    targetId: string;
                    kind: 'localServicePreview';
                    machineId: string;
                    display?: {
                        title: string;
                        addressLabel?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                    } | undefined;
                    sessionId?: string | undefined;
                } | undefined;
            }[];
            diagnostics: Record<string, unknown>[];
            previews?: {
                previewId: string;
                resource: {
                    previewId: string;
                    machineId: string;
                    owner: {
                        kind: 'user';
                        id: string;
                    } | {
                        kind: 'session';
                        id: string;
                    } | {
                        kind: 'plugin';
                        id: string;
                    } | {
                        kind: 'agent';
                        id: string;
                    };
                    target: {
                        scheme: 'http' | 'https';
                        host: string;
                        port: number;
                    };
                    initialPath: {
                        pathname: string;
                        search: string;
                    };
                    display: {
                        title: string;
                        addressLabel: string;
                        label?: string | undefined;
                        folderLabel?: string | undefined;
                        iconToken?: string | undefined;
                        tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                        diagnostics?: Record<string, unknown> | undefined;
                    };
                    originMode: 'host';
                    sessionId?: string | undefined;
                    serviceTarget?: {
                        machineId: string;
                        kind: 'managed_service';
                        managedServiceId: string;
                        cwd: string;
                        declaration: {
                            workspaceRefId: string;
                            selection: {
                                kind: 'manifest';
                                name: string;
                            } | {
                                kind: 'native';
                                source: {
                                    kind: 'native';
                                    tool: 'package_script' | 'mise' | 'make' | 'just' | 'taskfile' | 'turbo' | 'compose' | 'procfile' | 'devbox' | 'devenv' | 'flox';
                                    file: string;
                                    target: string;
                                } | {
                                    kind: 'pluginNative';
                                    adapter: {
                                        pluginId: string;
                                        localId: string;
                                    };
                                    file: string;
                                    target: string;
                                };
                            };
                        };
                        workspaceId?: string | undefined;
                    } | undefined;
                    policy?: {
                        allowedMethods: ('GET' | 'HEAD' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS')[];
                        cookiePolicy: 'drop' | 'isolate' | 'rewrite';
                        compressionPolicy: 'identity' | 'decode_reencode';
                        redirectPolicy: 'preserve_host_origin';
                        maxRequestBodyBytes: number;
                        maxResponseBodyBytes: number;
                    } | undefined;
                    browserTarget?: {
                        targetId: string;
                        kind: 'localServicePreview';
                        machineId: string;
                        display?: {
                            title: string;
                            addressLabel?: string | undefined;
                            folderLabel?: string | undefined;
                            iconToken?: string | undefined;
                            tone?: 'success' | 'neutral' | 'info' | 'warning' | 'danger' | 'accent' | undefined;
                        } | undefined;
                        sessionId?: string | undefined;
                    } | undefined;
                };
                accessUrl: string | null;
                expiresAt: number | null;
                diagnostics: {
                    v: 1;
                    code: 'invalid_preview_resource' | 'preview_registration_failed' | 'preview_token_secret_missing' | 'preview_public_base_url_missing' | 'preview_not_found' | 'preview_token_missing' | 'token_mismatch' | 'binding_mismatch' | 'expired' | 'not_yet_valid' | 'revoked' | 'host_origin_unavailable' | 'https_required' | 'invalid_public_base_url' | 'path_mode_degraded' | 'path_mode_cookie_semantics_unsupported' | 'service_worker_unavailable_in_path_mode' | 'cookie_isolated' | 'cookie_stripped' | 'upstream_header_stripped' | 'credentials_stripped' | 'method_not_allowed' | 'preview_loop_detected' | 'request_body_too_large' | 'response_body_too_large' | 'response_header_too_large' | 'upstream_response_invalid' | 'upstream_stream_failed' | 'invalid_upgrade_request' | 'web_socket_unavailable' | 'pms_observability_unavailable' | 'pms_relay_unavailable' | 'dns_tls_not_ready' | 'public_policy_denied' | 'public_preview_expired' | 'public_preview_rate_limited' | 'public_preview_revoked';
                    severity: 'error' | 'info' | 'warning';
                    scope: 'privatePreview' | 'publicPreview' | 'previewProxy';
                    details: Record<string, unknown>;
                    previewId?: string | undefined;
                    publicExposureId?: string | undefined;
                    emittedAtMs?: number | undefined;
                }[];
                accessUnavailableReasonCode?: 'preview_private_route_unavailable' | undefined;
                nativeDirect?: {
                    v: 1;
                    kind: 'iroh_preview';
                    previewId: string;
                    machineId: string;
                } | undefined;
            }[] | undefined;
        };
    };
};
