// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type MessagingActionInputById = {
    readonly "session.message.send": {
        idempotencyKey: string;
        sessionId: string;
        message: string;
        recipient?: {
            kind: 'execution_run';
            runId: string;
        } | {
            kind: 'agent_team_member';
            teamId: string;
            memberId: string;
        } | {
            kind: 'agent_team_broadcast';
            teamId: string;
        } | undefined;
        source?: {
            sourceRef: string;
            sourceRevisionOrEpoch: string;
            remoteApprovalMaxScope: 'off' | 'request' | 'session';
            requestedPermissionCeiling: 'default' | 'read-only' | 'safe-yolo' | 'yolo' | 'plan';
            externalActor?: {
                kind: 'human' | 'bot';
                displayNameSnapshot?: string | undefined;
            } | undefined;
            contentProvenance?: 'original' | 'forwarded' | 'viaBot' | undefined;
        } | undefined;
        attachments?: {
            attachmentLocalId: string;
            value: {
                key: string;
                value: unknown;
                presentation: {
                    label: string;
                    description?: string | undefined;
                    icon?: 'file' | 'external' | 'search' | 'error' | 'check' | 'action' | 'browser' | 'copy' | 'globe' | 'info' | 'preview' | 'refresh' | 'settings' | 'terminal' | 'warning' | 'add' | 'back' | 'close' | 'forward' | 'more' | 'change-open' | 'change-complete' | 'issue' | 'bug' | 'pin' | 'conversations' | 'waveform' | 'desktop' | 'pause' | 'failure' | 'unavailable' | 'denied' | 'review' | 'attention' | 'escalating' | 'merge-ready' | 'mention' | 'assigned' | 'new' | 'waiting' | 'list' | 'board' | undefined;
                    tone?: 'success' | 'info' | 'warning' | 'neutral' | 'danger' | undefined;
                };
            };
        }[] | undefined;
        toolAnswerDelivery?: {
            toolCallId: string;
        } | undefined;
    } | {
        sessionId: string;
        kind: 'sessionSubagentLaunch';
        launch: {
            [x: string]: unknown;
            kind: 'agent_team_create';
            teamId: string;
            description?: string | undefined;
        } | {
            [x: string]: unknown;
            kind: 'agent_team_member_create';
            teamId: string;
            memberLabel: string;
            instructions: string;
            runInBackground?: boolean | undefined;
        };
        idempotencyKey: string;
    };
    readonly "session.worker.publish": {
        summary: string;
        deliverables?: ({
            kind: 'workspace_file';
            sessionId: string;
            path: string;
        } | {
            kind: 'artifact';
            artifactId: string;
        })[] | undefined;
    };
};
export type MessagingActionResultById = {
    readonly "session.message.send": {
        status: 'accepted';
        localId: string;
    } | {
        status: 'alreadyAccepted';
        localId: string;
    } | {
        status: 'rejected';
        code: 'session_input_invalid' | 'model_not_granted' | 'permission_mode_not_granted' | 'session_input_archived' | 'session_input_unauthorized' | 'session_input_target_unavailable' | 'session_input_target_update_required' | 'session_input_cancelled' | 'session_input_untrusted_assertion' | 'session_input_idempotency_conflict' | 'session_input_source_authority_mismatch' | 'session_input_permission_ceiling_rejected' | 'session_input_encryption_mode_mismatch';
    } | {
        status: 'outcomeUnknown';
        localId: string;
        code: string;
    } | {
        status: 'failed';
        localId: string;
        code: 'session_input_turn_failed';
    } | {
        status: 'cancelled';
        localId: string;
        code: 'session_input_turn_cancelled';
    };
    readonly "session.worker.publish": {
        sessionId: string;
        leadSessionId: string;
        localId: string;
    };
};
