// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type NotificationConfigurationActionInputById = {
    readonly "notifications.webhooks.list": Record<string, never>;
    readonly "notifications.webhooks.add": {
        url: string;
    };
    readonly "notifications.webhooks.update": {
        channelId: string;
        patch: {
            url?: string | undefined;
            enabled?: boolean | undefined;
            topics?: {
                ready?: boolean | undefined;
                permissionRequest?: boolean | undefined;
                userActionRequest?: boolean | undefined;
            } | undefined;
            readyIncludeMessageText?: boolean | undefined;
            requestIncludeMessageText?: boolean | undefined;
        };
    };
    readonly "notifications.webhooks.remove": {
        channelId: string;
    };
    readonly "notifications.webhooks.signingSecret.set": {
        channelId: string;
        secret: string;
    };
    readonly "notifications.webhooks.signingSecret.clear": {
        channelId: string;
    };
};
export type NotificationConfigurationActionResultById = {
    readonly "notifications.webhooks.list": {
        items: {
            channelId: string;
            url: string;
            enabled: boolean;
            signingSecretConfigured: boolean;
            topics: {
                ready: boolean;
                permissionRequest: boolean;
                userActionRequest: boolean;
            };
            readyIncludeMessageText: boolean;
            requestIncludeMessageText: boolean;
        }[];
    };
    readonly "notifications.webhooks.add": {
        channelId: string;
    };
    readonly "notifications.webhooks.update": {
        channelId: string;
    };
    readonly "notifications.webhooks.remove": {
        channelId: string;
    };
    readonly "notifications.webhooks.signingSecret.set": {
        channelId: string;
    };
    readonly "notifications.webhooks.signingSecret.clear": {
        channelId: string;
    };
};
