// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type ObservationActionInputById = {
    readonly wait: {
        target: {
            kind: 'execution_run';
            serverId: string;
            machineId: string;
            runId: string;
            sessionId?: string | undefined;
        } | {
            kind: 'action_operation';
            serverId: string;
            machineId: string;
            operationId: string;
        } | {
            kind: 'session';
            serverId: string;
            sessionId: string;
        } | {
            kind: 'workflow_run';
            serverId: string;
            runId: string;
        } | {
            kind: 'plugin_source';
            serverId: string;
            pluginId: string;
            sourceId: string;
        };
        condition: {
            kind: 'terminal' | 'needs_attention' | 'terminal_or_needs_attention' | 'idle' | 'ready';
        } | {
            kind: 'turn_terminal';
            turnId: string;
        } | {
            kind: 'plugin';
            actionLocalId: string;
            condition: string;
        };
        timeout?: {
            durationMs: number;
        } | undefined;
    };
};
export type ObservationActionResultById = {
    readonly wait: {
        target: {
            kind: 'execution_run';
            serverId: string;
            machineId: string;
            runId: string;
            sessionId?: string | undefined;
        } | {
            kind: 'action_operation';
            serverId: string;
            machineId: string;
            operationId: string;
        } | {
            kind: 'session';
            serverId: string;
            sessionId: string;
        } | {
            kind: 'workflow_run';
            serverId: string;
            runId: string;
        } | {
            kind: 'plugin_source';
            serverId: string;
            pluginId: string;
            sourceId: string;
        };
        condition: {
            kind: 'terminal' | 'needs_attention' | 'terminal_or_needs_attention' | 'idle' | 'ready';
        } | {
            kind: 'turn_terminal';
            turnId: string;
        } | {
            kind: 'plugin';
            actionLocalId: string;
            condition: string;
        };
        disposition: 'matched' | 'observation_timeout' | 'cancelled' | 'target_unavailable' | 'permission_denied' | 'unsupported_condition' | 'disconnected' | 'outcome_uncertain';
        snapshot?: string | number | boolean | readonly JsonValue[] | {
            readonly [key: string]: JsonValue;
        } | null | undefined;
    };
};
