// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type PromptLibraryActionInputById = {
    readonly "prompt_doc.get": {
        artifactId: string;
    };
    readonly "prompt_doc.create": {
        title: string;
        markdown: string;
        folderId?: string | null | undefined;
        tags?: string[] | undefined;
        favorite?: boolean | undefined;
    } | {
        starter: 'happier_guide';
    };
    readonly "prompt_doc.favorite.set": {
        artifactId: string;
        favorite: boolean;
    };
    readonly "prompts.library.list": {
        query?: string | undefined;
        includeBundles?: false | undefined;
    };
    readonly "prompts.stack.update": {
        surface: 'coding' | 'voice';
        expectedRevision: number | 'absent';
        intent: {
            kind: 'attach';
            entry: {
                id: string;
                ref: {
                    kind: 'doc' | 'bundle';
                    artifactId: string;
                    serverId?: string | undefined;
                };
                enabled?: boolean | undefined;
                placement?: 'system_append' | 'composer_insert' | 'skill_instructions' | 'provider_asset' | undefined;
                maxChars?: number | undefined;
                required?: boolean | undefined;
            };
        } | {
            kind: 'detach';
            entryId: string;
        } | {
            kind: 'reorder';
            entryId: string;
            siblingId: string;
            position: 'before' | 'after';
        } | {
            kind: 'set_budget';
            entryId: string;
            maxChars: number | null;
        } | {
            kind: 'set_enabled';
            entryId: string;
            enabled: boolean;
        };
    };
    readonly "prompt_doc.update": {
        artifactId: string;
        title: string;
        markdown: string;
        expectedRevision?: {
            headerVersion: number;
            bodyVersion: number;
        } | undefined;
        folderId?: string | null | undefined;
        tags?: string[] | undefined;
    };
    readonly "prompt_bundle.update": {
        [x: string]: unknown;
        artifactId: string;
        title: string;
        skillMarkdown: string;
        folderId?: string | null | undefined;
        tags?: string[] | undefined;
    };
    readonly "prompt_asset.export": {
        [x: string]: unknown;
        artifactId: string;
        machineId: string;
        assetTypeId: string;
        scope: 'user' | 'project';
        directory?: string | undefined;
        targetPath?: string | undefined;
        targetName?: string | undefined;
        installMode?: 'copy' | 'symlink' | undefined;
    };
    readonly "prompt_registry.install": {
        [x: string]: unknown;
        machineId: string;
        sourceId: string;
        itemId: string;
        configuredSources?: {
            [x: string]: unknown;
            id: string;
            adapterId: string;
            title: string;
            enabled?: boolean | undefined;
            config?: Record<string, unknown> | undefined;
        }[] | undefined;
        installTarget?: {
            assetTypeId: string;
            scope: 'user' | 'project';
            targetName: string;
            directory?: string | undefined;
            installMode?: 'copy' | 'symlink' | undefined;
        } | undefined;
    };
    readonly "prompts.invocation.create": {
        token: string;
        title: string;
        target: {
            artifactId: string;
            kind: 'doc';
            serverId?: string | undefined;
        };
        behavior?: 'insert' | 'insert_on_send' | 'insert_and_send' | undefined;
        allowArgs?: boolean | undefined;
        availableIn?: 'global' | 'session_only' | undefined;
    };
};
export type PromptLibraryActionResultById = {
    readonly "prompt_doc.get": {
        ok: true;
        artifactId: string;
        title: string;
        markdown: string;
        revision: {
            headerVersion: number;
            bodyVersion: number;
        };
    };
    readonly "prompt_doc.create": {
        ok: true;
        artifactId: string;
    };
    readonly "prompt_doc.favorite.set": {
        ok: true;
        artifactId: string;
    };
    readonly "prompts.library.list": {
        coverage: 'complete' | 'partial' | 'unavailable';
        items: {
            artifactId: string;
            title: string;
            folderId: string | null;
            tags: string[];
            favorite: boolean;
            updatedAtMs: number;
        }[];
    };
    readonly "prompts.stack.update": {
        status: 'updated';
        revision: number;
    } | {
        status: 'conflict';
        revision: number;
    } | {
        status: 'unavailable';
        reason: string;
    } | {
        status: 'invalid';
        reason: 'entry_conflict' | 'entry_not_found' | 'invalid_parameters';
    };
    readonly "prompt_doc.update": {
        ok: true;
        artifactId: string;
        revision?: {
            headerVersion: number;
            bodyVersion: number;
        } | undefined;
    };
    readonly "prompt_bundle.update": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompt_asset.export": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompt_registry.install": string | number | boolean | readonly JsonValue[] | {
        readonly [key: string]: JsonValue;
    } | null;
    readonly "prompts.invocation.create": {
        status: 'updated';
        invocationId: string;
        token: string;
        revision: number;
    } | {
        status: 'invalid';
        reason: 'invalid' | 'reserved' | 'actionCollision' | 'duplicate';
    } | {
        status: 'conflict';
        revision: number;
    } | {
        status: 'unavailable';
        reason: string;
    };
};
