// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type RolesActionInputById = {
    readonly "session.role.set": {
        sessionId: string;
        roleId: string;
    };
    readonly "session.roles.override.set": {
        roleId: string;
        sessionId: string;
        engine?: {
            agentTargetKey: string;
            modelId?: string | undefined;
            effort?: string | undefined;
        } | undefined;
        runsAs?: {
            kind: 'session';
        } | {
            kind: 'background_run';
            intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
        } | undefined;
        profileId?: string | undefined;
        workspaceWrites?: 'allow' | 'deny' | undefined;
        secondOpinion?: 'off' | 'encouraged' | undefined;
    };
    readonly "session.roles.override.clear": {
        sessionId: string;
        roleId: string;
    };
    readonly "session.roles.add": {
        sessionId: string;
        roleId: string;
        role: {
            name: string;
            instructions: string;
            runsAs: {
                kind: 'session';
            } | {
                kind: 'background_run';
                intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
            };
            workspaceWrites: 'allow' | 'deny';
            secondOpinion: 'off' | 'encouraged';
            enabled: boolean;
            engine?: {
                agentTargetKey: string;
                modelId?: string | undefined;
                effort?: string | undefined;
            } | undefined;
            profileId?: string | undefined;
        };
    };
    readonly "session.roles.remove": {
        sessionId: string;
        roleId: string;
    };
    readonly "session.notes.set": {
        sessionId: string;
        notes: string;
    };
    readonly "session.roles.apply_to_reports": {
        sessionId: string;
    };
    readonly "roles.list": Record<string, never>;
    readonly "roles.get": {
        roleId: string;
    };
    readonly "roles.create": {
        role: {
            name: string;
            instructions: string;
            runsAs: {
                kind: 'session';
            } | {
                kind: 'background_run';
                intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
            };
            workspaceWrites: 'allow' | 'deny';
            secondOpinion: 'off' | 'encouraged';
            enabled: boolean;
            engine?: {
                agentTargetKey: string;
                modelId?: string | undefined;
                effort?: string | undefined;
            } | undefined;
            profileId?: string | undefined;
        };
        roleId?: string | undefined;
    };
    readonly "roles.update": {
        roleId: string;
        expectedRevision: {
            headerVersion: number;
            bodyVersion: number;
        };
        role: {
            name: string;
            instructions: string;
            runsAs: {
                kind: 'session';
            } | {
                kind: 'background_run';
                intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
            };
            workspaceWrites: 'allow' | 'deny';
            secondOpinion: 'off' | 'encouraged';
            enabled: boolean;
            engine?: {
                agentTargetKey: string;
                modelId?: string | undefined;
                effort?: string | undefined;
            } | undefined;
            profileId?: string | undefined;
        };
    };
    readonly "roles.delete": {
        roleId: string;
        expectedRevision: {
            headerVersion: number;
            bodyVersion: number;
        };
    };
    readonly "roles.override.set": {
        roleId: string;
        engine?: {
            agentTargetKey: string;
            modelId?: string | undefined;
            effort?: string | undefined;
        } | undefined;
        runsAs?: {
            kind: 'session';
        } | {
            kind: 'background_run';
            intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
        } | undefined;
        profileId?: string | undefined;
        workspaceWrites?: 'allow' | 'deny' | undefined;
        secondOpinion?: 'off' | 'encouraged' | undefined;
        instructionsOverride?: string | undefined;
    };
    readonly "roles.override.reset": {
        roleId: string;
    };
};
export type RolesActionResultById = {
    readonly "session.role.set": {
        updated: true;
    };
    readonly "session.roles.override.set": {
        updated: true;
    };
    readonly "session.roles.override.clear": {
        updated: true;
    };
    readonly "session.roles.add": {
        updated: true;
    };
    readonly "session.roles.remove": {
        updated: true;
    };
    readonly "session.notes.set": {
        updated: true;
    };
    readonly "session.roles.apply_to_reports": {
        updatedSessionIds: string[];
    };
    readonly "roles.list": {
        items: {
            roleId: string;
            role: {
                name: string;
                instructions: string;
                runsAs: {
                    kind: 'session';
                } | {
                    kind: 'background_run';
                    intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
                };
                workspaceWrites: 'allow' | 'deny';
                secondOpinion: 'off' | 'encouraged';
                enabled: boolean;
                engine?: {
                    agentTargetKey: string;
                    modelId?: string | undefined;
                    effort?: string | undefined;
                } | undefined;
                profileId?: string | undefined;
            };
            shared: boolean;
            viewOnly: boolean;
            migratedFromV0_2: boolean;
            revision?: {
                headerVersion: number;
                bodyVersion: number;
            } | undefined;
        }[];
        diagnostics: ({
            source: 'legacy-guidance';
            reason: 'unavailable' | 'invalid_root' | 'invalid_entry' | 'duplicate_id';
            index?: number | undefined;
            entryId?: string | undefined;
        } | {
            source: 'artifact';
            artifactId: string;
            reason: 'unavailable' | 'invalid_stored_content';
        })[];
    };
    readonly "roles.get": {
        roleId: string;
        role: {
            name: string;
            instructions: string;
            runsAs: {
                kind: 'session';
            } | {
                kind: 'background_run';
                intent: 'review' | 'plan' | 'delegate' | 'agent' | 'task' | 'voice_agent' | 'memory_hints' | 'scm_commit_message' | 'scm_diff_summary';
            };
            workspaceWrites: 'allow' | 'deny';
            secondOpinion: 'off' | 'encouraged';
            enabled: boolean;
            engine?: {
                agentTargetKey: string;
                modelId?: string | undefined;
                effort?: string | undefined;
            } | undefined;
            profileId?: string | undefined;
        };
        shared: boolean;
        viewOnly: boolean;
        migratedFromV0_2: boolean;
        revision?: {
            headerVersion: number;
            bodyVersion: number;
        } | undefined;
    };
    readonly "roles.create": {
        roleId: string;
        revision: {
            headerVersion: number;
            bodyVersion: number;
        };
    };
    readonly "roles.update": {
        roleId: string;
        revision: {
            headerVersion: number;
            bodyVersion: number;
        };
    };
    readonly "roles.delete": {
        deleted: true;
    };
    readonly "roles.override.set": {
        updated: true;
    };
    readonly "roles.override.reset": {
        updated: true;
    };
};
