// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type SessionAttentionActionInputById = {
    readonly "session.attention.set": {
        sessionId: string;
        standing?: boolean | null | undefined;
        remindAt?: number | null | undefined;
    };
};
export type SessionAttentionActionResultById = {
    readonly "session.attention.set": {
        standing: {
            sessionId: string;
            standing: boolean;
            updatedAt: number;
            remindAt?: number | undefined;
        } | null;
    };
};
