// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.

import type { JsonValue } from '../../identity.js';

export type SettingsDeclarationsActionInputById = {
    readonly "settings.list": {
        pageId?: string | undefined;
    };
    readonly "settings.get": {
        anchor: string;
    };
    readonly "settings.set": {
        anchor: string;
        value: unknown;
    };
    readonly "settings.invoke": {
        anchor: string;
        input?: {
            kind: 'model_pack';
            packId: string;
            machineId?: string | undefined;
        } | {
            kind: 'voice_preview';
            voiceId: string;
        } | {
            kind: 'diagnostics_enabled';
            enabled: boolean;
        } | {
            kind: 'diagnostics_export';
            artifactId: string;
            machineId?: string | undefined;
        } | {
            kind: 'diagnostics_session';
            sessionId: string;
            machineId: string;
        } | {
            kind: 'diagnostics_revocation';
            key: string;
            revision: number;
        } | undefined;
    };
};
export type SettingsDeclarationsActionResultById = {
    readonly "settings.list": {
        items: {
            anchor: string;
            pageId: string;
            title: string;
            readable: boolean;
            writable: boolean;
            sensitive: boolean;
            description?: string | undefined;
            storageScope?: 'account' | 'local' | undefined;
            allowedValues?: (string | number | boolean | null)[] | undefined;
            operation?: {
                actionId: 'settings.invoke';
                requiresHumanInteraction: boolean;
                requiresApproval?: boolean | undefined;
            } | undefined;
            unavailableReason?: 'sensitive' | 'not_bound' | 'read_only' | 'unsupported_host' | 'feature_disabled' | undefined;
        }[];
    };
    readonly "settings.get": {
        anchor: string;
        value: string | number | boolean | readonly JsonValue[] | {
            readonly [key: string]: JsonValue;
        } | null;
    } | {
        anchor: string;
        unset: true;
    };
    readonly "settings.set": {
        anchor: string;
        value: string | number | boolean | readonly JsonValue[] | {
            readonly [key: string]: JsonValue;
        } | null;
    };
    readonly "settings.invoke": {
        anchor: string;
        status: 'completed' | 'cancelled' | 'unavailable' | 'interaction_opened';
        reason?: string | undefined;
        value?: string | number | boolean | readonly JsonValue[] | {
            readonly [key: string]: JsonValue;
        } | null | undefined;
    };
};
