// This file is generated by scripts/generateActionTypeMap.mjs. Do not edit by hand.
// Type-only projection of Protocol-owned Action DTO declarations.


// Generated by packages/plugin-sdk/scripts/generateActionTypeMap.mjs. Do not edit by hand.
export type TodoSessionLinkActionInputById = {
    readonly "todos.session.link": {
        scope: {
            serverId: string;
            accountId: string;
        };
        taskId: string;
        session: {
            serverId: string;
            accountId: string;
            sessionId: string;
        };
    };
};
export type TodoSessionLinkActionResultById = {
    readonly "todos.session.link": {
        status: 'linked';
    } | {
        status: 'unavailable';
    } | {
        status: 'refused';
        reason: 'task_deleted' | 'task_scope_mismatch' | 'invalid_input';
    } | {
        status: 'unknown';
        reason: 'task_link_failed';
    };
};
