import { z } from 'zod';

import type { RuntimeActionIdV1 } from '../actionIds.js';
import {
  BrowserAutomationActionRequestV1Schema,
  BrowserAutomationActionResultV1Schema,
  BrowserAutomationCancelActiveInputV1Schema,
  BrowserAutomationCancelActiveResultV1Schema,
  BrowserAutomationTimelineV1Schema,
} from '../../browser/automation/v1.js';
import type { BrowserAutomationActionKindV1 } from '../../browser/automation/v1.js';
import {
  BrowserCloseViewCommandV1Schema,
  BrowserCommandDispatchResultV1Schema,
  BrowserFocusViewCommandV1Schema,
  BrowserGoBackCommandV1Schema,
  BrowserGoForwardCommandV1Schema,
  BrowserNavigateCommandV1Schema,
  BrowserOpenViewCommandV1Schema,
  BrowserReloadCommandV1Schema,
  BrowserSetTargetCommandV1Schema,
  BrowserStopCommandV1Schema,
} from '../../browser/control/v1.js';
import {
  BrowserAnnotationStyleIntentV1Schema,
  BrowserContextAttachmentV1Schema,
  BrowserContextCommandV1Schema,
  BrowserContextRouteResultV1Schema,
} from '../../browser/context/v1.js';
import {
  BrowserDiagnosticsElementPickerRequestV1Schema,
  BrowserDiagnosticsElementPickerResultV1Schema,
  BrowserDiagnosticsEvalRequestV1Schema,
  BrowserDiagnosticsEvalResultV1Schema,
  BrowserDiagnosticsGetPropertiesRequestV1Schema,
  BrowserDiagnosticsGetPropertiesResultV1Schema,
  BrowserDiagnosticsReleaseObjectGroupRequestV1Schema,
  BrowserDiagnosticsReleaseObjectGroupResultV1Schema,
  BrowserDiagnosticsSnapshotV1Schema,
} from '../../browser/diagnostics/v1.js';
import {
  BrowserRecordingSessionV1Schema,
  DaemonBrowserRecordingCancelInputV1Schema,
  DaemonBrowserRecordingCleanupInputV1Schema,
  DaemonBrowserRecordingCleanupResultV1Schema,
  DaemonBrowserRecordingListInputV1Schema,
  DaemonBrowserRecordingStartInputV1Schema,
  DaemonBrowserRecordingStartResultV1Schema,
  DaemonBrowserRecordingStatusInputV1Schema,
  DaemonBrowserRecordingStopInputV1Schema,
  DaemonBrowserRecordingStopResultV1Schema,
  DaemonBrowserRecordingTerminalResultV1Schema,
} from '../../browser/recording/v1.js';
import type { RuntimeActionSpecFamily } from './common.js';

const BrowserDiagnosticsClearResultV1Schema = z.object({
  ok: z.literal(true),
}).strict();

const BrowserDiagnosticsPauseResultV1Schema = z.object({
  ok: z.literal(true),
  status: z.literal('paused'),
  viewId: z.string().trim().min(1).max(256),
}).strict();

const BrowserDiagnosticsResumeResultV1Schema = z.object({
  ok: z.literal(true),
  status: z.literal('resumed'),
  viewId: z.string().trim().min(1).max(256),
}).strict();

const BrowserRecordingAttachToComposerResultV1Schema = z.object({
  ok: z.literal(true),
  attachmentId: z.string().trim().min(1).max(256),
}).strict();

const BrowserRecordingListResultV1Schema = z.array(BrowserRecordingSessionV1Schema);

type BrowserRuntimeActionId = Extract<RuntimeActionIdV1, `browser.${string}`>;

function createBrowserAutomationActionInputSchema<
  const TActionKind extends BrowserAutomationActionKindV1,
>(actionKind: TActionKind) {
  return z.intersection(
    BrowserAutomationActionRequestV1Schema,
    z.object({ actionKind: z.literal(actionKind) }).passthrough(),
  );
}

const RuntimeBrowserViewInputSchema = z
  .object({
    browserSessionId: z.string().trim().min(1).max(256),
    viewId: z.string().trim().min(1).max(256),
  })
  .passthrough();

const RuntimeBrowserContextActionInputSchema = RuntimeBrowserViewInputSchema.extend({
  navigationGeneration: z.number().int().nonnegative().optional(),
  contextId: z.string().trim().min(1).max(256).optional(),
  annotationId: z.string().trim().min(1).max(256).optional(),
  command: BrowserContextCommandV1Schema.optional(),
  comment: z.string().trim().min(1).max(2048).optional(),
  styleIntent: BrowserAnnotationStyleIntentV1Schema.optional(),
}).passthrough();

const RuntimeBrowserRecordingAttachInputSchema = z
  .object({
    recordingId: z.string().trim().min(1).max(256),
    sessionId: z.string().trim().min(1).max(256).optional(),
  })
  .passthrough();

export const BROWSER_RUNTIME_ACTION_TITLES: Readonly<Partial<Record<RuntimeActionIdV1, string>>> = Object.freeze({
  'browser.view.open': 'Open browser view',
  'browser.view.close': 'Close browser view',
  'browser.view.focus': 'Focus browser view',
  'browser.target.set': 'Set browser target',
  'browser.navigate': 'Navigate browser',
  'browser.reload': 'Reload browser',
  'browser.goBack': 'Go back in browser',
  'browser.goForward': 'Go forward in browser',
  'browser.stop': 'Stop browser load',
  'browser.diagnostics.snapshot': 'Get browser diagnostics snapshot',
  'browser.diagnostics.clear': 'Clear browser diagnostics',
  'browser.diagnostics.pause': 'Pause browser diagnostics',
  'browser.diagnostics.resume': 'Resume browser diagnostics',
  'browser.diagnostics.eval': 'Evaluate browser diagnostics expression',
  'browser.diagnostics.getProperties': 'Get browser remote object properties',
  'browser.diagnostics.releaseObjectGroup': 'Release browser remote object group',
  'browser.diagnostics.elementPicker.start': 'Start browser element picker',
  'browser.diagnostics.elementPicker.cancel': 'Cancel browser element picker',
  'browser.context.capturePage': 'Capture browser page context',
  'browser.context.captureScreenshot': 'Capture browser screenshot context',
  'browser.context.captureSelectedElement': 'Capture selected browser element',
  'browser.context.captureNetworkSummary': 'Capture browser network summary',
  'browser.context.captureConsoleSummary': 'Capture browser console summary',
  'browser.context.annotation.start': 'Start browser annotation',
  'browser.context.annotation.cancel': 'Cancel browser annotation',
  'browser.context.annotation.captureRegion': 'Capture browser annotation region',
  'browser.context.annotation.captureElement': 'Capture browser annotation element',
  'browser.context.annotation.attachComment': 'Attach browser annotation comment',
  'browser.context.annotation.attachStroke': 'Attach browser annotation stroke',
  'browser.context.annotation.attachStyleIntent': 'Attach browser annotation style intent',
  'browser.context.attachToComposer': 'Attach browser context to composer',
  'browser.context.attachToAgentTurn': 'Attach browser context to agent turn',
  'browser.context.clear': 'Clear browser context',
  'browser.automation.status': 'Get browser automation status',
  'browser.automation.snapshot': 'Capture browser automation snapshot',
  'browser.automation.semanticSnapshot': 'Capture browser semantic snapshot',
  'browser.automation.queryElements': 'Query browser elements',
  'browser.automation.waitFor': 'Wait for browser condition',
  'browser.automation.timeline.get': 'Get browser automation timeline',
  'browser.automation.cancelActive': 'Cancel active browser automation',
  'browser.automation.navigate': 'Automate browser navigation',
  'browser.automation.reload': 'Automate browser reload',
  'browser.automation.goBack': 'Automate browser back navigation',
  'browser.automation.goForward': 'Automate browser forward navigation',
  'browser.automation.click': 'Click browser element',
  'browser.automation.tap': 'Tap browser surface',
  'browser.automation.type': 'Type into browser',
  'browser.automation.press': 'Press browser key',
  'browser.automation.scroll': 'Scroll browser surface',
  'browser.automation.hover': 'Hover browser element',
  'browser.automation.focus': 'Focus browser element',
  'browser.automation.select': 'Select browser option',
  'browser.automation.setValue': 'Set browser field value',
  'browser.automation.upload': 'Upload files to browser input',
  'browser.automation.drag': 'Drag between browser elements',
  'browser.recording.start': 'Start browser recording',
  'browser.recording.stop': 'Stop browser recording',
  'browser.recording.cancel': 'Cancel browser recording',
  'browser.recording.status': 'Get browser recording status',
  'browser.recording.listForView': 'List browser recordings for view',
  'browser.recording.discard': 'Discard browser recording',
  'browser.recording.cleanupExpired': 'Clean up expired browser recordings',
  'browser.recording.attachToComposer': 'Attach browser recording to composer',
});

export const BROWSER_RUNTIME_ACTION_DESCRIPTIONS: Readonly<Partial<Record<RuntimeActionIdV1, string>>> = Object.freeze({
  'browser.view.open': 'Open a browser view inside an existing browser session.',
  'browser.view.close': 'Close a browser view and detach it from its session.',
  'browser.view.focus': 'Bring a browser view to the foreground of its session.',
  'browser.target.set': 'Point a browser view at a launch target or URL.',
  'browser.navigate': 'Navigate a browser view to a URL.',
  'browser.reload': 'Reload the current page in a browser view.',
  'browser.goBack': 'Navigate back in a browser view history.',
  'browser.goForward': 'Navigate forward in a browser view history.',
  'browser.stop': 'Stop the in-progress page load in a browser view.',
  'browser.context.capturePage': 'Capture the current browser page as shareable context.',
  'browser.context.captureScreenshot': 'Capture a screenshot of the browser view as context.',
  'browser.context.captureSelectedElement': 'Capture the selected browser element as context.',
  'browser.context.captureNetworkSummary': 'Capture a redacted summary of recent browser network activity.',
  'browser.context.captureConsoleSummary': 'Capture a redacted summary of recent browser console output.',
  'browser.context.annotation.start': 'Start an in-page browser annotation session.',
  'browser.context.annotation.cancel': 'Cancel the active browser annotation session.',
  'browser.context.annotation.captureRegion': 'Capture a cropped region for the active browser annotation.',
  'browser.context.annotation.captureElement': 'Capture a selected element for the active browser annotation.',
  'browser.context.annotation.attachComment': 'Attach a comment to the active browser annotation.',
  'browser.context.annotation.attachStroke': 'Attach a freehand stroke to the active browser annotation.',
  'browser.context.annotation.attachStyleIntent': 'Set the drawing style for the active browser annotation.',
  'browser.automation.status': 'Read the current browser automation status.',
  'browser.automation.snapshot': 'Capture an automation snapshot of the browser view.',
  'browser.automation.semanticSnapshot': 'Capture a semantic accessibility snapshot of the browser view.',
  'browser.automation.queryElements': 'Query elements in the browser view by selector or role.',
  'browser.automation.waitFor': 'Wait for a browser condition before continuing automation.',
  'browser.automation.timeline.get': 'Read the recorded browser automation action timeline.',
  'browser.automation.cancelActive': 'Cancel the active browser automation operation.',
  'browser.automation.navigate': 'Automate navigation of the browser view to a URL.',
  'browser.automation.reload': 'Automate reloading the current browser page.',
  'browser.automation.goBack': 'Automate navigating back in the browser view.',
  'browser.automation.goForward': 'Automate navigating forward in the browser view.',
  'browser.automation.click': 'Automate clicking a browser element.',
  'browser.automation.tap': 'Automate tapping the browser surface.',
  'browser.automation.type': 'Automate typing text into the browser view.',
  'browser.automation.press': 'Automate pressing a key in the browser view.',
  'browser.automation.scroll': 'Automate scrolling the browser surface.',
  'browser.automation.hover': 'Automate hovering over a browser element.',
  'browser.automation.focus': 'Automate focusing a browser element.',
  'browser.automation.select': 'Automate selecting an option in the browser view.',
  'browser.automation.setValue': 'Automate setting the value of a browser field.',
  'browser.automation.upload': 'Attach one or more files to a browser file input.',
  'browser.automation.drag': 'Drag a browser element onto a drop target.',
  'browser.recording.attachToComposer': 'Attach a captured browser recording to the message composer.',
});

/**
 * One concrete schema row per backed browser Action. This is deliberately a
 * data projection rather than a prefix switch so a newly public Action keeps
 * its exact Zod input/output carrier in generated API and Plugin maps.
 */
export const BROWSER_RUNTIME_ACTION_INPUT_SCHEMAS = Object.freeze({
  'browser.view.open': BrowserOpenViewCommandV1Schema,
  'browser.view.close': BrowserCloseViewCommandV1Schema,
  'browser.view.focus': BrowserFocusViewCommandV1Schema,
  'browser.target.set': BrowserSetTargetCommandV1Schema,
  'browser.navigate': BrowserNavigateCommandV1Schema,
  'browser.reload': BrowserReloadCommandV1Schema,
  'browser.goBack': BrowserGoBackCommandV1Schema,
  'browser.goForward': BrowserGoForwardCommandV1Schema,
  'browser.stop': BrowserStopCommandV1Schema,
  'browser.diagnostics.snapshot': RuntimeBrowserViewInputSchema,
  'browser.diagnostics.clear': RuntimeBrowserViewInputSchema,
  'browser.diagnostics.pause': RuntimeBrowserViewInputSchema,
  'browser.diagnostics.resume': RuntimeBrowserViewInputSchema,
  'browser.diagnostics.eval': BrowserDiagnosticsEvalRequestV1Schema,
  'browser.diagnostics.getProperties': BrowserDiagnosticsGetPropertiesRequestV1Schema,
  'browser.diagnostics.releaseObjectGroup': BrowserDiagnosticsReleaseObjectGroupRequestV1Schema,
  'browser.diagnostics.elementPicker.start': BrowserDiagnosticsElementPickerRequestV1Schema,
  'browser.diagnostics.elementPicker.cancel': BrowserDiagnosticsElementPickerRequestV1Schema,
  'browser.context.capturePage': RuntimeBrowserContextActionInputSchema,
  'browser.context.captureScreenshot': RuntimeBrowserContextActionInputSchema,
  'browser.context.captureSelectedElement': RuntimeBrowserContextActionInputSchema,
  'browser.context.captureNetworkSummary': RuntimeBrowserContextActionInputSchema,
  'browser.context.captureConsoleSummary': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.start': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.cancel': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.captureRegion': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.captureElement': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.attachComment': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.attachStroke': RuntimeBrowserContextActionInputSchema,
  'browser.context.annotation.attachStyleIntent': RuntimeBrowserContextActionInputSchema,
  'browser.context.attachToComposer': RuntimeBrowserContextActionInputSchema,
  'browser.context.attachToAgentTurn': RuntimeBrowserContextActionInputSchema,
  'browser.context.clear': RuntimeBrowserContextActionInputSchema,
  'browser.automation.status': createBrowserAutomationActionInputSchema('getStatus'),
  'browser.automation.snapshot': createBrowserAutomationActionInputSchema('snapshot'),
  'browser.automation.semanticSnapshot': createBrowserAutomationActionInputSchema('semanticSnapshot'),
  'browser.automation.queryElements': createBrowserAutomationActionInputSchema('queryElements'),
  'browser.automation.waitFor': createBrowserAutomationActionInputSchema('waitFor'),
  'browser.automation.timeline.get': createBrowserAutomationActionInputSchema('getActionTimeline'),
  'browser.automation.cancelActive': BrowserAutomationCancelActiveInputV1Schema,
  'browser.automation.navigate': createBrowserAutomationActionInputSchema('navigate'),
  'browser.automation.reload': createBrowserAutomationActionInputSchema('reload'),
  'browser.automation.goBack': createBrowserAutomationActionInputSchema('goBack'),
  'browser.automation.goForward': createBrowserAutomationActionInputSchema('goForward'),
  'browser.automation.click': createBrowserAutomationActionInputSchema('click'),
  'browser.automation.tap': createBrowserAutomationActionInputSchema('tap'),
  'browser.automation.type': createBrowserAutomationActionInputSchema('type'),
  'browser.automation.press': createBrowserAutomationActionInputSchema('press'),
  'browser.automation.scroll': createBrowserAutomationActionInputSchema('scroll'),
  'browser.automation.hover': createBrowserAutomationActionInputSchema('hover'),
  'browser.automation.focus': createBrowserAutomationActionInputSchema('focus'),
  'browser.automation.select': createBrowserAutomationActionInputSchema('select'),
  'browser.automation.setValue': createBrowserAutomationActionInputSchema('setValue'),
  'browser.automation.upload': createBrowserAutomationActionInputSchema('upload'),
  'browser.automation.drag': createBrowserAutomationActionInputSchema('drag'),
  'browser.recording.start': DaemonBrowserRecordingStartInputV1Schema,
  'browser.recording.stop': DaemonBrowserRecordingStopInputV1Schema,
  'browser.recording.cancel': DaemonBrowserRecordingCancelInputV1Schema,
  'browser.recording.status': DaemonBrowserRecordingStatusInputV1Schema,
  'browser.recording.listForView': DaemonBrowserRecordingListInputV1Schema,
  'browser.recording.discard': DaemonBrowserRecordingCancelInputV1Schema,
  'browser.recording.cleanupExpired': DaemonBrowserRecordingCleanupInputV1Schema,
  'browser.recording.attachToComposer': RuntimeBrowserRecordingAttachInputSchema,
} as const satisfies Readonly<Record<BrowserRuntimeActionId, z.ZodTypeAny>>);

export const BROWSER_RUNTIME_ACTION_OUTPUT_SCHEMAS = Object.freeze({
  'browser.view.open': BrowserCommandDispatchResultV1Schema,
  'browser.view.close': BrowserCommandDispatchResultV1Schema,
  'browser.view.focus': BrowserCommandDispatchResultV1Schema,
  'browser.target.set': BrowserCommandDispatchResultV1Schema,
  'browser.navigate': BrowserCommandDispatchResultV1Schema,
  'browser.reload': BrowserCommandDispatchResultV1Schema,
  'browser.goBack': BrowserCommandDispatchResultV1Schema,
  'browser.goForward': BrowserCommandDispatchResultV1Schema,
  'browser.stop': BrowserCommandDispatchResultV1Schema,
  'browser.diagnostics.snapshot': BrowserDiagnosticsSnapshotV1Schema,
  'browser.diagnostics.clear': BrowserDiagnosticsClearResultV1Schema,
  'browser.diagnostics.pause': BrowserDiagnosticsPauseResultV1Schema,
  'browser.diagnostics.resume': BrowserDiagnosticsResumeResultV1Schema,
  'browser.diagnostics.eval': BrowserDiagnosticsEvalResultV1Schema,
  'browser.diagnostics.getProperties': BrowserDiagnosticsGetPropertiesResultV1Schema,
  'browser.diagnostics.releaseObjectGroup': BrowserDiagnosticsReleaseObjectGroupResultV1Schema,
  'browser.diagnostics.elementPicker.start': BrowserDiagnosticsElementPickerResultV1Schema,
  'browser.diagnostics.elementPicker.cancel': BrowserDiagnosticsElementPickerResultV1Schema,
  'browser.context.capturePage': BrowserContextRouteResultV1Schema,
  'browser.context.captureScreenshot': BrowserContextRouteResultV1Schema,
  'browser.context.captureSelectedElement': BrowserContextRouteResultV1Schema,
  'browser.context.captureNetworkSummary': BrowserContextRouteResultV1Schema,
  'browser.context.captureConsoleSummary': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.start': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.cancel': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.captureRegion': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.captureElement': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.attachComment': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.attachStroke': BrowserContextRouteResultV1Schema,
  'browser.context.annotation.attachStyleIntent': BrowserContextRouteResultV1Schema,
  'browser.context.attachToComposer': BrowserContextAttachmentV1Schema,
  'browser.context.attachToAgentTurn': BrowserContextAttachmentV1Schema,
  'browser.context.clear': BrowserContextRouteResultV1Schema,
  'browser.automation.status': BrowserAutomationActionResultV1Schema,
  'browser.automation.snapshot': BrowserAutomationActionResultV1Schema,
  'browser.automation.semanticSnapshot': BrowserAutomationActionResultV1Schema,
  'browser.automation.queryElements': BrowserAutomationActionResultV1Schema,
  'browser.automation.waitFor': BrowserAutomationActionResultV1Schema,
  'browser.automation.timeline.get': BrowserAutomationTimelineV1Schema,
  'browser.automation.cancelActive': BrowserAutomationCancelActiveResultV1Schema,
  'browser.automation.navigate': BrowserAutomationActionResultV1Schema,
  'browser.automation.reload': BrowserAutomationActionResultV1Schema,
  'browser.automation.goBack': BrowserAutomationActionResultV1Schema,
  'browser.automation.goForward': BrowserAutomationActionResultV1Schema,
  'browser.automation.click': BrowserAutomationActionResultV1Schema,
  'browser.automation.tap': BrowserAutomationActionResultV1Schema,
  'browser.automation.type': BrowserAutomationActionResultV1Schema,
  'browser.automation.press': BrowserAutomationActionResultV1Schema,
  'browser.automation.scroll': BrowserAutomationActionResultV1Schema,
  'browser.automation.hover': BrowserAutomationActionResultV1Schema,
  'browser.automation.focus': BrowserAutomationActionResultV1Schema,
  'browser.automation.select': BrowserAutomationActionResultV1Schema,
  'browser.automation.setValue': BrowserAutomationActionResultV1Schema,
  'browser.automation.upload': BrowserAutomationActionResultV1Schema,
  'browser.automation.drag': BrowserAutomationActionResultV1Schema,
  'browser.recording.start': DaemonBrowserRecordingStartResultV1Schema,
  'browser.recording.stop': DaemonBrowserRecordingStopResultV1Schema,
  'browser.recording.cancel': DaemonBrowserRecordingTerminalResultV1Schema,
  'browser.recording.status': BrowserRecordingSessionV1Schema.nullable(),
  'browser.recording.listForView': BrowserRecordingListResultV1Schema,
  'browser.recording.discard': DaemonBrowserRecordingTerminalResultV1Schema,
  'browser.recording.cleanupExpired': DaemonBrowserRecordingCleanupResultV1Schema,
  'browser.recording.attachToComposer': BrowserRecordingAttachToComposerResultV1Schema,
} as const satisfies Readonly<Record<BrowserRuntimeActionId, z.ZodTypeAny>>);

export const BROWSER_RUNTIME_ACTION_SPEC_FAMILY = Object.freeze({
  titles: BROWSER_RUNTIME_ACTION_TITLES,
  descriptions: BROWSER_RUNTIME_ACTION_DESCRIPTIONS,
  inputSchemas: BROWSER_RUNTIME_ACTION_INPUT_SCHEMAS,
  outputSchemas: BROWSER_RUNTIME_ACTION_OUTPUT_SCHEMAS,
} satisfies RuntimeActionSpecFamily);
