import {
  HomeAccountDeleteResultV1Schema,
  HomeAccountDetailV1Schema,
  HomeAccountListInputV1Schema,
  HomeAccountListResultV1Schema,
  HomeAccountRoleSetInputV1Schema,
  HomeAccountRowV1Schema,
  HomeAccountSearchInputV1Schema,
  HomeAccountSearchResultV1Schema,
  HomeAccountTargetInputV1Schema,
  HomeAccountDeleteInputV1Schema,
} from '../../home/governance/accounts.js';
import {
  HomeGovernanceEligibilityGetInputV1Schema,
  HomeGovernanceGetInputV1Schema,
  HomeEmptinessGetInputV1Schema,
} from '../../home/governance/actionsV1.js';
import { HomeGovernancePolicySetInputV1Schema } from '../../home/governance/policy.js';
import {
  HomeGovernanceClaimInputV1Schema,
  HomeGovernanceClaimResultV1Schema,
} from '../../home/governance/claim.js';
import {
  HomeGovernancePolicyProjectionV1Schema,
  HomeGovernanceEligibilityV1Schema,
  HomeGovernanceProjectionV1Schema,
  HomeEmptinessV1Schema,
} from '../../home/governance/projection.js';
import {
  HomeAuditListInputV1Schema,
  HomeAuditListResultV1Schema,
} from '../../home/governance/audit.js';
import {
  HomeMailDeliveryGetInputV1Schema,
  HomeMailDeliveryReadinessV1Schema,
  HomeMailDeliveryTestInputV1Schema,
  HomeMailDeliveryTestResultV1Schema,
  HomeSettingsGetInputV1Schema,
  HomeSettingsProjectionV1Schema,
  HomeSettingsSetInputV1Schema,
} from '../../home/governance/settings.js';
import {
  HomeRetentionDryRunInputV1Schema,
  HomeRetentionDryRunResultV1Schema,
} from '../../home/governance/retention.js';
import {
  HomeReachabilityGetInputV1Schema,
  HomeReachabilityIrohSetInputV1Schema,
  HomeReachabilityV1Schema,
} from '../../home/governance/reachability.js';
import type { PreNormalizedActionSpec } from '../actionSpecs.js';
import { z } from 'zod';
import { lazyZodSchema } from '../../lazyZodSchema.js';
import { homeDomainActionRow, homeDomainApprovalField as approvalField } from './homeDomainRow.js';

const ACCOUNT_ID_FIELD = approvalField('accountId', 'Account ID', { required: true });

/**
 * Home Administration rows.
 *
 * They are core Home behavior, not a gated capability: a Home that understands
 * these operations must serve them whether or not Teams is enabled, because
 * Account status and Home role enforcement are the Home's own authority.
 *
 * Role, Disable and Re-enable answer with the Account row the Home now holds, so
 * a same-state mutation reports the unchanged current Account rather than an
 * acknowledgement the caller would have to re-read to trust.
 */
export const HOME_GOVERNANCE_ACTION_SPECS = Object.freeze([
  {
    ...homeDomainActionRow({
      id: 'home.search.rebuild', title: 'Rebuild Home search index',
      description: 'Rebuild this Personal Home’s derived search index from its canonical transcript rows.',
      safety: 'danger', sideEffectClass: 'danger', cliPath: ['home', 'search', 'rebuild'],
      path: '/v1/home/search/rebuild', inputSchema: HomeGovernanceGetInputV1Schema,
      outputSchema: lazyZodSchema(() => z.object({ ok: z.literal(true) }).strict()),
    }),
    // The existing server search owner requires present-user admission.
    requiredAuthority: 'present_user' as const,
  },
  homeDomainActionRow({
    id: 'home.governance.get',
    title: 'Get Home administration',
    description: 'Read this Home\'s governance projection for the authenticated Account.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'governance', 'get'],
    path: '/v1/home/governance/get',
    inputSchema: HomeGovernanceGetInputV1Schema,
    outputSchema: HomeGovernanceProjectionV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.governance.eligibility.get',
    title: 'Get Home eligibility',
    description: 'Read only Teams availability and this Account\'s effective Team-creation eligibility.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'governance', 'eligibility', 'get'],
    path: '/v1/home/governance/eligibility/get',
    inputSchema: HomeGovernanceEligibilityGetInputV1Schema,
    outputSchema: HomeGovernanceEligibilityV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.emptiness.get',
    title: 'Check whether this Home is empty',
    description: 'Read whether this Home has any sessions, other people, Teams or invitations.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'emptiness', 'get'],
    path: '/v1/home/emptiness/get',
    inputSchema: HomeEmptinessGetInputV1Schema,
    outputSchema: HomeEmptinessV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.governance.claim',
    title: 'Claim this Home',
    description: 'Become the first owner of an ownerless Home with the one-time code printed by `happier-server --print-home-claim-code`. Every refusal reads the same.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'governance', 'claim'],
    path: '/v1/home/governance/claim',
    inputSchema: HomeGovernanceClaimInputV1Schema,
    outputSchema: HomeGovernanceClaimResultV1Schema,
    inputHints: { fields: [approvalField('code', 'Claim code', { required: true })] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.list',
    title: 'List Home Accounts',
    description: 'Page through the Home People list as a Home administrator.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'accounts', 'list'],
    path: '/v1/home/accounts/list',
    inputSchema: HomeAccountListInputV1Schema,
    outputSchema: HomeAccountListResultV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.accounts.search',
    title: 'Search Home Accounts',
    description: 'Resolve people for an exact Home or Team scope without reading Home administration.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'accounts', 'search'],
    path: '/v1/home/accounts/search',
    inputSchema: HomeAccountSearchInputV1Schema,
    outputSchema: HomeAccountSearchResultV1Schema,
    inputHints: { fields: [
      approvalField('query', 'Search query', { required: true }),
      approvalField('scope.kind', 'Scope', { required: true }),
      approvalField('scope.teamId', 'Team ID'),
    ] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.get',
    title: 'Get Home Account',
    description: 'Read one person as Home administration sees them: role, status, sign-in facts, Teams, counts and recent administration events.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'accounts', 'get'],
    path: '/v1/home/accounts/get',
    inputSchema: HomeAccountTargetInputV1Schema,
    outputSchema: HomeAccountDetailV1Schema,
    inputHints: { fields: [ACCOUNT_ID_FIELD] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.role.set',
    title: 'Set Home role',
    description: 'Change one Account\'s Home role. The Home enforces its last-owner invariant.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'accounts', 'role', 'set'],
    path: '/v1/home/accounts/role/set',
    inputSchema: HomeAccountRoleSetInputV1Schema,
    outputSchema: HomeAccountRowV1Schema,
    inputHints: { fields: [
      ACCOUNT_ID_FIELD,
      approvalField('homeRole', 'Home role', { required: true }),
    ] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.disable',
    title: 'Disable Home Account',
    description: 'Place one Account on a reversible hold, ending its access to this Home.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'accounts', 'disable'],
    path: '/v1/home/accounts/disable',
    inputSchema: HomeAccountTargetInputV1Schema,
    outputSchema: HomeAccountRowV1Schema,
    inputHints: { fields: [ACCOUNT_ID_FIELD] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.enable',
    title: 'Re-enable Home Account',
    description: 'Lift a reversible hold and restore one Account\'s access to this Home.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'accounts', 'enable'],
    path: '/v1/home/accounts/enable',
    inputSchema: HomeAccountTargetInputV1Schema,
    outputSchema: HomeAccountRowV1Schema,
    inputHints: { fields: [ACCOUNT_ID_FIELD] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.delete',
    title: 'Delete Home Account',
    description: 'Erase one Account through the Home\'s single erasure owner. Incomplete cleanup is reported explicitly.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'accounts', 'delete'],
    path: '/v1/home/accounts/delete',
    inputSchema: HomeAccountDeleteInputV1Schema,
    outputSchema: HomeAccountDeleteResultV1Schema,
    inputHints: { fields: [ACCOUNT_ID_FIELD] },
  }),
  homeDomainActionRow({
    id: 'home.accounts.signOutEverywhere',
    title: 'Sign a Home Account out everywhere',
    description: 'End every signed-in session of one Account. API tokens stay valid until the Account is disabled.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'accounts', 'sign-out-everywhere'],
    path: '/v1/home/accounts/sign-out-everywhere',
    inputSchema: HomeAccountTargetInputV1Schema,
    outputSchema: HomeAccountRowV1Schema,
    inputHints: { fields: [ACCOUNT_ID_FIELD] },
  }),
  homeDomainActionRow({
    id: 'home.policy.set',
    title: 'Set Home policy',
    description: 'Update this Home\'s governance policy against the revision the caller last read.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'policy', 'set'],
    path: '/v1/home/policy/set',
    inputSchema: HomeGovernancePolicySetInputV1Schema,
    outputSchema: HomeGovernancePolicyProjectionV1Schema,
    inputHints: { fields: [
      approvalField('expectedRevision', 'Expected revision', { widget: 'integer', required: true }),
      approvalField('teamCreationPolicy', 'Team creation policy'),
      approvalField('teamsVisibleToMembers', 'Show Teams to members', { widget: 'boolean' }),
      approvalField('authenticationPolicy.enabledMethodIds', 'Enabled sign-in methods', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('authenticationPolicy.permittedAccountModes', 'Permitted Account modes', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('authenticationPolicy.recommendedProvisioningMode', 'Recommended Account mode'),
      approvalField('authenticationPolicy.admission', 'Account admission'),
      approvalField('authenticationPolicy.signInService.mode', 'Sign-in service'),
      approvalField('teamProviderPolicy.allowedTeamProviderKinds', 'Allowed Team provider kinds', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('teamProviderPolicy.teamJitAllowed', 'Team JIT allowed', { widget: 'boolean' }),
      approvalField('teamProviderPolicy.approvedGitHubEnterpriseOrigins', 'Approved GitHub Enterprise origins', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('identityNetworkPolicy.mode', 'Identity network mode'),
      approvalField('identityNetworkPolicy.hostnames', 'Allowed hostnames', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('identityNetworkPolicy.cidrs', 'Allowed CIDRs', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('identityNetworkPolicy.ports', 'Allowed ports', { widget: 'text_list', listSeparator: 'comma' }),
      approvalField('authenticationPolicy.anonymousSignup', 'Anonymous sign-up', { widget: 'boolean' }),
      approvalField('authenticationPolicy.storagePolicy', 'Storage policy'),
      approvalField('confirmWidening', 'Widening confirmed', { widget: 'boolean' }),
    ] },
  }),
  homeDomainActionRow({
    id: 'home.settings.get',
    title: 'Get Home settings',
    description: 'Read the effective server configuration of this Home with each value\'s source. Secrets report presence only.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'settings', 'get'],
    path: '/v1/home/settings/get',
    inputSchema: HomeSettingsGetInputV1Schema,
    outputSchema: HomeSettingsProjectionV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.settings.set',
    title: 'Set Home settings',
    description: 'Store Home setting values against the revision the caller last read. A deployment env value still wins; restart settings apply at the next server start.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'settings', 'set'],
    path: '/v1/home/settings/set',
    inputSchema: HomeSettingsSetInputV1Schema,
    outputSchema: HomeSettingsProjectionV1Schema,
    inputHints: { fields: [
      approvalField('expectedRevision', 'Expected revision', { widget: 'integer', required: true }),
    ] },
  }),
  homeDomainActionRow({
    id: 'home.mailDelivery.get',
    title: 'Get Home mail readiness',
    description: 'Read whether this Home can send mail: a configured transport and a buildable link.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'mail-delivery', 'get'],
    path: '/v1/home/mail-delivery/get',
    inputSchema: HomeMailDeliveryGetInputV1Schema,
    outputSchema: HomeMailDeliveryReadinessV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.mailDelivery.test',
    title: 'Send a test email',
    description: 'Send a fixed test message through this Home\'s mail settings. A failure reports its class only.',
    safety: 'danger',
    sideEffectClass: 'external',
    cliPath: ['home', 'mail-delivery', 'test'],
    path: '/v1/home/mail-delivery/test',
    inputSchema: HomeMailDeliveryTestInputV1Schema,
    outputSchema: HomeMailDeliveryTestResultV1Schema,
    inputHints: { fields: [approvalField('to', 'Send to', { required: true })] },
  }),
  homeDomainActionRow({
    id: 'home.audit.list',
    title: 'List Home administration activity',
    description: 'Page through this Home\'s administration events, newest first, optionally about one target.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'audit', 'list'],
    path: '/v1/home/audit/list',
    inputSchema: HomeAuditListInputV1Schema,
    outputSchema: HomeAuditListResultV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.reachability.get',
    title: 'Get how this Home is reached',
    description: 'Read the effective public and web-app addresses with their sources, the hosting computer\'s access method when known, and the direct-connection state.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'reachability', 'get'],
    path: '/v1/home/reachability/get',
    inputSchema: HomeReachabilityGetInputV1Schema,
    outputSchema: HomeReachabilityV1Schema,
  }),
  homeDomainActionRow({
    id: 'home.reachability.iroh.set',
    title: 'Turn direct connections on or off',
    description: 'Turning direct (Iroh) connections off retires the current direct-connection identity for good; turning them on creates a new one. Addresses and sign-ins stay the same.',
    safety: 'danger',
    sideEffectClass: 'danger',
    cliPath: ['home', 'reachability', 'iroh', 'set'],
    path: '/v1/home/reachability/iroh/set',
    inputSchema: HomeReachabilityIrohSetInputV1Schema,
    outputSchema: HomeReachabilityV1Schema,
    inputHints: { fields: [approvalField('mode', 'Direct connections', { required: true })] },
  }),
  homeDomainActionRow({
    id: 'home.retention.dryRun',
    title: 'Run a retention dry run',
    description: 'Run one retention sweep of this Home\'s current rules without deleting anything, and report what each domain would delete.',
    safety: 'safe',
    sideEffectClass: 'read',
    cliPath: ['home', 'retention', 'dry-run'],
    path: '/v1/home/retention/dry-run',
    inputSchema: HomeRetentionDryRunInputV1Schema,
    outputSchema: HomeRetentionDryRunResultV1Schema,
  }),
]) satisfies readonly PreNormalizedActionSpec[];
