export const SESSION_HELP_LINES = {
  list: 'happier session list [--active] [--archived] [--limit N] [--cursor C] [--include-system] [--resumable] [--plain] [--json]',
  status: 'happier session status <session-id-or-prefix> [--live] [--json]',
  create: 'happier session create [--path <path>] [--backend <backend-target>] [--title <text>] [--tag <tag>] [--prompt <text>|--message <text>] [--model <model-id> [--provider-connection <connection-id>]] [--permission-mode <mode>] [--mode <agent-mode-id>] [--config-option <id=value>] [--reasoning-effort <value>] [--ultracode] [--config-overrides-json <json>] [--launch-profile <profile-id>] [--env <KEY=VALUE>] [--auth <default|native|cs:<id>>|--connected-services <selector>|--auth-json <json>] [--mcp-selection-json <json>] [--transcript-storage <persisted|direct>] [--terminal-json <json>] [--runtime-descriptor-json <json>] [--host <host>] [--machine-id <machineId>] [--server-id <serverId>] [--spawn-attempt-id <id>] [--resume-spawn-attempt] [--json]',
  send: 'happier session send <session-id-or-prefix> <message|--message <text>|--prompt <text>> [--permission-mode <mode>] [--model <model-id>] [--wait] [--timeout <seconds>] [--json]',
  wait: 'happier session wait <session-id-or-prefix> [--timeout <seconds>] [--json]',
  stop: 'happier session stop <session-id-or-prefix> [--json]',
  history: 'happier session history <session-id-or-prefix> [--limit N] [--format compact|raw] [--raw] [--include-meta] [--include-structured-payload] [--json]',
  setTitle: 'happier session set-title <session-id-or-prefix> <title> [--json]',
  setPermissionMode: 'happier session set-permission-mode <session-id-or-prefix> <mode> [--json]',
  setModel: 'happier session set-model <session-id-or-prefix> <model-id> [--json]',
  archive: 'happier session archive <session-id-or-prefix> [--json]',
  unarchive: 'happier session unarchive <session-id-or-prefix> [--json]',
  reviewStart: 'happier session review start <session-id-or-prefix> --engines <id1,id2> --instructions <text> [--json]',
  planStart: 'happier session plan start <session-id-or-prefix> --backends <id1,id2> --instructions <text> [--json]',
  delegateStart: 'happier session delegate start <session-id-or-prefix> --backends <id1,id2> --instructions <text> [--json]',
  voiceAgentStart: 'happier session voice-agent start <session-id-or-prefix> --backends <id1,id2> --instructions <text> [--json]',
  actionsList: 'happier session actions list [--json]',
  actionsDescribe: 'happier session actions describe <action-id> [--json]',
  actionsExecute: 'happier session actions execute <session-id-or-prefix> <action-id> [--input-json <json>] [--action-request-id <id>] [--resume-action-request] [--json]',
  runStart: 'happier session run start <session-id-or-prefix> --intent <intent> --backend <backend-target> [--instructions <text>] [--permission-mode <mode>] [--retention <policy>] [--run-class <class>] [--io-mode <mode>] [--json]',
  runList: 'happier session run list <session-id-or-prefix> [--backend <backend-target>] [--status <status>] [--limit <count>] [--json]',
  runGet: 'happier session run get <session-id-or-prefix> <run-id> [--include-structured] [--json]',
  runSend: 'happier session run send <session-id-or-prefix> <run-id> <message> [--resume] [--json]',
  runStop: 'happier session run stop <session-id-or-prefix> <run-id> [--json]',
  runAction: 'happier session run action <session-id-or-prefix> <run-id> <action-id> [--input-json <json>] [--json]',
  runWait: 'happier session run wait <session-id-or-prefix> <run-id> [--timeout <seconds>] [--json]',
  runStreamStart: 'happier session run stream-start <session-id-or-prefix> <run-id> <message> [--resume] [--json]',
  runStreamRead: 'happier session run stream-read <session-id-or-prefix> <run-id> <stream-id> --cursor <n> [--max-events <n>] [--json]',
  runStreamCancel: 'happier session run stream-cancel <session-id-or-prefix> <run-id> <stream-id> [--json]',
} as const;

export const SESSION_TOP_LEVEL_HELP_LINES = [
  SESSION_HELP_LINES.list,
  SESSION_HELP_LINES.status,
  SESSION_HELP_LINES.create,
  SESSION_HELP_LINES.send,
  SESSION_HELP_LINES.wait,
  SESSION_HELP_LINES.stop,
  SESSION_HELP_LINES.history,
  SESSION_HELP_LINES.setTitle,
  SESSION_HELP_LINES.setPermissionMode,
  SESSION_HELP_LINES.setModel,
  SESSION_HELP_LINES.archive,
  SESSION_HELP_LINES.unarchive,
  SESSION_HELP_LINES.reviewStart,
  SESSION_HELP_LINES.planStart,
  SESSION_HELP_LINES.delegateStart,
  SESSION_HELP_LINES.voiceAgentStart,
  SESSION_HELP_LINES.actionsList,
  SESSION_HELP_LINES.actionsDescribe,
  SESSION_HELP_LINES.actionsExecute,
  SESSION_HELP_LINES.runStart,
  SESSION_HELP_LINES.runList,
  SESSION_HELP_LINES.runGet,
  SESSION_HELP_LINES.runSend,
  SESSION_HELP_LINES.runStop,
  SESSION_HELP_LINES.runAction,
  SESSION_HELP_LINES.runWait,
  SESSION_HELP_LINES.runStreamStart,
  SESSION_HELP_LINES.runStreamRead,
  SESSION_HELP_LINES.runStreamCancel,
] as const;

export const SESSION_SUBCOMMAND_HELP_LINES: Record<string, readonly string[]> = {
  list: [SESSION_HELP_LINES.list],
  status: [SESSION_HELP_LINES.status],
  create: [SESSION_HELP_LINES.create],
  send: [SESSION_HELP_LINES.send],
  wait: [SESSION_HELP_LINES.wait],
  stop: [SESSION_HELP_LINES.stop],
  history: [SESSION_HELP_LINES.history],
  'set-title': [SESSION_HELP_LINES.setTitle],
  'set-permission-mode': [SESSION_HELP_LINES.setPermissionMode],
  'set-model': [SESSION_HELP_LINES.setModel],
  archive: [SESSION_HELP_LINES.archive],
  unarchive: [SESSION_HELP_LINES.unarchive],
  review: [SESSION_HELP_LINES.reviewStart],
  plan: [SESSION_HELP_LINES.planStart],
  delegate: [SESSION_HELP_LINES.delegateStart],
  'voice-agent': [SESSION_HELP_LINES.voiceAgentStart],
  actions: [SESSION_HELP_LINES.actionsList, SESSION_HELP_LINES.actionsDescribe, SESSION_HELP_LINES.actionsExecute],
  run: [
    SESSION_HELP_LINES.runStart,
    SESSION_HELP_LINES.runList,
    SESSION_HELP_LINES.runGet,
    SESSION_HELP_LINES.runSend,
    SESSION_HELP_LINES.runStop,
    SESSION_HELP_LINES.runAction,
    SESSION_HELP_LINES.runWait,
    SESSION_HELP_LINES.runStreamStart,
    SESSION_HELP_LINES.runStreamRead,
    SESSION_HELP_LINES.runStreamCancel,
  ],
};

export const SESSION_NESTED_SUBCOMMAND_HELP_LINES: Record<string, string> = {
  'review start': SESSION_HELP_LINES.reviewStart,
  'plan start': SESSION_HELP_LINES.planStart,
  'delegate start': SESSION_HELP_LINES.delegateStart,
  'voice-agent start': SESSION_HELP_LINES.voiceAgentStart,
  'actions list': SESSION_HELP_LINES.actionsList,
  'actions describe': SESSION_HELP_LINES.actionsDescribe,
  'actions execute': SESSION_HELP_LINES.actionsExecute,
  'run start': SESSION_HELP_LINES.runStart,
  'run list': SESSION_HELP_LINES.runList,
  'run get': SESSION_HELP_LINES.runGet,
  'run send': SESSION_HELP_LINES.runSend,
  'run stop': SESSION_HELP_LINES.runStop,
  'run action': SESSION_HELP_LINES.runAction,
  'run wait': SESSION_HELP_LINES.runWait,
  'run stream-start': SESSION_HELP_LINES.runStreamStart,
  'run stream-read': SESSION_HELP_LINES.runStreamRead,
  'run stream-cancel': SESSION_HELP_LINES.runStreamCancel,
};
