// GENERATED by scripts/i18n-generate-entries.mjs from enterprise.tsx — do not edit.
import { mount } from './_mount';
import { registerOverlay } from '../i18n/siteData';
import ns_enterprise from '../i18n/generated/slices/de/enterprise.json';
import ns_navigation from '../i18n/generated/slices/de/navigation.json';
import ns_pageProse from '../i18n/generated/slices/de/pageProse.json';


// Registered here, not discovered by a glob: this entry is the only place
// that knows the page is de, which keeps the other nine locales out of
// its download. The imports above are the translation NAMESPACES this route
// was measured to read — scripts/i18n-slice-overlays.mjs renders the page to
// find them and proves the set reproduces its HTML byte for byte. Rollup
// shares each namespace chunk between the routes that import it.
registerOverlay('de', Object.assign({}, ns_enterprise, ns_navigation, ns_pageProse));

/** `/enterprise` — see src/entries/home.tsx for what an entry may and may not import. */
mount('de');
