// GENERATED by scripts/i18n-generate-entries.mjs from security.tsx — do not edit.
import { SecurityPage } from '../pages/SecurityPage';
import { mount } from './_mount';
import { registerOverlay } from '../i18n/siteData';
import overlay from '../i18n/messages/overlays/es.json';


// Registered here, not discovered by a glob: this entry is the only place that
// knows the page is es, and importing one overlay keeps the other eight out
// of every other route's download. See registerOverlay in src/i18n/siteData.ts.
registerOverlay('es', overlay);

/** `/security` — see src/entries/home.tsx for what an entry may and may not import. */
mount('es', <SecurityPage />);
