// GENERATED by scripts/i18n-generate-entries.mjs from agents--auggie.tsx — do not edit.
import { mountAgentPage } from './_agent';
import { registerOverlay } from '../i18n/siteData';
import overlay from '../i18n/messages/overlays/es.json';


// Registered here, not discovered by a glob: this entry is the only place that
// knows the page is es, and importing one overlay keeps the other eight out
// of every other route's download. See registerOverlay in src/i18n/siteData.ts.
registerOverlay('es', overlay);

/** `/agents/auggie` — see src/entries/_agent.tsx for the shared half. */
mountAgentPage('es', 'auggie');
