// GENERATED by scripts/i18n-generate-entries.mjs from agents--kiro.tsx — do not edit.
import { mountAgentPage } from './_agent';
import { registerOverlay } from '../i18n/siteData';
import ns_agents from '../i18n/generated/slices/fr/agents.json';
import ns_navigation from '../i18n/generated/slices/fr/navigation.json';
import ns_pageProse from '../i18n/generated/slices/fr/pageProse.json';


// Registered here, not discovered by a glob: this entry is the only place
// that knows the page is fr, which keeps the other nine locales out of
// its download. The imports above are the translation NAMESPACES this route
// was measured to read — scripts/i18n-slice-overlays.mjs renders the page to
// find them and proves the set reproduces its HTML byte for byte. Rollup
// shares each namespace chunk between the routes that import it.
registerOverlay('fr', Object.assign({}, ns_agents, ns_navigation, ns_pageProse));

/** `/agents/kiro` — see src/entries/_agent.tsx for the shared half. */
mountAgentPage('fr', 'kiro');
