// GENERATED by scripts/i18n-generate-entries.mjs from agents.tsx — do not edit.
import { mount } from './_mount';
import { registerOverlay } from '../i18n/siteData';
import ns_agents from '../i18n/generated/slices/it/agents.json';
import ns_availability from '../i18n/generated/slices/it/availability.json';
import ns_navigation from '../i18n/generated/slices/it/navigation.json';
import ns_pageProse from '../i18n/generated/slices/it/pageProse.json';


// Registered here, not discovered by a glob: this entry is the only place
// that knows the page is it, which keeps the other nine locales out of
// its download. The imports above are the translation NAMESPACES this route
// was measured to read — scripts/i18n-slice-overlays.mjs renders the page to
// find them and proves the set reproduces its HTML byte for byte. Rollup
// shares each namespace chunk between the routes that import it.
registerOverlay('it', Object.assign({}, ns_agents, ns_availability, ns_navigation, ns_pageProse));

/** `/agents` — see src/entries/home.tsx for what an entry may and may not import. */
mount('it');
