// GENERATED by scripts/i18n-generate-entries.mjs from vs--codex-remote.tsx — do not edit.
import { mount } from './_mount';
import { registerOverlay } from '../i18n/siteData';
import ns_agents from '../i18n/generated/slices/pl/agents.json';
import ns_codexRemote from '../i18n/generated/slices/pl/codexRemote.json';
import ns_navigation from '../i18n/generated/slices/pl/navigation.json';
import ns_pageProse from '../i18n/generated/slices/pl/pageProse.json';


// Registered here, not discovered by a glob: this entry is the only place
// that knows the page is pl, which keeps the other nine locales out of
// its download. The imports above are the translation NAMESPACES this route
// was measured to read — scripts/i18n-slice-overlays.mjs renders the page to
// find them and proves the set reproduces its HTML byte for byte. Rollup
// shares each namespace chunk between the routes that import it.
registerOverlay('pl', Object.assign({}, ns_agents, ns_codexRemote, ns_navigation, ns_pageProse));

/** `/vs/codex-remote` — see src/entries/home.tsx for what an entry may and may not import. */
mount('pl');
