// GENERATED by scripts/i18n-generate-entries.mjs from agents--grok.tsx — do not edit.
import { mountAgentPage } from './_agent';
import { registerOverlay } from '../i18n/siteData';
import overlay from '../i18n/messages/overlays/pt.json';


// Registered here, not discovered by a glob: this entry is the only place that
// knows the page is pt, and importing one overlay keeps the other eight out
// of every other route's download. See registerOverlay in src/i18n/siteData.ts.
registerOverlay('pt', overlay);

/** `/agents/grok` — see src/entries/_agent.tsx for the shared half. */
mountAgentPage('pt', 'grok');
