// GENERATED by scripts/i18n-generate-entries.mjs from features--usage-limits.tsx — do not edit.
import { mount } from './_mount';
import { registerOverlay } from '../i18n/siteData';
import ns_navigation from '../i18n/generated/slices/pt/navigation.json';
import ns_pageProse from '../i18n/generated/slices/pt/pageProse.json';
import ns_usageLimits from '../i18n/generated/slices/pt/usageLimits.json';


// Registered here, not discovered by a glob: this entry is the only place
// that knows the page is pt, which keeps the other nine locales out of
// its download. The imports above are the translation NAMESPACES this route
// was measured to read — scripts/i18n-slice-overlays.mjs renders the page to
// find them and proves the set reproduces its HTML byte for byte. Rollup
// shares each namespace chunk between the routes that import it.
registerOverlay('pt', Object.assign({}, ns_navigation, ns_pageProse, ns_usageLimits));

/** `/features/usage-limits` — see src/entries/home.tsx for what an entry may and may not import. */
mount('pt');
