import { describe, expect, it } from 'vitest';

import * as provider from './index.js';

describe('Channels V1 provider barrel', () => {
    it('publishes the one complete operation vocabulary without relative-only composition parsers', () => {
        expect(Object.keys(provider).sort()).toEqual([
            'ConversationConnectionTestInputV1JsonSchema',
            'ConversationConnectionTestInputV1Schema',
            'ConversationConnectionTestResultV1JsonSchema',
            'ConversationConnectionTestResultV1Schema',
            'ConversationDeliveryInputV1JsonSchema',
            'ConversationDeliveryInputV1Schema',
            'ConversationDeliveryReconcileInputV1JsonSchema',
            'ConversationDeliveryReconcileInputV1Schema',
            'ConversationDeliveryReplyContextV1JsonSchema',
            'ConversationDeliveryReplyContextV1Schema',
            'ConversationDeliveryResultV1JsonSchema',
            'ConversationDeliveryResultV1Schema',
            'ConversationEndpointIdentityV1JsonSchema',
            'ConversationEndpointIdentityV1Schema',
            'ConversationEndpointResolveInputV1JsonSchema',
            'ConversationEndpointResolveInputV1Schema',
            'ConversationEndpointResolveResultV1JsonSchema',
            'ConversationEndpointResolveResultV1Schema',
            'ConversationPollInputV1JsonSchema',
            'ConversationPollInputV1Schema',
            'ConversationPollResultV1JsonSchema',
            'ConversationPollResultV1Schema',
            'ConversationPrincipalResolveInputV1JsonSchema',
            'ConversationPrincipalResolveInputV1Schema',
            'ConversationPrincipalResolveResultV1JsonSchema',
            'ConversationPrincipalResolveResultV1Schema',
            'ConversationProviderConnectionInputV1JsonSchema',
            'ConversationProviderConnectionInputV1Schema',
            'ConversationProviderConnectionReadInputV1JsonSchema',
            'ConversationProviderConnectionReadInputV1Schema',
            'ConversationProviderConnectionReadResultV1JsonSchema',
            'ConversationProviderConnectionReadResultV1Schema',
            'ConversationProviderConnectionReconciliationSnapshotV1JsonSchema',
            'ConversationProviderConnectionReconciliationSnapshotV1Schema',
            'ConversationProviderConnectionStopInputV1JsonSchema',
            'ConversationProviderConnectionStopInputV1Schema',
            'ConversationProviderConnectionStopResultV1JsonSchema',
            'ConversationProviderConnectionStopResultV1Schema',
            'ConversationProviderConnectionsListInputV1JsonSchema',
            'ConversationProviderConnectionsListInputV1Schema',
            'ConversationProviderConnectionsListResultV1JsonSchema',
            'ConversationProviderConnectionsListResultV1Schema',
            'ConversationProviderConnectionsSnapshotV1JsonSchema',
            'ConversationProviderConnectionsSnapshotV1Schema',
            'ConversationProviderSetupOutcomeV1JsonSchema',
            'ConversationProviderSetupOutcomeV1Schema',
            'ConversationProviderSetupRemediationResultV1JsonSchema',
            'ConversationProviderSetupRemediationResultV1Schema',
            'ConversationProviderSetupRemediationV1JsonSchema',
            'ConversationProviderSetupRemediationV1Schema',
            'ConversationProviderSetupResultV1JsonSchema',
            'ConversationProviderSetupResultV1Schema',
            'ConversationProvidersContributionPointV1',
            'ConversationProvidersContributionProtocolV1',
            'ConversationResolvedEndpointV1JsonSchema',
            'ConversationResolvedEndpointV1Schema',
            'ConversationResolvedPrincipalV1JsonSchema',
            'ConversationResolvedPrincipalV1Schema',
            'areConversationEndpointIdentitiesEqual',
            'compareCanonicalConversationResolutionCandidatesV1',
            'hasCanonicalConversationResolutionCandidateOrderV1',
        ]);
        expect(Object.keys(provider).some((key) => key.endsWith('ProtocolSchema'))).toBe(false);
    });
});
