export {
  resolveAnnotationCropClip,
  strokeViewportBounds,
  unionViewportRects,
  type AnnotationCropClip,
  type AnnotationCropClipResult,
  type AnnotationCropSurfaceBounds,
  type AnnotationCropViewportInput,
  type AnnotationStrokePointViewport,
  type AnnotationViewportRect,
  type ResolveAnnotationCropClipInput,
} from './annotationCropGeometry.js';
export {
  BrowserContextAttachmentV1Schema,
  BrowserContextAnnotationStructuredBlockV1Schema,
  BrowserContextAnnotationActionResultV1Schema,
  BrowserContextCommandV1Schema,
  BrowserContextEventV1Schema,
  BrowserContextItemV1Schema,
  BrowserContextKindV1Schema,
  BrowserContextLifecycleStateV1Schema,
  BrowserContextRedactionLevelV1Schema,
  BrowserContextRouteFailureV1Schema,
  BrowserContextRouteResultV1Schema,
  BrowserAnnotationStrokeV1Schema,
  BrowserAnnotationStyleIntentV1Schema,
  BrowserAnnotationTargetV1Schema,
  BrowserScreenshotMediaReferenceV1Schema,
  BrowserContextSnapshotV1Schema,
  BrowserContextSnapshotAxNodeV1Schema,
  BrowserContextSnapshotInteractiveElementV1Schema,
  DaemonBrowserContextDispatchRequestV1Schema,
  DaemonBrowserContextDispatchResponseV1Schema,
  type BrowserAnnotationRectV1,
  type BrowserContextAnnotationActionResultV1,
  type BrowserContextAnnotationStructuredBlockV1,
  type BrowserAnnotationStrokeV1,
  type BrowserAnnotationStyleIntentV1,
  type BrowserAnnotationTargetV1,
  type BrowserContextAttachmentV1,
  type BrowserContextCommandV1,
  type BrowserContextEventV1,
  type BrowserContextItemV1,
  type BrowserContextKindV1,
  type BrowserContextLifecycleStateV1,
  type BrowserContextRedactionLevelV1,
  type BrowserContextRouteFailureV1,
  type BrowserContextRouteResultV1,
  type BrowserContextSnapshotV1,
  type BrowserContextSnapshotAxNodeV1,
  type BrowserContextSnapshotInteractiveElementV1,
  type BrowserScreenshotMediaReferenceV1,
  type DaemonBrowserContextDispatchRequestV1,
  type DaemonBrowserContextDispatchResponseV1,
} from './v1.js';
