export {
  BrowserDiagnosticCollectorV1Schema,
  BrowserDiagnosticEventBatchV1Schema,
  BrowserDiagnosticEventKindV1Schema,
  BrowserDiagnosticEventV1Schema,
  BrowserDiagnosticFamilyV1Schema,
  BrowserDiagnosticFidelityV1Schema,
  BrowserDiagnosticRedactionLevelV1Schema,
  BrowserDiagnosticRedactionV1Schema,
  BrowserDiagnosticUnavailableReasonV1Schema,
  BrowserDiagnosticsSnapshotV1Schema,
  DaemonBrowserDiagnosticsSnapshotRequestV1Schema,
  DaemonBrowserDiagnosticsSnapshotResponseV1Schema,
  BrowserDiagnosticsElementPickerActionV1Schema,
  BrowserDiagnosticsElementPickerCommandMessageV1Schema,
  BrowserDiagnosticsElementPickerRectV1Schema,
  BrowserDiagnosticsElementSourceLocationV1Schema,
  BrowserDiagnosticsElementPickerRequestV1Schema,
  BrowserDiagnosticsElementPickerResultMessageV1Schema,
  BrowserDiagnosticsElementPickerResultV1Schema,
  BrowserDiagnosticsEvalCommandMessageV1Schema,
  BrowserDiagnosticsEvalRequestV1Schema,
  BrowserDiagnosticsEvalResultMessageV1Schema,
  BrowserDiagnosticsEvalResultV1Schema,
  BrowserDiagnosticsEvalTierV1Schema,
  BrowserDiagnosticsExpandedRemoteObjectV1Schema,
  BrowserDiagnosticsGetPropertiesCommandMessageV1Schema,
  BrowserDiagnosticsGetPropertiesRequestV1Schema,
  BrowserDiagnosticsGetPropertiesResultMessageV1Schema,
  BrowserDiagnosticsGetPropertiesResultV1Schema,
  BrowserDiagnosticsObjectPropertyV1Schema,
  BrowserDiagnosticsReleaseObjectGroupCommandMessageV1Schema,
  BrowserDiagnosticsReleaseObjectGroupRequestV1Schema,
  BrowserDiagnosticsReleaseObjectGroupResultMessageV1Schema,
  BrowserDiagnosticsReleaseObjectGroupResultV1Schema,
  BrowserDiagnosticsRemoteObjectPreviewPropertyV1Schema,
  BrowserDiagnosticsRemoteObjectV1Schema,
  type BrowserDiagnosticCollectorV1,
  type BrowserDiagnosticEventBatchV1,
  type BrowserDiagnosticEventKindV1,
  type BrowserDiagnosticEventV1,
  type BrowserDiagnosticFamilyV1,
  type BrowserDiagnosticFidelityV1,
  type BrowserDiagnosticRedactionLevelV1,
  type BrowserDiagnosticRedactionV1,
  type BrowserDiagnosticUnavailableReasonV1,
  type BrowserDiagnosticsSnapshotV1,
  type DaemonBrowserDiagnosticsSnapshotRequestV1,
  type DaemonBrowserDiagnosticsSnapshotResponseV1,
  type BrowserDiagnosticsElementPickerActionV1,
  type BrowserDiagnosticsElementPickerCommandMessageV1,
  type BrowserDiagnosticsElementPickerRectV1,
  type BrowserDiagnosticsElementSourceLocationV1,
  type BrowserDiagnosticsElementPickerRequestV1,
  type BrowserDiagnosticsElementPickerResultMessageV1,
  type BrowserDiagnosticsElementPickerResultV1,
  type BrowserDiagnosticsEvalCommandMessageV1,
  type BrowserDiagnosticsEvalRequestV1,
  type BrowserDiagnosticsEvalResultMessageV1,
  type BrowserDiagnosticsEvalResultV1,
  type BrowserDiagnosticsEvalTierV1,
  type BrowserDiagnosticsExpandedRemoteObjectV1,
  type BrowserDiagnosticsGetPropertiesCommandMessageV1,
  type BrowserDiagnosticsGetPropertiesRequestV1,
  type BrowserDiagnosticsGetPropertiesResultMessageV1,
  type BrowserDiagnosticsGetPropertiesResultV1,
  type BrowserDiagnosticsObjectPropertyV1,
  type BrowserDiagnosticsReleaseObjectGroupCommandMessageV1,
  type BrowserDiagnosticsReleaseObjectGroupRequestV1,
  type BrowserDiagnosticsReleaseObjectGroupResultMessageV1,
  type BrowserDiagnosticsReleaseObjectGroupResultV1,
  type BrowserDiagnosticsRemoteObjectPreviewPropertyV1,
  type BrowserDiagnosticsRemoteObjectV1,
} from './v1.js';
export {
  classifyBrowserDiagnosticField,
  classifyBrowserDiagnosticFieldForDestination,
  resolveRedactionLevel,
  INJECTED_EVENT_ALLOWED_FIELDS,
  INJECTED_OWNER_ONLY_FIELDS,
  INJECTED_CONSOLE_TEXT_MAX_LENGTH,
  INJECTED_OWNER_VALUE_MAX_LENGTH,
  ALWAYS_STRIP_FIELD_NAMES,
  isForbiddenBrowserEgressKey,
  rejectUnsafeBrowserEgressKeys,
  type RejectUnsafeBrowserEgressKeysOptions,
  isSensitiveUrlPathSegment,
  redactSensitiveUrlPathSegments,
  stripBrowserDiagnosticUrlValues,
  stripUrlValuesInString,
  SANITIZE_URL_PARITY_VECTORS,
  SAFE_TELEMETRY_HEADER_NAMES,
  isSafeTelemetryHeaderName,
  normalizeTelemetryHeaderName,
  redactDiagnosticsHeaders,
  redactDiagnosticsUrl,
  type BrowserDiagnosticFieldDisposition,
  type BrowserDiagnosticEgressDestination,
  type TelemetryHeaders,
  type RedactedDiagnosticsUrl,
} from './egress/index.js';
