import { definePlugin } from '@happier-dev/plugin-sdk';
import type { ActionHandler } from '@happier-dev/plugin-sdk/actions';
import type { PluginSettingsContribution } from '@happier-dev/plugin-sdk/settings';
import { INSPECTOR_ADDITIONAL_UI_TRANSLATIONS } from './ui/additionalTranslations.js';

export const INSPECTOR_PLUGIN_ID = 'happier.inspector';
export const INSPECTOR_NATIVE_BUNDLE_ID = 'inspector-app-native';
export const INSPECTOR_APP_SURFACE_ID = 'inspector-app';
/**
 * EU-5b dogfood: the inspector's full-page destination. The host routes it at
 * `/plugins/happier.inspector/inspector-page/*` and hands the surface only the
 * remainder as `subPath`; the plugin never names a route.
 */
export const INSPECTOR_PAGE_SURFACE_ID = 'inspector-page';
export const INSPECTOR_BROWSER_PANEL_SURFACE_ID = 'inspector-browser-panel';
export const INSPECTOR_SERVICES_PANEL_SURFACE_ID = 'inspector-services-panel';
export const INSPECTOR_RENDERER_ID = 'inspector-renderer';
export const INSPECTOR_SETTINGS_ID = 'settings';
export const INSPECTOR_SHOW_DIAGNOSTICS_SETTING_ID = 'show-diagnostics';
export const INSPECTOR_BRAND_RESOURCE_ID = 'brand-icon';
export const INSPECTOR_INVENTORY_ILLUSTRATION_RESOURCE_ID = 'inventory-illustration';
/**
 * A small real action owned by the Inspector itself. The surface invokes this
 * through the public Action adapter so the reference plugin exercises the
 * same declared-action/host-dispatch path available to external authors.
 */
export const INSPECTOR_SELF_CHECK_ACTION_ID = 'self-check';

/**
 * A deliberately side-effect-free action used by the reference surface to
 * prove the public declared-action path without creating another dispatcher.
 */
export const runInspectorSelfCheck: ActionHandler = async () => ({ ok: true });

export const INSPECTOR_SETTINGS = {
  id: INSPECTOR_SETTINGS_ID,
  title: { key: 'plugins.inspector.title', fallback: 'Plugin Inspector' },
  description: 'Local presentation preferences for the Plugin Inspector.',
  target: { kind: 'plugin' },
  scope: 'daemon',
  fields: [
    {
      id: INSPECTOR_SHOW_DIAGNOSTICS_SETTING_ID,
      title: {
        key: 'plugins.inspector.settings.showDiagnostics',
        fallback: 'Show diagnostics in Plugin Inspector',
      },
      description: {
        key: 'plugins.inspector.settings.showDiagnostics.description',
        fallback: 'Display per-plugin diagnostic details in the inspector surface.',
      },
      schema: { type: 'boolean' },
      default: true,
    },
  ],
} satisfies PluginSettingsContribution;

export const INSPECTOR_UI = {
  views: [{
    id: INSPECTOR_APP_SURFACE_ID,
    container: 'rightSidebarTab' as const,
    target: { kind: 'app' as const },
    renderer: INSPECTOR_RENDERER_ID,
    title: {
      key: 'plugins.inspector.title',
      fallback: 'Plugin Inspector',
    },
  }, {
    // The SAME renderer serves both direct destinations: one surface, two
    // destinations. The host-projected surface context distinguishes them and
    // provides the plugin-local location through `context.subPath` on the page.
    id: INSPECTOR_PAGE_SURFACE_ID,
    container: 'appPage' as const,
    target: { kind: 'app' as const },
    renderer: INSPECTOR_RENDERER_ID,
    title: {
      key: 'plugins.inspector.title',
      fallback: 'Plugin Inspector',
    },
  }, {
    id: INSPECTOR_BROWSER_PANEL_SURFACE_ID,
    container: 'browserPanel' as const,
    target: { kind: 'browser' as const, browserViewIdPath: '/browser/viewId' },
    renderer: INSPECTOR_RENDERER_ID,
    title: {
      key: 'plugins.inspector.title',
      fallback: 'Plugin Inspector',
    },
  }, {
    id: INSPECTOR_SERVICES_PANEL_SURFACE_ID,
    container: 'servicesPanel' as const,
    target: { kind: 'services' as const },
    renderer: INSPECTOR_RENDERER_ID,
    title: {
      key: 'plugins.inspector.title',
      fallback: 'Plugin Inspector',
    },
  }],
  renderers: [{
    id: INSPECTOR_RENDERER_ID,
    kind: 'reactNative' as const,
    artifact: INSPECTOR_NATIVE_BUNDLE_ID,
    requiredHostMethods: ['executeAction' as const],
  }],
  translations: [
    {
                locale: 'en',
                messages: {
                  ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.en,
                  'plugins.inspector.title': 'Plugin Inspector',
                  'plugins.inspector.description': 'Inspect installed plugins, diagnostics, and reload state.',
                  'plugins.inspector.settings.showDiagnostics': 'Show diagnostics in Plugin Inspector',
                  'plugins.inspector.settings.showDiagnostics.description': 'Display per-plugin diagnostic details in the inspector surface.',
                  // Rendered by the executable surface through `surface.translations`
                  // (§3.2): the host projects this bundle for the user's locale, so the
                  // surface resolves keys synchronously and never owns a string catalog.
                  'plugins.inspector.surface.reload': 'Reload',
                  'plugins.inspector.surface.reloading': 'Reloading…',
                  'plugins.inspector.surface.search': 'Search installed plugins',
                  'plugins.inspector.surface.searchPlaceholder': 'Search by name or plugin ID',
                  'plugins.inspector.surface.inventoryIllustration': 'Plugin inventory illustration',
                  'plugins.inspector.surface.noMatches': 'No matching plugins',
                  'plugins.inspector.surface.noMatchesDescription': 'Try a different name or plugin ID.',
                  'plugins.inspector.surface.loading': 'Loading…',
                  'plugins.inspector.surface.refreshing': 'Refreshing plugin inventory',
                  'plugins.inspector.surface.empty': 'No plugins installed.',
                  'plugins.inspector.surface.reloadSucceeded': 'Last reload succeeded',
                  'plugins.inspector.surface.reloadFailed': 'Last reload failed',
                  'plugins.inspector.surface.registryStatus': 'Registry: {status}',
                  'plugins.inspector.surface.changedPlugins': 'Changed: {plugins}',
                  'plugins.inspector.surface.openPage': 'Open full page',
                  'plugins.inspector.surface.openDiagnostics': 'Open diagnostics',
                  'plugins.inspector.surface.pageRoot': 'Page root',
                  'plugins.inspector.surface.showActions': 'Inspector actions',
                  'plugins.inspector.surface.showActionsContext': 'Open Inspector context actions',
                  'plugins.inspector.surface.selfCheck': 'Run Inspector self-check',
                  'plugins.inspector.surface.selfCheckDescription': 'Verify the Inspector action bridge.',
                },
              },
    {
        locale: "ru",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.ru,
          "plugins.inspector.title": "Инспектор плагинов",
          "plugins.inspector.description": "Проверьте установленные плагины, диагностику и состояние перезагрузки.",
          "plugins.inspector.settings.showDiagnostics": "Показать диагностику в инспекторе плагинов",
          "plugins.inspector.settings.showDiagnostics.description": "Отображение диагностических сведений для каждого плагина на поверхности инспектора.",
          "plugins.inspector.surface.reload": "Перезагрузить",
          "plugins.inspector.surface.reloading": "Перезагрузка…",
          "plugins.inspector.surface.search": "Поиск установленных плагинов",
          "plugins.inspector.surface.searchPlaceholder": "Поиск по названию или идентификатору плагина",
          "plugins.inspector.surface.inventoryIllustration": "Иллюстрация инвентаря плагина",
          "plugins.inspector.surface.noMatches": "Нет подходящих плагинов",
          "plugins.inspector.surface.noMatchesDescription": "Попробуйте другое имя или идентификатор плагина.",
          "plugins.inspector.surface.loading": "Загрузка…",
          "plugins.inspector.surface.refreshing": "Обновление инвентаря плагинов",
          "plugins.inspector.surface.empty": "Плагины не установлены.",
          "plugins.inspector.surface.reloadSucceeded": "Последняя перезагрузка прошла успешно",
          "plugins.inspector.surface.reloadFailed": "Последняя перезагрузка не удалась",
          "plugins.inspector.surface.registryStatus": "Реестр: {status}",
          "plugins.inspector.surface.changedPlugins": "Изменено: {plugins}",
          "plugins.inspector.surface.openPage": "Открыть полную страницу",
          "plugins.inspector.surface.openDiagnostics": "Открытая диагностика",
          "plugins.inspector.surface.pageRoot": "Корень страницы",
          "plugins.inspector.surface.showActions": "Действия инспектора",
          "plugins.inspector.surface.showActionsContext": "Действия контекста открытия инспектора",
          "plugins.inspector.surface.selfCheck": "Запустите самопроверку инспектора",
          "plugins.inspector.surface.selfCheckDescription": "Проверьте мост действий инспектора.",
        },
      },
    {
        locale: "pl",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.pl,
          "plugins.inspector.title": "Inspektor wtyczek",
          "plugins.inspector.description": "Sprawdź zainstalowane wtyczki, diagnostykę i stan przeładowania.",
          "plugins.inspector.settings.showDiagnostics": "Pokaż diagnostykę w Inspektorze wtyczek",
          "plugins.inspector.settings.showDiagnostics.description": "Wyświetl szczegóły diagnostyczne poszczególnych wtyczek na powierzchni inspektora.",
          "plugins.inspector.surface.reload": "Przeładować",
          "plugins.inspector.surface.reloading": "Ładuję ponownie…",
          "plugins.inspector.surface.search": "Wyszukaj zainstalowane wtyczki",
          "plugins.inspector.surface.searchPlaceholder": "Szukaj według nazwy lub identyfikatora wtyczki",
          "plugins.inspector.surface.inventoryIllustration": "Ilustracja spisu wtyczek",
          "plugins.inspector.surface.noMatches": "Brak pasujących wtyczek",
          "plugins.inspector.surface.noMatchesDescription": "Wypróbuj inną nazwę lub identyfikator wtyczki.",
          "plugins.inspector.surface.loading": "Załadunek…",
          "plugins.inspector.surface.refreshing": "Odświeżanie zapasów wtyczek",
          "plugins.inspector.surface.empty": "Brak zainstalowanych wtyczek.",
          "plugins.inspector.surface.reloadSucceeded": "Ostatnie przeładowanie powiodło się",
          "plugins.inspector.surface.reloadFailed": "Ostatnie przeładowanie nie powiodło się",
          "plugins.inspector.surface.registryStatus": "Rejestr: {status}",
          "plugins.inspector.surface.changedPlugins": "Zmieniono: {plugins}",
          "plugins.inspector.surface.openPage": "Otwórz całą stronę",
          "plugins.inspector.surface.openDiagnostics": "Otwarta diagnostyka",
          "plugins.inspector.surface.pageRoot": "Strona główna",
          "plugins.inspector.surface.showActions": "Działania inspektora",
          "plugins.inspector.surface.showActionsContext": "Otwórz akcje kontekstowe Inspektora",
          "plugins.inspector.surface.selfCheck": "Uruchom samokontrolę programu Inspector",
          "plugins.inspector.surface.selfCheckDescription": "Sprawdź mostek akcji Inspektora.",
        },
      },
    {
        locale: "es",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.es,
          "plugins.inspector.title": "Inspector de complementos",
          "plugins.inspector.description": "Inspeccione los complementos instalados, los diagnósticos y el estado de recarga.",
          "plugins.inspector.settings.showDiagnostics": "Mostrar diagnóstico en el inspector de complementos",
          "plugins.inspector.settings.showDiagnostics.description": "Muestra detalles de diagnóstico por complemento en la superficie del inspector.",
          "plugins.inspector.surface.reload": "Recargar",
          "plugins.inspector.surface.reloading": "Recargando…",
          "plugins.inspector.surface.search": "Buscar complementos instalados",
          "plugins.inspector.surface.searchPlaceholder": "Buscar por nombre o ID de complemento",
          "plugins.inspector.surface.inventoryIllustration": "Ilustración de inventario de complementos",
          "plugins.inspector.surface.noMatches": "No hay complementos coincidentes",
          "plugins.inspector.surface.noMatchesDescription": "Pruebe con un nombre o ID de complemento diferente.",
          "plugins.inspector.surface.loading": "Cargando…",
          "plugins.inspector.surface.refreshing": "Actualización del inventario de complementos",
          "plugins.inspector.surface.empty": "No hay complementos instalados.",
          "plugins.inspector.surface.reloadSucceeded": "La última recarga fue exitosa",
          "plugins.inspector.surface.reloadFailed": "La última recarga falló",
          "plugins.inspector.surface.registryStatus": "Registro: {status}",
          "plugins.inspector.surface.changedPlugins": "Modificados: {plugins}",
          "plugins.inspector.surface.openPage": "Abrir página completa",
          "plugins.inspector.surface.openDiagnostics": "Diagnóstico abierto",
          "plugins.inspector.surface.pageRoot": "raíz de la página",
          "plugins.inspector.surface.showActions": "Acciones del inspector",
          "plugins.inspector.surface.showActionsContext": "Acciones de contexto de Abrir Inspector",
          "plugins.inspector.surface.selfCheck": "Ejecute la autocomprobación del Inspector",
          "plugins.inspector.surface.selfCheckDescription": "Verifique el puente de acción del Inspector.",
        },
      },
    {
        locale: "fr",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.fr,
          "plugins.inspector.title": "Inspecteur de plugins",
          "plugins.inspector.description": "Inspectez les plugins installés, les diagnostics et l’état de rechargement.",
          "plugins.inspector.settings.showDiagnostics": "Afficher les diagnostics dans l'inspecteur de plug-in",
          "plugins.inspector.settings.showDiagnostics.description": "Affichez les détails du diagnostic par plug-in dans la surface de l'inspecteur.",
          "plugins.inspector.surface.reload": "Recharger",
          "plugins.inspector.surface.reloading": "Rechargement…",
          "plugins.inspector.surface.search": "Rechercher les plugins installés",
          "plugins.inspector.surface.searchPlaceholder": "Rechercher par nom ou ID de plugin",
          "plugins.inspector.surface.inventoryIllustration": "Illustration de l'inventaire des plugins",
          "plugins.inspector.surface.noMatches": "Aucun plugin correspondant",
          "plugins.inspector.surface.noMatchesDescription": "Essayez un autre nom ou ID de plugin.",
          "plugins.inspector.surface.loading": "Chargement…",
          "plugins.inspector.surface.refreshing": "Actualisation de l'inventaire des plugins",
          "plugins.inspector.surface.empty": "Aucun plugin installé.",
          "plugins.inspector.surface.reloadSucceeded": "Dernier rechargement réussi",
          "plugins.inspector.surface.reloadFailed": "Le dernier rechargement a échoué",
          "plugins.inspector.surface.registryStatus": "Registre : {status}",
          "plugins.inspector.surface.changedPlugins": "Modifiés : {plugins}",
          "plugins.inspector.surface.openPage": "Ouvrir la page entière",
          "plugins.inspector.surface.openDiagnostics": "Ouvrir le diagnostic",
          "plugins.inspector.surface.pageRoot": "Racine de la page",
          "plugins.inspector.surface.showActions": "Actions de l'inspecteur",
          "plugins.inspector.surface.showActionsContext": "Actions contextuelles de l'inspecteur ouvert",
          "plugins.inspector.surface.selfCheck": "Exécuter l'auto-vérification de l'inspecteur",
          "plugins.inspector.surface.selfCheckDescription": "Vérifiez le pont d’action de l’inspecteur.",
        },
      },
    {
        locale: "it",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.it,
          "plugins.inspector.title": "Ispettore plugin",
          "plugins.inspector.description": "Ispeziona i plugin installati, la diagnostica e lo stato di ricarica.",
          "plugins.inspector.settings.showDiagnostics": "Mostra la diagnostica nell'ispettore plugin",
          "plugins.inspector.settings.showDiagnostics.description": "Visualizza i dettagli diagnostici per plug-in nella superficie di ispezione.",
          "plugins.inspector.surface.reload": "Ricaricare",
          "plugins.inspector.surface.reloading": "Ricaricamento in corso...",
          "plugins.inspector.surface.search": "Cerca i plugin installati",
          "plugins.inspector.surface.searchPlaceholder": "Cerca per nome o ID plug-in",
          "plugins.inspector.surface.inventoryIllustration": "Illustrazione dell'inventario dei plug-in",
          "plugins.inspector.surface.noMatches": "Nessun plugin corrispondente",
          "plugins.inspector.surface.noMatchesDescription": "Prova un nome o un ID plug-in diverso.",
          "plugins.inspector.surface.loading": "Caricamento…",
          "plugins.inspector.surface.refreshing": "Aggiornamento dell'inventario dei plug-in",
          "plugins.inspector.surface.empty": "Nessun plugin installato.",
          "plugins.inspector.surface.reloadSucceeded": "L'ultima ricarica è riuscita",
          "plugins.inspector.surface.reloadFailed": "L'ultima ricarica non è riuscita",
          "plugins.inspector.surface.registryStatus": "Registro: {status}",
          "plugins.inspector.surface.changedPlugins": "Modificati: {plugins}",
          "plugins.inspector.surface.openPage": "Apri la pagina intera",
          "plugins.inspector.surface.openDiagnostics": "Apri la diagnostica",
          "plugins.inspector.surface.pageRoot": "Radice della pagina",
          "plugins.inspector.surface.showActions": "Azioni dell'ispettore",
          "plugins.inspector.surface.showActionsContext": "Apri le azioni contestuali di Inspector",
          "plugins.inspector.surface.selfCheck": "Esegui l'autocontrollo dell'ispettore",
          "plugins.inspector.surface.selfCheckDescription": "Verificare il ponte di azione dell'ispettore.",
        },
      },
    {
        locale: "pt",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.pt,
          "plugins.inspector.title": "Inspetor de plug-ins",
          "plugins.inspector.description": "Inspecione plug-ins instalados, diagnósticos e estado de recarga.",
          "plugins.inspector.settings.showDiagnostics": "Mostrar diagnósticos no Plugin Inspector",
          "plugins.inspector.settings.showDiagnostics.description": "Exibir detalhes de diagnóstico por plug-in na superfície do inspetor.",
          "plugins.inspector.surface.reload": "Recarregar",
          "plugins.inspector.surface.reloading": "Recarregando…",
          "plugins.inspector.surface.search": "Pesquise plug-ins instalados",
          "plugins.inspector.surface.searchPlaceholder": "Pesquise por nome ou ID do plugin",
          "plugins.inspector.surface.inventoryIllustration": "Ilustração de inventário de plug-ins",
          "plugins.inspector.surface.noMatches": "Nenhum plug-in correspondente",
          "plugins.inspector.surface.noMatchesDescription": "Tente um nome ou ID de plugin diferente.",
          "plugins.inspector.surface.loading": "Carregando…",
          "plugins.inspector.surface.refreshing": "Atualizando inventário de plug-ins",
          "plugins.inspector.surface.empty": "Nenhum plug-in instalado.",
          "plugins.inspector.surface.reloadSucceeded": "Última recarga bem-sucedida",
          "plugins.inspector.surface.reloadFailed": "Falha na última recarga",
          "plugins.inspector.surface.registryStatus": "Registo: {status}",
          "plugins.inspector.surface.changedPlugins": "Alterados: {plugins}",
          "plugins.inspector.surface.openPage": "Abrir página inteira",
          "plugins.inspector.surface.openDiagnostics": "Diagnóstico aberto",
          "plugins.inspector.surface.pageRoot": "Raiz da página",
          "plugins.inspector.surface.showActions": "Ações do inspetor",
          "plugins.inspector.surface.showActionsContext": "Abrir ações de contexto do Inspetor",
          "plugins.inspector.surface.selfCheck": "Execute a autoverificação do Inspetor",
          "plugins.inspector.surface.selfCheckDescription": "Verifique a ponte de ação do Inspetor.",
        },
      },
    {
        locale: "ca",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.ca,
          "plugins.inspector.title": "Inspector de connectors",
          "plugins.inspector.description": "Inspeccioneu els connectors instal·lats, els diagnòstics i l'estat de recàrrega.",
          "plugins.inspector.settings.showDiagnostics": "Mostra els diagnòstics a Plugin Inspector",
          "plugins.inspector.settings.showDiagnostics.description": "Mostra els detalls de diagnòstic per connector a la superfície de l'inspector.",
          "plugins.inspector.surface.reload": "Torna a carregar",
          "plugins.inspector.surface.reloading": "S'està tornant a carregar…",
          "plugins.inspector.surface.search": "Cerca connectors instal·lats",
          "plugins.inspector.surface.searchPlaceholder": "Cerca per nom o identificador del connector",
          "plugins.inspector.surface.inventoryIllustration": "Il·lustració de l'inventari de connectors",
          "plugins.inspector.surface.noMatches": "No hi ha connectors coincidents",
          "plugins.inspector.surface.noMatchesDescription": "Prova un nom o un ID de connector diferents.",
          "plugins.inspector.surface.loading": "S'està carregant…",
          "plugins.inspector.surface.refreshing": "S'està actualitzant l'inventari de connectors",
          "plugins.inspector.surface.empty": "No hi ha connectors instal·lats.",
          "plugins.inspector.surface.reloadSucceeded": "La darrera recàrrega s'ha realitzat correctament",
          "plugins.inspector.surface.reloadFailed": "La darrera recàrrega ha fallat",
          "plugins.inspector.surface.registryStatus": "Registre: {status}",
          "plugins.inspector.surface.changedPlugins": "Canviats: {plugins}",
          "plugins.inspector.surface.openPage": "Obre la pàgina sencera",
          "plugins.inspector.surface.openDiagnostics": "Diagnòstic obert",
          "plugins.inspector.surface.pageRoot": "Arrel de la pàgina",
          "plugins.inspector.surface.showActions": "Accions dels inspectors",
          "plugins.inspector.surface.showActionsContext": "Accions de context Open Inspector",
          "plugins.inspector.surface.selfCheck": "Executeu l'autocomprovació de l'inspector",
          "plugins.inspector.surface.selfCheckDescription": "Verifiqueu el pont d'acció de l'inspector.",
        },
      },
    {
        locale: "zh-Hans",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS["zh-Hans"],
          "plugins.inspector.title": "插件检查器",
          "plugins.inspector.description": "检查已安装的插件、诊断和重新加载状态。",
          "plugins.inspector.settings.showDiagnostics": "在插件检查器中显示诊断",
          "plugins.inspector.settings.showDiagnostics.description": "在检查器界面中显示每个插件的诊断详细信息。",
          "plugins.inspector.surface.reload": "重新加载",
          "plugins.inspector.surface.reloading": "正在重新加载...",
          "plugins.inspector.surface.search": "搜索已安装的插件",
          "plugins.inspector.surface.searchPlaceholder": "按名称或插件 ID 搜索",
          "plugins.inspector.surface.inventoryIllustration": "插件库存图",
          "plugins.inspector.surface.noMatches": "没有匹配的插件",
          "plugins.inspector.surface.noMatchesDescription": "尝试不同的名称或插件 ID 。",
          "plugins.inspector.surface.loading": "加载中…",
          "plugins.inspector.surface.refreshing": "刷新插件清单",
          "plugins.inspector.surface.empty": "没有安装插件。",
          "plugins.inspector.surface.reloadSucceeded": "上次重新加载成功",
          "plugins.inspector.surface.reloadFailed": "上次重新加载失败",
          "plugins.inspector.surface.registryStatus": "注册表：{status}",
          "plugins.inspector.surface.changedPlugins": "已更改：{plugins}",
          "plugins.inspector.surface.openPage": "打开整页",
          "plugins.inspector.surface.openDiagnostics": "打开诊断",
          "plugins.inspector.surface.pageRoot": "页面根目录",
          "plugins.inspector.surface.showActions": "检查员行动",
          "plugins.inspector.surface.showActionsContext": "打开检查器上下文操作",
          "plugins.inspector.surface.selfCheck": "运行 Inspector 自检",
          "plugins.inspector.surface.selfCheckDescription": "验证 Inspector 操作桥。",
        },
      },
    {
        locale: "zh-Hant",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS["zh-Hant"],
          "plugins.inspector.title": "插件檢查器",
          "plugins.inspector.description": "檢查已安裝的插件、診斷和重新載入狀態。",
          "plugins.inspector.settings.showDiagnostics": "在插件檢查器中顯示診斷",
          "plugins.inspector.settings.showDiagnostics.description": "在檢查器介面中顯示每個插件的診斷詳細資訊。",
          "plugins.inspector.surface.reload": "重新載入",
          "plugins.inspector.surface.reloading": "正在重新加載...",
          "plugins.inspector.surface.search": "搜尋已安裝的插件",
          "plugins.inspector.surface.searchPlaceholder": "按名稱或插件ID搜尋",
          "plugins.inspector.surface.inventoryIllustration": "插件庫存圖",
          "plugins.inspector.surface.noMatches": "沒有匹配的插件",
          "plugins.inspector.surface.noMatchesDescription": "嘗試不同的名稱或插件ID 。",
          "plugins.inspector.surface.loading": "載入中…",
          "plugins.inspector.surface.refreshing": "刷新插件清單",
          "plugins.inspector.surface.empty": "沒有安裝插件。",
          "plugins.inspector.surface.reloadSucceeded": "上次重新載入成功",
          "plugins.inspector.surface.reloadFailed": "上次重新載入失敗",
          "plugins.inspector.surface.registryStatus": "登錄檔：{status}",
          "plugins.inspector.surface.changedPlugins": "已變更：{plugins}",
          "plugins.inspector.surface.openPage": "打開整頁",
          "plugins.inspector.surface.openDiagnostics": "打開診斷",
          "plugins.inspector.surface.pageRoot": "頁面根目錄",
          "plugins.inspector.surface.showActions": "檢查員行動",
          "plugins.inspector.surface.showActionsContext": "開啟檢查器上下文操作",
          "plugins.inspector.surface.selfCheck": "運行 Inspector 自檢",
          "plugins.inspector.surface.selfCheckDescription": "驗證 Inspector 操作橋。",
        },
      },
    {
        locale: "ja",
        messages: {
          ...INSPECTOR_ADDITIONAL_UI_TRANSLATIONS.ja,
          "plugins.inspector.title": "プラグインインスペクター",
          "plugins.inspector.description": "インストールされているプラ​​グイン、診断、およびリロード状態を検査します。",
          "plugins.inspector.settings.showDiagnostics": "Plugin Inspector で診断を表示する",
          "plugins.inspector.settings.showDiagnostics.description": "インスペクター画面にプラグインごとの診断の詳細を表示します。",
          "plugins.inspector.surface.reload": "リロード",
          "plugins.inspector.surface.reloading": "リロード中…",
          "plugins.inspector.surface.search": "インストールされているプラ​​グインを検索する",
          "plugins.inspector.surface.searchPlaceholder": "名前またはプラグイン ID で検索",
          "plugins.inspector.surface.inventoryIllustration": "プラグインインベントリの図",
          "plugins.inspector.surface.noMatches": "一致するプラグインがありません",
          "plugins.inspector.surface.noMatchesDescription": "別の名前またはプラグイン ID を試してください。",
          "plugins.inspector.surface.loading": "読み込み中…",
          "plugins.inspector.surface.refreshing": "プラグインインベントリの更新",
          "plugins.inspector.surface.empty": "プラグインがインストールされていません。",
          "plugins.inspector.surface.reloadSucceeded": "最後のリロードは成功しました",
          "plugins.inspector.surface.reloadFailed": "最後のリロードに失敗しました",
          "plugins.inspector.surface.registryStatus": "レジストリ: {status}",
          "plugins.inspector.surface.changedPlugins": "変更済み: {plugins}",
          "plugins.inspector.surface.openPage": "全ページを開く",
          "plugins.inspector.surface.openDiagnostics": "オープン診断",
          "plugins.inspector.surface.pageRoot": "ページルート",
          "plugins.inspector.surface.showActions": "検査官のアクション",
          "plugins.inspector.surface.showActionsContext": "インスペクターのコンテキストアクションを開く",
          "plugins.inspector.surface.selfCheck": "インスペクターのセルフチェックを実行する",
          "plugins.inspector.surface.selfCheckDescription": "Inspector アクション ブリッジを確認します。",
        },
      },
  ],
};

export const INSPECTOR_PLUGIN = definePlugin({
  id: INSPECTOR_PLUGIN_ID,
  version: '0.0.0',
  displayName: 'Plugin Inspector',
  description: 'First-party Plugin SDK inspector for installed plugin state and reload diagnostics.',
  brand: { iconResourceId: INSPECTOR_BRAND_RESOURCE_ID },
  engines: { happier: '^0.0.0' }, runtime: { apiVersion: 1 },
  entrypoints: { daemon: './.happier-plugin/daemon.js' },
  hostAccess: {
    required: [],
    optional: [],
  },
  actions: {
    [INSPECTOR_SELF_CHECK_ACTION_ID]: {
      title: {
        key: 'plugins.inspector.surface.selfCheck',
        fallback: 'Run Inspector self-check',
      },
      execution: { target: 'daemon' },
      description: {
        key: 'plugins.inspector.surface.selfCheckDescription',
        fallback: 'Verify the Inspector action bridge.',
      },
      scopes: ['global'],
      surfaces: ['ui'],
      placementBindings: ['toolbar'],
      dangerLevel: 'safe',
      resultSchema: {
        type: 'object',
        additionalProperties: false,
        properties: { ok: { type: 'boolean' } },
        required: ['ok'],
      },
      run: runInspectorSelfCheck,
    },
  },
  resources: {
    [INSPECTOR_BRAND_RESOURCE_ID]: {
      kind: 'asset' as const,
      path: 'assets/brand.png',
      contentType: 'image/png',
    },
    [INSPECTOR_INVENTORY_ILLUSTRATION_RESOURCE_ID]: {
      kind: 'asset' as const,
      path: 'assets/inventory.png',
      contentType: 'image/png',
    },
  },
  settings: {
    [INSPECTOR_SETTINGS_ID]: INSPECTOR_SETTINGS,
  },
  ui: INSPECTOR_UI,
});

export const PLUGIN_MANIFEST = INSPECTOR_PLUGIN.manifest;
