/** Action-domain envelope over the shared input vocabulary. */
export {
  InputWidgetSchema as ActionInputWidgetSchema,
  type InputWidget as ActionInputWidget,
  type InputOptionValue as ActionInputOptionValue,
  InputOptionValueSchema as ActionInputOptionValueSchema,
  readInputOptionValue as readActionInputOptionValue,
  isSameInputOptionValue as isSameActionInputOptionValue,
  inputOptionValueKey as actionInputOptionValueKey,
  inputOptionValueSearchText as actionInputOptionValueSearchText,
  type InputHintOptionDescriptor as ActionInputHintOptionDescriptor,
  type InputFieldHintDescriptor as ActionInputFieldHintDescriptor,
  type InputHintsDescriptor as ActionInputHintsDescriptor,
  createInputHintsSchemas as createActionInputHintsSchemas,
  createInputHintsSchemasWithoutOptionsSource as createActionInputHintsSchemasWithoutOptionsSource,
  createInputHintsSchemasWithStaticOptionsOnly as createActionInputHintsSchemasWithStaticOptionsOnly,
  InputOptionSchema as ActionInputOptionSchema,
  type InputOption as ActionInputOption,
  InputFieldHintSchema as ActionInputFieldHintSchema,
  type InputFieldHint as ActionInputFieldHint,
  InputHintsSchema as ActionInputHintsSchema,
  type InputHints as ActionInputHints,
  normalizeInputHintsText as normalizeActionInputHintsText,
} from '../inputs/inputFields.js';
export { InputPathSchema as ActionInputPathSchema, type InputPath as ActionInputPath } from '../inputs/inputPredicates.js';
