import { z } from 'zod';

import { PLUGIN_SETTINGS_ADMINISTRATION_ACTION_IDS_V1 } from '../plugins/settingsAdministration.js';

/**
 * The closed host Action vocabulary for the public plugin-authoring journey.
 * These operations project existing CLI/daemon owners; they do not make
 * plugin authoring a second command dispatcher.
 */
export const PLUGIN_DEV_LOOP_ACTION_IDS_V1 = [
  'plugins.scaffold',
  'plugins.install',
  'plugins.uninstall',
  'plugins.dev',
  'plugins.author.install',
  'plugins.author.typecheck',
  'plugins.author.build',
  'plugins.author.test',
  'plugins.doctor',
  'plugins.pack',
  'plugins.reload',
  'plugins.list',
  'plugins.change.status',
] as const;
export type PluginDevLoopActionIdV1 = typeof PLUGIN_DEV_LOOP_ACTION_IDS_V1[number];

export function isPluginDevLoopActionIdV1(value: string): value is PluginDevLoopActionIdV1 {
  return (PLUGIN_DEV_LOOP_ACTION_IDS_V1 as readonly string[]).includes(value);
}

// B8 closure note:
// Action ids remain protocol-owned and closed in this wave.
// Plugin/runtime unification must not imply plugin-defined action-id authoring parity yet.
export const ACTION_ID_FAMILIES_V1 = Object.freeze({
  discovery: [
    'action.spec.search',
    'action.spec.get',
    'action.options.resolve',
    'action.invoke',
  ],
  session_lifecycle: [
    'session.open',
    'session.fork',
    'session.continue_with_replay',
    'session.rollback',
    'session.checkpoint_code_rollback',
    'session.checkpoint',
    'session.restore',
    'session.handoff',
    'session.handoff.prepare_target',
    'session.handoff.prepare_target.resume',
    'session.handoff.prepare_target_result.get',
    'session.handoff.commit',
    'session.handoff.abort',
    'session.handoff.status.get',
    'session.spawn_new',
  ],
  inventory: [
    'paths.list_recent',
    'machines.list',
    'servers.list',
    'review.engines.list',
    'agents.backends.list',
    'agents.models.list',
    'agents.config_options.list',
    'agents.session_modes.list',
    'sessions.spawn.profiles.list',
    'sessions.spawn.connected_services.list',
    'sessions.spawn.mcp_servers.preview',
  ],
  messaging: [
    'session.message.send',
  ],
  session_control: [
    'session.stop',
    'session.title.set',
    'session.model.set',
    'session.permission_mode.set',
    'session.archive',
    'session.unarchive',
    'session.status.get',
    'session.work_state.get',
    'session.goal.get',
    'session.goal.set',
    'session.goal.clear',
    'session.usageLimit.waitResume.enable',
    'session.usageLimit.waitResume.cancel',
    'session.usageLimit.checkNow',
    'session.usageLimit.consumeResetCredit',
    'session.terminalComposer.clear',
    'session.pendingInput.interruptAndRun',
    'session.vendor_plugin_catalog.list',
    'session.skill_catalog.list',
    'session.history.get',
    'session.wait.idle',
  ],
  intent_start: [
    'review.start',
    'subagents.plan.start',
    'subagents.delegate.start',
    'voice_agent.start',
  ],
  review_comments: [
    'reviews.comments.create',
    'reviews.comments.list',
    'reviews.comments.get',
    'reviews.comments.transition',
    'reviews.comments.edit',
    'reviews.comments.reply',
    'reviews.comments.redact',
    'reviews.comments.setDisposition',
    'reviews.comments.attachEvidence',
    'reviews.comments.bulkTransition',
  ],
  subagent_registry: [
    'sessions.subagents.list',
    'sessions.subagents.get',
    'sessions.subagents.watch',
    'sessions.subagents.upsert',
    'sessions.subagents.updateStatus',
    'sessions.subagents.complete',
  ],
  execution_run_control: [
    'execution.run.start',
    'execution.run.list',
    'execution.run.get',
    'execution.run.send',
    'execution.run.ensure',
    'execution.run.ensure_or_start',
    'execution.run.stream.start',
    'execution.run.stream.read',
    'execution.run.stream.cancel',
    'execution.run.stop',
    'execution.run.action',
    'execution.run.wait',
  ],
  session_targeting: [
    'session.target.primary.set',
    'session.target.tracked.set',
    'session.list',
    'session.activity.get',
    'session.messages.recent.get',
  ],
  session_transcripts: [
    'session.transcript.get',
    'session.events.get',
    'session.log.tail',
    'transcript.page',
    'transcript.readAfter',
    'transcript.follow',
    'transcript.unfollow',
    'transcript.import',
    'transcript.search',
  ],
  session_permissions: [
    'session.permission.respond',
    'session.permission.remote.pending.list',
    'session.permission.remote.respond',
    'session.permission.remote.grants.list',
    'session.permission.remote.grants.revoke',
    'session.user_action.answer',
    'session.mode.set',
  ],
  external_sessions: [
    'sessions.external.candidates.list',
    'sessions.external.link.ensure',
    'sessions.external.follow',
    'sessions.external.unfollow',
    'sessions.external.backgroundFollow.set',
    'sessions.external.status.get',
    'sessions.external.transcript.page',
    'sessions.external.transcript.readAfter',
    'sessions.external.takeover',
    'sessions.external.materialize.start',
    'sessions.external.takeover.start',
    'sessions.external.operation.status.get',
    'sessions.external.operation.cancel',
    'sessions.external.operation.resume',
    'sessions.external.operation.retry',
    'sessions.external.operation.discard',
  ],
  voice_controls: [
    'ui.voice_global.reset',
    'ui.voice_agent.teleport',
  ],
  current_ui_context: [
    'ui.current_context.read',
    'ui.current_context.command.invoke',
  ],
  companion_controls: [
    'ui.pet.choose',
  ],
  memory: [
    'memory.search',
    'memory.get_window',
    'memory.ensure_up_to_date',
  ],
  prompt_library: [
    'prompt_doc.update',
    'prompt_bundle.update',
    'prompt_asset.export',
    'prompt_registry.install',
  ],
  daemon_admin: [
    'daemon.promptAssets.discover',
    'daemon.promptAssets.delete',
    'daemon.promptRegistry.scanSource',
    'daemon.promptRegistry.install',
    'daemon.filesystem.readFile',
    'daemon.filesystem.writeFile',
    'daemon.filesystem.listDirectory',
    'daemon.filesystem.getDirectoryTree',
    'daemon.filesystem.listRoots',
    'daemon.filesystem.browseDirectory',
    'bugreport.collectDiagnostics',
    'bugreport.getLogTail',
    'bugreport.uploadArtifact',
  ],
  browser_control: [
    'browser.session.create',
    'browser.session.close',
    'browser.view.open',
    'browser.view.close',
    'browser.view.focus',
    'browser.target.set',
    'browser.navigate',
    'browser.reload',
    'browser.goBack',
    'browser.goForward',
    'browser.stop',
  ],
  browser_diagnostics: [
    'browser.diagnostics.snapshot',
    'browser.diagnostics.clear',
    'browser.diagnostics.pause',
    'browser.diagnostics.resume',
    'browser.diagnostics.eval',
    'browser.diagnostics.getProperties',
    'browser.diagnostics.releaseObjectGroup',
    'browser.diagnostics.elementPicker.start',
    'browser.diagnostics.elementPicker.cancel',
  ],
  browser_context: [
    'browser.context.capturePage',
    'browser.context.captureScreenshot',
    'browser.context.captureSelectedElement',
    'browser.context.captureNetworkSummary',
    'browser.context.captureConsoleSummary',
    'browser.context.annotation.start',
    'browser.context.annotation.cancel',
    'browser.context.annotation.captureRegion',
    'browser.context.annotation.captureElement',
    'browser.context.annotation.attachComment',
    'browser.context.annotation.attachStroke',
    'browser.context.annotation.attachStyleIntent',
    'browser.context.attachToComposer',
    'browser.context.attachToAgentTurn',
    'browser.context.clear',
  ],
  browser_automation: [
    'browser.automation.status',
    'browser.automation.snapshot',
    'browser.automation.semanticSnapshot',
    'browser.automation.queryElements',
    'browser.automation.waitFor',
    'browser.automation.timeline.get',
    'browser.automation.cancelActive',
    'browser.automation.navigate',
    'browser.automation.reload',
    'browser.automation.goBack',
    'browser.automation.goForward',
    'browser.automation.click',
    'browser.automation.tap',
    'browser.automation.type',
    'browser.automation.press',
    'browser.automation.scroll',
    'browser.automation.hover',
    'browser.automation.focus',
    'browser.automation.select',
    'browser.automation.setValue',
  ],
  browser_recording: [
    'browser.recording.start',
    'browser.recording.stop',
    'browser.recording.cancel',
    'browser.recording.status',
    'browser.recording.listForView',
    'browser.recording.discard',
    'browser.recording.cleanupExpired',
    'browser.recording.attachToComposer',
  ],
  local_services_inventory: [
    'localServices.inventory.list',
    'localServices.inventory.refresh',
  ],
  local_services_launcher: [
    'localServices.launcher.snapshot',
    'localServices.launcher.start',
    'localServices.launcher.openPreview',
    'localServices.launcher.registerPreview',
    'localServices.launcher.history.clear',
  ],
  local_services_preview: [
    'localServices.preview.openOrCreate',
    'localServices.preview.status',
    'localServices.preview.revoke',
  ],
  local_services_public_preview: [
    'localServices.publicPreview.create',
    'localServices.publicPreview.status',
    'localServices.publicPreview.revoke',
    'localServices.publicPreview.copyUrl',
  ],
  local_services_actions: [
    'localServices.actions.copyUrl',
    'localServices.actions.openPreview',
    'localServices.actions.forget',
    'localServices.actions.stopManaged',
    'localServices.actions.restartManaged',
    'localServices.actions.terminateDetected',
  ],
  peer_mediation_observability: [
    'peerMediation.observability.snapshot',
    'peerMediation.observability.subscribe',
    'peerMediation.observability.unsubscribe',
  ],
  devices_simulator: [
    'devices.simulator.list',
    'devices.simulator.stream.keyframe',
    'devices.simulator.stream.snapshot',
    'devices.simulator.stream.quality.set',
    'devices.simulator.stream.fps.set',
    'devices.simulator.stream.scale.set',
    'devices.simulator.lease.acquire',
    'devices.simulator.lease.renew',
    'devices.simulator.lease.release',
    'devices.simulator.input.tap',
    'devices.simulator.input.swipe',
    'devices.simulator.input.text',
    'devices.simulator.input.key',
    'devices.simulator.input.button',
    'devices.simulator.input.orientation',
    'devices.simulator.input.pinch',
    'devices.simulator.input.rotate',
    'devices.simulator.sideband.request',
  ],
  approvals: [
    'approval.request.list',
    'approval.request.get',
    'approval.request.create',
    'approval.request.decide',
  ],
  plugin_dev_loop: [
    ...PLUGIN_DEV_LOOP_ACTION_IDS_V1,
    'plugins.sessionHooks.status.get',
    'plugins.sessionHooks.install',
    'plugins.sessionHooks.disable',
    'plugins.sessionHooks.enable',
    'plugins.sessionHooks.uninstall',
  ],
  plugin_settings_administration: PLUGIN_SETTINGS_ADMINISTRATION_ACTION_IDS_V1,
  plugin_permission_grants: [
    'plugins.permissions.grants.list',
    'plugins.permissions.grants.request',
    'plugins.permissions.grants.grant',
    'plugins.permissions.grants.revoke',
    'plugins.permissions.grants.dismissRequest',
  ],
  plugin_webhooks: [
    'plugin.webhook.endpoint.ensure',
    'plugin.webhook.endpoint.read',
    'plugin.webhook.endpoint.revoke',
    'plugin.webhook.endpoint.retarget',
    'plugin.webhook.endpoint.checkCorrespondence',
    'plugin.webhook.delivery.movePending',
    'plugin.webhook.endpoint.credential.configure',
    'plugin.webhook.endpoint.credential.rotate',
    'plugin.webhook.endpoint.credential.finishRotation',
  ],
  account_plugin_data: [
    'account.plugins.data.erase',
  ],
  account_sessions: [
    'account.sessions.signOutEverywhere',
  ],
  account_api_tokens: [
    'account.apiTokens.create',
    'account.apiTokens.list',
    'account.apiTokens.revoke',
    'account.apiTokens.revokeAll',
  ],
  automation_events: [
    'automation.event.sources.list',
    'automation.event.admit',
    'automation.event.source.status.report',
  ],
  automation_conversation: [
    'automation.conversation.targets.list',
    'automation.conversation.target.verify',
    'automation.conversation.admit',
  ],
  scm_pull_request: [
    'scm.pullRequest.list',
    'scm.pullRequest.get',
    'scm.pullRequest.openOrReuse',
    'scm.pullRequest.openCompose',
    'scm.pullRequest.checkout',
    'scm.pullRequest.prepareWorktree',
    'scm.pullRequest.runStacked',
  ],
  scm_repository: [
    'scm.repository.clone',
    'scm.repository.init',
    'scm.repository.removeIndexLock',
    'scm.hostingRepository.describePublishTargets',
    'scm.hostingRepository.publish',
  ],
  scm_diff_summary: [
    'scm.diffSummary.generate',
  ],
} as const);

export const ACTION_IDS = [
  ...ACTION_ID_FAMILIES_V1.discovery,
  ...ACTION_ID_FAMILIES_V1.session_lifecycle,
  ...ACTION_ID_FAMILIES_V1.inventory,
  ...ACTION_ID_FAMILIES_V1.messaging,
  ...ACTION_ID_FAMILIES_V1.session_control,
  ...ACTION_ID_FAMILIES_V1.intent_start,
  ...ACTION_ID_FAMILIES_V1.review_comments,
  ...ACTION_ID_FAMILIES_V1.subagent_registry,
  ...ACTION_ID_FAMILIES_V1.execution_run_control,
  ...ACTION_ID_FAMILIES_V1.session_targeting,
  ...ACTION_ID_FAMILIES_V1.session_transcripts,
  ...ACTION_ID_FAMILIES_V1.session_permissions,
  ...ACTION_ID_FAMILIES_V1.external_sessions,
  ...ACTION_ID_FAMILIES_V1.voice_controls,
  ...ACTION_ID_FAMILIES_V1.current_ui_context,
  ...ACTION_ID_FAMILIES_V1.companion_controls,
  ...ACTION_ID_FAMILIES_V1.memory,
  ...ACTION_ID_FAMILIES_V1.prompt_library,
  ...ACTION_ID_FAMILIES_V1.daemon_admin,
  ...ACTION_ID_FAMILIES_V1.browser_control,
  ...ACTION_ID_FAMILIES_V1.browser_diagnostics,
  ...ACTION_ID_FAMILIES_V1.browser_context,
  ...ACTION_ID_FAMILIES_V1.browser_automation,
  ...ACTION_ID_FAMILIES_V1.browser_recording,
  ...ACTION_ID_FAMILIES_V1.local_services_inventory,
  ...ACTION_ID_FAMILIES_V1.local_services_launcher,
  ...ACTION_ID_FAMILIES_V1.local_services_preview,
  ...ACTION_ID_FAMILIES_V1.local_services_public_preview,
  ...ACTION_ID_FAMILIES_V1.local_services_actions,
  ...ACTION_ID_FAMILIES_V1.peer_mediation_observability,
  ...ACTION_ID_FAMILIES_V1.devices_simulator,
  ...ACTION_ID_FAMILIES_V1.approvals,
  ...ACTION_ID_FAMILIES_V1.plugin_dev_loop,
  ...ACTION_ID_FAMILIES_V1.plugin_settings_administration,
  ...ACTION_ID_FAMILIES_V1.plugin_permission_grants,
  ...ACTION_ID_FAMILIES_V1.plugin_webhooks,
  ...ACTION_ID_FAMILIES_V1.account_plugin_data,
  ...ACTION_ID_FAMILIES_V1.account_sessions,
  ...ACTION_ID_FAMILIES_V1.account_api_tokens,
  ...ACTION_ID_FAMILIES_V1.automation_events,
  ...ACTION_ID_FAMILIES_V1.automation_conversation,
  ...ACTION_ID_FAMILIES_V1.scm_pull_request,
  ...ACTION_ID_FAMILIES_V1.scm_repository,
  ...ACTION_ID_FAMILIES_V1.scm_diff_summary,
] as const;

export const RUNTIME_ACTION_IDS_V1 = [
  ...ACTION_ID_FAMILIES_V1.browser_control,
  ...ACTION_ID_FAMILIES_V1.browser_diagnostics,
  ...ACTION_ID_FAMILIES_V1.browser_context,
  ...ACTION_ID_FAMILIES_V1.browser_automation,
  ...ACTION_ID_FAMILIES_V1.browser_recording,
  ...ACTION_ID_FAMILIES_V1.local_services_inventory,
  ...ACTION_ID_FAMILIES_V1.local_services_launcher,
  ...ACTION_ID_FAMILIES_V1.local_services_preview,
  ...ACTION_ID_FAMILIES_V1.local_services_public_preview,
  ...ACTION_ID_FAMILIES_V1.local_services_actions,
  ...ACTION_ID_FAMILIES_V1.peer_mediation_observability,
  ...ACTION_ID_FAMILIES_V1.devices_simulator,
] as const;

export const ActionIdSchema = z.enum(ACTION_IDS);
export type ActionId = z.infer<typeof ActionIdSchema>;
export type ActionIdFamilyV1 = keyof typeof ACTION_ID_FAMILIES_V1;

export const RuntimeActionIdV1Schema = z.enum(RUNTIME_ACTION_IDS_V1);
export type RuntimeActionIdV1 = z.infer<typeof RuntimeActionIdV1Schema>;

const RUNTIME_ACTION_ID_V1_SET: ReadonlySet<string> = new Set(RUNTIME_ACTION_IDS_V1);

export function isRuntimeActionIdV1(value: string): value is RuntimeActionIdV1 {
  return RUNTIME_ACTION_ID_V1_SET.has(value);
}

const LEGACY_ACTION_ID_ALIASES: Readonly<Record<string, ActionId>> = Object.freeze({
  'plan.start': 'subagents.plan.start',
  'delegate.start': 'subagents.delegate.start',
  'sessions.external.attach': 'sessions.external.follow',
  'sessions.external.detach': 'sessions.external.unfollow',
});

export function normalizeLegacyActionId(value: string): string {
  return LEGACY_ACTION_ID_ALIASES[value] ?? value;
}
