import { z } from 'zod';

// B8 closure note:
// Action ids remain protocol-owned and closed in this wave.
// Plugin/runtime unification must not imply plugin-defined action-id authoring parity yet.
export const ACTION_ID_FAMILIES_V1 = Object.freeze({
  discovery: [
    'action.spec.search',
    'action.spec.get',
    'action.options.resolve',
  ],
  session_lifecycle: [
    'session.open',
    'session.fork',
    'session.continue_with_replay',
    'session.rollback',
    'session.checkpoint_code_rollback',
    'session.checkpoint',
    'session.restore',
    'session.handoff',
    'session.handoff.prepare_target',
    'session.handoff.prepare_target_result.get',
    'session.handoff.commit',
    'session.handoff.abort',
    'session.handoff.status.get',
    'session.spawn_new',
    'session.spawn_picker',
  ],
  inventory: [
    'paths.list_recent',
    'machines.list',
    'servers.list',
    'review.engines.list',
    'agents.backends.list',
    'agents.models.list',
  ],
  messaging: [
    'session.message.send',
  ],
  session_control: [
    'session.stop',
    'session.title.set',
    'session.model.set',
    'session.permission_mode.set',
    'session.archive',
    'session.unarchive',
    'session.status.get',
    'session.work_state.get',
    'session.goal.get',
    'session.goal.set',
    'session.goal.clear',
    'session.usageLimit.waitResume.enable',
    'session.usageLimit.waitResume.cancel',
    'session.usageLimit.checkNow',
    'session.vendor_plugin_catalog.list',
    'session.skill_catalog.list',
    'session.history.get',
    'session.wait.idle',
  ],
  intent_start: [
    'review.start',
    'subagents.plan.start',
    'subagents.delegate.start',
    'voice_agent.start',
  ],
  review_comments: [
    'reviews.comments.create',
    'reviews.comments.list',
    'reviews.comments.get',
    'reviews.comments.transition',
    'reviews.comments.edit',
    'reviews.comments.reply',
    'reviews.comments.redact',
    'reviews.comments.setDisposition',
    'reviews.comments.attachEvidence',
    'reviews.comments.bulkTransition',
  ],
  subagent_registry: [
    'sessions.subagents.list',
    'sessions.subagents.get',
    'sessions.subagents.watch',
    'sessions.subagents.upsert',
    'sessions.subagents.updateStatus',
    'sessions.subagents.complete',
  ],
  execution_run_control: [
    'execution.run.start',
    'execution.run.list',
    'execution.run.get',
    'execution.run.send',
    'execution.run.ensure',
    'execution.run.ensure_or_start',
    'execution.run.stream.start',
    'execution.run.stream.read',
    'execution.run.stream.cancel',
    'execution.run.stop',
    'execution.run.action',
    'execution.run.wait',
  ],
  session_targeting: [
    'session.target.primary.set',
    'session.target.tracked.set',
    'session.list',
    'session.activity.get',
    'session.messages.recent.get',
  ],
  session_transcripts: [
    'session.transcript.get',
    'session.events.get',
    'session.log.tail',
    'transcript.page',
    'transcript.readAfter',
    'transcript.follow',
    'transcript.import',
    'transcript.search',
  ],
  session_permissions: [
    'session.permission.respond',
    'session.user_action.answer',
    'session.mode.set',
  ],
  external_sessions: [
    'sessions.external.candidates.list',
    'sessions.external.link.ensure',
    'sessions.external.follow',
    'sessions.external.unfollow',
    'sessions.external.followPolicy.set',
    'sessions.external.status.get',
    'sessions.external.transcript.page',
    'sessions.external.transcript.readAfter',
    'sessions.external.takeover',
  ],
  voice_controls: [
    'ui.voice_global.reset',
    'ui.voice_agent.teleport',
  ],
  companion_controls: [
    'ui.pet.choose',
  ],
  memory: [
    'memory.search',
    'memory.get_window',
    'memory.ensure_up_to_date',
  ],
  prompt_library: [
    'prompt_doc.update',
    'prompt_bundle.update',
    'prompt_asset.export',
    'prompt_registry.install',
  ],
  daemon_admin: [
    'daemon.promptAssets.discover',
    'daemon.promptAssets.delete',
    'daemon.promptRegistry.scanSource',
    'daemon.promptRegistry.install',
    'daemon.filesystem.readFile',
    'daemon.filesystem.writeFile',
    'daemon.filesystem.listDirectory',
    'daemon.filesystem.getDirectoryTree',
    'daemon.filesystem.listRoots',
    'daemon.filesystem.browseDirectory',
    'bugreport.collectDiagnostics',
    'bugreport.getLogTail',
    'bugreport.uploadArtifact',
  ],
  approvals: [
    'approval.request.list',
    'approval.request.get',
    'approval.request.create',
    'approval.request.decide',
  ],
  plugin_permission_grants: [
    'plugins.permissions.grants.list',
    'plugins.permissions.grants.request',
    'plugins.permissions.grants.grant',
    'plugins.permissions.grants.revoke',
    'plugins.permissions.grants.dismissRequest',
  ],
  scm_pull_request: [
    'scm.pullRequest.list',
    'scm.pullRequest.get',
    'scm.pullRequest.openOrReuse',
    'scm.pullRequest.openCompose',
    'scm.pullRequest.checkout',
    'scm.pullRequest.prepareWorktree',
    'scm.pullRequest.runStacked',
  ],
  scm_repository: [
    'scm.repository.clone',
    'scm.repository.init',
    'scm.repository.removeIndexLock',
    'scm.hostingRepository.describePublishTargets',
    'scm.hostingRepository.publish',
  ],
  scm_diff_summary: [
    'scm.diffSummary.generate',
  ],
} as const);

export const ACTION_IDS = [
  ...ACTION_ID_FAMILIES_V1.discovery,
  ...ACTION_ID_FAMILIES_V1.session_lifecycle,
  ...ACTION_ID_FAMILIES_V1.inventory,
  ...ACTION_ID_FAMILIES_V1.messaging,
  ...ACTION_ID_FAMILIES_V1.session_control,
  ...ACTION_ID_FAMILIES_V1.intent_start,
  ...ACTION_ID_FAMILIES_V1.review_comments,
  ...ACTION_ID_FAMILIES_V1.subagent_registry,
  ...ACTION_ID_FAMILIES_V1.execution_run_control,
  ...ACTION_ID_FAMILIES_V1.session_targeting,
  ...ACTION_ID_FAMILIES_V1.session_transcripts,
  ...ACTION_ID_FAMILIES_V1.session_permissions,
  ...ACTION_ID_FAMILIES_V1.external_sessions,
  ...ACTION_ID_FAMILIES_V1.voice_controls,
  ...ACTION_ID_FAMILIES_V1.companion_controls,
  ...ACTION_ID_FAMILIES_V1.memory,
  ...ACTION_ID_FAMILIES_V1.prompt_library,
  ...ACTION_ID_FAMILIES_V1.daemon_admin,
  ...ACTION_ID_FAMILIES_V1.approvals,
  ...ACTION_ID_FAMILIES_V1.plugin_permission_grants,
  ...ACTION_ID_FAMILIES_V1.scm_pull_request,
  ...ACTION_ID_FAMILIES_V1.scm_repository,
  ...ACTION_ID_FAMILIES_V1.scm_diff_summary,
] as const;

export const ActionIdSchema = z.enum(ACTION_IDS);
export type ActionId = z.infer<typeof ActionIdSchema>;
export type ActionIdFamilyV1 = keyof typeof ACTION_ID_FAMILIES_V1;

const LEGACY_ACTION_ID_ALIASES: Readonly<Record<string, ActionId>> = Object.freeze({
  'plan.start': 'subagents.plan.start',
  'delegate.start': 'subagents.delegate.start',
  'sessions.external.attach': 'sessions.external.follow',
  'sessions.external.detach': 'sessions.external.unfollow',
});

export function normalizeLegacyActionId(value: string): string {
  return LEGACY_ACTION_ID_ALIASES[value] ?? value;
}
