import {
  ScmPullRequestCheckoutRequestSchema,
  ScmPullRequestCheckoutResponseSchema,
  ScmPullRequestGetRequestSchema,
  ScmPullRequestGetResponseSchema,
  ScmPullRequestListRequestSchema,
  ScmPullRequestListResponseSchema,
  ScmPullRequestOpenComposeRequestSchema,
  ScmPullRequestOpenComposeResponseSchema,
  ScmPullRequestOpenOrReuseRequestSchema,
  ScmPullRequestOpenOrReuseResponseSchema,
  ScmPullRequestPrepareWorktreeRequestSchema,
  ScmPullRequestPrepareWorktreeResponseSchema,
  ScmPullRequestRunStackedRequestSchema,
  ScmPullRequestRunStackedResponseSchema,
} from '../scm/pullRequests.js';
import {
  ScmReviewWorkspaceMaterializePreparedRequestSchema,
  ScmReviewWorkspaceMaterializePreparedResponseSchema,
} from '../scm/reviewWorkspace.js';
import {
  ScmHostingRepositoryDescribePublishTargetsRequestSchema,
  ScmHostingRepositoryDescribePublishTargetsResponseSchema,
  ScmHostingRepositoryPublishRequestSchema,
  ScmHostingRepositoryPublishResponseSchema,
  ScmRepositoryInitRequestSchema,
  ScmRepositoryInitResponseSchema,
  ScmRepositoryRemoveIndexLockRequestSchema,
  ScmRepositoryRemoveIndexLockResponseSchema,
} from '../scm/repositoryProvisioning.js';
import {
  ScmDiffSummaryGenerateInputSchema,
  ScmDiffSummaryGenerateOutputSchema,
  ScmComparisonCaptureInputSchema,
  ScmComparisonCaptureOutputSchema,
} from '../scm/diffSummary.js';
import {
  ScmRepositoryCloneInputSchema,
  ScmRepositoryCloneOutputSchema,
  ScmHostingRepositoryResolveAddressRequestV1Schema,
  ScmHostingRepositoryResolveAddressResponseV1Schema,
  SourceControlCloneProtocolSchema,
  type SourceControlCloneProtocol,
} from '../scm/repositoryClone.js';
import {
  ScmDiffSummaryResultReadInputSchema, ScmDiffSummaryResultRevisionInputSchema,
  ScmDiffSummaryResultEditInputSchema, ScmDiffSummaryRefineInputSchema,
  ScmDiffSummaryAddOutputsInputSchema, ScmDiffSummaryDiscussInputSchema,
  ScmDiffSummaryResultResponseSchema, ScmDiffSummaryResultDeleteResponseSchema,
  ScmDiffSummaryResultListInputSchema, ScmDiffSummaryResultListResponseSchema,
  ScmDiffSummaryResultClearInputSchema, ScmDiffSummaryResultClearResponseSchema,
} from '../scm/diffSummaryResult.js';
import { ScmReviewedMarkInputSchema, ScmReviewedMarkResponseSchema } from '../scm/reviewedMarks.js';
import { ScmCommitPlanAcceptInputSchema, ScmCommitPlanControlInputSchema, ScmCommitPlanIncludeHookChangesInputSchema } from '../scm/diffSummaryCommitPlan.js';
import { RPC_METHODS } from '../rpc/methods.js';
import * as scm from '../scm/index.js';
import * as branches from '../scm/branches.js';
import * as stash from '../scm/stash.js';
import * as worktrees from '../scm/worktrees.js';
import { z } from 'zod';
import { ScmHistoryEntriesInputV1Schema, ScmHistoryEntriesResponseSchema } from '../scm/entriesHistoryV1.js';
import type { ActionId } from './actionIds.js';
import type { PreNormalizedActionSpec } from './actionSpecs.js';

/** Named metadata keeps declaration emission bounded without widening the wire schemas. */
export type ScmActionSpecDefinition<
  TId extends ActionId,
  TInput extends z.ZodTypeAny,
  TOutput extends z.ZodTypeAny,
> = Omit<PreNormalizedActionSpec, 'id' | 'inputSchema' | 'outputSchema'> & Readonly<{
  id: TId;
  inputSchema: TInput;
  outputSchema: TOutput;
}>;

function defineScmActionSpec<
  const TId extends ActionId,
  TInput extends z.ZodTypeAny,
  TOutput extends z.ZodTypeAny,
>(spec: ScmActionSpecDefinition<TId, TInput, TOutput>): ScmActionSpecDefinition<TId, TInput, TOutput> {
  return spec;
}

/** Core repository Actions reuse the backend's canonical request and result schemas. */
const SCM_GIT_ACTION_SPECS_PREFIX = [
  defineScmActionSpec({
    id: 'scm.backend.describe',
    title: 'Backend describe',
    description: 'Backend describe in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.backend.describe' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmBackendDescribeRequestSchema,
    outputSchema: scm.ScmBackendDescribeResponseSchema,
    inputHints: {
      title: 'Backend describe',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.status.snapshot',
    title: 'Status snapshot',
    description: 'Status snapshot in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.status.snapshot' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmStatusSnapshotRequestSchema,
    outputSchema: scm.ScmStatusSnapshotResponseSchema,
    inputHints: {
      title: 'Status snapshot',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'includeWorktreeStatus', title: 'include Worktree Status', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.worktrees.enrichment',
    title: 'Worktrees enrichment',
    description: 'Worktrees enrichment in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.worktrees.enrichment' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmWorktreesEnrichmentRequestSchema,
    outputSchema: scm.ScmWorktreesEnrichmentResponseSchema,
    inputHints: {
      title: 'Worktrees enrichment',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'worktreePaths', title: 'worktree Paths', widget: 'text_list', listSeparator: 'newline' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.diff.file',
    title: 'Diff file',
    description: 'Diff file in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.diff.file' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmDiffFileRequestSchema,
    outputSchema: scm.ScmDiffFileResponseSchema,
    inputHints: {
      title: 'Diff file',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'path', title: 'path', widget: 'text' },
        { path: 'area', title: 'area', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.diff.commit',
    title: 'Diff commit',
    description: 'Diff commit in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.diff.commit' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmDiffCommitRequestSchema,
    outputSchema: scm.ScmDiffCommitResponseSchema,
    inputHints: {
      title: 'Diff commit',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'commit', title: 'commit', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.change.include',
    workspaceWrite: true,
    title: 'Change include',
    description: 'Change include in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.change.include' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmChangeApplyRequestSchema,
    outputSchema: scm.ScmChangeApplyResponseSchema,
    inputHints: {
      title: 'Change include',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'paths', title: 'paths', widget: 'text_list', listSeparator: 'newline' },
        { path: 'patch', title: 'patch', widget: 'textarea' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.change.exclude',
    workspaceWrite: true,
    title: 'Change exclude',
    description: 'Change exclude in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.change.exclude' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmChangeApplyRequestSchema,
    outputSchema: scm.ScmChangeApplyResponseSchema,
    inputHints: {
      title: 'Change exclude',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'paths', title: 'paths', widget: 'text_list', listSeparator: 'newline' },
        { path: 'patch', title: 'patch', widget: 'textarea' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.change.discard',
    workspaceWrite: true,
    title: 'Change discard',
    description: 'Change discard in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.change.discard' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'danger',
    inputSchema: scm.ScmChangeDiscardRequestSchema,
    outputSchema: scm.ScmChangeDiscardResponseSchema,
    inputHints: {
      title: 'Change discard',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'entries', title: 'entries', widget: 'json' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.commit.create',
    workspaceWrite: true,
    title: 'Commit create',
    description: 'Commit create in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.commit.create' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmCommitCreateRequestSchema,
    outputSchema: scm.ScmCommitCreateResponseSchema,
    inputHints: {
      title: 'Commit create',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'message', title: 'message', widget: 'textarea' },
        { path: 'mode', title: 'Commit mode', widget: 'select', options: [{ value: 'commit', label: 'Create commit' }, { value: 'amend', label: 'Amend HEAD' }] },
        { path: 'signOff', title: 'Add sign-off', widget: 'boolean' },
        { path: 'allowPublishedAmend', title: 'Acknowledge published HEAD rewrite', widget: 'boolean' },
        { path: 'scope', title: 'scope', widget: 'json' },
        { path: 'patches', title: 'patches', widget: 'json' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.commit.resolveOutcome',
    title: 'Resolve commit outcome',
    description: 'Inspect a known candidate commit and its expected target history without publishing or retrying it.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: RPC_METHODS.SCM_COMMIT_RESOLVE_OUTCOME, mcpToolName: 'scm_commit_resolve_outcome' },
    surfaces: { ui: true, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    cli: { commands: [{ path: ['scm', 'commit', 'resolve-outcome'], visibility: 'canonical' }] },
    inputSchema: scm.ScmCommitResolveOutcomeRequestSchema,
    outputSchema: scm.ScmCommitResolveOutcomeResponseSchema,
    inputHints: { title: 'Resolve commit outcome', fields: [
      { path: 'cwd', title: 'cwd', widget: 'text' },
      { path: 'candidateOid', title: 'Known candidate commit', widget: 'text' },
      { path: 'expectedHeadOid', title: 'Expected parent', widget: 'text' },
      { path: 'expectedRef', title: 'Expected target ref', widget: 'text' },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.commit.undoLast',
    workspaceWrite: true,
    title: 'Undo last commit',
    description: 'Undo the observed unpushed HEAD commit and keep all changes staged.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.commit.undoLast' },
    surfaces: { ui: true, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmCommitUndoLastRequestSchema,
    outputSchema: scm.ScmCommitUndoLastResponseSchema,
    inputHints: {
      title: 'Undo last commit',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'expectedHeadOid', title: 'Observed HEAD commit', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.commit.backout',
    workspaceWrite: true,
    title: 'Commit backout',
    description: 'Commit backout in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.commit.backout' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmCommitBackoutRequestSchema,
    outputSchema: scm.ScmCommitBackoutResponseSchema,
    inputHints: {
      title: 'Commit backout',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'commit', title: 'commit', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.history.entries',
    title: 'Entry history',
    description: 'Read actual last-touch commits for demanded entries in the explicitly selected repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: RPC_METHODS.SCM_HISTORY_ENTRIES },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    // The catalog needs classic Zod composition; parsing stays at the one Mini owner.
    inputSchema: z.lazy(() => ScmHistoryEntriesInputV1Schema),
    outputSchema: z.lazy(() => ScmHistoryEntriesResponseSchema),
    inputHints: { title: 'Entry history', fields: [
      { path: 'cwd', title: 'Working directory', widget: 'text' },
      { path: 'folder', title: 'Folder', widget: 'text' },
      { path: 'paths', title: 'Entries', widget: 'text_list', listSeparator: 'newline' },
      { path: 'headOid', title: 'Observed HEAD', widget: 'text' },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.log.list',
    title: 'Log list',
    description: 'Log list in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.log.list' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: scm.ScmLogListRequestSchema,
    outputSchema: scm.ScmLogListResponseSchema,
    inputHints: {
      title: 'Log list',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'limit', title: 'limit', widget: 'text' },
        { path: 'skip', title: 'skip', widget: 'text' },
        { path: 'query', title: 'query', widget: 'text' },
        { path: 'range', title: 'range', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.list',
    title: 'Branch list',
    description: 'Branch list in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.list' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: branches.ScmBranchListRequestSchema,
    outputSchema: branches.ScmBranchListResponseSchema,
    inputHints: {
      title: 'Branch list',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'includeRemotes', title: 'include Remotes', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.create',
    workspaceWrite: true,
    title: 'Branch create',
    description: 'Branch create in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.create' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: branches.ScmBranchCreateRequestSchema,
    outputSchema: branches.ScmBranchCreateResponseSchema,
    inputHints: {
      title: 'Branch create',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'name', title: 'name', widget: 'text' },
        { path: 'checkout', title: 'checkout', widget: 'boolean' },
        { path: 'startPoint', title: 'start Point', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.checkout',
    workspaceWrite: true,
    title: 'Branch checkout',
    description: 'Branch checkout in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.checkout' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: branches.ScmBranchCheckoutRequestSchema,
    outputSchema: branches.ScmBranchCheckoutResponseSchema,
    inputHints: {
      title: 'Branch checkout',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'name', title: 'name', widget: 'text' },
        { path: 'strategy', title: 'strategy', widget: 'text' },
        { path: 'overwriteCurrentBranchStash', title: 'overwrite Current Branch Stash', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.merge',
    workspaceWrite: true,
    title: 'Branch merge',
    description: 'Branch merge in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.merge' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmBranchIntegrationRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Branch merge',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'sourceRef', title: 'source Ref', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.rebase',
    workspaceWrite: true,
    title: 'Branch rebase',
    description: 'Branch rebase in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.rebase' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmBranchIntegrationRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Branch rebase',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'sourceRef', title: 'source Ref', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.operation.continue',
    workspaceWrite: true,
    title: 'Branch operation continue',
    description: 'Branch operation continue in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.operation.continue' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmBranchOperationControlRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Branch operation continue',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'operation', title: 'operation', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.operation.skip',
    workspaceWrite: true,
    title: 'Branch operation skip',
    description: 'Branch operation skip in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.operation.skip' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmBranchOperationControlRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Branch operation skip',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'operation', title: 'operation', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.branch.operation.abort',
    workspaceWrite: true,
    title: 'Branch operation abort',
    description: 'Branch operation abort in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.branch.operation.abort' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmBranchOperationControlRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Branch operation abort',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'operation', title: 'operation', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.conflict.acceptSide',
    workspaceWrite: true,
    title: 'Conflict accept Side',
    description: 'Conflict accept Side in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.conflict.acceptSide' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmConflictAcceptSideRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Conflict accept Side',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'path', title: 'path', widget: 'text' },
        { path: 'side', title: 'side', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.conflict.markResolved',
    workspaceWrite: true,
    title: 'Conflict mark Resolved',
    description: 'Conflict mark Resolved in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.conflict.markResolved' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmConflictMarkResolvedRequestSchema,
    outputSchema: scm.ScmBranchIntegrationResponseSchema,
    inputHints: {
      title: 'Conflict mark Resolved',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'paths', title: 'paths', widget: 'text_list', listSeparator: 'newline' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.worktree.create',
    workspaceWrite: true,
    title: 'Worktree create',
    description: 'Worktree create in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.worktree.create' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: worktrees.ScmWorktreeCreateRequestSchema,
    outputSchema: worktrees.ScmWorktreeCreateResponseSchema,
    inputHints: {
      title: 'Worktree create',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'displayName', title: 'display Name', widget: 'text' },
        { path: 'baseRef', title: 'base Ref', widget: 'text' },
        { path: 'branchMode', title: 'branch Mode', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.worktree.remove',
    workspaceWrite: true,
    title: 'Worktree remove',
    description: 'Worktree remove in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.worktree.remove' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'danger',
    inputSchema: worktrees.ScmWorktreeRemoveRequestSchema,
    outputSchema: worktrees.ScmWorktreeRemoveResponseSchema,
    inputHints: {
      title: 'Worktree remove',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'worktreePath', title: 'worktree Path', widget: 'text' },
        { path: 'confirmed', title: 'confirmed', widget: 'boolean' },
        { path: 'authorizationToken', title: 'authorization Token', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.worktree.prune',
    workspaceWrite: true,
    title: 'Worktree prune',
    description: 'Worktree prune in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.worktree.prune' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'danger',
    inputSchema: worktrees.ScmWorktreePruneRequestSchema,
    outputSchema: worktrees.ScmWorktreePruneResponseSchema,
    inputHints: {
      title: 'Worktree prune',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.add',
    workspaceWrite: true,
    title: 'Remote add',
    description: 'Remote add in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.add' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmRemoteAddRequestSchema,
    outputSchema: scm.ScmRemoteManagementResponseSchema,
    inputHints: {
      title: 'Remote add',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'name', title: 'name', widget: 'text' },
        { path: 'fetchUrl', title: 'fetch Url', widget: 'text' },
        { path: 'pushUrl', title: 'push Url', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.setUrl',
    workspaceWrite: true,
    title: 'Remote set Url',
    description: 'Remote set Url in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.setUrl' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmRemoteSetUrlRequestSchema,
    outputSchema: scm.ScmRemoteManagementResponseSchema,
    inputHints: {
      title: 'Remote set Url',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'name', title: 'name', widget: 'text' },
        { path: 'fetchUrl', title: 'fetch Url', widget: 'text' },
        { path: 'pushUrl', title: 'push Url', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.remove',
    workspaceWrite: true,
    title: 'Remote remove',
    description: 'Remote remove in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.remove' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: scm.ScmRemoteRemoveRequestSchema,
    outputSchema: scm.ScmRemoteManagementResponseSchema,
    inputHints: {
      title: 'Remote remove',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'name', title: 'name', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.fetch',
    workspaceWrite: true,
    title: 'Remote fetch',
    description: 'Remote fetch in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.fetch' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'external',
    inputSchema: scm.ScmRemoteRequestSchema,
    outputSchema: scm.ScmRemoteResponseSchema,
    inputHints: {
      title: 'Remote fetch',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'remote', title: 'remote', widget: 'text' },
        { path: 'branch', title: 'branch', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.pull',
    workspaceWrite: true,
    title: 'Remote pull',
    description: 'Remote pull in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.pull' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'external',
    inputSchema: scm.ScmRemoteRequestSchema,
    outputSchema: scm.ScmRemoteResponseSchema,
    inputHints: {
      title: 'Remote pull',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'remote', title: 'remote', widget: 'text' },
        { path: 'branch', title: 'branch', widget: 'text' },
        { path: 'dirtyPolicy', title: 'dirty Policy', widget: 'text' },
        { path: 'reconcile', title: 'reconcile', widget: 'text' },
      ],
    },
  }),
] as const;

const SCM_GIT_ACTION_SPECS_SUFFIX = [
  defineScmActionSpec({
    id: 'scm.remote.push',
    workspaceWrite: true,
    title: 'Remote push',
    description: 'Remote push in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.push' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'external',
    inputSchema: scm.ScmRemoteRequestSchema,
    outputSchema: scm.ScmRemoteResponseSchema,
    inputHints: {
      title: 'Remote push',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'remote', title: 'remote', widget: 'text' },
        { path: 'branch', title: 'branch', widget: 'text' },
        { path: 'pushMode', title: 'push Mode', widget: 'text' },
        { path: 'expectedRemoteOid', title: 'expected Remote Oid', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.remote.publish',
    workspaceWrite: true,
    title: 'Remote publish',
    description: 'Remote publish in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.remote.publish' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'external',
    inputSchema: branches.ScmRemotePublishRequestSchema,
    outputSchema: branches.ScmRemotePublishResponseSchema,
    inputHints: {
      title: 'Remote publish',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'remote', title: 'remote', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.list',
    title: 'Stash list',
    description: 'Stash list in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.list' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: stash.ScmStashListRequestSchema,
    outputSchema: stash.ScmStashListResponseSchema,
    inputHints: {
      title: 'Stash list',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'includeAll', title: 'include All', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.show',
    title: 'Stash show',
    description: 'Stash show in the explicitly selected source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.show' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'read',
    inputSchema: stash.ScmStashShowRequestSchema,
    outputSchema: stash.ScmStashShowResponseSchema,
    inputHints: {
      title: 'Stash show',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'stashRef', title: 'stash Ref', widget: 'text' },
        { path: 'maxBytes', title: 'max Bytes', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.create',
    workspaceWrite: true,
    title: 'Stash create',
    description: 'Stash create in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.create' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: stash.ScmStashCreateRequestSchema,
    outputSchema: stash.ScmStashCreateResponseSchema,
    inputHints: {
      title: 'Stash create',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'message', title: 'message', widget: 'textarea' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.apply',
    workspaceWrite: true,
    title: 'Stash apply',
    description: 'Stash apply in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.apply' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: stash.ScmStashApplyRequestSchema,
    outputSchema: stash.ScmStashApplyResponseSchema,
    inputHints: {
      title: 'Stash apply',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'stashRef', title: 'stash Ref', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.pop',
    workspaceWrite: true,
    title: 'Stash pop',
    description: 'Stash pop in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.pop' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'write',
    inputSchema: stash.ScmStashPopRequestSchema,
    outputSchema: stash.ScmStashPopResponseSchema,
    inputHints: {
      title: 'Stash pop',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'stashRef', title: 'stash Ref', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.stash.drop',
    workspaceWrite: true,
    title: 'Stash drop',
    description: 'Stash drop in the explicitly selected source-control repository.',
    safety: 'danger',
    placements: [],
    bindings: { rpcMethod: 'scm.stash.drop' },
    surfaces: { ui: false, voice: false, agent: true, mcp: true, cli: true, rpc: true },
    sideEffectClass: 'danger',
    inputSchema: stash.ScmStashDropRequestSchema,
    outputSchema: stash.ScmStashDropResponseSchema,
    inputHints: {
      title: 'Stash drop',
      fields: [
        { path: 'cwd', title: 'cwd', widget: 'text' },
        { path: 'stashRef', title: 'stash Ref', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.list',
    title: 'List pull requests',
    description: 'List pull requests for the current source-control repository.',
    safety: 'safe',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.list',
      sdkMethod: 'scm.pullRequest.list',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'read',
    outputSchema: ScmPullRequestListResponseSchema,
    inputSchema: ScmPullRequestListRequestSchema,
    inputHints: {
      title: 'List pull requests',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'providerId', title: 'Provider id', widget: 'text' },
        { path: 'base', title: 'Base branch', widget: 'text' },
        { path: 'head', title: 'Head branch', widget: 'text' },
        {
          path: 'state',
          title: 'State',
          widget: 'select',
          options: [
            { value: 'open', label: 'Open' },
            { value: 'closed', label: 'Closed' },
            { value: 'merged', label: 'Merged' },
            { value: 'draft', label: 'Draft' },
            { value: 'unknown', label: 'Unknown' },
          ],
        },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.get',
    title: 'Get pull request',
    description: 'Read one pull request by number, URL, or head branch.',
    safety: 'safe',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.get',
      sdkMethod: 'scm.pullRequest.get',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'read',
    outputSchema: ScmPullRequestGetResponseSchema,
    inputSchema: ScmPullRequestGetRequestSchema,
    inputHints: {
      title: 'Get pull request',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'prReference.number', title: 'Pull request number', widget: 'text' },
        { path: 'prReference.url', title: 'Pull request URL', widget: 'text' },
        { path: 'prReference.headBranch', title: 'Head branch', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.openOrReuse',
    title: 'Open or reuse pull request',
    description: 'Create a pull request or return an existing one for the current branch.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.openOrReuse',
      sdkMethod: 'scm.pullRequest.openOrReuse',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'external',
    outputSchema: ScmPullRequestOpenOrReuseResponseSchema,
    inputSchema: ScmPullRequestOpenOrReuseRequestSchema,
    inputHints: {
      title: 'Open or reuse pull request',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'providerId', title: 'Provider id', widget: 'text' },
        { path: 'base', title: 'Base branch', widget: 'text', required: true },
        { path: 'head', title: 'Head branch', widget: 'text' },
        { path: 'title', title: 'Title', widget: 'text' },
        { path: 'body', title: 'Body', widget: 'textarea' },
        { path: 'draft', title: 'Draft', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.openCompose',
    title: 'Open pull-request compose URL',
    description: 'Build a provider-approved compose URL for the current branch.',
    safety: 'safe',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.openCompose',
      sdkMethod: 'scm.pullRequest.openCompose',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'read',
    outputSchema: ScmPullRequestOpenComposeResponseSchema,
    inputSchema: ScmPullRequestOpenComposeRequestSchema,
    inputHints: {
      title: 'Open pull-request compose URL',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'providerId', title: 'Provider id', widget: 'text' },
        { path: 'base', title: 'Base branch', widget: 'text', required: true },
        { path: 'head', title: 'Head branch', widget: 'text', required: true },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.checkout',
    workspaceWrite: true,
    title: 'Check out pull request',
    description: 'Check out a pull request reference in the current repository.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.checkout',
      sdkMethod: 'scm.pullRequest.checkout',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'write',
    outputSchema: ScmPullRequestCheckoutResponseSchema,
    inputSchema: ScmPullRequestCheckoutRequestSchema,
    inputHints: {
      title: 'Check out pull request',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'prReference.number', title: 'Pull request number', widget: 'text' },
        { path: 'prReference.url', title: 'Pull request URL', widget: 'text' },
        { path: 'prReference.headBranch', title: 'Head branch', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.prepareWorktree',
    workspaceWrite: true,
    title: 'Prepare pull-request worktree',
    description: 'Prepare a local worktree for a pull request reference.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.prepareWorktree',
      sdkMethod: 'scm.pullRequest.prepareWorktree',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'write',
    outputSchema: ScmPullRequestPrepareWorktreeResponseSchema,
    inputSchema: ScmPullRequestPrepareWorktreeRequestSchema,
    inputHints: {
      title: 'Prepare pull-request worktree',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        { path: 'sourcePath', title: 'Source path', widget: 'text', required: true },
        { path: 'prReference.number', title: 'Pull request number', widget: 'text' },
        { path: 'prReference.url', title: 'Pull request URL', widget: 'text' },
        { path: 'prReference.headBranch', title: 'Head branch', widget: 'text' },
        {
          path: 'mode',
          title: 'Mode',
          widget: 'select',
          options: [
            { value: 'local', label: 'Local checkout' },
            { value: 'worktree', label: 'Worktree' },
          ],
        },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.reviewWorkspace.materializePrepared',
    workspaceWrite: true,
    title: 'Materialize or verify prepared review workspace',
    description: 'Materialize prepared checkout facts or read the local HEAD of an already-prepared path in one exact selected workspace.',
    safety: 'danger',
    placements: [],
    bindings: {
      sdkMethod: 'scm.reviewWorkspace.materializePrepared',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: false,
      mcp: false,
      cli: false,
      rpc: false,
    },
    sideEffectClass: 'write',
    outputSchema: ScmReviewWorkspaceMaterializePreparedResponseSchema,
    inputSchema: ScmReviewWorkspaceMaterializePreparedRequestSchema,
    inputHints: {
      title: 'Materialize prepared review workspace',
      fields: [
        { path: 'cwd', title: 'Selected workspace root', widget: 'text', required: true },
        { path: 'displayName', title: 'Workspace label', widget: 'text', required: true },
        { path: 'sourceTip', title: 'Provider-authorized source tip', widget: 'json', required: true },
        { path: 'verification', title: 'Already-prepared path verification', widget: 'json' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.pullRequest.runStacked',
    workspaceWrite: true,
    title: 'Run stacked pull-request workflow',
    description: 'Run a structured branch, commit, push, and pull-request workflow.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.pullRequest.runStacked',
      sdkMethod: 'scm.pullRequest.runStacked',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'danger',
    outputSchema: ScmPullRequestRunStackedResponseSchema,
    inputSchema: ScmPullRequestRunStackedRequestSchema,
    inputHints: {
      title: 'Run stacked pull-request workflow',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text' },
        {
          path: 'action',
          title: 'Action',
          widget: 'select',
          required: true,
          options: [
            { value: 'commit', label: 'Commit' },
            { value: 'push', label: 'Push' },
            { value: 'openOrReuse', label: 'Open or reuse pull request' },
            { value: 'commitAndPush', label: 'Commit and push' },
            { value: 'pushAndOpenOrReuse', label: 'Push and open or reuse pull request' },
            { value: 'commitPushAndOpenOrReuse', label: 'Commit, push, and open or reuse pull request' },
          ],
        },
        { path: 'commitMessage', title: 'Commit message', widget: 'textarea' },
        { path: 'featureBranch', title: 'Feature branch', widget: 'text' },
        { path: 'filePaths', title: 'File paths', widget: 'text_list', listSeparator: 'newline' },
        { path: 'base', title: 'Base branch', widget: 'text' },
        { path: 'head', title: 'Head branch', widget: 'text' },
        { path: 'title', title: 'Pull request title', widget: 'text' },
        { path: 'body', title: 'Pull request body', widget: 'textarea' },
        {
          path: 'defaultBranchPushPolicy',
          title: 'Default-branch push policy',
          widget: 'select',
          options: [
            { value: 'allow', label: 'Allow' },
            { value: 'requires-feature-branch', label: 'Require feature branch' },
            { value: 'deny', label: 'Deny' },
          ],
        },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.repository.clone',
    workspaceWrite: true,
    title: 'Clone source-control repository',
    description: 'Clone a hosting-provider repository into an explicitly selected local destination.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.repository.clone',
      sdkMethod: 'scm.repository.clone',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'external',
    outputSchema: ScmRepositoryCloneOutputSchema,
    inputSchema: ScmRepositoryCloneInputSchema,
    inputHints: {
      title: 'Clone source-control repository',
      fields: [
        { path: 'provider', title: 'Hosting provider (json)', widget: 'textarea', required: true },
        { path: 'repository', title: 'Repository (json)', widget: 'textarea', required: true },
        { path: 'destinationParentPath', title: 'Destination parent directory', widget: 'text', required: true },
        { path: 'destinationDirectoryName', title: 'Destination directory name', widget: 'text', required: true },
        {
          path: 'protocol',
          title: 'Clone protocol',
          widget: 'select',
          required: true,
          options: SourceControlCloneProtocolSchema.options.map((value: SourceControlCloneProtocol) => ({
            value,
            label: value.toUpperCase(),
          })),
        },
        { path: 'confirmed', title: 'Confirm repository clone', widget: 'boolean', required: true },
        { path: 'authorizationToken', title: 'Authorization token', widget: 'text', required: true },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.repository.init',
    workspaceWrite: true,
    title: 'Initialize source-control repository',
    description: 'Initialize source control for a directory through the SCM provisioning route.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.repository.init',
      sdkMethod: 'scm.repository.init',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'write',
    outputSchema: ScmRepositoryInitResponseSchema,
    inputSchema: ScmRepositoryInitRequestSchema,
    inputHints: {
      title: 'Initialize source-control repository',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
        { path: 'initialBranch', title: 'Initial branch', widget: 'text' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.repository.removeIndexLock',
    workspaceWrite: true,
    title: 'Remove stale source-control index lock',
    description: 'Remove a confirmed stale Git index lock using backend-owned path resolution.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.repository.removeIndexLock',
      sdkMethod: 'scm.repository.removeIndexLock',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'danger',
    outputSchema: ScmRepositoryRemoveIndexLockResponseSchema,
    inputSchema: ScmRepositoryRemoveIndexLockRequestSchema,
    inputHints: {
      title: 'Remove stale source-control index lock',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
        { path: 'confirmed', title: 'Confirm stale index-lock removal', widget: 'boolean', required: true },
        { path: 'confirmationToken', title: 'Confirmation token', widget: 'text', required: true },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.hostingRepository.resolveAddress',
    title: 'Resolve repository address',
    description: 'Resolve a credential-free repository address through the selected Machine’s SCM hosting providers.',
    safety: 'safe', placements: [], sideEffectClass: 'read',
    bindings: { rpcMethod: RPC_METHODS.SCM_HOSTING_REPOSITORY_RESOLVE_ADDRESS, sdkMethod: 'scm.hostingRepository.resolveAddress',
      mcpToolName: 'scm_hosting_repository_resolve_address', voiceClientToolName: 'resolveScmRepositoryAddress' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    cli: { commands: [{ path: ['scm', 'hosting-repository', 'resolve-address'], visibility: 'canonical' }] },
    inputSchema: ScmHostingRepositoryResolveAddressRequestV1Schema,
    outputSchema: ScmHostingRepositoryResolveAddressResponseV1Schema,
    inputHints: { title: 'Resolve repository address', fields: [{ path: 'address', title: 'Repository address', widget: 'text', required: true }] },
  }),
  defineScmActionSpec({
    id: 'scm.hostingRepository.describePublishTargets',
    title: 'Describe hosting repository publish targets',
    description: 'Describe authenticated hosting-provider targets that can receive a repository publish.',
    safety: 'safe',
    placements: [],
    bindings: {
      rpcMethod: 'scm.hostingRepository.describePublishTargets',
      sdkMethod: 'scm.hostingRepository.describePublishTargets',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'read',
    outputSchema: ScmHostingRepositoryDescribePublishTargetsResponseSchema,
    inputSchema: ScmHostingRepositoryDescribePublishTargetsRequestSchema,
    inputHints: {
      title: 'Describe hosting repository publish targets',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
        {
          path: 'providerKind',
          title: 'Hosting provider',
          widget: 'select',
          options: [
            { value: 'github', label: 'GitHub' },
            { value: 'gitlab', label: 'GitLab' },
            { value: 'bitbucket', label: 'Bitbucket' },
            { value: 'custom', label: 'Custom' },
            { value: 'unknown', label: 'Unknown' },
          ],
        },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.hostingRepository.publish',
    workspaceWrite: true,
    title: 'Publish repository to hosting provider',
    description: 'Create or bind a hosting repository and publish the active source-control state.',
    safety: 'danger',
    placements: [],
    bindings: {
      rpcMethod: 'scm.hostingRepository.publish',
      sdkMethod: 'scm.hostingRepository.publish',
    },
    surfaces: {
      ui: false,
      voice: false,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'external',
    outputSchema: ScmHostingRepositoryPublishResponseSchema,
    inputSchema: ScmHostingRepositoryPublishRequestSchema,
    inputHints: {
      title: 'Publish repository to hosting provider',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
        {
          path: 'providerKind',
          title: 'Hosting provider',
          widget: 'select',
          required: true,
          options: [
            { value: 'github', label: 'GitHub' },
            { value: 'gitlab', label: 'GitLab' },
            { value: 'bitbucket', label: 'Bitbucket' },
            { value: 'custom', label: 'Custom' },
            { value: 'unknown', label: 'Unknown' },
          ],
        },
        { path: 'owner', title: 'Owner', widget: 'text', required: true },
        {
          path: 'ownerKind',
          title: 'Owner kind',
          widget: 'select',
          options: [
            { value: 'user', label: 'User' },
            { value: 'org', label: 'Organization' },
          ],
        },
        { path: 'repositoryName', title: 'Repository name', widget: 'text', required: true },
        {
          path: 'visibility',
          title: 'Visibility',
          widget: 'select',
          required: true,
          options: [
            { value: 'private', label: 'Private' },
            { value: 'public', label: 'Public' },
            { value: 'internal', label: 'Internal' },
          ],
        },
        { path: 'description', title: 'Description', widget: 'textarea' },
        { path: 'remoteName', title: 'Remote name', widget: 'text' },
        {
          path: 'remoteUrlKind',
          title: 'Remote URL kind',
          widget: 'select',
          options: [
            { value: 'https', label: 'HTTPS' },
            { value: 'ssh', label: 'SSH' },
          ],
        },
        {
          path: 'remoteConflictStrategy',
          title: 'Remote conflict strategy',
          widget: 'select',
          options: [
            { value: 'fail', label: 'Fail' },
            { value: 'set-url', label: 'Set URL' },
          ],
        },
        { path: 'pushCurrentBranch', title: 'Push current branch', widget: 'boolean' },
      ],
    },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.capture',
    examples: { voice: { argsExample: '{"cwd":"/repo","source":{"kind":"workingTree"}}' } },
    title: 'Capture source-control comparison',
    description: 'Read comparison inventory and evidence without starting model analysis.',
    safety: 'safe', placements: [],
    bindings: { rpcMethod: RPC_METHODS.SCM_DIFF_SUMMARY_CAPTURE, sdkMethod: 'scm.diffSummary.capture', mcpToolName: 'scm_diff_summary_capture', voiceClientToolName: 'captureScmComparison' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'capture'], visibility: 'canonical' }] },
    sideEffectClass: 'read',
    inputSchema: ScmComparisonCaptureInputSchema,
    outputSchema: ScmComparisonCaptureOutputSchema,
    inputHints: { title: 'Capture comparison', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'sessionId', title: 'Session id', widget: 'text' },
      { path: 'source.kind', title: 'Comparison source', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.generate',
    examples: { voice: { argsExample: '{"cwd":"/repo","source":{"kind":"workingTree"},"outputs":["summary"]}' } },
    title: 'Generate source-control diff summary',
    description: 'Capture comparison evidence and start retained summary, walkthrough, or commit-plan analysis.',
    safety: 'safe',
    placements: [],
    bindings: {
      rpcMethod: RPC_METHODS.SCM_DIFF_SUMMARY_GENERATE,
      sdkMethod: 'scm.diffSummary.generate',
      mcpToolName: 'scm_diff_summary_generate',
      voiceClientToolName: 'generateScmDiffSummary',
    },
    surfaces: {
      ui: true,
      voice: true,
      agent: true,
      mcp: true,
      cli: true,
      rpc: true,
    },
    sideEffectClass: 'external',
    cli: { commands: [{ path: ['scm', 'diff-summary', 'generate'], visibility: 'canonical' }] },
    outputSchema: ScmDiffSummaryGenerateOutputSchema,
    inputSchema: ScmDiffSummaryGenerateInputSchema,
    inputHints: {
      title: 'Generate diff summary',
      description: 'Read captured changes immediately while the selected session analyses them. Turn and session evidence is resolved by the host.',
      fields: [
        { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
        { path: 'sessionId', title: 'Session id', widget: 'text' },
        {
          path: 'source.kind',
          title: 'Summary source',
          widget: 'select',
          required: true,
          options: [
            { value: 'turnCheckpoint', label: 'Turn checkpoint' },
            { value: 'workingTree', label: 'Working tree' },
            { value: 'session', label: 'This session' },
            { value: 'branch', label: 'Branch versus base' },
            { value: 'commit', label: 'Commit' },
            { value: 'pullRequest', label: 'Pull request' },
          ],
        },
        { path: 'turnId', title: 'Turn id', widget: 'text' },
        { path: 'checkpointReceiptId', title: 'Checkpoint receipt id', widget: 'text' },
        { path: 'modelSelector.profileId', title: 'Model profile id', widget: 'text' },
        { path: 'modelSelector.modelId', title: 'Model id', widget: 'text' },
        { path: 'modelSelector.backendTargetKey', title: 'Backend target key', widget: 'text' },
      ],
    },
  }),
] as const;

const SCM_DIFF_SUMMARY_RESULT_ACTION_SPECS = [
  defineScmActionSpec({
    id: 'scm.diffSummary.result.list', title: 'List saved change explanations',
    description: 'Read permitted saved results, storage usage and available seven-day cost records from the selected machine.',
    safety: 'safe', placements: [], sideEffectClass: 'read',
    bindings: { rpcMethod: 'scm.diffSummary.result.list', sdkMethod: 'scm.diffSummary.result.list', mcpToolName: 'scm_diff_summary_result_list', voiceClientToolName: 'listScmDiffSummaryResults' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultListInputSchema, outputSchema: ScmDiffSummaryResultListResponseSchema,
    examples: { voice: { argsExample: '{}' } },
    inputHints: { title: 'List saved change explanations', fields: [] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.result.clear', title: 'Clear selected saved change explanations',
    description: 'Delete only explicitly listed saved revisions and their manual edits on the selected machine.',
    safety: 'danger', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.result.clear', sdkMethod: 'scm.diffSummary.result.clear', mcpToolName: 'scm_diff_summary_result_clear', voiceClientToolName: 'clearScmDiffSummaryResults' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultClearInputSchema, outputSchema: ScmDiffSummaryResultClearResponseSchema,
    examples: { voice: { argsExample: '{"results":[{"cwd":"/repo","resultId":"saved-result","expectedRevision":1,"comparisonId":"saved-comparison"}]}' } },
    inputHints: { title: 'Clear selected saved change explanations', fields: [
      { path: 'results', title: 'Exact saved result revisions', widget: 'json', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.commitPlan.accept', title: 'Accept and apply commit proposals',
    description: 'Apply the exact ordered pending proposal bound to the checkout and current saved revision.',
    safety: 'danger', workspaceWrite: true, placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.commitPlan.accept', sdkMethod: 'scm.diffSummary.commitPlan.accept', mcpToolName: 'scm_diff_summary_commit_plan_accept', voiceClientToolName: 'acceptScmCommitPlan' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmCommitPlanAcceptInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    cli: { commands: [{ path: ['scm', 'diff-summary', 'commit-plan', 'accept'], visibility: 'canonical' }] },
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"saved-result","expectedRevision":0,"acceptance":{"comparisonId":"pending-comparison","repositoryRootPath":"/repo","expectedHeadOid":null,"expectedRef":"refs/heads/main","groups":[{"id":"first","message":"fix: selected changes","rationale":"Related correction","changeRefs":["change-1"]}],"leftOutChangeRefs":[]}}' } },
    inputHints: { title: 'Accept commit proposals', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'acceptance', title: 'Exact acceptance binding', widget: 'json', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.commitPlan.stop', title: 'Stop after the current commit',
    description: 'Let the active atomic writer finish, then admit no next commit group.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.commitPlan.stop', sdkMethod: 'scm.diffSummary.commitPlan.stop', mcpToolName: 'scm_diff_summary_commit_plan_stop', voiceClientToolName: 'stopScmCommitPlan' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmCommitPlanControlInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    cli: { commands: [{ path: ['scm', 'diff-summary', 'commit-plan', 'stop'], visibility: 'canonical' }] },
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"saved-result","expectedRevision":1}' } },
    inputHints: { title: 'Stop commit proposals', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.commitPlan.includeHookChanges', title: 'Include displayed hook changes and commit',
    description: 'Explicitly accept only the displayed hook tree at the current paused revision.',
    safety: 'danger', workspaceWrite: true, placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.commitPlan.includeHookChanges', sdkMethod: 'scm.diffSummary.commitPlan.includeHookChanges', mcpToolName: 'scm_diff_summary_commit_plan_include_hook_changes', voiceClientToolName: 'includeScmCommitPlanHookChanges' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmCommitPlanIncludeHookChangesInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    cli: { commands: [{ path: ['scm', 'diff-summary', 'commit-plan', 'include-hook-changes'], visibility: 'canonical' }] },
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"saved-result","expectedRevision":2,"groupId":"first","beforeTreeOid":"1111111111111111111111111111111111111111","afterTreeOid":"2222222222222222222222222222222222222222"}' } },
    inputHints: { title: 'Include hook changes', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'groupId', title: 'Paused commit', widget: 'text', required: true },
      { path: 'beforeTreeOid', title: 'Displayed original tree', widget: 'text', required: true },
      { path: 'afterTreeOid', title: 'Displayed hook tree', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.commitPlan.cancel', title: 'Cancel remaining commit proposals',
    description: 'Cancel remaining steps without resetting commits or worktree changes.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.commitPlan.cancel', sdkMethod: 'scm.diffSummary.commitPlan.cancel', mcpToolName: 'scm_diff_summary_commit_plan_cancel', voiceClientToolName: 'cancelScmCommitPlan' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmCommitPlanControlInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    cli: { commands: [{ path: ['scm', 'diff-summary', 'commit-plan', 'cancel'], visibility: 'canonical' }] },
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"saved-result","expectedRevision":1}' } },
    inputHints: { title: 'Cancel commit proposals', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.commitPlan.recover', title: 'Reconcile an uncertain commit outcome',
    description: 'Resolve recorded Git publication without retrying or rolling back.',
    safety: 'safe', placements: [], sideEffectClass: 'read',
    bindings: { rpcMethod: 'scm.diffSummary.commitPlan.recover', sdkMethod: 'scm.diffSummary.commitPlan.recover', mcpToolName: 'scm_diff_summary_commit_plan_recover', voiceClientToolName: 'recoverScmCommitPlan' },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmCommitPlanControlInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    cli: { commands: [{ path: ['scm', 'diff-summary', 'commit-plan', 'recover'], visibility: 'canonical' }] },
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"saved-result","expectedRevision":1}' } },
    inputHints: { title: 'Reconcile commit outcome', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.reviewed.mark', title: 'Mark changes reviewed',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","changeRefs":["change-main"]}' } },
    description: 'Explicitly mark exact changes reviewed in the authenticated personal Account.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: RPC_METHODS.SCM_DIFF_SUMMARY_REVIEWED_MARK, sdkMethod: 'scm.diffSummary.reviewed.mark', mcpToolName: 'scm_diff_summary_reviewed_mark', voiceClientToolName: 'markScmChangesReviewed' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'reviewed', 'mark'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmReviewedMarkInputSchema, outputSchema: ScmReviewedMarkResponseSchema,
    inputHints: { title: 'Mark changes reviewed', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'changeRefs', title: 'Exact change references', widget: 'text_list', listSeparator: 'newline', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.reviewed.unmark', title: 'Unmark reviewed changes',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","changeRefs":["change-main"]}' } },
    description: 'Explicitly remove personal reviewed marks for exact comparison changes.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: RPC_METHODS.SCM_DIFF_SUMMARY_REVIEWED_UNMARK, sdkMethod: 'scm.diffSummary.reviewed.unmark', mcpToolName: 'scm_diff_summary_reviewed_unmark', voiceClientToolName: 'unmarkScmChangesReviewed' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'reviewed', 'unmark'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmReviewedMarkInputSchema, outputSchema: ScmReviewedMarkResponseSchema,
    inputHints: { title: 'Unmark reviewed changes', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'changeRefs', title: 'Exact change references', widget: 'text_list', listSeparator: 'newline', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.result.read', title: 'Read saved change explanation',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main"}' } },
    description: 'Read the current saved result and revision from its owning machine.',
    safety: 'safe', placements: [], sideEffectClass: 'read',
    bindings: { rpcMethod: 'scm.diffSummary.result.read', sdkMethod: 'scm.diffSummary.result.read', mcpToolName: 'scm_diff_summary_result_read', voiceClientToolName: 'readScmDiffSummaryResult' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'result', 'read'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultReadInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Read saved change explanation', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.result.edit', title: 'Edit saved change explanation',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1,"edit":{"kind":"renameWalkthrough","title":"Changes"}}' } },
    description: 'Apply a structured edit to the expected result revision.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.result.edit', sdkMethod: 'scm.diffSummary.result.edit', mcpToolName: 'scm_diff_summary_result_edit', voiceClientToolName: 'editScmDiffSummaryResult' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'result', 'edit'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultEditInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Edit saved change explanation', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'edit', title: 'Structured edit', widget: 'json', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.result.undo', title: 'Undo change explanation edit',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1}' } },
    description: 'Restore the immediate previous output at the expected result revision.',
    safety: 'safe', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.result.undo', sdkMethod: 'scm.diffSummary.result.undo', mcpToolName: 'scm_diff_summary_result_undo', voiceClientToolName: 'undoScmDiffSummaryResult' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'result', 'undo'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultRevisionInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Undo change explanation edit', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.result.delete', title: 'Delete saved change explanation',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1}' } },
    description: 'Delete a saved result and its manual edits at the expected revision.',
    safety: 'danger', placements: [], sideEffectClass: 'write',
    bindings: { rpcMethod: 'scm.diffSummary.result.delete', sdkMethod: 'scm.diffSummary.result.delete', mcpToolName: 'scm_diff_summary_result_delete', voiceClientToolName: 'deleteScmDiffSummaryResult' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'result', 'delete'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryResultRevisionInputSchema, outputSchema: ScmDiffSummaryResultDeleteResponseSchema,
    inputHints: { title: 'Delete saved change explanation', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.refine', title: 'Refine change explanation',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1,"output":"summary","instructions":"Explain the user-visible changes."}' } },
    description: 'Request targeted structured refinement without overwriting newer edits.',
    safety: 'safe', placements: [], sideEffectClass: 'external',
    bindings: { rpcMethod: 'scm.diffSummary.refine', sdkMethod: 'scm.diffSummary.refine', mcpToolName: 'scm_diff_summary_refine', voiceClientToolName: 'refineScmDiffSummary' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'refine'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryRefineInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Refine change explanation', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'output', title: 'Requested output', widget: 'text', required: true },
      { path: 'instructions', title: 'Refinement instructions', widget: 'textarea', required: true },
      { path: 'stopIds', title: 'Selected stops', widget: 'text_list', listSeparator: 'newline' },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.addOutputs', title: 'Add change explanation outputs',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1,"outputs":["walkthrough"]}' } },
    description: 'Continue the saved comparison analysis with additional requested outputs.',
    safety: 'safe', placements: [], sideEffectClass: 'external',
    bindings: { rpcMethod: 'scm.diffSummary.addOutputs', sdkMethod: 'scm.diffSummary.addOutputs', mcpToolName: 'scm_diff_summary_add_outputs', voiceClientToolName: 'addScmDiffSummaryOutputs' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'add-outputs'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryAddOutputsInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Add change explanation outputs', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'outputs', title: 'Requested outputs', widget: 'text_list', listSeparator: 'newline', required: true },
    ] },
  }),
  defineScmActionSpec({
    id: 'scm.diffSummary.discuss', title: 'Discuss change explanation',
    examples: { voice: { argsExample: '{"cwd":"/repo","resultId":"result-main","expectedRevision":1,"message":"What should I review first?"}' } },
    description: 'Send a follow-up to the actual retained generator or explicitly start a seeded conversation.',
    safety: 'safe', placements: [], sideEffectClass: 'external',
    bindings: { rpcMethod: 'scm.diffSummary.discuss', sdkMethod: 'scm.diffSummary.discuss', mcpToolName: 'scm_diff_summary_discuss', voiceClientToolName: 'discussScmDiffSummary' },
    cli: { commands: [{ path: ['scm', 'diff-summary', 'discuss'], visibility: 'canonical' }] },
    surfaces: { ui: true, voice: true, agent: true, mcp: true, cli: true, rpc: true },
    inputSchema: ScmDiffSummaryDiscussInputSchema, outputSchema: ScmDiffSummaryResultResponseSchema,
    inputHints: { title: 'Discuss change explanation', fields: [
      { path: 'cwd', title: 'Repository directory', widget: 'text', required: true },
      { path: 'resultId', title: 'Saved result', widget: 'text', required: true },
      { path: 'expectedRevision', title: 'Expected revision', widget: 'text', required: true },
      { path: 'message', title: 'Message', widget: 'textarea', required: true },
      { path: 'stopIds', title: 'Selected stops', widget: 'text_list', listSeparator: 'newline' },
      { path: 'startNew', title: 'Start a seeded conversation', widget: 'boolean' },
    ] },
  }),

] as const;

// Preserve exact Action/schema correlations without serializing one oversized tuple.
export const SCM_GIT_ACTION_SPECS: readonly (
  | (typeof SCM_GIT_ACTION_SPECS_PREFIX)[number]
  | (typeof SCM_GIT_ACTION_SPECS_SUFFIX)[number]
  | (typeof SCM_DIFF_SUMMARY_RESULT_ACTION_SPECS)[number]
)[] = [...SCM_GIT_ACTION_SPECS_PREFIX, ...SCM_GIT_ACTION_SPECS_SUFFIX, ...SCM_DIFF_SUMMARY_RESULT_ACTION_SPECS];

/** A projection of the declaration owner, not a separate operation taxonomy. */
export function getScmRpcSideEffectClass(method: string) {
  return SCM_GIT_ACTION_SPECS.find((spec) => spec.bindings && 'rpcMethod' in spec.bindings && spec.bindings.rpcMethod === method)?.sideEffectClass;
}
