import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ensureWorkspacePackagesBuiltByName } from '../../../scripts/workspaces/ensureWorkspacePackagesBuilt.mjs';

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = resolve(packageRoot, '../..');
const outputPath = resolve(packageRoot, 'src/actions/generated.ts');
const reservedRoots = new Set(['execute', 'search', 'invoke']);
const hazardousSegments = new Set(['__proto__', 'constructor', 'prototype']);
const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/u;

export type SdkMethodRow = Readonly<{ actionId: string; methodPath: string; mutation?: boolean }>;

export function validateSdkMethodRows(rows: readonly SdkMethodRow[]): void {
  const ownerByPath = new Map<string, string>();
  for (const row of rows) {
    const segments = row.methodPath.split('.');
    if (reservedRoots.has(segments[0] ?? '')) {
      throw new Error(`Public Action ${row.actionId} uses reserved SDK root ${segments[0]}`);
    }
    if (segments.length === 0 || segments.some((segment) => !identifier.test(segment) || hazardousSegments.has(segment))) {
      throw new Error(`Public Action ${row.actionId} has invalid SDK method path ${row.methodPath}`);
    }
    const existing = ownerByPath.get(row.methodPath);
    if (existing) {
      throw new Error(`Public Actions ${existing} and ${row.actionId} share SDK method path ${row.methodPath}`);
    }
    ownerByPath.set(row.methodPath, row.actionId);
  }

  const paths = [...ownerByPath.keys()].sort();
  for (let index = 1; index < paths.length; index += 1) {
    const previous = paths[index - 1] as string;
    const current = paths[index] as string;
    if (current.startsWith(`${previous}.`)) {
      throw new Error(
        `Public Actions ${ownerByPath.get(previous)} and ${ownerByPath.get(current)} conflict at SDK namespace ${previous}`,
      );
    }
  }
}

type MethodTree = Map<string, MethodTree | SdkMethodRow>;

function createMethodTree(rows: readonly SdkMethodRow[]): MethodTree {
  const root: MethodTree = new Map();
  for (const row of rows) {
    const segments = row.methodPath.split('.');
    let cursor = root;
    for (const [index, segment] of segments.entries()) {
      if (index === segments.length - 1) {
        cursor.set(segment, row);
        continue;
      }
      const existing = cursor.get(segment);
      if (existing instanceof Map) {
        cursor = existing;
        continue;
      }
      const child: MethodTree = new Map();
      cursor.set(segment, child);
      cursor = child;
    }
  }
  return root;
}

function renderTree(tree: MethodTree, indent: string, mode: 'implementation' | 'type'): string {
  const entries = [...tree.entries()].sort(([left], [right]) => left.localeCompare(right));
  return entries.map(([segment, value]) => {
    if (value instanceof Map) {
      return mode === 'type'
        ? `${indent}readonly ${segment}: Readonly<{\n${renderTree(value, `${indent}  `, mode)}\n${indent}}> ;`
        : `${indent}${segment}: {\n${renderTree(value, `${indent}  `, mode)}\n${indent}},`;
    }
    const id = JSON.stringify(value.actionId);
    return mode === 'type'
      ? `${indent}readonly ${segment}: (input: PublicActionInputById[${id}], options?: ActionExecutionOptions) => Promise<PublicActionResultById[${id}]>;`
      : `${indent}${segment}: (input: PublicActionInputById[${id}], options?: ActionExecutionOptions) => execute(${id}, input, options),`;
  }).join('\n');
}

export function renderGeneratedActions(rows: readonly SdkMethodRow[]): string {
  validateSdkMethodRows(rows);
  const mutationIds = rows.filter((row) => row.mutation === true).map((row) => row.actionId).sort();
  return `// Generated by scripts/generateActions.ts. Do not edit.\n\n`
    + `import type { PublicActionInputById, PublicActionResultById } from '@happier-dev/protocol/actions';\n\n`
    + `import type { ActionExecute, ActionExecutionOptions } from '../types.js';\n\n`
    + `export type PublicActionId = keyof PublicActionInputById & keyof PublicActionResultById;\n`
    + `export type { PublicActionInputById, PublicActionResultById };\n\n`
    + `export const MUTATING_PUBLIC_ACTION_IDS: ReadonlySet<PublicActionId> = new Set(${JSON.stringify(mutationIds, null, 2)} as PublicActionId[]);\n\n`
    + `export type GeneratedActions = Readonly<{\n${renderTree(createMethodTree(rows), '  ', 'type')}\n}>;\n\n`
    + `export function createGeneratedActions(execute: ActionExecute): GeneratedActions {\n`
    + `  return {\n${renderTree(createMethodTree(rows), '    ', 'implementation')}\n  };\n}\n`;
}

async function currentRows(): Promise<readonly SdkMethodRow[]> {
  await ensureWorkspacePackagesBuiltByName(repoRoot, ['@happier-dev/protocol'], {
    includeDevDependencies: false,
    force: true,
    publicationMode: 'artifact',
    quiet: true,
  });
  const actionOwner = await import('../../protocol/dist/actions/index.js');
  return actionOwner.PUBLIC_ACTION_IDS
    .map((actionId) => actionOwner.getActionSpec(actionId))
    .map((spec) => ({
      actionId: spec.id,
      methodPath: actionOwner.resolveActionSdkMethodName(spec),
      mutation: spec.sideEffectClass === 'write'
        || spec.sideEffectClass === 'external'
        || spec.sideEffectClass === 'danger',
    }));
}

async function main(): Promise<void> {
  const mode = process.argv[2];
  if (mode !== '--write' && mode !== '--check') {
    throw new Error('Usage: generateActions.ts --write|--check');
  }
  const output = renderGeneratedActions(await currentRows());
  if (mode === '--write') {
    await writeFile(outputPath, output, 'utf8');
    return;
  }
  const existing = await readFile(outputPath, 'utf8').catch(() => '');
  if (existing !== output) throw new Error('Generated SDK Action layer is stale. Run yarn generate:actions.');
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
