export type { ActionContract } from './service.js';
export type { UsageCoachFinding, UsageCoachEvaluation } from './dtos/pluginActionDtoSupport.generated.js';
export type { InputTypePickerLaunchInputV1 } from './inputHints.js';
export { readInputTypePickerLaunchInput } from './inputHints.js';
export type { SessionTerminalLayoutV1, QualifiedAudienceSelection, SessionAudienceSelectionV1 } from './dtos/pluginActionDtoSupport.generated.js';
export type { ProviderCatalogParserV1, VoiceProviderSettingsJsonValueV1 } from './dtos/pluginActionDtoSupport.generated.js';
export type { ExternalSessionsSource } from './dtos/pluginActionDtoSupport.generated.js';
/** Named dependencies of the canonical host Action input/result maps. */
export type { AccountApiTokensActionInputById, AccountApiTokensActionResultById } from './dtos/accountApiTokensActionDtos.generated.js';
export type { AccountPluginDataActionInputById, AccountPluginDataActionResultById } from './dtos/accountPluginDataActionDtos.generated.js';
export type { AccountSecurityActionInputById, AccountSecurityActionResultById } from './dtos/accountSecurityActionDtos.generated.js';
export type { AccountSessionsActionInputById, AccountSessionsActionResultById } from './dtos/accountSessionsActionDtos.generated.js';
export type { AgentAcpCatalogActionInputById, AgentAcpCatalogActionResultById } from './dtos/agentAcpCatalogActionDtos.generated.js';
export type { ApprovalsActionInputById, ApprovalsActionResultById } from './dtos/approvalsActionDtos.generated.js';
export type { AppShellActionInputById, AppShellActionResultById } from './dtos/appShellActionDtos.generated.js';
export type { AppUpdatesActionInputById, AppUpdatesActionResultById } from './dtos/appUpdatesActionDtos.generated.js';
export type { ArtifactAccessActionInputById, ArtifactAccessActionResultById } from './dtos/artifactAccessActionDtos.generated.js';
export type { ArtifactFoldersActionInputById, ArtifactFoldersActionResultById } from './dtos/artifactFoldersActionDtos.generated.js';
export type { ArtifactsActionInputById, ArtifactsActionResultById } from './dtos/artifactsActionDtos.generated.js';
export type { AutomationConversationActionInputById, AutomationConversationActionResultById } from './dtos/automationConversationActionDtos.generated.js';
export type { AutomationEventsActionInputById, AutomationEventsActionResultById } from './dtos/automationEventsActionDtos.generated.js';
export type { BoardsActionInputById, BoardsActionResultById } from './dtos/boardsActionDtos.generated.js';
export type { BrowserAutomationActionInputById, BrowserAutomationActionResultById } from './dtos/browserAutomationActionDtos.generated.js';
export type { BrowserContextActionInputById, BrowserContextActionResultById } from './dtos/browserContextActionDtos.generated.js';
export type { BrowserControlActionInputById, BrowserControlActionResultById } from './dtos/browserControlActionDtos.generated.js';
export type { BrowserDiagnosticsActionInputById, BrowserDiagnosticsActionResultById } from './dtos/browserDiagnosticsActionDtos.generated.js';
export type { BrowserRecordingActionInputById, BrowserRecordingActionResultById } from './dtos/browserRecordingActionDtos.generated.js';
export type { CaptureViewingActionInputById, CaptureViewingActionResultById } from './dtos/captureViewingActionDtos.generated.js';
export type { CommandPaletteActionInputById, CommandPaletteActionResultById } from './dtos/commandPaletteActionDtos.generated.js';
export type { CompanionControlsActionInputById, CompanionControlsActionResultById } from './dtos/companionControlsActionDtos.generated.js';
export type { ComposerIngressActionInputById, ComposerIngressActionResultById } from './dtos/composerIngressActionDtos.generated.js';
export type { ComputerControlActionInputById, ComputerControlActionResultById } from './dtos/computerControlActionDtos.generated.js';
export type { ConnectedServicesConfigurationActionInputById, ConnectedServicesConfigurationActionResultById } from './dtos/connectedServicesConfigurationActionDtos.generated.js';
export type { UsageActionInputById, UsageActionResultById } from './dtos/usageActionDtos.generated.js';
export type { UsageSourcesActionInputById, UsageSourcesActionResultById } from './dtos/usageSourcesActionDtos.generated.js';
export type { CurrentUiContextActionInputById, CurrentUiContextActionResultById } from './dtos/currentUiContextActionDtos.generated.js';
export type { DaemonAdminActionInputById, DaemonAdminActionResultById } from './dtos/daemonAdminActionDtos.generated.js';
export type { DevicesSimulatorActionInputById, DevicesSimulatorActionResultById } from './dtos/devicesSimulatorActionDtos.generated.js';
export type { DiscoveryActionInputById, DiscoveryActionResultById } from './dtos/discoveryActionDtos.generated.js';
export type { ExecutionRunControlActionInputById, ExecutionRunControlActionResultById } from './dtos/executionRunControlActionDtos.generated.js';
export type { ExternalSessionsActionInputById, ExternalSessionsActionResultById } from './dtos/externalSessionsActionDtos.generated.js';
export type { FindActionInputById, FindActionResultById } from './dtos/findActionDtos.generated.js';
export type { FilesystemActionInputById, FilesystemActionResultById } from './dtos/filesystemActionDtos.generated.js';
export type { WorkspaceFileSearchActionInputById, WorkspaceFileSearchActionResultById } from './dtos/workspaceFileSearchActionDtos.generated.js';
export type { HomeGovernanceActionInputById, HomeGovernanceActionResultById } from './dtos/homeGovernanceActionDtos.generated.js';
export type { HomeHubLayoutActionInputById, HomeHubLayoutActionResultById } from './dtos/homeHubLayoutActionDtos.generated.js';
export type { IdentityGithubAppsActionInputById, IdentityGithubAppsActionResultById } from './dtos/identityGithubAppsActionDtos.generated.js';
export type { IdentityProvidersActionInputById, IdentityProvidersActionResultById } from './dtos/identityProvidersActionDtos.generated.js';
export type { IntentStartActionInputById, IntentStartActionResultById } from './dtos/intentStartActionDtos.generated.js';
export type { InventoryActionInputById, InventoryActionResultById } from './dtos/inventoryActionDtos.generated.js';
export type { LaunchProfilesActionInputById, LaunchProfilesActionResultById } from './dtos/launchProfilesActionDtos.generated.js';
export type { ListReorderActionInputById, ListReorderActionResultById } from './dtos/listReorderActionDtos.generated.js';
export type { LocalServicesActionsActionInputById, LocalServicesActionsActionResultById } from './dtos/localServicesActionsActionDtos.generated.js';
export type { LocalServicesInventoryActionInputById, LocalServicesInventoryActionResultById } from './dtos/localServicesInventoryActionDtos.generated.js';
export type { LocalServicesLauncherActionInputById, LocalServicesLauncherActionResultById } from './dtos/localServicesLauncherActionDtos.generated.js';
export type { LocalServicesPreviewActionInputById, LocalServicesPreviewActionResultById } from './dtos/localServicesPreviewActionDtos.generated.js';
export type { LocalServicesPublicPreviewActionInputById, LocalServicesPublicPreviewActionResultById } from './dtos/localServicesPublicPreviewActionDtos.generated.js';
export type { MachineAgentInstallActionInputById, MachineAgentInstallActionResultById } from './dtos/machineAgentInstallActionDtos.generated.js';
export type { MachineAgentSignInActionInputById, MachineAgentSignInActionResultById } from './dtos/machineAgentSignInActionDtos.generated.js';
export type { MachineConnectionActionInputById, MachineConnectionActionResultById } from './dtos/machineConnectionActionDtos.generated.js';
export type { MachineAccessActionInputById, MachineAccessActionResultById } from './dtos/machineAccessActionDtos.generated.js';
export type { MachinePoolsActionInputById, MachinePoolsActionResultById } from './dtos/machinePoolsActionDtos.generated.js';
export type { MachinePresetsActionInputById, MachinePresetsActionResultById } from './dtos/machinePresetsActionDtos.generated.js';
export type { MachineWorkSummaryActionInputById, MachineWorkSummaryActionResultById } from './dtos/machineWorkSummaryActionDtos.generated.js';
export type { McpServersActionInputById, McpServersActionResultById } from './dtos/mcpServersActionDtos.generated.js';
export type { ManagedMachinesActionInputById, ManagedMachinesActionResultById } from './dtos/managedMachinesActionDtos.generated.js';
export type { MemoryActionInputById, MemoryActionResultById } from './dtos/memoryActionDtos.generated.js';
export type { MessagingActionInputById, MessagingActionResultById } from './dtos/messagingActionDtos.generated.js';
export type { NotificationConfigurationActionInputById, NotificationConfigurationActionResultById } from './dtos/notificationConfigurationActionDtos.generated.js';
export type { NotificationsActionInputById, NotificationsActionResultById } from './dtos/notificationsActionDtos.generated.js';
export type { ObservationActionInputById, ObservationActionResultById } from './dtos/observationActionDtos.generated.js';
export type { OperationOutputActionInputById, OperationOutputActionResultById } from './dtos/operationOutputActionDtos.generated.js';
export type { PeerMediationObservabilityActionInputById, PeerMediationObservabilityActionResultById } from './dtos/peerMediationObservabilityActionDtos.generated.js';
export type { PluginDevLoopActionInputById, PluginDevLoopActionResultById } from './dtos/pluginDevLoopActionDtos.generated.js';
export type { PluginPermissionGrantsActionInputById, PluginPermissionGrantsActionResultById } from './dtos/pluginPermissionGrantsActionDtos.generated.js';
export type { PluginSettingsAdministrationActionInputById, PluginSettingsAdministrationActionResultById } from './dtos/pluginSettingsAdministrationActionDtos.generated.js';
export type { PluginWebhooksActionInputById, PluginWebhooksActionResultById } from './dtos/pluginWebhooksActionDtos.generated.js';
export type { PromptLibraryActionInputById, PromptLibraryActionResultById } from './dtos/promptLibraryActionDtos.generated.js';
export type { PromptPickerActionInputById, PromptPickerActionResultById } from './dtos/promptPickerActionDtos.generated.js';
export type { ProvidersActionInputById, ProvidersActionResultById } from './dtos/providersActionDtos.generated.js';
export type { ReviewCommentsActionInputById, ReviewCommentsActionResultById } from './dtos/reviewCommentsActionDtos.generated.js';
export type { RemoteHostsActionInputById, RemoteHostsActionResultById } from './dtos/remoteHostsActionDtos.generated.js';
export type { RolesActionInputById, RolesActionResultById } from './dtos/rolesActionDtos.generated.js';
export type { SavedSecretSharingActionInputById, SavedSecretSharingActionResultById } from './dtos/savedSecretSharingActionDtos.generated.js';
export type { ScmDiffSummaryActionInputById, ScmDiffSummaryActionResultById } from './dtos/scmDiffSummaryActionDtos.generated.js';
export type { ScmGitActionInputById, ScmGitActionResultById } from './dtos/scmGitActionDtos.generated.js';
export type { ScmPullRequestActionInputById, ScmPullRequestActionResultById } from './dtos/scmPullRequestActionDtos.generated.js';
export type { ScmRepositoryActionInputById, ScmRepositoryActionResultById } from './dtos/scmRepositoryActionDtos.generated.js';
export type { ScopeActionInputById, ScopeActionResultById } from './dtos/scopeActionDtos.generated.js';
export type { SessionAccessActionInputById, SessionAccessActionResultById } from './dtos/sessionAccessActionDtos.generated.js';
export type { SessionAttentionActionInputById, SessionAttentionActionResultById } from './dtos/sessionAttentionActionDtos.generated.js';
export type { SessionAuthoringActionInputById, SessionAuthoringActionResultById } from './dtos/sessionAuthoringActionDtos.generated.js';
export type { SessionBoardActionInputById, SessionBoardActionResultById } from './dtos/sessionBoardActionDtos.generated.js';
export type { SessionControlActionInputById, SessionControlActionResultById } from './dtos/sessionControlActionDtos.generated.js';
export type { SessionDiscussionActionInputById, SessionDiscussionActionResultById } from './dtos/sessionDiscussionActionDtos.generated.js';
export type { SessionFollowActionInputById, SessionFollowActionResultById } from './dtos/sessionFollowActionDtos.generated.js';
export type { SessionLifecycleActionInputById, SessionLifecycleActionResultById } from './dtos/sessionLifecycleActionDtos.generated.js';
export type { SessionOrganizationMoveActionInputById, SessionOrganizationMoveActionResultById } from './dtos/sessionOrganizationMoveActionDtos.generated.js';
export type { SessionOrganizationResourcesActionInputById, SessionOrganizationResourcesActionResultById } from './dtos/sessionOrganizationResourcesActionDtos.generated.js';
export type { SessionPermissionsActionInputById, SessionPermissionsActionResultById } from './dtos/sessionPermissionsActionDtos.generated.js';
export type { SessionReadStateActionInputById, SessionReadStateActionResultById } from './dtos/sessionReadStateActionDtos.generated.js';
export type { SessionTargetingActionInputById, SessionTargetingActionResultById } from './dtos/sessionTargetingActionDtos.generated.js';
export type { SessionTerminalsActionInputById, SessionTerminalsActionResultById } from './dtos/sessionTerminalsActionDtos.generated.js';
export type { SessionTranscriptsActionInputById, SessionTranscriptsActionResultById } from './dtos/sessionTranscriptsActionDtos.generated.js';
export type { SettingsDeclarationsActionInputById, SettingsDeclarationsActionResultById } from './dtos/settingsDeclarationsActionDtos.generated.js';
export type { SubagentRegistryActionInputById, SubagentRegistryActionResultById } from './dtos/subagentRegistryActionDtos.generated.js';
export type { TeamsActionInputById, TeamsActionResultById } from './dtos/teamsActionDtos.generated.js';
export type { TodoSessionLinkActionInputById, TodoSessionLinkActionResultById } from './dtos/todoSessionLinkActionDtos.generated.js';
export type { VoiceControlsActionInputById, VoiceControlsActionResultById } from './dtos/voiceControlsActionDtos.generated.js';
export type { WidgetsActionInputById, WidgetsActionResultById } from './dtos/widgetsActionDtos.generated.js';
export type { WorkflowAuthoringActionInputById, WorkflowAuthoringActionResultById } from './dtos/workflowAuthoringActionDtos.generated.js';
export type { WorkflowEffectsActionInputById, WorkflowEffectsActionResultById } from './dtos/workflowEffectsActionDtos.generated.js';
export type { WorkflowsActionInputById, WorkflowsActionResultById } from './dtos/workflowsActionDtos.generated.js';
export type { WorkspaceLayoutActionInputById, WorkspaceLayoutActionResultById } from './dtos/workspaceLayoutActionDtos.generated.js';
export type { ProjectWorkersActionInputById, ProjectWorkersActionResultById } from './dtos/projectWorkersActionDtos.generated.js';
export type { ProjectDefinitionsActionInputById, ProjectDefinitionsActionResultById } from './dtos/projectDefinitionsActionDtos.generated.js';
export type { ProjectExecutionActionInputById, ProjectExecutionActionResultById } from './dtos/projectExecutionActionDtos.generated.js';
export type { ProjectSourcesActionInputById, ProjectSourcesActionResultById } from './dtos/projectSourcesActionDtos.generated.js';
export type { PluginAgentExternalSessionLinkDataArray } from './actionTypeMap.generated.js';
export type { PluginAgentExternalSessionLinkDataObject } from './actionTypeMap.generated.js';
export type { PluginAgentExternalSessionLinkDataValue } from './actionTypeMap.generated.js';
export type { JSONType } from './actionTypeMap.generated.js';
export type {
    AdmittedTargetedOperationExecutionHandle,
    AdmittedTargetedOperationIdentity,
} from './admittedTargetedOperation.js';
export type { AdmittedTargetedOperationExecutionOptions } from './service.js';
export type { AdmittedTargetedOperationExecutionWithOriginOptions } from './service.js';
export type { PluginMachineExecutionOriginV1 } from './executionOrigin.js';
export { PluginMachineExecutionOriginV1Schema } from './executionOrigin.js';
export type { ActionContribution } from './service.js';
export type { ActionApprovalRequestCreatedResult } from './service.js';
export type { ActionExecuteResult } from './service.js';
export type { ActionHandler } from './service.js';
export type { PluginActionInvocationSurfaceV2 } from './service.js';
export type { PluginClientActionContext } from './service.js';
export type { PluginClientActionHandler } from './service.js';
export type { PluginClientActionUi } from './service.js';
export type { ActionInputFieldHint } from './inputHints.js';
export type { ActionInputHints } from './inputHints.js';
export type { ActionFormFieldHint, ActionFormHints } from './inputHints.js';
export type { InputFieldHint, InputHints, InputOption, InputOptionValue, InputPredicate, EffectiveInputField } from './inputHints.js';
export { readInputPath, writeInputPath, resolveEffectiveInputFields, normalizeInputByFieldHints } from './inputHints.js';
export type { ActionInputOption } from './inputHints.js';
export type { ActionInputOptionValue } from './inputHints.js';
export type { ActionInputPredicate } from './inputHints.js';
export type { ActionSpec } from './service.js';
export type { ActionId } from './service.js';
export type { ActionsService } from './service.js';
export type { CommandContribution } from './service.js';
export type { ContributedActionExecutionWithOriginOptions } from './service.js';
export type { ContributedActionExecutionWithOriginResult } from './service.js';
export type { EffectiveActionInputField } from './inputHints.js';
export type { PluginActionDeclaration } from '../definePlugin.js';
export type { PluginActionExecutionV2 } from '../definePlugin.js';
export type { PluginActionAuthorDefaults } from '../definePlugin.js';
export type { PluginActionHandlerInvocation } from './service.js';
export type { PluginActionPlacement } from '../definePlugin.js';
export type { PluginActionInputById } from './service.js';
export type { PluginActionResultById } from './service.js';
export type { PluginActionWorkflowAuthoredResultReferenceV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowBlockV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowConditionV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowDefinitionV1 } from './service.js';
export type { PluginActionWorkflowEvaluatorHistoryModeV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowFailurePolicyV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowIngressBlockV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowItemExecutionModeV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowParallelBranchV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowRepetitionV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowStepV1 } from './actionTypeMap.generated.js';
export type { PluginActionWorkflowValueReferenceV1 } from './actionTypeMap.generated.js';
export type { PluginInvocableActionId } from './service.js';
export type { PluginJsonSchemaV2 } from './actionTypeMap.generated.js';
export type { PluginPolicyExpressionV2 } from './actionTypeMap.generated.js';
export type { SessionUsageLimitCheckNowRequestV1Input } from './actionTypeMap.generated.js';
export type { SessionUsageLimitConsumeResetCreditRequestV1Input } from './actionTypeMap.generated.js';
export type { SessionTranscriptGetExternalShareableInputV1 } from './service.js';
export type { SessionTranscriptGetExternalShareableResultV1 } from './service.js';
export type { ToolContribution } from './service.js';
export { actionInputOptionValueKey } from './inputHints.js';
export { getActionSpec } from './service.js';
export {
  EXTERNAL_ACTION_ACTION_ID_MAX_LENGTH,
  EXTERNAL_ACTION_REQUEST_ID_MAX_LENGTH_V1,
  EXTERNAL_ACTION_RESPONSE_MAX_SERIALIZED_BYTES,
  isExternalActionResultWithinResponseEnvelopeLimitV1,
  measureExternalActionResultResponseEnvelopeUtf8BytesV1,
} from './externalActionLimits.js';
export { isPluginActionApprovalRequestCreated } from './service.js';
export { isPluginActionHandlerInvocationNotStartedAdvisory } from './service.js';
export { isSameActionInputOptionValue } from './inputHints.js';
export { normalizeActionInputByFieldHints } from './inputHints.js';
export { readActionInputOptionValue } from './inputHints.js';
export { resolveEffectiveActionInputFields } from './inputHints.js';
