import type { PluginManifest } from '@happier-dev/plugin-sdk/manifest';

export const PLUGIN_MANIFEST = {
  schemaVersion: 2,
  id: '__pluginId__',
  version: '0.0.0',
  displayName: '__pluginDisplayName__',
  description: 'Template plugin generated for local development.',
  engines: { happier: '^0.0.0' }, runtime: { apiVersion: 1 },
  entrypoints: { daemon: './dist/index.js' },
  hostAccess: { required: [], optional: [] },
  contributes: {
    actions: [{
      id: 'save-note',
      title: 'Save note',
      description: 'Stores a note in plugin-local storage and returns it.',
      scopes: ['global'],
      surfaces: ['agent', 'cli', 'mcp'],
      placement: 'commandPalette',
      dangerLevel: 'safe',
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        properties: { note: { type: 'string' } },
        required: ['note'],
      },
      resultSchema: {
        type: 'object',
        additionalProperties: false,
        properties: { note: { type: 'string' } },
        required: ['note'],
      },
    }],
    tools: [{
      id: 'notes-add',
      name: 'notes_add',
      title: 'Add note',
      description: 'Stores a note through the canonical save-note action.',
      surfaces: ['agent', 'mcp'],
      inputSchema: {
        type: 'object',
        additionalProperties: false,
        properties: { note: { type: 'string' } },
        required: ['note'],
      },
      action: 'save-note',
    }],
    commands: [{
      id: 'notes-add-command',
      title: 'Add note',
      path: ['notes', 'add'],
      action: 'save-note',
    }],
    hooks: [{
      id: 'session-spawned',
      on: 'session.spawned',
      hookApiVersion: 1,
      category: 'lifecycle',
      scope: 'session',
      executionKind: 'observe',
    }],
    settings: [{
      id: 'preferences',
      title: 'Plugin preferences',
      target: { kind: 'plugin' },
      scope: 'local',
      fields: [{
        id: 'enabled',
        title: 'Enabled',
        description: 'Example host-rendered plugin preference.',
        schema: { type: 'boolean' },
        default: true,
      }],
    }],
  },
} satisfies PluginManifest;
