import { RPC_METHODS, SESSION_RPC_METHODS } from '../../../../rpc.js';

export type MachineRpcGovernanceClassification = 'action_spec_bound' | 'internal_only' | 'advisory_unclassified';

export type MachineRpcGovernanceMetadataV1 = Readonly<{
  rpcClassification: MachineRpcGovernanceClassification;
  actionSpecId?: string;
}>;

const ACTION_SPEC_RPC_METHOD_IDS = Object.freeze({
  [RPC_METHODS.SPAWN_HAPPY_SESSION]: 'session.spawn_new',
  [RPC_METHODS.STOP_SESSION]: 'session.stop',
  [RPC_METHODS.SESSION_CONTINUE_WITH_REPLAY]: 'session.continue_with_replay',
  [RPC_METHODS.SESSION_FORK]: 'session.fork',
  [RPC_METHODS.SESSION_PERMISSION_RESPOND]: 'session.permission.respond',
  [RPC_METHODS.SESSION_USER_ACTION_ANSWER]: 'session.user_action.answer',
  [RPC_METHODS.SESSION_PERMISSION_MODE_SET]: 'session.permission_mode.set',
  [RPC_METHODS.APPROVAL_REQUEST_LIST]: 'approval.request.list',
  [RPC_METHODS.APPROVAL_REQUEST_GET]: 'approval.request.get',
  [RPC_METHODS.APPROVAL_REQUEST_CREATE]: 'approval.request.create',
  [RPC_METHODS.APPROVAL_REQUEST_DECIDE]: 'approval.request.decide',
  [RPC_METHODS.SESSIONS_SUBAGENTS_LIST]: 'sessions.subagents.list',
  [RPC_METHODS.SESSIONS_SUBAGENTS_GET]: 'sessions.subagents.get',
  [RPC_METHODS.SESSIONS_SUBAGENTS_WATCH]: 'sessions.subagents.watch',
  [RPC_METHODS.SESSIONS_SUBAGENTS_UPSERT]: 'sessions.subagents.upsert',
  [RPC_METHODS.SESSIONS_SUBAGENTS_UPDATE_STATUS]: 'sessions.subagents.updateStatus',
  [RPC_METHODS.SESSIONS_SUBAGENTS_COMPLETE]: 'sessions.subagents.complete',
  [SESSION_RPC_METHODS.SESSION_ROLLBACK]: 'session.rollback',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_START]: 'session.handoff',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_PREPARE_TARGET]: 'session.handoff.prepare_target',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_PREPARE_TARGET_RESULT_GET]: 'session.handoff.prepare_target_result.get',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_COMMIT]: 'session.handoff.commit',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_ABORT]: 'session.handoff.abort',
  [RPC_METHODS.DAEMON_SESSION_HANDOFF_STATUS_GET]: 'session.handoff.status.get',
  [SESSION_RPC_METHODS.EXECUTION_RUN_START]: 'execution.run.start',
  [SESSION_RPC_METHODS.EXECUTION_RUN_LIST]: 'execution.run.list',
  [SESSION_RPC_METHODS.EXECUTION_RUN_GET]: 'execution.run.get',
  [SESSION_RPC_METHODS.EXECUTION_RUN_SEND]: 'execution.run.send',
  [SESSION_RPC_METHODS.EXECUTION_RUN_ENSURE]: 'execution.run.ensure',
  [SESSION_RPC_METHODS.EXECUTION_RUN_ENSURE_OR_START]: 'execution.run.ensure_or_start',
  [SESSION_RPC_METHODS.EXECUTION_RUN_STREAM_START]: 'execution.run.stream.start',
  [SESSION_RPC_METHODS.EXECUTION_RUN_STREAM_READ]: 'execution.run.stream.read',
  [SESSION_RPC_METHODS.EXECUTION_RUN_STREAM_CANCEL]: 'execution.run.stream.cancel',
  [SESSION_RPC_METHODS.EXECUTION_RUN_STOP]: 'execution.run.stop',
  [SESSION_RPC_METHODS.EXECUTION_RUN_ACTION]: 'execution.run.action',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSIONS_CANDIDATES_LIST]: 'sessions.external.candidates.list',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_LINK_ENSURE]: 'sessions.external.link.ensure',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_ATTACH]: 'sessions.external.follow',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_DETACH]: 'sessions.external.unfollow',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_FOLLOW_POLICY_SET]: 'sessions.external.followPolicy.set',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_STATUS_GET]: 'sessions.external.status.get',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_TRANSCRIPT_PAGE]: 'sessions.external.transcript.page',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_TRANSCRIPT_READ_AFTER]: 'sessions.external.transcript.readAfter',
  [RPC_METHODS.DAEMON_EXTERNAL_SESSION_TAKEOVER]: 'sessions.external.takeover',
  [RPC_METHODS.DAEMON_DIRECT_SESSIONS_CANDIDATES_LIST_LEGACY]: 'sessions.external.candidates.list',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_LINK_ENSURE_LEGACY]: 'sessions.external.link.ensure',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_ATTACH_LEGACY]: 'sessions.external.follow',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_DETACH_LEGACY]: 'sessions.external.unfollow',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_FOLLOW_POLICY_SET_LEGACY]: 'sessions.external.followPolicy.set',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_STATUS_GET_LEGACY]: 'sessions.external.status.get',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_TRANSCRIPT_PAGE_LEGACY]: 'sessions.external.transcript.page',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_TRANSCRIPT_READ_AFTER_LEGACY]: 'sessions.external.transcript.readAfter',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_TAKEOVER_LEGACY]: 'sessions.external.takeover',
  [RPC_METHODS.DAEMON_DIRECT_SESSION_TAKEOVER_PERSIST_LEGACY]: 'sessions.external.takeover',
  [RPC_METHODS.DAEMON_PROMPT_ASSETS_DISCOVER]: 'daemon.promptAssets.discover',
  [RPC_METHODS.DAEMON_PROMPT_ASSETS_DELETE]: 'daemon.promptAssets.delete',
  [RPC_METHODS.DAEMON_PROMPT_REGISTRY_SCAN_SOURCE]: 'daemon.promptRegistry.scanSource',
  [RPC_METHODS.DAEMON_PROMPT_REGISTRY_INSTALL]: 'daemon.promptRegistry.install',
  [RPC_METHODS.READ_FILE]: 'daemon.filesystem.readFile',
  [RPC_METHODS.WRITE_FILE]: 'daemon.filesystem.writeFile',
  [RPC_METHODS.LIST_DIRECTORY]: 'daemon.filesystem.listDirectory',
  [RPC_METHODS.GET_DIRECTORY_TREE]: 'daemon.filesystem.getDirectoryTree',
  [RPC_METHODS.DAEMON_FILESYSTEM_LIST_ROOTS]: 'daemon.filesystem.listRoots',
  [RPC_METHODS.DAEMON_FILESYSTEM_LIST_DIRECTORY]: 'daemon.filesystem.browseDirectory',
  [RPC_METHODS.BUGREPORT_COLLECT_DIAGNOSTICS]: 'bugreport.collectDiagnostics',
  [RPC_METHODS.BUGREPORT_GET_LOG_TAIL]: 'bugreport.getLogTail',
  [RPC_METHODS.BUGREPORT_UPLOAD_ARTIFACT]: 'bugreport.uploadArtifact',
  [RPC_METHODS.SESSION_LOG_TAIL]: 'session.log.tail',
  [RPC_METHODS.TRANSCRIPT_PAGE]: 'transcript.page',
  [RPC_METHODS.TRANSCRIPT_READ_AFTER]: 'transcript.readAfter',
  [RPC_METHODS.TRANSCRIPT_FOLLOW]: 'transcript.follow',
  [RPC_METHODS.TRANSCRIPT_IMPORT]: 'transcript.import',
  [RPC_METHODS.TRANSCRIPT_SEARCH]: 'transcript.search',
  [RPC_METHODS.SCM_PULL_REQUEST_LIST]: 'scm.pullRequest.list',
  [RPC_METHODS.SCM_PULL_REQUEST_GET]: 'scm.pullRequest.get',
  [RPC_METHODS.SCM_PULL_REQUEST_OPEN_OR_REUSE]: 'scm.pullRequest.openOrReuse',
  [RPC_METHODS.SCM_PULL_REQUEST_OPEN_COMPOSE]: 'scm.pullRequest.openCompose',
  [RPC_METHODS.SCM_PULL_REQUEST_CHECKOUT]: 'scm.pullRequest.checkout',
  [RPC_METHODS.SCM_PULL_REQUEST_PREPARE_WORKTREE]: 'scm.pullRequest.prepareWorktree',
  [RPC_METHODS.SCM_PULL_REQUEST_RUN_STACKED]: 'scm.pullRequest.runStacked',
  [RPC_METHODS.SCM_REPOSITORY_CLONE]: 'scm.repository.clone',
  [RPC_METHODS.SCM_REPOSITORY_INIT]: 'scm.repository.init',
  [RPC_METHODS.SCM_REPOSITORY_REMOVE_INDEX_LOCK]: 'scm.repository.removeIndexLock',
  [RPC_METHODS.SCM_HOSTING_REPOSITORY_DESCRIBE_PUBLISH_TARGETS]: 'scm.hostingRepository.describePublishTargets',
  [RPC_METHODS.SCM_HOSTING_REPOSITORY_PUBLISH]: 'scm.hostingRepository.publish',
  [RPC_METHODS.SCM_DIFF_SUMMARY_GENERATE]: 'scm.diffSummary.generate',
} satisfies Readonly<Record<string, string>>);

const PMS5_DIRECT_INTERNAL_METHODS = new Set<string>([
  RPC_METHODS.DAEMON_EXECUTION_RUNS_LIST,
  RPC_METHODS.DAEMON_MEMORY_STATUS,
  RPC_METHODS.DAEMON_MEMORY_SETTINGS_GET,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STATUS,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_MODELS_LIST,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_MODELS_STATUS,
  RPC_METHODS.DAEMON_EXTENSIONS_RELOAD_STATUS,
  RPC_METHODS.DAEMON_MERGED_CONTRIBUTION_REGISTRY_PROJECTION_DESCRIBE,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_LIST_TYPES,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_LIST_ADAPTERS,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_LIST_SOURCES,
  RPC_METHODS.DAEMON_MARKETPLACE_SOURCE_REGISTRY_GET,
  RPC_METHODS.SCM_BACKEND_DESCRIBE,
  RPC_METHODS.CAPABILITIES_DESCRIBE,
]);

const PROMPT_TRANSFER_INTERNAL_METHODS = new Set<string>([
  RPC_METHODS.DAEMON_PROMPT_ASSETS_UPLOAD_INIT,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_UPLOAD_CHUNK,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_UPLOAD_FINALIZE,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_UPLOAD_ABORT,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_DOWNLOAD_INIT,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_DOWNLOAD_CHUNK,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_DOWNLOAD_FINALIZE,
  RPC_METHODS.DAEMON_PROMPT_ASSETS_DOWNLOAD_ABORT,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_DOWNLOAD_INIT,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_DOWNLOAD_CHUNK,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_DOWNLOAD_FINALIZE,
  RPC_METHODS.DAEMON_PROMPT_REGISTRY_DOWNLOAD_ABORT,
]);

const A12_VOICE_CLEANUP_INTERNAL_METHODS = new Set<string>([
  RPC_METHODS.DAEMON_VOICE_INFERENCE_MODELS_INSTALL,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_MODELS_REMOVE,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_MODELS_WARM,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_TTS_SYNTHESIZE,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_TTS_CHUNK,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_TTS_FINALIZE,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_TTS_ABORT,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_TTS_CANCEL,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_UPLOAD_INIT,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_UPLOAD_CHUNK,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_UPLOAD_FINALIZE,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_UPLOAD_ABORT,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_TRANSCRIBE,
  RPC_METHODS.DAEMON_VOICE_INFERENCE_STT_CANCEL,
]);

export function resolveMachineRpcGovernance(method: string): MachineRpcGovernanceMetadataV1 {
  const actionSpecId = ACTION_SPEC_RPC_METHOD_IDS[method as keyof typeof ACTION_SPEC_RPC_METHOD_IDS];
  if (actionSpecId) {
    return { rpcClassification: 'action_spec_bound', actionSpecId };
  }
  if (
    method === RPC_METHODS.STOP_DAEMON
    || PMS5_DIRECT_INTERNAL_METHODS.has(method)
    || PROMPT_TRANSFER_INTERNAL_METHODS.has(method)
    || A12_VOICE_CLEANUP_INTERNAL_METHODS.has(method)
  ) {
    return { rpcClassification: 'internal_only' };
  }
  return { rpcClassification: 'advisory_unclassified' };
}
