export const SETTINGS_ROUTES = {
    general: '/settings',
    account: '/settings/account',
    teams: '/settings/teams',
    homeAdministration: '/settings/home',
    accountSecurity: '/settings/account/security',
    apiTokens: '/settings/account/api-tokens',
    secrets: '/settings/secrets',
    usage: '/settings/usage',
    machines: '/settings/machines',
    machineDefaults: '/settings/machines/defaults',
    machinePoolsNew: '/settings/machines/pools/new',
    machinesAdd: '/settings/machines/add',
    machinesThisComputer: '/settings/machines/this-computer',
    remoteHosts: '/settings/remote-hosts',
    remoteHostsAccess: '/settings/remote-hosts/access',
    appearance: '/settings/appearance',
    appearanceThemes: '/settings/appearance/themes',
    keyboard: '/settings/keyboard',
    language: '/settings/language',
    features: '/settings/features',
    pets: '/settings/pets',
    agents: '/settings/agents',
    providers: '/settings/providers',
    subAgent: '/settings/sub-agent',
    profiles: '/settings/profiles',
    roles: '/settings/roles',
    delegation: '/settings/delegation',
    connectedServices: '/settings/connected-services',
    connectedServicesAgentSignIn: '/settings/connected-services/sign-in',
    notifications: '/settings/notifications',
    notificationsPush: '/settings/notifications/push',
    mcp: '/settings/mcp',
    mcpOnMachine: '/settings/mcp/on-machine',
    mcpPreview: '/settings/mcp/preview',
    plugins: '/settings/plugins',
    pluginWebhooks: '/settings/plugins/webhooks',
    pluginSources: '/settings/plugins/sources',
    pluginDevelopment: '/settings/plugins/development',
    pluginDiagnostics: '/settings/plugins/diagnostics',
    prompts: '/settings/prompts',
    promptsTemplates: '/settings/prompts/templates',
    promptsFolders: '/settings/prompts/folders',
    promptsStacks: '/settings/prompts/stacks',
    promptsRegistries: '/settings/prompts/registries',
    promptsLibrary: '/settings/prompts/docs',
    promptsAssets: '/settings/prompts/assets',
    voice: '/settings/voice',
    voiceDictation: '/settings/voice/dictation',
    voiceConversations: '/settings/voice/conversations',
    voiceService: '/settings/voice/service',
    voicePrivacy: '/settings/voice/privacy',
    voiceAdvanced: '/settings/voice/advanced',
    voiceHistory: '/settings/voice-history',
    memory: '/settings/memory',
    session: '/settings/session',
    externalSessions: '/settings/external-sessions',
    actions: '/settings/actions',
    embeds: '/settings/embeds',
    newSessionWizard: '/settings/session/new-session-wizard',
    sessionComposer: '/settings/session/composer',
    sessionProviderLimits: '/settings/session/provider-limits',
    sessionResume: '/settings/session/resume',
    sessionRuntime: '/settings/session/runtime',
    transcript: '/settings/session/transcript',
    transcriptAdvanced: '/settings/session/transcript/advanced',
    permissions: '/settings/session/permissions',
    toolRendering: '/settings/session/tool-rendering',
    handoff: '/settings/session/handoff',
    sourceControl: '/settings/source-control',
    attachments: '/settings/attachments',
    servers: '/settings/server',
    serversAdd: '/settings/server/add',
    systemStatus: '/settings/system-status',
    updates: '/settings/updates',
    diagnosis: '/settings/diagnosis',
    desktop: '/settings/desktop',
    reportIssue: '/settings/report-issue',
    runs: '/runs',
} as const;

/**
 * The page a catalog route names, without the query an entry link may carry (Home Administration is
 * entered with `?entry=settings`). Which page is open is always read from this.
 */
export function settingsRoutePathname(route: string): string {
    const query = route.indexOf('?');
    return query === -1 ? route : route.slice(0, query);
}
