export const ANTIGRAVITY_CLI_MODELS_COMMAND_ARGS = ['models'] as const;
export const ANTIGRAVITY_CLI_MODELS_READINESS_TIMEOUT_MS = 15_000;
export const ANTIGRAVITY_CLI_MODELS_READINESS_OUTPUT_MAX_BYTES = 16_384;
