import { createMachineSharingTranslations } from '../machineSharingTranslations.shared';
export const machineSharing = createMachineSharingTranslations({
    terminals: { projectEmpty: 'Abre un terminal en este Proyecto.', opening: 'Abriendo terminal.', sharedOs: 'Este terminal se ejecuta como el usuario del sistema operativo de {machine}. Ese usuario puede leer credenciales locales y claves de cifrado. Usa una máquina dedicada al equipo para el trabajo compartido.', denied: 'Ya no tienes acceso a este terminal.', rootDenied: 'Este espacio de trabajo no está disponible para un terminal.', offline: 'Esta máquina está desconectada. Se muestra la última salida conocida.', openUnknown: 'Es posible que el terminal se haya abierto. Comprueba los terminales existentes antes de intentarlo de nuevo.', unavailable: 'Los terminales no están disponibles en esta máquina.', failed: 'No se pudo abrir este terminal.' },
    revoked: '{owner} dejó de compartir {machine}. Se está deteniendo tu trabajo en curso aquí. Tus sesiones permanecen en el historial; no puedes iniciar trabajo nuevo aquí.',
    recipientEncryptionIncompatible: 'Esta máquina cifrada de extremo a extremo requiere una cuenta con cifrado de extremo a extremo.',
    destinations: { yours: 'Tus máquinas', created: 'Creado por Happier', shared: 'Compartido contigo · {team}', owner: 'De {owner} · {platform}', pendingKey: 'Esperando acceso seguro', sharedPurposeUnsupported: 'Este trabajo requiere una de tus máquinas.' },
    title: 'Compartir', description: 'Las personas y equipos que añadas pueden iniciar sesiones, ejecutar scripts y abrir terminales en los espacios de trabajo de {machine}.',
    trustedOs: 'Las personas con acceso al terminal o a los agentes de {machine} ejecutan comandos como tu usuario del sistema operativo y pueden obtener tus credenciales locales y la clave de cifrado de la cuenta, si existe. Ninguna API de Happier lee ni exporta credenciales o claves del propietario; la salida del terminal compartido puede contenerlas. Recomendamos compartir una máquina dedicada al equipo.',
    manageHelp: 'Quienes pueden administrar {machine} también pueden compartirla con otras personas y darles el mismo acceso.', empty: 'Comparte {machine} para que tu equipo trabaje aquí.',
    loading: 'Cargando el acceso a {machine}.', readError: 'No se pudo cargar el acceso a {machine}.', offline: '{machine} está sin conexión. Los cambios de acceso se guardan aquí.',
    denied: 'Solo quienes pueden administrar {machine} pueden cambiar el acceso compartido.', use: 'Puede usar', manage: 'Puede administrar', allMembers: 'Todos los miembros actuales, incluidos quienes se incorporen después',
    pending: 'Esperando a que una persona autorizada con la clave prepare el acceso a {machine}.', incompatible: '{machine} tiene cifrado de extremo a extremo y la cuenta de {person} no, por lo que {person} no puede abrirla.',
    incompatibleHelp: 'Comparte una máquina sin cifrado o pide a {person} que active el cifrado de extremo a extremo en los ajustes de la cuenta.',
    plain: 'Sus datos no tienen cifrado de extremo a extremo, por lo que el Home puede leerlos.', saved: 'Acceso compartido actualizado', yourAccess: 'Tu acceso',
    ownHistory: 'Las sesiones que inicies aquí seguirán siendo tuyas en Happier. Quienes hayan iniciado sesión en el sistema operativo de {machine} pueden ver allí sus archivos y resultados.',
    leave: 'Salir de este acceso', inherited: 'Aún tienes acceso a través de {audience}. Pide a su administrador que cambie tu acceso.', unavailable: 'No se pudo comprobar el acceso a {machine}.',
    effectiveLoss: 'A quienes pierdan su último acceso se les detendrán las sesiones, scripts, ejecuciones, trabajo en cola y en preparación, terminales y servicios. Su historial de Happier seguirá siendo suyo; los datos ya obtenidos no se pueden retirar.',
    overlap: 'Se mantiene otro acceso válido. Su trabajo seguirá ejecutándose.', custodianProtected: 'El propietario original de la máquina no se puede eliminar ni sustituir aquí.',
});
