export const SESSION_SYNC_PROTOCOL_VERSION_RUNTIME_ACTIVITY = 2 as const;
export const SESSION_SYNC_PROTOCOL_VERSION_PUBLISHER_AUTHORITY_CHECK = 3 as const;
export const PENDING_INPUT_PROTOCOL_VERSION_V1 = 1 as const;
export const CURRENT_PENDING_INPUT_PROTOCOL_VERSION = PENDING_INPUT_PROTOCOL_VERSION_V1;
export const EXTERNAL_SESSION_IMPORT_PUBLICATION_FENCE_VERSION_V1 = 1 as const;
export const EXTERNAL_SESSION_HOSTED_ADMISSION_VERSION_V2 = 2 as const;
export const EXTERNAL_SESSION_RUNTIME_BOUND_ADMISSION_VERSION_V3 = 3 as const;
export const CURRENT_EXTERNAL_SESSION_IMPORT_PUBLICATION_FENCE_VERSION =
  EXTERNAL_SESSION_RUNTIME_BOUND_ADMISSION_VERSION_V3;
