import { cmd, sectionTitle } from '@happier-dev/cli-common/output';

export function showAuthHelp(): void {
  console.log([
    `${sectionTitle('happier auth')} - Authentication management`,
    '',
    sectionTitle('Usage:'),
    `  ${cmd('happier auth login [--no-open] [--force] [--method web|mobile] [--server <name-or-id> | --server-url <url> [--webapp-url <url>] [--persist|--no-persist]]')}    Authenticate with Happier`,
    `  ${cmd('happier auth request --json [--server <name-or-id> | --server-url <url> [--webapp-url <url>] [--persist|--no-persist]]')}                                    Create a claim-gated auth request (headless-friendly)`,
    `  ${cmd('happier auth approve --public-key <base64> --json [--server <name-or-id> | --server-url <url> [--webapp-url <url>] [--persist|--no-persist]]')}              Approve an auth request using your local credentials`,
    `  ${cmd('happier auth wait --public-key <base64> --json [--server <name-or-id> | --server-url <url> [--webapp-url <url>] [--persist|--no-persist]]')}                Wait for approval and write credentials for this machine`,
    `  ${cmd('happier auth pair-remote --ssh <user@host> --json')}                                                                                                                Fully automated remote pairing over SSH`,
    `  ${cmd('happier auth logout [--all]')}     Log out (active server by default)`,
    `  ${cmd('happier auth status')}             Show authentication status`,
    `  ${cmd('happier auth help')}               Show this help message`,
    '',
    sectionTitle('Options:'),
    `  --no-open  Do not attempt to open a browser (prints URL instead)`,
    `  --force    Clear credentials, machine ID, and stop daemon before re-auth`,
    `  --method   Force authentication method (web|mobile). Useful for headless/non-TTY.`,
    `  --print-configure-links  Print advanced “configure server” links for tooling (rare)`,
    `  --all      When used with logout, remove local data for all servers`,
    `  --json       Print machine-readable JSON (recommended for containers)`,
    `  --public-key Used with approve/wait; the terminal public key from "auth request --json"`,
    `  --ssh        Used with pair-remote; ssh target (e.g. user@host)`,
    `  --server      Use an existing saved server profile`,
    `  --server-url  Use a specific server URL (does not persist unless --persist)`,
    `  --webapp-url  Override web app URL for this server profile`,
    `  --persist     Persist --server-url as the active server profile`,
    `  --no-persist  Use --server-url for this invocation only (default)`,
    '',
    `${sectionTitle('PS:')} Your master secret never leaves your mobile/web device. Each CLI machine`,
    'receives only a derived key for per-machine encryption, so backup codes',
    'cannot be displayed from the CLI.',
  ].join('\n'));
}
