import type { AIBackendProfile } from '../../profiles/backendProfileSchema.js';
import { BUILT_IN_BACKEND_PROFILE_VERSION } from '../../profiles/builtInProfileVersion.js';

export const CLAUDE_BUILT_IN_BACKEND_PROFILES: ReadonlyArray<AIBackendProfile> = [
  {
    id: 'anthropic',
    name: 'Anthropic (Default)',
    authMode: 'machineLogin',
    requiresMachineLoginTargetKey: 'agent:claude',
    environmentVariables: [],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    envVarRequirements: [],
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek (Reasoner)',
    envVarRequirements: [{ name: 'DEEPSEEK_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${DEEPSEEK_BASE_URL:-https://api.deepseek.com/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${DEEPSEEK_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${DEEPSEEK_API_TIMEOUT_MS:-600000}' },
      { name: 'ANTHROPIC_MODEL', value: '${DEEPSEEK_MODEL:-deepseek-reasoner}' },
      { name: 'ANTHROPIC_SMALL_FAST_MODEL', value: '${DEEPSEEK_SMALL_FAST_MODEL:-deepseek-chat}' },
      { name: 'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC', value: '${DEEPSEEK_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-1}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM-4.6)',
    envVarRequirements: [{ name: 'Z_AI_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${Z_AI_BASE_URL:-https://api.z.ai/api/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${Z_AI_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${Z_AI_API_TIMEOUT_MS:-3000000}' },
      { name: 'ANTHROPIC_MODEL', value: '${Z_AI_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_OPUS_MODEL', value: '${Z_AI_OPUS_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_SONNET_MODEL', value: '${Z_AI_SONNET_MODEL:-GLM-4.6}' },
      { name: 'ANTHROPIC_DEFAULT_HAIKU_MODEL', value: '${Z_AI_HAIKU_MODEL:-GLM-4.5-Air}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'minimax',
    name: 'MiniMax (M3)',
    envVarRequirements: [{ name: 'MINIMAX_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${MINIMAX_BASE_URL:-https://api.minimax.io/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${MINIMAX_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${MINIMAX_API_TIMEOUT_MS:-600000}' },
      // Match Claude Code's compaction window to M3's 1M context capacity.
      { name: 'CLAUDE_CODE_AUTO_COMPACT_WINDOW', value: '${MINIMAX_AUTO_COMPACT_WINDOW:-1000000}' },
      { name: 'ANTHROPIC_MODEL', value: '${MINIMAX_MODEL:-MiniMax-M3}' },
      { name: 'ANTHROPIC_DEFAULT_OPUS_MODEL', value: '${MINIMAX_OPUS_MODEL:-MiniMax-M3}' },
      { name: 'ANTHROPIC_DEFAULT_SONNET_MODEL', value: '${MINIMAX_SONNET_MODEL:-MiniMax-M3}' },
      // MiniMax maps every tier to M3; we keep the cheaper documented M2.7 for
      // Haiku-class background work, which is what that tier exists for.
      { name: 'ANTHROPIC_DEFAULT_HAIKU_MODEL', value: '${MINIMAX_HAIKU_MODEL:-MiniMax-M2.7}' },
      { name: 'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC', value: '${MINIMAX_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-1}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
  {
    id: 'minimax-cn',
    name: 'MiniMax (M3, CN)',
    envVarRequirements: [{ name: 'MINIMAX_CN_AUTH_TOKEN', kind: 'secret', required: true }],
    environmentVariables: [
      { name: 'ANTHROPIC_BASE_URL', value: '${MINIMAX_CN_BASE_URL:-https://api.minimaxi.com/anthropic}' },
      { name: 'ANTHROPIC_AUTH_TOKEN', value: '${MINIMAX_CN_AUTH_TOKEN}' },
      { name: 'API_TIMEOUT_MS', value: '${MINIMAX_CN_API_TIMEOUT_MS:-600000}' },
      { name: 'CLAUDE_CODE_AUTO_COMPACT_WINDOW', value: '${MINIMAX_CN_AUTO_COMPACT_WINDOW:-1000000}' },
      { name: 'ANTHROPIC_MODEL', value: '${MINIMAX_CN_MODEL:-MiniMax-M3}' },
      { name: 'ANTHROPIC_DEFAULT_OPUS_MODEL', value: '${MINIMAX_CN_OPUS_MODEL:-MiniMax-M3}' },
      { name: 'ANTHROPIC_DEFAULT_SONNET_MODEL', value: '${MINIMAX_CN_SONNET_MODEL:-MiniMax-M3}' },
      { name: 'ANTHROPIC_DEFAULT_HAIKU_MODEL', value: '${MINIMAX_CN_HAIKU_MODEL:-MiniMax-M2.7}' },
      { name: 'CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC', value: '${MINIMAX_CN_CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC:-1}' },
    ],
    defaultPermissionModeByTargetKey: { 'agent:claude': 'default' },
    defaultPermissionModeByAgent: {},
    defaultPersistenceModeByTargetKey: {},
    defaultPersistenceModeByAgent: {},
    compatibilityByTargetKey: { 'agent:claude': true, 'agent:codex': false, 'agent:gemini': false },
    compatibility: {},
    isBuiltIn: true,
    defaultEnabled: true,
    createdAt: 0,
    updatedAt: 0,
    version: BUILT_IN_BACKEND_PROFILE_VERSION,
  },
] as const;
