export {
  BrowserAdapterUnavailableEventV1Schema,
  BrowserDownloadRequestedEventV1Schema,
  BrowserEventKindV1Schema,
  BrowserEventV1Schema,
  BrowserExternalOpenRequestedEventV1Schema,
  BrowserFaviconChangedEventV1Schema,
  BrowserLoadingProgressChangedEventV1Schema,
  BrowserNavigationCommittedEventV1Schema,
  BrowserNavigationFailedEventV1Schema,
  BrowserNavigationFinishedEventV1Schema,
  BrowserNavigationLoadingStateV1Schema,
  BrowserNavigationStartedEventV1Schema,
  BrowserNavigationStateChangedEventV1Schema,
  BrowserPermissionRequestedEventV1Schema,
  BrowserPopupRequestedEventV1Schema,
  BrowserSessionClosedEventV1Schema,
  BrowserSessionCreatedEventV1Schema,
  BrowserTargetChangedEventV1Schema,
  BrowserTitleChangedEventV1Schema,
  BrowserViewClosedEventV1Schema,
  BrowserViewCrashedEventV1Schema,
  BrowserViewFocusedEventV1Schema,
  BrowserViewOpenedEventV1Schema,
  type BrowserEventKindV1,
  type BrowserEventV1,
  type BrowserNavigationLoadingStateV1,
} from './v1.js';
