import type {
  ParsedPluginBackendContributionV2,
  ParsedPluginEventContributionV1,
  ParsedPluginManifestV2,
  PluginActionContributionV2,
  PluginBackendContributionV2,
  PluginContributesV2,
  PluginEventContributionV1,
  PluginManifestV2,
  PluginMcpContributesV1,
  PluginPermissionCapabilityV1,
  PluginPermissionDeclarationV1,
  PluginRequestInterceptorContributionV1,
  PluginRequestInterceptorScopeV1,
  PluginRequestInterceptorTargetV1,
  PluginRequestInterceptorUrlOriginV1,
  PluginHostedWebContributionV1,
  PluginReactNativeBundleContributionV1,
  PluginSessionHeaderActionDescriptorV1,
  PluginSessionSurfaceDescriptorV1,
  PluginStructuredMessageDescriptorV1,
  PluginSystemToolContributionV1,
  PluginToolContributionV2,
  PluginUiArtifactContributionV1,
  PluginUiTranslationsContributionV1,
} from '@happier-dev/protocol';

export function definePluginManifest<const TManifest>(
  manifest: TManifest,
): TManifest {
  return manifest;
}

export type {
  ParsedPluginBackendContributionV2,
  ParsedPluginEventContributionV1,
  ParsedPluginManifestV2,
  PluginActionContributionV2,
  PluginBackendContributionV2,
  PluginContributesV2,
  PluginEventContributionV1,
  PluginManifestV2,
  PluginMcpContributesV1,
  PluginPermissionCapabilityV1,
  PluginPermissionDeclarationV1,
  PluginRequestInterceptorContributionV1,
  PluginRequestInterceptorScopeV1,
  PluginRequestInterceptorTargetV1,
  PluginRequestInterceptorUrlOriginV1,
  PluginHostedWebContributionV1,
  PluginReactNativeBundleContributionV1,
  PluginSessionHeaderActionDescriptorV1,
  PluginSessionSurfaceDescriptorV1,
  PluginStructuredMessageDescriptorV1,
  PluginSystemToolContributionV1,
  PluginToolContributionV2,
  PluginUiArtifactContributionV1,
  PluginUiTranslationsContributionV1,
};
