import { PluginSettingsContributionV2Schema } from '@happier-dev/protocol';
import type {
  AIBackendProfile,
  ParsedPluginAgentContributionV2,
  ParsedPluginEventContributionV1,
  PluginBackendExternalSessionSourceDeclarationV1,
  PluginBackendExternalSessionSourceKeySegmentV1,
  PluginBackendExternalSessionSourceKeyV1,
  PluginBackendExternalSessionSourceSchemaFieldV1,
  PluginBackendExternalSessionSourceSchemaRefinementV1,
  PluginBackendExternalSessionSourceSchemaV1,
  PluginBackendExternalSessionSourceWhenV1,
  PluginBackendExternalSessionSurfaceV1,
  PluginBackendSurfacesV1,
  PluginAgentContributionV2,
  ParsedPluginManifestV2,
  PluginActionContributionV2,
  PluginBrowserActionContributionV1,
  PluginBrowserActionKindV1,
  PluginBrowserActionPolicyV1,
  PluginBrowserProfileModeV1,
  PluginBrowserTargetContributionV1,
  PluginHookContributionV2,
  PluginManagedDependencyContributionV2,
  PluginContributesV2,
  PluginEventContributionV1,
  PluginManifestV2,
  PluginMcpContributesV1,
  PluginCapabilityDeclarationV1,
  PluginDeclaredCapabilityV1,
  PluginPermissionCapabilityV1,
  PluginPermissionDeclarationV1,
  PluginAgentSettingsAnalyticsV1,
  PluginAgentSettingsContributionV1,
  PluginAgentSettingsFieldSchemaV1,
  PluginAgentSettingsFieldV1,
  PluginAgentSettingsUiDescriptorV1,
  PluginRequestInterceptorContributionV1,
  PluginRequestInterceptorScopeV1,
  PluginRequestInterceptorTargetV1,
  PluginRequestInterceptorUrlOriginV1,
  PluginSettingsContributionV2,
  PluginHostedWebContributionV1,
  PluginPromptAssetContributionV1,
  PluginReactNativeBundleContributionV1,
  PluginSessionHeaderActionDescriptorV1,
  PluginSurfacePlacementDescriptorV1,
  PluginStructuredMessageDescriptorV1,
  PluginSystemToolContributionV1,
  PluginToolContributionV2,
  PluginUiArtifactContributionV1,
  PluginUiTranslationsContributionV1,
  PromptAssetCapabilitiesV1,
  PromptAssetTypeDescriptorV1,
} from '@happier-dev/protocol';

export {
  BackendSurfaceOperationCatalogV1,
  PluginBackendCapabilitiesV1Schema,
} from '@happier-dev/protocol';

export function definePluginManifest<const TManifest>(
  manifest: TManifest,
): TManifest {
  return manifest;
}

export function definePluginSettingsContribution<const TContribution extends PluginSettingsContributionV2>(
  contribution: TContribution,
): TContribution {
  return PluginSettingsContributionV2Schema.parse(contribution) as TContribution;
}

export type {
  AIBackendProfile,
  ParsedPluginAgentContributionV2,
  ParsedPluginEventContributionV1,
  PluginBackendExternalSessionSourceDeclarationV1,
  PluginBackendExternalSessionSourceKeySegmentV1,
  PluginBackendExternalSessionSourceKeyV1,
  PluginBackendExternalSessionSourceSchemaFieldV1,
  PluginBackendExternalSessionSourceSchemaRefinementV1,
  PluginBackendExternalSessionSourceSchemaV1,
  PluginBackendExternalSessionSourceWhenV1,
  PluginBackendExternalSessionSurfaceV1,
  PluginBackendSurfacesV1,
  PluginAgentContributionV2,
  ParsedPluginManifestV2,
  PluginActionContributionV2,
  PluginBrowserActionContributionV1,
  PluginBrowserActionKindV1,
  PluginBrowserActionPolicyV1,
  PluginBrowserProfileModeV1,
  PluginBrowserTargetContributionV1,
  PluginHookContributionV2,
  PluginManagedDependencyContributionV2,
  PluginContributesV2,
  PluginEventContributionV1,
  PluginManifestV2,
  PluginMcpContributesV1,
  PluginCapabilityDeclarationV1,
  PluginDeclaredCapabilityV1,
  PluginPermissionCapabilityV1,
  PluginPermissionDeclarationV1,
  PluginAgentSettingsAnalyticsV1,
  PluginAgentSettingsContributionV1,
  PluginAgentSettingsFieldSchemaV1,
  PluginAgentSettingsFieldV1,
  PluginAgentSettingsUiDescriptorV1,
  PluginRequestInterceptorContributionV1,
  PluginRequestInterceptorScopeV1,
  PluginRequestInterceptorTargetV1,
  PluginRequestInterceptorUrlOriginV1,
  PluginSettingsContributionV2,
  PluginHostedWebContributionV1,
  PluginPromptAssetContributionV1,
  PluginReactNativeBundleContributionV1,
  PluginSessionHeaderActionDescriptorV1,
  PluginSurfacePlacementDescriptorV1,
  PluginStructuredMessageDescriptorV1,
  PluginSystemToolContributionV1,
  PluginToolContributionV2,
  PluginUiArtifactContributionV1,
  PluginUiTranslationsContributionV1,
  PromptAssetCapabilitiesV1,
  PromptAssetTypeDescriptorV1,
};

export {
  booleanAgentSetting,
  buildAgentSettingsDefaults,
  defineAgentSettingsContribution,
  enumArrayAgentSetting,
  enumAgentSetting,
  jsonObjectStringAgentSetting,
  positiveIntegerAgentSetting,
  agentSettingsContributionToUiDescriptor,
  stringRecordAgentSetting,
  stringAgentSetting,
} from '@happier-dev/protocol';
