export const SESSION_STATE_FIELD_IDS = [
  'identity.runtimeDescriptor',
  'identity.providerSessionId',
  'intent.model',
  'intent.role',
  'intent.sessionRoles',
  'intent.memoryEnabled',
  'intent.voicePreference',
  'intent.context',
  'intent.permissionMode',
  'intent.acpSessionMode',
  'intent.acpConfigOption',
  'display.title',
  'display.bot',
  'runtime.workState',
  'runtime.activity',
  'runtime.externalAgent',
  'runtime.externalSessionOperation',
  'runtime.usageLimitRecovery',
  'runtime.sessionRunner',
  'view.readState',
  'view.attention',
  'view.transcriptToolCalls',
] as const;

export const SESSION_STATE_FIELD_CLASSES = [
  'identity',
  'intent',
  'display',
  'runtime',
  'view',
] as const;
