import { describe, expect, it } from 'vitest';

import type { PluginJsonSchema } from '@happier-dev/plugin-sdk/protocol';

import { defineProtocolString, defineProtocolUtf8String } from '@happier-dev/plugin-sdk/protocol';

import {
    ASCII_FILL_ALPHABET,
    WORST_CASE_JSON_ESCAPE_BYTES,
    buildMaximalSchemaString,
    buildMaximalSchemaValue,
    codePointsOf,
    collectSchemaStringFields,
    deriveMaximumEncodedBytesByLabel,
    encodedJsonBytes,
    jsonEscapedByteCost,
    utf8ByteLength,
    type MeasurableSchemaV1,
} from '../testing/v1/maximumEncodedValue.js';
import {
    MAX_TRIAGE_SCAN_PAGE_ENTRIES_V1,
    MAX_TRIAGE_TEXT_UTF8_BYTES_V1,
    TRIAGE_SINGLE_LINE_STRING_PATTERN_V1,
} from './bounds.js';
import { TriageReadConfiguredSourceInstancesResultV1Schema } from './configuredInstances.js';
import { TriageSourcesContributionProtocolV1 } from './contribution.js';
import { TriageSourceDescriptorV1Schema } from './descriptor.js';
import { TriageDetailSurfaceInputV1Schema } from './detail.js';
import { TriageEntryLocatorV1Schema, TriageEntryRefV1Schema } from './identity.js';
import {
    TriageConfiguredSourceInstanceV1Schema,
    TriageListInstancesInputV1Schema,
    TriageListInstancesResultV1Schema,
} from './instances.js';
import { TriageSourceObservationV1Schema } from './observations.js';
import {
    TriageGetInputV1Schema,
    TriageGetResultV1Schema,
    TriageScanInputV1Schema,
    TriageScanResultV1Schema,
} from './operations.js';
import { TriageSourceAdministrationActionInputV1Schema } from './sourceAdministration.js';
import {
    TriagePrepareReviewWorkspaceInputV1Schema,
    TriagePrepareReviewWorkspaceResultV1Schema,
} from './workspace.js';

/**
 * `CONTRACT.md` §2.1 and §9 require this package to derive the largest
 * structurally valid encoded value each operation can carry from the real
 * composable schemas — a true worst-case upper bound, never an observed or
 * average sample — and to rerun that derivation whenever a contributing bound
 * changes.
 *
 * Nothing here is hand-built. Every measured value is generated by
 * `testing/v1/maximumEncodedValue.ts` — the one published derivation, which the
 * Triage target reuses to measure its own aggregate Action result against the
 * same gate — by walking the published JSON Schema projection of its own
 * schema, parsing it back through that schema so a structurally invalid value
 * can never be measured, and counting it as serialized JSON. A new field, a
 * widened bound, a raised count, a new union arm, or a relaxed string grammar
 * therefore changes a pinned total below rather than slipping past a fixture
 * that never mentioned it. The exact limits of the derivation are documented
 * with it.
 */

/**
 * The canonical ceiling every contributed Action input and result crosses,
 * owned by `packages/protocol/src/runtime/agentSessionLimitsV1.ts`
 * (`p0MeasuredCandidates.jsonValueMaxJsonBytes`) and enforced by
 * `AgentRuntimeJsonValueV1Schema` in
 * `packages/protocol/src/runtime/agentSessionV1.ts`, which
 * `packages/protocol/src/plugins/actions/invocation.ts` parses every plugin
 * Action input and result through before the manifest `resultSchema` is
 * consulted. It rejects an oversized value rather than truncating it. It is
 * referenced by value because `@happier-dev/protocol` is deliberately outside
 * this package's feature-protocol import allowlist; the Triage target's
 * `actions/maximumEncodedActionValue.test.ts` measures the same values through
 * that schema itself, so a relocation of the ceiling is caught there.
 *
 * It measures serialized UTF-8 JSON bytes, which is exactly what
 * `JSON.stringify` produces here.
 */
const ACTION_JSON_BYTE_GATE = 1_024 * 1_024;

/**
 * The framing the host adds around a derived value on the way to that gate —
 * measured, not reserved.
 *
 * Three facts fix it at zero:
 *
 * - the gate owner measures exactly the one value handed to it. Its serializer
 *   emits `JSON.stringify` for every scalar and plain `{}[]",:` for structure,
 *   so the totals below are the host's own measurement of the same value
 *   rather than an approximation of it, and it throws instead of truncating;
 * - the value handed to it is the operation value itself. `contribution.ts`
 *   declares each operation's `input.schema` as the whole Action input and its
 *   `resultSchema` as the whole Action result; the test below pins that, so a
 *   later envelope with sibling members fails here rather than eating headroom
 *   nobody budgeted;
 * - nothing may be added to one. Every measured value is a closed object, and
 *   `deriveMaximumEncodedBytes` throws when an unknown property survives
 *   parsing — so a host member added beside the declared ones is rejected by
 *   the source, never carried into a result this derivation measured short.
 *
 * The predecessor of this constant reserved half the gate for framing that was
 * never measured, and that reserve — not the gate — was what held
 * `MAX_TRIAGE_TEXT_UTF8_BYTES_V1` at a width no non-Latin title fits. What
 * keeps a later additive field from quietly spending the difference is the pin
 * on every total below: it fails on the byte rather than on a fraction, and it
 * fails whether the value is near the gate or far from it.
 */
const MEASURED_HOST_FRAMING_BYTES = 0;
const ADMITTED_ENCODED_BYTES = ACTION_JSON_BYTE_GATE - MEASURED_HOST_FRAMING_BYTES;

/**
 * The effective private-envelope ceiling of one persisted row, owned by
 * `packages/protocol/src/plugins/data/collectionLimitsV1.ts`
 * (`maximumPrivateEnvelopeEncodedBytes`).
 *
 * Only genuine user state is persisted at an Account: the canonical entry
 * reference a pin or Session link names, and the configured source instance.
 * Provider-derived observations are not a persisted corpus, so they are
 * measured against the Action gate above and never against this ceiling.
 */
const PRIVATE_ENVELOPE_CEILING_BYTES = 512 * 1024;

const measuredSchemas = {
    presentObservation: TriageSourceObservationV1Schema,
    scanPage: TriageScanResultV1Schema,
    getInput: TriageGetInputV1Schema,
    listInstancesResult: TriageListInstancesResultV1Schema,
    detailInput: TriageDetailSurfaceInputV1Schema,
    descriptor: TriageSourceDescriptorV1Schema,
    prepareReviewWorkspaceInput: TriagePrepareReviewWorkspaceInputV1Schema,
    administrationInput: TriageSourceAdministrationActionInputV1Schema,
    // The caller-scoped configured-instance read is the target's own Action, but
    // its result is composed entirely from this package's schemas and crosses
    // the same gate, so it is derived here beside the administration input
    // rather than in a second ledger.
    readConfiguredInstancesResult: TriageReadConfiguredSourceInstancesResultV1Schema,
} as const satisfies Readonly<Record<string, MeasurableSchemaV1>>;

const persistedRowSchemas = {
    entryRef: TriageEntryRefV1Schema,
    configuredInstance: TriageConfiguredSourceInstanceV1Schema,
} as const satisfies Readonly<Record<string, MeasurableSchemaV1>>;

const derivedMaxima = deriveMaximumEncodedBytesByLabel(measuredSchemas);
const derivedPersistedRowMaxima = deriveMaximumEncodedBytesByLabel(persistedRowSchemas);

function reachableStringFields(): ReadonlyMap<string, PluginJsonSchema> {
    const fields = new Map<string, PluginJsonSchema>();
    for (const schema of [
        ...Object.values<MeasurableSchemaV1>(measuredSchemas),
        ...Object.values<MeasurableSchemaV1>(persistedRowSchemas),
    ]) {
        collectSchemaStringFields(schema.jsonSchema, '(root)', fields);
    }
    return fields;
}

describe('worst-case JSON escaping', () => {
    it('expands no code point past the worst case, whatever its width', () => {
        const samples = [
            ...ASCII_FILL_ALPHABET,
            'ÿ',
            '一',
            '\u{1f600}',
            // A lone surrogate, the widest escape a non-ASCII code unit reaches.
            '\ud800',
        ];
        for (const sample of samples) {
            expect(jsonEscapedByteCost(sample), `${JSON.stringify(sample)} per code point`)
                .toBeLessThanOrEqual(WORST_CASE_JSON_ESCAPE_BYTES);
            expect(jsonEscapedByteCost(sample) / utf8ByteLength(sample), `${JSON.stringify(sample)} per byte`)
                .toBeLessThanOrEqual(WORST_CASE_JSON_ESCAPE_BYTES);
        }
        expect(jsonEscapedByteCost(String.fromCharCode(0x1f))).toBe(WORST_CASE_JSON_ESCAPE_BYTES);
    });

    it('names every field whose grammar admits the sixfold escape', () => {
        const sixfold = [...reachableStringFields()]
            .filter(([name, fragment]) => codePointsOf(buildMaximalSchemaString(fragment, name))
                .some((character) => jsonEscapedByteCost(character) === WORST_CASE_JSON_ESCAPE_BYTES))
            .map(([name]) => name)
            .sort();

        // Two are the V1 composite identifiers, which admit exactly one
        // separator between two single-line components. The others are
        // external protocol-owned identity strings this protocol embeds whose
        // only grammar is "no outer whitespace", so every control character is
        // admitted throughout. A V1 string that joins this set widens the
        // maxima above and is a deliberate protocol decision, not a detail.
        //
        // `instanceId` LEFT this set with the Composer-origin `originComposer`
        // address, which now lives only in Triage's own closed private launch
        // input (PEP `03d1` §17.8) and never crosses this Action gate. The
        // remaining `sessionId` is the linked-Session projection's own.
        expect(sixfold).toEqual([
            'accountId',
            'collisionScope',
            'localInstanceKey',
            'sessionId',
        ]);
    });

    it('confines each composite identifier to a single separator', () => {
        const separator = String.fromCharCode(0x1f);
        for (const name of ['collisionScope', 'localInstanceKey']) {
            const fragment = reachableStringFields().get(name);
            if (fragment === undefined) throw new Error(`${name} is no longer a reachable string`);
            const fill = buildMaximalSchemaString(fragment, name);
            const bound = fragment['x-happier-max-utf8-bytes'];
            expect(codePointsOf(fill).filter((character) => character === separator)).toHaveLength(1);
            expect(utf8ByteLength(JSON.stringify(fill)))
                .toBe((Number(bound) - 1) * 2 + WORST_CASE_JSON_ESCAPE_BYTES + 2);
        }
    });
});

describe('what the gate measures', () => {
    /**
     * The framing allowance above is zero because the operation value is the
     * whole Action value. This is where that stops being a claim: each
     * declared operation schema has to be exactly the schema measured below,
     * so a seam that later wrapped a result in an envelope with sibling
     * members fails here instead of spending headroom nobody budgeted.
     */
    it('declares the measured value as the whole operation input and result', () => {
        const operations = TriageSourcesContributionProtocolV1.operations;
        const declared = [
            [operations.listInstances.declaration, TriageListInstancesInputV1Schema, TriageListInstancesResultV1Schema],
            [operations.scan.declaration, TriageScanInputV1Schema, TriageScanResultV1Schema],
            [operations.get.declaration, TriageGetInputV1Schema, TriageGetResultV1Schema],
            [
                operations.prepareReviewWorkspace.declaration,
                TriagePrepareReviewWorkspaceInputV1Schema,
                TriagePrepareReviewWorkspaceResultV1Schema,
            ],
        ] as const;

        for (const [declaration, input, result] of declared) {
            expect(declaration.input.kind).toBe('protocolDefined');
            if (declaration.input.kind !== 'protocolDefined') continue;
            expect(declaration.input.schema.jsonSchema).toEqual(input.jsonSchema);
            expect(declaration.resultSchema.jsonSchema).toEqual(result.jsonSchema);
        }
    });
});

describe('the derivation follows the schema', () => {
    /**
     * A byte bound and a code-point bound are not the same bound, and the fill
     * that maximizes one does not maximize the other.
     *
     * Under a byte bound the costliest admitted code point per **byte** wins,
     * and that is always an ASCII one: `"` doubles its single byte, and a
     * control sextuples it. Under a code-point bound the costliest admitted code
     * point per **code point** wins instead — and when the grammar excludes
     * controls, that is a four-byte astral code point, which JSON emits
     * literally, not the two-byte `\"` an ASCII-only search settles for. Every
     * V1 string grammar admits astral code points, so a search that never
     * considers one measures such a field at exactly half its real maximum and
     * the pinned totals below stop being an upper bound.
     *
     * Both directions are asserted against a value the real composable schema
     * parses, so neither is a claim about a value nothing would accept.
     */
    it('measures a code-point-bounded string at the widest code point it admits', () => {
        const codePoints = 8;
        const schema = defineProtocolString({
            minLength: 1,
            maxLength: codePoints,
            pattern: TRIAGE_SINGLE_LINE_STRING_PATTERN_V1,
        });
        // Four UTF-8 bytes each, emitted literally by JSON, and admitted by
        // every V1 string grammar.
        const astral = '\u{10000}'.repeat(codePoints);
        expect(schema.parse(astral)).toBe(astral);

        expect(encodedJsonBytes(buildMaximalSchemaString(schema.jsonSchema, 'codePointBounded')))
            .toBeGreaterThanOrEqual(encodedJsonBytes(astral));
    });

    it('keeps a byte-bounded string on the fill that maximizes bytes, not code points', () => {
        const maxUtf8Bytes = 32;
        const schema = defineProtocolUtf8String({
            minLength: 1,
            maxUtf8Bytes,
            pattern: TRIAGE_SINGLE_LINE_STRING_PATTERN_V1,
        });
        const fill = buildMaximalSchemaString(schema.jsonSchema, 'byteBounded');
        expect(schema.parse(fill)).toBe(fill);

        // The whole budget spent on single-byte code points that each double.
        expect(encodedJsonBytes(fill)).toBe(maxUtf8Bytes * 2 + 2);
    });

    it('grows when a schema gains a field', () => {
        const locator = TriageEntryLocatorV1Schema.jsonSchema;
        const routingToken = locator.properties?.routingToken;
        if (routingToken === undefined) throw new Error('the locator no longer carries a routing token');
        const widened: PluginJsonSchema = {
            ...locator,
            properties: { ...locator.properties, addedFieldV1: routingToken },
        };

        expect(encodedJsonBytes(buildMaximalSchemaValue(widened, 'widened')))
            .toBeGreaterThan(encodedJsonBytes(buildMaximalSchemaValue(locator, 'locator')));
    });

    it('refuses to measure a value the schema does not bound', () => {
        expect(() => buildMaximalSchemaValue({ type: 'string' }, 'string')).toThrow(/unbounded string/u);
        expect(() => buildMaximalSchemaValue({ type: 'array', items: { const: 1 } }, 'array'))
            .toThrow(/unbounded array/u);
        expect(() => buildMaximalSchemaValue({ type: 'string', maxLength: 4, pattern: '^\\p{Lu}{5}$' }, 'fill'))
            .toThrow(/no admitted maximal fill/u);
    });
});

describe('maximum encoded value derivation', () => {
    it('derives the exact maximum encoded bytes of every value that crosses the gate', () => {
        // Pinned so that any bound, count, field, or grammar change reruns the
        // derivation instead of silently consuming the remaining headroom.
        expect(derivedMaxima).toEqual({
            presentObservation: 11_219,
            scanPage: 726_672,
            getInput: 11_496,
            listInstancesResult: 360_213,
            detailInput: 91_691,
            descriptor: 77_679,
            prepareReviewWorkspaceInput: 11_993,
            administrationInput: 7_775,
            readConfiguredInstancesResult: 266_066,
        });
    });

    it('keeps every derived maximum below the gate the host actually enforces', () => {
        for (const [label, bytes] of Object.entries(derivedMaxima)) {
            expect(
                bytes,
                `${label} must stay below the Action gate once host framing is counted`,
            ).toBeLessThan(ADMITTED_ENCODED_BYTES);
        }
    });

    /**
     * The assertion above is only worth its line if a real breach reaches it.
     * Raising the page count — the one bound that multiplies every per-entry
     * byte — is the cheapest true breach, and it has to fail without any help
     * from a pinned total.
     */
    it('fails on a real breach rather than only on a changed pin', () => {
        const page = TriageScanResultV1Schema.jsonSchema.anyOf?.[0];
        const observations = page?.properties?.observations;
        if (page === undefined || observations?.maxItems === undefined) {
            throw new Error('the scan page no longer carries a bounded observations array');
        }
        const breached = buildMaximalSchemaValue({
            ...page,
            properties: {
                ...page.properties,
                observations: { ...observations, maxItems: observations.maxItems * 3 },
            },
        }, 'breachedScanPage');

        expect(encodedJsonBytes(breached)).toBeGreaterThan(ADMITTED_ENCODED_BYTES);
    });

    /**
     * Headroom is only meaningful in the unit that would spend it. The one
     * thing that consumes it at scale is another display string on every
     * entry: a single-line string expands at most twofold
     * (`TRIAGE_SINGLE_LINE_STRING_PATTERN_V1` is what buys that), so one costs
     * the page count times the display bound times two. Stating the margin
     * this way is what makes it re-decidable — a V1 that wants a seventh or an
     * eighth row string beside today's six can see here whether it still has
     * the room, instead of discovering the gate at runtime.
     */
    it('leaves the binding value room for several more per-entry display strings', () => {
        const perEntryDisplayString = MAX_TRIAGE_SCAN_PAGE_ENTRIES_V1
            * MAX_TRIAGE_TEXT_UTF8_BYTES_V1
            * 2;

        expect(Math.floor(
            (ADMITTED_ENCODED_BYTES - derivedMaxima.scanPage) / perEntryDisplayString,
        )).toBeGreaterThanOrEqual(4);
    });

    it('keeps a full scan page the largest value, so the page count is the binding bound', () => {
        const others = Object.entries(derivedMaxima)
            .filter(([label]) => label !== 'scanPage')
            .map(([, bytes]) => bytes);

        expect(derivedMaxima.scanPage).toBeGreaterThan(Math.max(...others));
        expect(derivedMaxima.scanPage)
            .toBeGreaterThan(derivedMaxima.presentObservation * MAX_TRIAGE_SCAN_PAGE_ENTRIES_V1);
    });
});

describe('persisted user-state rows', () => {
    /**
     * Provider-derived observations are not persisted, so only genuine user
     * state meets this ceiling: the canonical entry reference a pin or Session
     * link names, and the configured source instance.
     */
    it('keeps every persisted row below the private-envelope ceiling, base64 included', () => {
        expect(derivedPersistedRowMaxima).toEqual({
            entryRef: 1_496,
            configuredInstance: 8_269,
        });

        for (const [label, bytes] of Object.entries(derivedPersistedRowMaxima)) {
            // Base64 expansion alone, before nonce, authentication tag, padding,
            // and JSON framing; the encoder owns the exact envelope.
            expect(Math.ceil(bytes / 3) * 4, `${label} envelope`)
                .toBeLessThan(PRIVATE_ENVELOPE_CEILING_BYTES);
        }
    });
});
