import { describe, expect, it } from 'vitest';

import type { PluginJsonSchema } from '@happier-dev/plugin-sdk/protocol';

import { defineProtocolString, defineProtocolUtf8String } from '@happier-dev/plugin-sdk/protocol';

import {
    ASCII_FILL_ALPHABET,
    WORST_CASE_JSON_ESCAPE_BYTES,
    buildMaximalSchemaString,
    buildMaximalSchemaValue,
    codePointsOf,
    collectSchemaStringFields,
    deriveMaximumEncodedBytesByLabel,
    encodedJsonBytes,
    jsonEscapedByteCost,
    utf8ByteLength,
    type MeasurableSchemaV1,
} from '../testing/v1/maximumEncodedValue.js';
import { TRIAGE_SINGLE_LINE_STRING_PATTERN_V1 } from './bounds.js';
import { TriageSourcesContributionProtocolV1 } from './contribution.js';
import { TriageDetailSurfaceInputV1Schema } from './detail.js';
import { TriageEntryLocatorV1Schema, TriageEntryRefV1Schema } from './identity.js';
import {
    TriageListInstancesInputV1Schema,
    TriageListInstancesResultV1Schema,
} from './instances.js';
import { TriageSourceObservationV1Schema } from './observations.js';
import {
    TriageGetInputV1Schema,
    TriageGetResultV1Schema,
    TriageScanInputV1Schema,
    TriageScanResultV1Schema,
} from './operations.js';
import { TriageSourceAdministrationActionInputV1Schema } from './sourceAdministration.js';
import {
    TriagePrepareReviewWorkspaceInputV1Schema,
    TriagePrepareReviewWorkspaceResultV1Schema,
} from './workspace.js';

/**
 * `CONTRACT.md` §2.1 and §9 require this package to derive the largest
 * structurally valid encoded value each **finite** operation can carry from the
 * real composable schemas — a true worst-case upper bound, never an observed
 * or average sample — and to rerun that derivation whenever a contributing
 * bound changes. Discovery, configured-instance reads, and descriptor kinds
 * deliberately have no picked membership ceiling: their callers page or
 * materialize the real set, so they are not finite operation shapes to measure
 * here.
 *
 * Nothing here is hand-built. Every measured value is generated by
 * `testing/v1/maximumEncodedValue.ts` — the one published derivation, which the
 * Triage target reuses to measure its own aggregate Action result against the
 * same gate — by walking the published JSON Schema projection of its own
 * schema, parsing it back through that schema so a structurally invalid value
 * can never be measured, and counting it as serialized JSON. A new field, a
 * widened bound, a raised count, a new union arm, or a relaxed string grammar
 * therefore changes a pinned total below rather than slipping past a fixture
 * that never mentioned it. The exact limits of the derivation are documented
 * with it.
 */

const measuredSchemas = {
    presentObservation: TriageSourceObservationV1Schema,
    getInput: TriageGetInputV1Schema,
    detailInput: TriageDetailSurfaceInputV1Schema,
    prepareReviewWorkspaceInput: TriagePrepareReviewWorkspaceInputV1Schema,
    administrationInput: TriageSourceAdministrationActionInputV1Schema,
} as const satisfies Readonly<Record<string, MeasurableSchemaV1>>;

const derivedMaxima = deriveMaximumEncodedBytesByLabel(measuredSchemas);

function reachableStringFields(): ReadonlyMap<string, PluginJsonSchema> {
    const fields = new Map<string, PluginJsonSchema>();
    for (const schema of Object.values<MeasurableSchemaV1>(measuredSchemas)) {
        collectSchemaStringFields(schema.jsonSchema, '(root)', fields);
    }
    return fields;
}

describe('worst-case JSON escaping', () => {
    it('expands no code point past the worst case, whatever its width', () => {
        const samples = [
            ...ASCII_FILL_ALPHABET,
            'ÿ',
            '一',
            '\u{1f600}',
            // A lone surrogate, the widest escape a non-ASCII code unit reaches.
            '\ud800',
        ];
        for (const sample of samples) {
            expect(jsonEscapedByteCost(sample), `${JSON.stringify(sample)} per code point`)
                .toBeLessThanOrEqual(WORST_CASE_JSON_ESCAPE_BYTES);
            expect(jsonEscapedByteCost(sample) / utf8ByteLength(sample), `${JSON.stringify(sample)} per byte`)
                .toBeLessThanOrEqual(WORST_CASE_JSON_ESCAPE_BYTES);
        }
        expect(jsonEscapedByteCost(String.fromCharCode(0x1f))).toBe(WORST_CASE_JSON_ESCAPE_BYTES);
    });

    it('names every field whose grammar admits the sixfold escape', () => {
        const sixfold = [...reachableStringFields()]
            .filter(([name, fragment]) => codePointsOf(buildMaximalSchemaString(fragment, name))
                .some((character) => jsonEscapedByteCost(character) === WORST_CASE_JSON_ESCAPE_BYTES))
            .map(([name]) => name)
            .sort();

        // Two are the V1 composite identifiers, which admit exactly one
        // separator between two single-line components. The others are
        // external protocol-owned identity strings this protocol embeds whose
        // only grammar is "no outer whitespace", so every control character is
        // admitted throughout. A V1 string that joins this set widens the
        // maxima above and is a deliberate protocol decision, not a detail.
        //
        // `instanceId` LEFT this set with the Composer-origin `originComposer`
        // address, which now lives only in Triage's own closed private launch
        // input (PEP `03d1` §17.8). The
        // remaining `sessionId` is the linked-Session projection's own.
        expect(sixfold).toEqual([
            'accountId',
            'collisionScope',
            'localInstanceKey',
            'sessionId',
        ]);
    });

    it('confines each composite identifier to a single separator', () => {
        const separator = String.fromCharCode(0x1f);
        for (const name of ['collisionScope', 'localInstanceKey']) {
            const fragment = reachableStringFields().get(name);
            if (fragment === undefined) throw new Error(`${name} is no longer a reachable string`);
            const fill = buildMaximalSchemaString(fragment, name);
            const bound = fragment['x-happier-max-utf8-bytes'];
            expect(codePointsOf(fill).filter((character) => character === separator)).toHaveLength(1);
            expect(utf8ByteLength(JSON.stringify(fill)))
                .toBe((Number(bound) - 1) * 2 + WORST_CASE_JSON_ESCAPE_BYTES + 2);
        }
    });
});

describe('what the gate measures', () => {
    /**
     * The framing allowance above is zero because the operation value is the
     * whole Action value. This is where that stops being a claim: each
     * declared operation schema has to be exactly the schema measured below,
     * so a seam that later wrapped a result in an envelope with sibling
     * members fails here instead of spending headroom nobody budgeted.
     */
    it('declares the measured value as the whole operation input and result', () => {
        const operations = TriageSourcesContributionProtocolV1.operations;
        const declared = [
            [operations.listInstances.declaration, TriageListInstancesInputV1Schema, TriageListInstancesResultV1Schema],
            [operations.scan.declaration, TriageScanInputV1Schema, TriageScanResultV1Schema],
            [operations.get.declaration, TriageGetInputV1Schema, TriageGetResultV1Schema],
            [
                operations.prepareReviewWorkspace.declaration,
                TriagePrepareReviewWorkspaceInputV1Schema,
                TriagePrepareReviewWorkspaceResultV1Schema,
            ],
        ] as const;

        for (const [declaration, input, result] of declared) {
            expect(declaration.input.kind).toBe('protocolDefined');
            if (declaration.input.kind !== 'protocolDefined') continue;
            expect(declaration.input.schema.jsonSchema).toEqual(input.jsonSchema);
            expect(declaration.resultSchema.jsonSchema).toEqual(result.jsonSchema);
        }
    });
});

describe('the derivation follows the schema', () => {
    /**
     * A byte bound and a code-point bound are not the same bound, and the fill
     * that maximizes one does not maximize the other.
     *
     * Under a byte bound the costliest admitted code point per **byte** wins,
     * and that is always an ASCII one: `"` doubles its single byte, and a
     * control sextuples it. Under a code-point bound the costliest admitted code
     * point per **code point** wins instead — and when the grammar excludes
     * controls, that is a four-byte astral code point, which JSON emits
     * literally, not the two-byte `\"` an ASCII-only search settles for. Every
     * V1 string grammar admits astral code points, so a search that never
     * considers one measures such a field at exactly half its real maximum and
     * the pinned totals below stop being an upper bound.
     *
     * Both directions are asserted against a value the real composable schema
     * parses, so neither is a claim about a value nothing would accept.
     */
    it('measures a code-point-bounded string at the widest code point it admits', () => {
        const codePoints = 8;
        const schema = defineProtocolString({
            minLength: 1,
            maxLength: codePoints,
            pattern: TRIAGE_SINGLE_LINE_STRING_PATTERN_V1,
        });
        // Four UTF-8 bytes each, emitted literally by JSON, and admitted by
        // every V1 string grammar.
        const astral = '\u{10000}'.repeat(codePoints);
        expect(schema.parse(astral)).toBe(astral);

        expect(encodedJsonBytes(buildMaximalSchemaString(schema.jsonSchema, 'codePointBounded')))
            .toBeGreaterThanOrEqual(encodedJsonBytes(astral));
    });

    it('keeps a byte-bounded string on the fill that maximizes bytes, not code points', () => {
        const maxUtf8Bytes = 32;
        const schema = defineProtocolUtf8String({
            minLength: 1,
            maxUtf8Bytes,
            pattern: TRIAGE_SINGLE_LINE_STRING_PATTERN_V1,
        });
        const fill = buildMaximalSchemaString(schema.jsonSchema, 'byteBounded');
        expect(schema.parse(fill)).toBe(fill);

        // The whole budget spent on single-byte code points that each double.
        expect(encodedJsonBytes(fill)).toBe(maxUtf8Bytes * 2 + 2);
    });

    it('grows when a schema gains a field', () => {
        const locator = TriageEntryLocatorV1Schema.jsonSchema;
        const routingToken = locator.properties?.routingToken;
        if (routingToken === undefined) throw new Error('the locator no longer carries a routing token');
        const widened: PluginJsonSchema = {
            ...locator,
            properties: { ...locator.properties, addedFieldV1: routingToken },
        };

        expect(encodedJsonBytes(buildMaximalSchemaValue(widened, 'widened')))
            .toBeGreaterThan(encodedJsonBytes(buildMaximalSchemaValue(locator, 'locator')));
    });

    it('refuses to measure a value the schema does not bound', () => {
        expect(() => buildMaximalSchemaValue({ type: 'string' }, 'string')).toThrow(/unbounded string/u);
        expect(() => buildMaximalSchemaValue({ type: 'array', items: { const: 1 } }, 'array'))
            .toThrow(/unbounded array/u);
        expect(() => buildMaximalSchemaValue({ type: 'string', maxLength: 4, pattern: '^\\p{Lu}{5}$' }, 'fill'))
            .toThrow(/no admitted maximal fill/u);
    });
});

describe('maximum encoded value derivation', () => {
    it('derives the exact maximum encoded bytes of every finite operation shape', () => {
        // Pinned so that any bound, count, field, or grammar change reruns the
        // derivation instead of silently consuming the remaining headroom.
        expect(derivedMaxima).toEqual({
            presentObservation: 12_887,
            getInput: 11_496,
            detailInput: 468_370,
            prepareReviewWorkspaceInput: 14_243,
            administrationInput: 7_775,
        });
    });

    it('leaves the scan result unbounded until the canonical Action envelope', () => {
        expect(() => buildMaximalSchemaValue(TriageScanResultV1Schema, 'scan result'))
            .toThrow();
    });
});
