export type { ForgeHttpErrorContext } from '../hostingProvider.js';
export type { ForgeHttpErrorMapper } from '../hostingProvider.js';
export type { ForgeHttpFetcher } from '../hostingProvider.js';
export type { ForgeHttpJsonRequest } from '../hostingProvider.js';
export type { ForgeHttpResponse } from '../hostingProvider.js';
export type { HostingProviderCompareUrlInput } from '../hostingProvider.js';
export type { HostingProviderCompareUrlResult } from '../hostingProvider.js';
export type { HostingProviderContribution } from '../hostingProvider.js';
export type { HostingProviderDescriptor } from '../hostingProvider.js';
export type { HostingProviderPullRequestCheckoutCapability } from '../hostingProvider.js';
export type { HostingProviderPullRequestCheckoutReferenceInput } from '../hostingProvider.js';
export type { HostingProviderPullRequestCheckoutReferenceMetadata } from '../hostingProvider.js';
export type { HostingProviderPullRequestCreateInput } from '../hostingProvider.js';
export type { HostingProviderPullRequestGetInput } from '../hostingProvider.js';
export type { HostingProviderPullRequestListInput } from '../hostingProvider.js';
export type { HostingProviderPullRequestsCapability } from '../hostingProvider.js';
export type { HostingProviderRegistryDiagnostic } from '../hostingProvider.js';
export type { HostingProviderRemoteDetectionInput } from '../hostingProvider.js';
export type { HostingProviderRemoteDetectionResult } from '../hostingProvider.js';
export type { HostingProviderRepositoryCloneCapability } from '../hostingProvider.js';
export type { HostingProviderRepositoryCreateInput } from '../hostingProvider.js';
export type { HostingProviderRepositoryDescribeCloneTargetsInput } from '../hostingProvider.js';
export type { HostingProviderRepositoryDescribePublishTargetsInput } from '../hostingProvider.js';
export type { HostingProviderRepositoryDescribePublishTargetsResult } from '../hostingProvider.js';
export type { HostingProviderRepositoryGetInput } from '../hostingProvider.js';
export type { HostingProviderRepositoryPublishingCapability } from '../hostingProvider.js';
export type { HostingProviderResolvedProvider } from '../hostingProvider.js';
export type { HostingProviderResolvedRegistry } from '../hostingProvider.js';
export type { HostingProviderResolvedRemote } from '../hostingProvider.js';
export type { HostingProviderRoutingCapability } from '../hostingProvider.js';
export type { HostingProviderRuntime } from '../hostingProvider.js';
export type { HostingProviderRuntimeAdapter } from '../hostingProvider.js';
export type { HostingProviderRuntimeBasicAuthMaterializationResult } from '../hostingProvider.js';
export type { HostingProviderRuntimeCommandResult } from '../hostingProvider.js';
export type { HostingProviderRuntimeRegistration } from '../hostingProvider.js';
export type { HostingProviderRuntimeServices } from '../hostingProvider.js';
export type { HostingProviderRuntimeTokenMaterializationResult } from '../hostingProvider.js';
export type { HostingProviderUnresolvedRemote } from '../hostingProvider.js';
export type { ScmHostingProviderKind } from '../hostingProvider.js';
export { ScmHostingProviderKindSchema } from '../hostingProvider.js';
export type { ScmHostingProviderRef } from '../hostingProvider.js';
export { readCurrentHostingProviderRuntimeServices } from '../hostingProvider.js';
export { requestForgeJson } from '../hostingProvider.js';
export { resolveScmHostingProviderFollowupAllowedBaseUrl } from '../hostingProvider.js';
export { runWithHostingProviderRuntimeServices } from '../hostingProvider.js';
