export const AGENT_SESSION_RUNTIME_EVENT_KINDS_V1 = Object.freeze([
  'input-accepted',
  'input-rejected',
  'input-custody-unknown',
  'input-delivery-failed',
  'provider-session-id',
  'available-commands',
  'turn-start',
  'turn-progress',
  'turn-agent-id-observed',
  'turn-complete',
  'turn-failed',
  'turn-cancelled',
  'runtime-ended',
  'runtime-activity-snapshot',
  'message-delta',
  'tool-call',
  'tool-progress',
  'tool-result',
  'transcript-message-committed',
  'file-edit',
  'usage-observed',
  'turn-rollback-boundary',
  'context-compaction',
] as const);
