import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const defaultProjectDir = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Generate the browser asset consumed in place by source and bundled servers. */
export async function buildPublicShareViewerBundle({ projectDir = defaultProjectDir, check = false, printPatch = false } = {}) {
    const sourceDir = resolve(projectDir, 'sources/app/api/routes/share');
    const target = resolve(sourceDir, 'publicShareViewerBundle.generated.ts');
    const result = await build({
        absWorkingDir: projectDir,
        entryPoints: [resolve(sourceDir, 'publicShareViewerBrowser.ts')],
        bundle: true, write: false, minify: true, platform: 'browser', format: 'iife', target: ['es2022'],
        conditions: ['happier-source'],
        // Source builds bind portable presentation to the workspace's existing web host runtime.
        nodePaths: [resolve(projectDir, '../ui/node_modules')],
        alias: {
            'react': resolve(projectDir, '../ui/node_modules/react'),
            'react-dom': resolve(projectDir, '../ui/node_modules/react-dom'),
            'react-native': resolve(projectDir, '../ui/node_modules/react-native-web/dist/index.js'),
            'react-native-svg': resolve(projectDir, '../ui/node_modules/react-native-svg/lib/module/elements.web.js'),
        },
        define: { 'process.env.NODE_ENV': '"production"', '__DEV__': 'false' },
        legalComments: 'eof',
        plugins: [{ name: 'public-viewer-protocol-source', setup(builder) {
            builder.onResolve({ filter: /^@happier-dev\/protocol\/sharing\/public-viewer$/ }, () => ({
                path: resolve(projectDir, '../../packages/protocol/src/sharing/publicViewer.ts'),
            }));
        } }],
    });
    const source = '// Generated by scripts/buildPublicShareViewer.mjs; do not edit.\n'
        + `export const PUBLIC_SHARE_VIEWER_SCRIPT = ${JSON.stringify(result.outputFiles[0].text)};\n`;
    if (printPatch) {
        // stdout is a generator transport for remote execution, not runtime code.
        process.stdout.write(`*** Begin Patch\n*** Add File: ${target}\n${source.split('\n').filter(Boolean).map(line => '+' + line).join('\n')}\n*** End Patch\n`);
        return;
    }
    if (check) {
        if (await readFile(target, 'utf8') !== source) throw new Error('Public-share browser bundle is stale; run build:public-viewer');
    } else {
        await writeFile(target, source);
    }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
    await buildPublicShareViewerBundle({ check: process.argv.includes('--check'), printPatch: process.argv.includes('--print-patch') });
}
