export const GOVERNANCE_REPORT_DIRECTORY = '.project/testing/reports/governance';

export const GOVERNANCE_REPORT_PATHS = Object.freeze({
  inventorySummaryMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/inventory-summary.md`,
  inventorySummaryJson: `${GOVERNANCE_REPORT_DIRECTORY}/inventory-summary.json`,
  v2ZeroInventoryMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-inventory.md`,
  v2ZeroInventoryJson: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-inventory.json`,
  v2ZeroLaneA1Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a1-extract.md`,
  v2ZeroLaneA1Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a1-extract.json`,
  v2ZeroLaneA2A3Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a2-a3-extract.md`,
  v2ZeroLaneA2A3Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a2-a3-extract.json`,
  v2ZeroLaneA4Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a4-extract.md`,
  v2ZeroLaneA4Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a4-extract.json`,
  v2ZeroLaneA5Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a5-extract.md`,
  v2ZeroLaneA5Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-a5-extract.json`,
  v2ZeroLaneV21Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-1-extract.md`,
  v2ZeroLaneV21Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-1-extract.json`,
  v2ZeroLaneV22Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-2-extract.md`,
  v2ZeroLaneV22Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-2-extract.json`,
  v2ZeroLaneV23Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-3-extract.md`,
  v2ZeroLaneV23Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-3-extract.json`,
  v2ZeroLaneV24Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-4-extract.md`,
  v2ZeroLaneV24Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-4-extract.json`,
  v2ZeroLaneV25Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-5-extract.md`,
  v2ZeroLaneV25Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-5-extract.json`,
  v2ZeroLaneV26Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-6-extract.md`,
  v2ZeroLaneV26Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-6-extract.json`,
  v2ZeroLaneV27Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-7-extract.md`,
  v2ZeroLaneV27Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-v2-7-extract.json`,
  v2ZeroLaneB8Markdown: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-b8-extract.md`,
  v2ZeroLaneB8Json: `${GOVERNANCE_REPORT_DIRECTORY}/v2-0-lane-b8-extract.json`,
  deprecatedImportsMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/deprecated-imports.md`,
  deprecatedImportsJson: `${GOVERNANCE_REPORT_DIRECTORY}/deprecated-imports.json`,
  duplicatePatternsMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/duplicate-patterns.md`,
  duplicatePatternsJson: `${GOVERNANCE_REPORT_DIRECTORY}/duplicate-patterns.json`,
  rolloutStateMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/rollout-state.md`,
  commandsRunMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/commands-run.md`,
  migrationAccountingMarkdown: `${GOVERNANCE_REPORT_DIRECTORY}/migration-accounting.md`,
});
