export const FEATURE_ENV_KEYS = Object.freeze({
  automationsEnabled: 'HAPPIER_FEATURE_AUTOMATIONS__ENABLED',

  bugReportsEnabled: 'HAPPIER_FEATURE_BUG_REPORTS__ENABLED',
  bugReportsProviderUrl: 'HAPPIER_FEATURE_BUG_REPORTS__PROVIDER_URL',
  bugReportsDefaultIncludeDiagnostics: 'HAPPIER_FEATURE_BUG_REPORTS__DEFAULT_INCLUDE_DIAGNOSTICS',
  bugReportsMaxArtifactBytes: 'HAPPIER_FEATURE_BUG_REPORTS__MAX_ARTIFACT_BYTES',
  bugReportsUploadTimeoutMs: 'HAPPIER_FEATURE_BUG_REPORTS__UPLOAD_TIMEOUT_MS',
  bugReportsAcceptedArtifactKinds: 'HAPPIER_FEATURE_BUG_REPORTS__ACCEPTED_ARTIFACT_KINDS',
  bugReportsContextWindowMs: 'HAPPIER_FEATURE_BUG_REPORTS__CONTEXT_WINDOW_MS',

  voiceEnabled: 'HAPPIER_FEATURE_VOICE__ENABLED',
  voiceRequireSubscription: 'HAPPIER_FEATURE_VOICE__REQUIRE_SUBSCRIPTION',

  connectedServicesEnabled: 'HAPPIER_FEATURE_CONNECTED_SERVICES__ENABLED',
  connectedServicesQuotasEnabled: 'HAPPIER_FEATURE_CONNECTED_SERVICES_QUOTAS__ENABLED',

  updatesOtaEnabled: 'HAPPIER_FEATURE_UPDATES_OTA__ENABLED',

  attachmentsUploadsEnabled: 'HAPPIER_FEATURE_ATTACHMENTS_UPLOADS__ENABLED',

  socialFriendsEnabled: 'HAPPIER_FEATURE_SOCIAL_FRIENDS__ENABLED',
  socialFriendsAllowUsername: 'HAPPIER_FEATURE_SOCIAL_FRIENDS__ALLOW_USERNAME',
  socialFriendsIdentityProvider: 'HAPPIER_FEATURE_SOCIAL_FRIENDS__IDENTITY_PROVIDER',

  authRecoveryProviderResetEnabled: 'HAPPIER_FEATURE_AUTH_RECOVERY__PROVIDER_RESET_ENABLED',
  authLoginKeyChallengeEnabled: 'HAPPIER_FEATURE_AUTH_LOGIN__KEY_CHALLENGE_ENABLED',
  authUiAutoRedirectEnabled: 'HAPPIER_FEATURE_AUTH_UI__AUTO_REDIRECT_ENABLED',
  authUiAutoRedirectProviderId: 'HAPPIER_FEATURE_AUTH_UI__AUTO_REDIRECT_PROVIDER_ID',
  authUiRecoveryKeyReminderEnabled: 'HAPPIER_FEATURE_AUTH_UI__RECOVERY_KEY_REMINDER_ENABLED',

  encryptionStoragePolicy: 'HAPPIER_FEATURE_ENCRYPTION__STORAGE_POLICY',
  encryptionAllowAccountOptOut: 'HAPPIER_FEATURE_ENCRYPTION__ALLOW_ACCOUNT_OPTOUT',
  encryptionDefaultAccountMode: 'HAPPIER_FEATURE_ENCRYPTION__DEFAULT_ACCOUNT_MODE',
});

export type FeatureEnvKey = (typeof FEATURE_ENV_KEYS)[keyof typeof FEATURE_ENV_KEYS];
